### ISSUE TITLE
Great Britain pop culture

### ISSUE THREAD

**Issue by Harold-the-Axeman** [simsulla/nwomod#1]
Hi, the primary culture of Great Britain is white anglo, however most of the pop in the British Isles is English(London is white anglo). 

Another question: do you intend to make white anglo the primary culture of  U.S, Canada, GB and Australis.

**Comment by Harold-the-Axeman** [comment]
Another question: does the following link define the term white-anglo in the mod?
http://en.wikipedia.org/wiki/White_Anglo-Saxon_Protestant

**Comment by simsulla** [comment]
Corrected. In UK white_anglo now is accepted. English is primary.  White anglo is primary for Canada, US, Australia. White anglo is basically anglophones. WASP is a politically a bit to loaded term, white anglo is a broader group than just people form the British isles.
