### ISSUE TITLE
Vanilla Victoria 2 newpaper and pitctures

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1004]
Having tested out the latest version of NWO, I noticed that in the newspapers some of their pictures and titles were straight from vanilla Victoria 2, was this change intentional or unintentional.
![20170331215938_1](https://cloud.githubusercontent.com/assets/20518264/24569300/67057daa-165d-11e7-9a1e-aa7dafd825c1.jpg)

**Comment by simsulla** [comment]
This is a bug, I accidentally removed the,. Will readd.
