### ISSUE TITLE
Latgalian Culture and their distribution in Latvia

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1010]
Creating the Latgalian Culture, and adding it as a core culture of Latvia, also balancing their demographics in the country

**Comment by arandomperson5000** [comment]
Why are you adding in the Latgalian culture as as an accepted culture of Latvia when its primary language is just Latvian and there is a debate going on whether Latgalian is its own separate language or is a dialect of the Latvian language. Also its standardised form is recognised and protected as a verity of the Latvian language by Latvian law.

**Comment by RedstoneCobra** [comment]
I am Latvian, let me explain. Latgalian is only called a dialect of the language for political reasons, to prevent separatism from growing. From a linguistic stand point it is quite difficult for a normal Latvian to understand and the Latgalians are a Catholic group, unlike the rest of the protestant Latvian population

**Comment by arandomperson5000** [comment]
Those are some very good points, I would like to see the Latgalian culture​ be added into NWO as it could provide a more interesting setting for Latvia. As for the Russians it's possible that there could be a new country for the Russians living in Latvia or Estonia as the Russians living in the Donbass region of Ukraine self proclaimed their independence as new countries, not join Russia.

**Comment by RedstoneCobra** [comment]
I've already submitted it all :) Just waiting for Simsulla to Green light it

**Comment by RedstoneCobra** [comment]
Do you guys use any messaging app? cause it's inconvenient having to wait long periods of time to communicate

**Comment by simsulla** [comment]
All green. Looking forward to the "Pull request" with your code changes.

**Comment by RedstoneCobra** [comment]
While on this topic, could it be possible to create a new small state for Riga like currently exists in Delhi? as the country is highly centralised.

**Comment by simsulla** [comment]
Nice work RedstoneCobra. It is in committed to the master. Will close this issue.


On Riga, there already is a "small" Riga province (correlating to the real world admin division).  See no point in making it even smaller.
