### ISSUE TITLE
Veneto referendum

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1014]
I know I've already discussed this issue at the forums but it appears that due to the success of the yes vote in the Brexit referendum, demands for the autonomy of the Veneto region in Italy have increased for example in 2017 Luca Zaia the president of the Veneto region had made a request to the Italian Prime Minister Paolo Gentiloni for a autonomy referendum for the Veneto region to held later this yearafter his request for a Venetian autonomy referendum to be held along with the Italian constitutional referendum on 4th December was rejected.

Sources
https://www.neweurope.eu/article/veneto-president-will-vote-autonomy-2017/
http://www.italy24.ilsole24ore.com/art/politics/2016-06-24/the-referenda-on-the-autonomy-of-lombardy-and-veneto-also-to-take-place-by-the-end-of-2016-100153.php?uuid=ADn3dMi

**Comment by simsulla** [comment]
The answer was: On Veneto - online polls really means little - there has to be a real political movement. Show a real political movement with real support. An could add "online polls or what some lower official intends means little". According to the article "In Veneto they consider the initiative a mere “publicity stunt” by the governor - an intrepid Lega Nord politician who is establishing the parameters of an edgy and difficult negotiation. ". [Lega Nord](https://en.wikipedia.org/wiki/Lega_Nord) thoug is a real regionalist movement in Italy. 
We have some core (FVG) in northen Italy that could be converted into something like Lega Nords Padania (_In September of 1996 in Venice, the party unilaterally proclaimed the independence of Padania_).

**Comment by arandomperson5000** [comment]
There are some political parties in Veneto that advocate either the region's independence or autonomy that are completely separate from the Lega Nord such as Liga Veneta Repubblica and Liga Veneta Repubblica however the number of votes they get in Veneto's regional elections are quite small for example in the 2015 Venetian regional elections Venetian nationalist parties got a rate as low as 0.2% to as high as 5.7%. Given these are very small election rates I don't think Veneto warrants its own core.
https://en.m.wikipedia.org/wiki/Venetian_regional_election,_2015

**Comment by simsulla** [comment]
But you could make an event on the proposal for referendum, giving more populism in the north of Italy.

**Comment by arandomperson5000** [comment]
That was a very interesting suggestion I like it. As for Padania we could use the old country files of Indochina instead of FVG as it is currently an unused country and remnant from Darkest Hour in NWO.

**Comment by arandomperson5000** [comment]
Should I make the event for the proposal for referendum and add in Padania as a new country in NWO.

**Comment by simsulla** [comment]
Convert FVG to Pandania.

**Comment by arandomperson5000** [comment]
![20170402180806_1](https://cloud.githubusercontent.com/assets/20518264/24589257/78b1c694-17cf-11e7-9313-45b0a84b2a81.jpg)

**Comment by simsulla** [comment]
The countries.txt is messed up
+WJA = "countries/West Java.txt"
 +CJA = "countries/Central Java.txt"
 +EJA = "countries/East Java.txt"
 +ESU = "countries/East Sumatra.txt"
 +SSM = "countries/South Sumatra.txt"
 +ROU = "countries/Riouw.txt"
 +BKA = "countries/Bangka.txt"
 +MDU = "countries/Madura.txt"
 +WBO = "countries/West Borneo.txt"
 +EBO = "countries/East Borneo.txt"
 +SBO = "countries/Southeast Borneo.txt"
