### ISSUE TITLE
1955 Pogrom of Istanbul + Greek population In Turkey

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1016]
I propose the creation of the Istanbul Pogrom as an event, which would deteriorate relations between Turkey and Greece. Also, based on the demographics in the source provided, I'd also add the appropriate Greek populations in Turkey, this should make the Megali Idea slightly more realistic.
http://www.demography-lab.prd.uth.gr/DDAoG/article/cont/ergasies/tsilenis.htm

Upon reading about Turkeys demographics, the country in the 1946 start has 2 million people in excess. I'll also rebalance this number

**Comment by simsulla** [comment]
Nice idea do it. 
Btw "appropriate" is Turkish census not, pre-[Population exchange between Greece and Turkey ](https://en.wikipedia.org/wiki/Population_exchange_between_Greece_and_Turkey)

**Comment by RedstoneCobra** [comment]
I am aware, these statistics which i'm using are from 1945

**Comment by RedstoneCobra** [comment]
I'm trying to create a pull request and I get "request failed" "validation failed" what should i do?
