### ISSUE TITLE
Greek claims on North Epirus

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1021]
Proposition to make a decision just like the Megali Idea, but more lax, as this was a more realistic issue of the time

**Comment by simsulla** [comment]
ok

**Comment by simsulla** [comment]
There are several errors in the validator. Could you please look at them.

![image](https://cloud.githubusercontent.com/assets/10263809/24643863/a015699c-1910-11e7-855e-32793bcbaf8b.png)
