### ISSUE TITLE
Rename Baltic provinces to their appropriate names

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1024]
Most of the province names in the Baltic states right now would be like calling Texas state "Houston" or California "LA". Thus will rename them to their proper provincial names

**Comment by simsulla** [comment]
Naming provinces after the dominant city is from vanilla Vic2. In many cases there are no proper proper provincial names as a NWO province is multiple real world provinces.

"States" should be named after Administrative division (ex. Latvia - as it is).

**Comment by RedstoneCobra** [comment]
The ones I have in mind are proper provincial names which are existent and in use today.
https://en.wikipedia.org/wiki/Statistical_regions_of_Latvia
https://en.wikipedia.org/wiki/Cultural_regions_of_Latvia
https://en.wikipedia.org/wiki/Planning_regions_of_Latvia
