### ISSUE TITLE
Turkey and More

### ISSUE THREAD

**Issue by Jasebon** [simsulla/nwomod#1028]
Hi, 
Can be added to the game :
Restoration Monarchy Option  https://en.wikipedia.org/wiki/Osmano%C4%9Flu_family
Turanism https://en.wikipedia.org/wiki/Turanism
Neo Ottomanism https://en.wikipedia.org/wiki/Neo-Ottomanism
More population growth for https://en.wikipedia.org/wiki/Refugees_of_the_Syrian_Civil_War
https://en.wikipedia.org/wiki/Immigration_to_Turkey
https://en.wikipedia.org/wiki/Afghans_in_Turkey
https://en.wikipedia.org/wiki/Bosniaks_in_Turkey
https://en.wikipedia.org/wiki/Accession_of_Turkey_to_the_European_Union
https://en.wikipedia.org/wiki/Turkic_Council
https://en.wikipedia.org/wiki/Bosnian_genocide
https://en.wikipedia.org/wiki/Persecution_of_Ottoman_Muslims
Turkey political party name : False "AKP" ,   True "Ak Parti"
Ak Parti politicy :
Big Tent 
Free Trade
Laissez Faire
https://en.wikipedia.org/wiki/Justice_and_Development_Party_(Turkey)#cite_note-Cook-3

Turkey's Traditional Party = https://en.wikipedia.org/wiki/Great_Unity_Party

**Comment by simsulla** [comment]
No, Restoration Monarchy is not realist. 
Turanism is in the mod.
Neo Ottomanism is in the mod as greater Turkey #834
Migration uses a separate mechanism - not generic pop growth in Turkey.
As it is now, Adalet ve Kalkinma Partisi is a traditionalist party. Dogru Yol Partisi occupies the conservative slot.
