### ISSUE TITLE
Tatarstan core

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#103]
Tatarstan has a core on Chuvashia instead of itself. It should have core on Kazan province
https://en.wikipedia.org/wiki/Tatarstan

**Comment by simsulla** [comment]
Tataristan will get cores on Kazan. The vic2 province borders is a mess. No plan By definition 1033 is Chuvachia. 1032 is Chistopol. 1031 is Udmurt. Tataristan is 1030 and 1034
