### ISSUE TITLE
Aragonese and Astur-Leonese cultures

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1030]
Proposition to create the Aragonese and Astur-Leonese cultures in spain. But NOT as core cultures.

**Comment by simsulla** [comment]
Ok, but don't make them to large, from wiki Aragonese [50,000](https://en.wikipedia.org/wiki/Aragonese_language) speakers, Asturian [110,000](https://en.wikipedia.org/wiki/Asturian_language) .  And make them only rural (farmer, miner). 

_We should be a little bit careful for adding to many pops (spiting a farmer pop of Spanish into one Spanish and one Asturian adds a pop) as it has negative performance implications on the game._

**Comment by RedstoneCobra** [comment]
Am aware, just adding them in as some flavour. Nothing major

**Comment by RedstoneCobra** [comment]
Okay, i'm having one problem.
The Asturians ethnically number at 500,000
And from them 110,000 speak it as a first language
and an additional 500,000 people speak the language as their second language. Most of which are ethnic Asturians

Should I count the Asturians as 110,000 or 500,000?

**Comment by simsulla** [comment]
I would go with the lower number. i.e. Language. Culture should define primary loyalty (like in Catalonia if you are a spanish speaking you should be Spanish, not catalonian). I am not sure how "astutian identity" is defined.

**Comment by simsulla** [comment]
If you want to add cultures, there is a white spot on the map - Africa and The Pacific. Recomended to start with countries with good census data on ethnicity.

**Comment by simsulla** [comment]
Also, this morning I did a lot of resource renaming. You need to update your clone from master

**Comment by RedstoneCobra** [comment]
did your update get a partially incomplete French basque province?

**Comment by RedstoneCobra** [comment]
Because I updated, and only the province file was missing
