### ISSUE TITLE
Creation of Lur culture in Iran

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1032]
Creation of culture
https://upload.wikimedia.org/wikipedia/commons/f/f3/Ethnicities_and_religions_in_Iran.png

**Comment by simsulla** [comment]
Aren't they Persians (a dialect there of)? Are they in any Iranian census of ethnicity?

**Comment by RedstoneCobra** [comment]
They've basically got the exact same status as the Kurds do, in relation to the Persians that is

**Comment by simsulla** [comment]
From [wiki](https://en.wikipedia.org/wiki/Lurs#cite_note-1) the source seems to be CIA. 
[Ethnologue ](https://www.ethnologue.com/country/IR/languages)has them at significantly lower numbers. I you can find census figures that would be the best, else use the most moderate approach and make the pops rural (miner, farmers)

**Comment by simsulla** [comment]
Merge Lur culture #1045
