### ISSUE TITLE
Remove South Tyrol core from Trent

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1039]
Proposition to remove the South Tyrolian core from Trent, as the South Tyrolean secessionist movement does not aim for Trents independence.

**Comment by simsulla** [comment]
No, South Tyrol is very much an own core, and I plan to use it as part of #981

**Comment by simsulla** [comment]
I have been in South Tyrol, for a one week bike race '[Giro delle Dolomiti](http://www.girodolomiti.com/index.php?lang=en)'. Beautiful country, and not at all Italian.
Suggest closing this issue.

**Comment by RedstoneCobra** [comment]
I'm not talking about South Tyrol, i'm talking about Trent, which is below South Tyrol

**Comment by RedstoneCobra** [comment]
Bozen province is German / South Tyrol
Trent is not

**Comment by simsulla** [comment]
Aha.... sorry, sorry. Yes, Trent remove the core.
