### ISSUE TITLE
Russian Federal Republics

### ISSUE THREAD

**Issue by RedstoneCobra** [simsulla/nwomod#1042]
Proposition to create the last two Russian federal republics of: 
- Khakassia
- Karelia

Also, why does the Far Eastern Republic still exist?

**Comment by simsulla** [comment]
In princip being a Republic in Russia qualifies for a core. But there are exceptions, when the population is overwhelmingly Russian. Then it does not. Karelia and Khakassia are such. Karelia was removed from the mod of this reason. 

Have no good explanation for why FER remain, but lets keep it.
