### ISSUE TITLE
Population of the USA

### ISSUE THREAD

**Issue by Tileta98** [simsulla/nwomod#1049]
Hi Simsulla:
Playing with the USA, I have detected that the USA population are incorrect in both scenarios (1946 and 1992).
![v2_1](https://cloud.githubusercontent.com/assets/16515741/24657191/a4a29c98-1945-11e7-9cad-92a0e4c96636.jpg)
![v2_3](https://cloud.githubusercontent.com/assets/16515741/24657413/65b6b626-1946-11e7-9169-a4812920ce4e.jpg)

The real population of USA in 1946 was 140 million people, and in 1992 was 256 million people.
This is the place where I found the information:
http://www.datosmacro.com/demografia/poblacion/usa
Please, solve this issue to give more historical realism to the game.
Thanks for reading.

**Comment by simsulla** [comment]
There is something wrong with your installation.
Latest version is v1.13 
**1946** (not includes S.Korea, Occupied Germany pops)
![image](https://cloud.githubusercontent.com/assets/10263809/24666435/9880797e-1960-11e7-8040-fddb0d23c6c5.png)
**1992** 
![image](https://cloud.githubusercontent.com/assets/10263809/24666552/f75fa988-1960-11e7-85b7-8d2a7d83f52b.png)

**Comment by simsulla** [comment]
No bug. Closing this issue.

**Comment by Tileta98** [comment]
But I install the latest version (1.13), and I'm having the same error. I can't understand this situation. Please, help me.

**Comment by simsulla** [comment]
Clear the cache. 
Remove the old mod/NWO folder. 
Then install the new NWO 1.13 download (i.e ensure you don't have file duples).
