### ISSUE TITLE
Conscription

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1051]
I think there should be a reform table for conscription because multiple countries that have abandoned conscription such as Lithuania have reintroduced it in recent years. If conscription was added to the mod it would be a significant factor in determining the number of units is gained by mobilisation for example perhaps fitting into the fall of america issue #1026  a progressive government would be in favour of reducing the years of service a conscript has to serve until conscription is abolished entirely paving a transition to an all volunteer military while a militaristic government would gradually increase the number of years a conscript has to serve. This system would be very similar to the conscription used in the PDM mod.

**Comment by simsulla** [comment]
Likewise Sweden has also reintroduced conscription. I suggest taking it as part of #1026 and not as a separate issue.

**Comment by arandomperson5000** [comment]
Ok
