### ISSUE TITLE
Yugoslavia forming into Serbia bug

### ISSUE THREAD

**Issue by discretehero** [simsulla/nwomod#1063]
So when I start the 1992 start date as Yugoslavia some time afterwards I get an event to either protect/support the Serbs (and turn into Serbia) or "remember the communist legacy". When I click the first option the end screen appears with my country shown as Serbia and then the game crashes.

**Comment by simsulla** [comment]
Seems like I misunderstood the meaning of change_tag_no_core_switch. To use this the country must exist or the game ends for the player.
