### ISSUE TITLE
trouble choosing country

### ISSUE THREAD

**Issue by NirelKitsune** [simsulla/nwomod#107]
first excuse my bad english.

So it turns out that was trying to play with the mod is not installed normally, but when I start the game and I choose a country he simpleste error and closes. I reintalei the mod and play, but nothing works the first time you open the game with the mod that is for the part of adapting the story and closes, then simply close when I choose a country

**Comment by simsulla** [comment]
NirelKitsune, I will move your question to Issue #46. And answer it there, as this is installation related.
