### ISSUE TITLE
Reorganized National Government of the Republic of China and Qing Empire

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1083]
These countries seem to be leftovers from the Darkest Hour conversion should we keep them as they are, delete them or use their tags for another country.

**Comment by arandomperson5000** [comment]
I think the Reorganized National Government of the Republic of China in NWO is quite useless right now as a country could just simply puppet China by war or releasing them as a vassal.

**Comment by simsulla** [comment]
Well, China is so strong (even after dismantle) that they are still bound to be a super power even no.1 late game. Vassaling them will not possible.  My idea was to let the enemy player conquer part of china, Reorganized National Government of the Republic of China  core it and in a "special" war type "liberate" that nation. Thus making China weaker.

**Comment by arandomperson5000** [comment]
Maybe both the Qing Empire and the Reorganized National Government of the Republic of China could be used as tags for new countries for example the Talysh-Mughan Autonomous Republic a short lived self declared state that lasted from June to August 1993, I had only found out this country even existed quite recently. Also there is a tag for Indochina in NWO should this tag be kept as a sort of a potential union between the countries of Indochina or should it be deleted.

**Comment by simsulla** [comment]
Yes, but I suggest renaming the tags :), It is easier to read code if the tag indicates country (TAL, TMA or whatever for Talysh). Having QNG ad Talysh is a bit confusing.

**Comment by arandomperson5000** [comment]
Ok I will get to work on Talysh-Mughan Autonomous Republic right away,

**Comment by arandomperson5000** [comment]
I suppose the tag for the Reorganized National Government of the Republic of China could be used for Cordillera to fit in with  https://github.com/simsulla/nwomod/issues/835 perhaps the Igorot people could be added as a culture aswell since the Igorot culture groups is largely distinct from the Filipinos.

**Comment by simsulla** [comment]
There is already a Moro core. Just remove the Reorganized National Government of the Republic of China core.

**Comment by simsulla** [comment]
But the basic principle of _one core per province majority culture_ is good. It is just that of all open issues and bug reports, I think those should be addressed first. And when we do add cores we should do this with events and decisions making that new core a real playable nation. _Events and decisions_ has not even been added to current cores.
