### ISSUE TITLE
"Constitution Convention" Spam

### ISSUE THREAD

**Issue by devinity1337** [simsulla/nwomod#1091]
I'm playing the current version (as Israel, 1940's and 50's) and keep getting spammed by Constitution Convention event (wants to switch to Promote Democratic).
Just an FYI.

**Comment by simsulla** [comment]
Dveduu said: ↑ 
Whenever I have a liberal government, I get spammed by "Constitution Convention" event. It keeps telling me to take the reform "Promote Democratic", but I already have the reform.
