### ISSUE TITLE
Judaization of Jerusalem

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1096]
-1967 war event didn't fire, so I never got a core on Jerusalem. Possibly because I already captured the Golan heights? Perhaps there should be an event "Judaization of Jerusalem" that lets you get a core on the state if you capture it outside of the 1967 war.

**Comment by simsulla** [comment]
**Deveduu**
From the Israeli population statistics of Jerusalem "These official Israeli statistics refer to the expanded Israel municipality of Jerusalem. This includes not only the area of the pre-1967 Israeli and Jordanian municipalities, but also outlying Palestinian villages and neighbourhoods east of the city, which were not part of Jordanian East Jerusalem prior to 1967."

https://en.wikipedia.org/wiki/Demographic_history_of_Jerusalem

So it looks like the 1940's data is a little more restricted in area compared to the Israeli data, but both have jews in the absolute majority.

**Comment by devinity1337** [comment]
I suggest to make this event only fire after Israel goes independent from Britain, otherwise Jerusalem becomes the capital of mandatory palestine.
