### ISSUE TITLE
Russia and the EU

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#11]
Hi, thanks for the great job making this mod!

Russia, Belarus and Kazakhstan should really be given a possibility to join the EU (and probably the Chinese-dominant union), for purposes of alternate history, plus it's all really getting to this - EU or China. Something like EuroMaidan Revolution is actually starting right now in Moscow - http://www.youtube.com/watch?v=XmkHpuz0bAw

**Comment by simsulla** [comment]
Agreed that one might consider an alt-history scenario where just like in Ukraine oligarchs consolidate their grip on power and ability to influence opinion to eventually facilitate the orientation to the west EU. Ukraine has taken this path. If you want to make such chain. Please do and I will add it.  In the mod now there is a Eurasian Union that Russia, Belarus and Kazakhstan and others may form.
