### ISSUE TITLE
June 30 1996 CTD

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1106]
Commit 0b08123 29 Apr casues a CTD on 30 Jun 1950 or 30 Jun 1996 depending on start date.
There is a election result at that time.
![image](https://cloud.githubusercontent.com/assets/10263809/25883352/3d939c52-354a-11e7-97f5-bd2cb8571850.png)

**Comment by simsulla** [comment]
Strangely enough seems like commit 07817fc fixed this #1011 for the 1946 start date!!?

**Comment by simsulla** [comment]
The game still caches 30 Jun 1996  on completion of an election.

**Comment by arandomperson5000** [comment]
Did you check the validator on this issue

**Comment by simsulla** [comment]
Validator is ok. Does not detect this error... :(

**Comment by arandomperson5000** [comment]
This problem is a little bit wierd, as using cheats to get past 1996 a few months ago, I was able to avert this problem and therefore I manage to stage a full election with getting a ctd, meaning that the problem could be gone now.
