### ISSUE TITLE
OS X Extreme Lag

### ISSUE THREAD

**Issue by zachary123212** [simsulla/nwomod#111]
I am running the mod on the App Store version of Victoria 2 on a 2.5Ghz Intel Core i7 Macbook Pro with 16GB of memory and an AMD Radeon R9 M370X graphics card.  
Although the computer can run Vanilla and HPM Victoria 2 completely fine, when running the NWO mod, the game is virtually unplayable, frame rate dropping to about 1 FPS with extreme input lag.  
Is this to be expected from a computer like this?

**Comment by simsulla** [comment]
What version are you playing? 1.0.1 there was an issue. For 1.0.2 I was unable to reproduce (though not sure what caused it).

**Comment by zachary123212** [comment]
I am using 1.0.2, cloned from the git repo.

**Comment by zachary123212** [comment]
Additionally, I should probably note that my CPU and Memory Usages are not very high when not running the mod.

**Comment by simsulla** [comment]
I will see if i can reproduce withe the upcomming 1.0.3 release. 
In general :) please use one of the download zips for installing, then i know exactly what you have installed. Git hub head changes all the time (it is pre-1.0.3 att the moment)

**Comment by simsulla** [comment]
Tested upcomming 1.0.3 (i.e. github head). Unable to reproduce extreme lag. I did a test on my Mac Mini (2014). 1946-56 with highest speed took 40 min.

Do this:
1. clear your cache. See if you still see lag.
2. reinstall the NWO mod form downloaded zip, Ensure that you delete the old NWO files before reinstalling. Then test (also this time clear the cache - just to be safe).

With that said I believe it is time for a general performance tuning of the mod (i.e .effecting both Windows and Mac). Created issue for this: Performance tune NWO #124

**Comment by zachary123212** [comment]
After trying both of these steps, the game still lags. Just to confirm, are you using the App Store version of HOD?

**Comment by simsulla** [comment]
Yes

**Comment by zachary123212** [comment]
I managed to fix the FPS issue by running my windows copy of Victoria 2 in wine. I still don't know why this happens on the App Store version, but I've tried running the App Store version on another Macbook and encountered the same issue.
