### ISSUE TITLE
Indirect Rule in the British Empire

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1111]
I'm not sure whether this deserves its own issue or not but however I think you'll be quite interested into this topic. Since the British was the largest empire in history, governing its vast territories was quite difficult and would have consumed a lot of resources to set up an effective bureaucracy made up of people from the British Isles in a colony. To solve this problem they used pre-existing local power structures made up of traditional rulers for the day to day government and administration of certain areas such as Uganda and India. A clear example of this system is the Princely States of India. However indirect rule in other parts of the British Empire such as Nigeria and Uganda are not at all represented in NWO. Both Nigeria and Uganda before their decolonisation were colonies that had large portions of their total territory governed by traditional rulers such as the various Emirates that were established in Northern Nigeria after the British conquered the Sokoto Caliphate in 1903 and the traditional kingdoms of Uganda such as Bunyoro and Buganda.
More information on indirect rule in the British Empire
https://en.wikipedia.org/wiki/Indirect_rule

**Comment by simsulla** [comment]
One could consider having them using existing cores. But only together with events later integrating these territories later on. Given the problems with the UN Mandates #981 , such chains needs thorough validation - and is a lot of work.

**Comment by arandomperson5000** [comment]
Perhaps province or country modifiers could be used to represent indirect rule in British colonies such as the various Emirates in Nigeria instead of actual countries as I think these areas weren't as autonomous as other examples of British indirect rule such as the Indian princely states and it could save a lot of time on events.

**Comment by arandomperson5000** [comment]
As of right now the United Arab Emirates (Trucial States) in NWO doesn't really have anything to show that it is a federation which it is in real life, to solve this problem I would suggest representing the various emirates of that country as political parties with competing interests similar to the political system of Saudi Arabia in NWO as the UAE doesn't have political parties in real life and it is a federation of monarchies with its president being a ruler of an emirate.
