### ISSUE TITLE
Turbercolosis

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1115]
**james9883**
Also, this event seems out of date:
![image](https://cloud.githubusercontent.com/assets/10263809/26292290/e984e28c-3eb4-11e7-894a-ce356af57220.png)

**Comment by arandomperson5000** [comment]
I would suggest keeping this event as many people including 1 million children are infected with the disease each year, however as a country's medical technology advances in NWO, the chances of getting this event are drastically reduced. Also the text of this event needs to be updated for obvious reasons.

I think events should be made for major diseases that weren't present in vanilla Victoria 2 s timeline for example HIV/AIDS which in 2015 37.3 million people were living with HIV/AIDS and 1.2 million died from it.

**Comment by simsulla** [comment]
Updated the event text. AIDS would be a separate event.
