### ISSUE TITLE
US state borders

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1119]
**endosys**
I noticed some strange things in the map and am not sure if they are there on purpose.
![image](https://cloud.githubusercontent.com/assets/10263809/26665839/875b8300-469c-11e7-8b95-225dc53d1811.png)

1. North Dakota does not have that bump below Bismarck.
2. The top of Utah that borders Idaho is straight.
3. Baton Rouge is the capital of Louisiana so it should probably be in the Louisiana region.
4. Virginia controls the southern tip of the Delmarva peninsula.
There are a lot of missing pixels across the map, more so than the actual Vanilla map which already has a lot. I could help clean them up if you want.[/QUOTE]

**Comment by arandomperson5000** [comment]
This file which contains an updated provinces map for this issue was too big to fit in as a commit so I'm leaving ti here as a zip for you to put in.
[provinces.zip](https://github.com/simsulla/nwomod/files/1045072/provinces.zip)
