### ISSUE TITLE
Southern Africa pops 1946

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1123]
**CaptainCrape**
Awesome mod! However, and I don't know if this has been fixed, but many countries start without political parties for some ideologies, such as a populist party in France. Also, another issue I have found is that the POPs in South Africa, the Central Rhodesian Federation and Namibia are inaccurate for 1946 and 1992 even though accurate population data is[ out there](https://en.wikipedia.org/wiki/Federation_of_Rhodesia_and_Nyasaland#Constitutional_origins). Here are the demographics for The Central Rhodesian Federation in 1946 and other years, And [for South Africa](https://en.wikipedia.org/wiki/Demographics_of_South_Africa#Historical_censuses). Another odd issue I had is Lesotho randomly had a constant, huge increase in White Anglo POPs. Which is very odd considering it doesn't start with any, it received 0 immigration and its only accepted culture is Sotho. Here is an example of that 
![image](https://cloud.githubusercontent.com/assets/10263809/26832739/b12c302a-4ad0-11e7-95e1-ff86a2137039.png)

Anyways, those are the only issues i've noticed so far in my main game as South Africa. Keep up the good work!

**Comment by arandomperson5000** [comment]
Just wondering are some of these issues coming from private conversations with other members at the paradoxplaza as I couldn't find the post you have displayed above on the main NWO thread in the paradox plaza forum.

**Comment by simsulla** [comment]
From [reddit](https://www.reddit.com/r/paradoxplaza/comments/62n9cf/new_world_order_nwo_mod_for_victoria_2_v113/?st=j3lr836t&sh=79ebf910).

**Comment by simsulla** [comment]
Corrected the demographics... not perfect but a lot better than before. The issue of British in Nyasa-land is mysterious and remains unresolved.
