### ISSUE TITLE
Yugoslavia cb

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1133]
**pesgores**
Maybe this is a bug: playing as Yugoslavia, lost 2 of my states to Italy in 2 different wars (Dalmatia and Trieste). Now I want to take them back, but the Reconquest CB is nowhere to be found. So I Justify War with a Conquest CB and I can't select either of those 2 states as the objective of the war... So I can't take these 2 states back. I am going to try and declare war and then add the Acquire Core CB and see if it works.

UPDATE: It did. But the option should be available right away, right?

**Comment by arandomperson5000** [comment]
Not sure on what the problem is here, it could be that Italy is a part of NATO or another alliance that prevents the reconquest cb from being used.
