### ISSUE TITLE
Old Version of Save File Crashes 

### ISSUE THREAD

**Issue by angusfung98** [simsulla/nwomod#1136]
I have an old save from an older version of the mod from last year. I think the version number is 1.03. The version of the mod with the old start screen and old music. 

Anyway, I recently updated to 1.13. When I select my old save, the game crashes. If I pick a new scenario it works just fine. I tried fixing it by doing a full reinstall of the mod, but it still doesn't work.

**Comment by simsulla** [comment]
There is not backward compatibility between 1.13 and 1.03. I.e. you can't play a 1.03 save with 1.13.
