### ISSUE TITLE
Dhaka terrain

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1137]
misiame,
I don't have the mod running on this laptop but I have a bug related to terrain. The "dhaka" terrain that is meant for the city of dhaka isn't located in "dhaka" province but is located in a province in upper myanmar/burma around the shan states. I can't recall the exact one, but it might be touangoo. Sorry for not beinnng about to give exact positioning but this was a big that was long in the mod.

**Comment by arandomperson5000** [comment]
Closing this issue as it was already solved by the commits for the map overhaul of Myanmar.
