### ISSUE TITLE
Donetsk Peoples Republic unified with Russia

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#1138]
**redstonecobra**
Just today 18/7/2017 the leader of the Donetsk Peoples Republic announced their intent of forming the new state of Malorossiya (Little Russia).
With the intent of becoming the successor state of Ukraine. It's capital being in Donetsk, demoting Kiev from that role.
The country would seek to join the State Union of Russia and Belarus.
As time passes and this information solidifies could it be added into the game?
**simsulla**
To some extent I think this is in the mod - via "national unification". This needs to be verified though.

**Comment by RedstoneCobra** [comment]
Simsulla, it's not just Unification. The Donetsk Peoples Republic declared a new state today with the intent of annexing all of Ukraine.
