### ISSUE TITLE
New flag for Mauritania

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1150]
On 15 August 2017 Mauritania adopted a new flag after a referendum regarding controversial changes to the Mauritanian constitution such as abolishing the senate was held in which supposedly 86% of voters approved of the changes. The new flag is basically the previous flag except with a red band stripes were added onto the top and bottom of the flag, these stripes symbolize "the efforts and sacrifices that the people of Mauritania will keep consenting, to the price of their blood, to defend their territory".

Picture of the new Mauritanian flag

![image](https://user-images.githubusercontent.com/20518264/29488934-f5c40b4c-850c-11e7-86f8-b0e7a369e0f4.png)

https://en.wikipedia.org/wiki/Flag_of_Mauritania
https://en.wikipedia.org/wiki/Mauritanian_constitutional_referendum,_2017

**Comment by simsulla** [comment]
Then this would go together with some event making Mauritania change gov type (having this new flag). Right?

**Comment by arandomperson5000** [comment]
Yep  the current party ruling Mauritania, the Union for the Republic seems to to be populist so this could be used as a flag for when Mauritania has a provisional government/populist dictatorship.
