### ISSUE TITLE
Mismatches/Omissions in factory goods-in-state efficiency bonuses

### ISSUE THREAD

**Issue by kbernges** [simsulla/nwomod#1151]
-Nuclear Power Plant factory gains efficiency where there are Coal RGOs, rather than Other Minerals RGOs
-Jewellery Factory is an odd case where having one input provides bonus, but having both provides no further bonus
-Beverage & Tobacco factory gains efficiency with Beverages Brewery factory, but not Soft Beverage or Coffee Beverage factories (possibly deliberate)
-Furniture & house-ware factory gains efficiency with Electricity Plant factory but not Nuclear Power Plant factory
-Military Industry factory has Electric Gear as input but uses Telecommunications producing factories for bonuses
-Advanced Military Industry factory uses Car Factory in the Telecommunications OR{} instead of Telecom and Electronics, providing a double bonus if the Car Factory is present and providing no bonus if Telecom and Electronics is used in absence of Car Factory

**Comment by simsulla** [comment]
Is this bug report for version 1.13 of the mod?

**Comment by kbernges** [comment]
Yes. If it's been fixed post-patch, then I suppose this is irrelevant.

**Comment by simsulla** [comment]
Thanks any how 👍 . These type of bug reports are super use full in "balancing" the production system - which is a tedious and hard thing to do.
