### ISSUE TITLE
Separate culture for the American Deep South and Kiwi and Aussie culture renaming

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1152]
This idea was suggested by me in a previous issue however the idea never really got off the ground. Due to some research I have done about the post-Civil War situation of the Deep South and the cultural divisions present in the U.S, my interest in making them its own culture in NWO has sparked again. There has been a few problems that I need to solve before I make a Southerner culture. Firstly while their population at the 1946 startdate has been largely figured out thanks to the results of the 1948 presidential election, their population at the 1992 startdate would require a lot more guesswork since there isn't really any stats on the current population of Southerners, I would suggest having their percentage of the states they live in reduced by 20% in 1992 since while they do still make up a very large percentage of these state's populations, in recent decades, they 're being increasingly at odds with the growing number of people who mainly identify as what could be called the mainstream American culture for example the ongoing controversy surrounding the removal of statues of Confederate soldiers and generals. Secondly I'm a bit confused on which poptype am I meant to implement the Southerner culture culture in, do I just put them in as farmers, labourers and workers or do I put them in as all poptypes.

Map of the results of the 1948 US presidential election by county
![image](https://user-images.githubusercontent.com/20518264/29498618-31643f00-85f8-11e7-9b24-eae8a26aa308.png)
https://commons.wikimedia.org/wiki/File:1948nationwidecountymapshadedbyvoteshare.svg

Also about the Aussie and Kiwi  cultures, they've not been renamed yet so I'll rename them to Australian and New Zealander.

**Comment by simsulla** [comment]
Nice on the pops. 
But I just forgot - why change  Aussie and Kiwi names?

**Comment by arandomperson5000** [comment]
I think the Aussie and Kiwi cultures should be rrnwmed to Australian and New Zealander since Aussie and Kiwi are more or less regional nicknames while Australian and New Zealander are more or less the official names for these people being used in things such as in a few. Also other mods like HPM use the name Australian rather than Aussie to display that culture.

**Comment by simsulla** [comment]
Ok - Australian and New Zealander it is.

**Comment by arandomperson5000** [comment]
![20170823005055_1](https://user-images.githubusercontent.com/20518264/29592632-3f3780e6-879d-11e7-8ec2-7c29f09e6e18.jpg)
I've added in Southerner pops for the 1992 startdate, instead of using a 20% reduction of the percentage that the Southerners occupy, I have used a 10% reduction as the 20% reduction would have caused the Southerner population to be too small from what it could have been in real life.
