### ISSUE TITLE
Border Problem in the Congo

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#1154]
I think I have may just found an incorrectly shaped border between the Democratic Republic of the Congo and the Republic of the Congo.
![20170825093028_1](https://user-images.githubusercontent.com/20518264/29705976-2808bd2c-8978-11e7-8e94-9af9084780f1.jpg)

![image](https://user-images.githubusercontent.com/20518264/29706215-de094614-8978-11e7-9572-3115700fd55f.png)

**Comment by simsulla** [comment]
No, the map is based on http://www.gadm.org/ administrative borders data, and definitely not wrong. Unless there are very fine grained features on pixel level.

**Comment by arandomperson5000** [comment]
This is the part of the border I was talking about
![20170825131003_1](https://user-images.githubusercontent.com/20518264/29713599-47260a56-8997-11e7-81de-5fcdfde4db58.jpg)
As you can see this part of the border in NWO juts inwards towards the Republic of the Congo however that part is incorrect as that part of the border in real life is roughly based around the Ubangi River.
![image](https://user-images.githubusercontent.com/20518264/29713779-23e7db72-8998-11e7-8430-2f42a0740a90.png)
Map of the Administrative borders in the Democratic Republic of the Congo (Source: [Global Administrative Areas](http://www.gadm.org/))
![image](https://user-images.githubusercontent.com/20518264/29713797-2f0aa99e-8998-11e7-8b87-434edcd341fb.png)
Map of the Administrative borders in the Republic of the Congo (Source: [Global Administrative Areas](http://www.gadm.org/))

![image](https://user-images.githubusercontent.com/20518264/29713766-0e795324-8998-11e7-9b09-5cf6cc951dd5.png)
Map of the Ubangi RIver (Source: [the Robinson Library](http://www.robinsonlibrary.com/history/africa/congoriver/ubangi.htm))

**Comment by simsulla** [comment]
Maybe we found a bug in  http://www.gadm.org/ data :) One area is registered as part of ROC instead of DRC. 
Yes, then please correct it.

**Comment by arandomperson5000** [comment]
I've just found out what this little strange part of of the border is, It is apparently called the Impfondo district which is just one of the three districts of the Likouala Department the northernmost region of the Republic of Congo. This district is also home to the town its named after Impfondo which is the capital of the Likouala district. Due to this I'm going to edit this part of the DRC-ROC border so it pretty much lines up roughly with the Ubangi River.

**Comment by arandomperson5000** [comment]
Here is the new border with it being based roughly around the Ubangi River now.
![20170826174828_1](https://user-images.githubusercontent.com/20518264/29743307-5bedf480-8a87-11e7-9ca5-98694255f2b5.jpg)

**Comment by arandomperson5000** [comment]
Just wondering are you able to add this updated version of the province map into NWO since I can't add it in manually as the map file size is too big to put in as a commit.
[provinces.zip](https://github.com/simsulla/nwomod/files/1254018/provinces.zip)
