### ISSUE TITLE
Possiblility to play as Israel/Palestine via and event.

### ISSUE THREAD

**Issue by ghost** [simsulla/nwomod#1156]
Basically would it not be a good idea to allow the player (as UK) to switch to Israel or Palestine via an event after the player decides to handover the partition issue to the UN?

Also similar thing could be implemented for USSR, France, USA and UK after the end of the occupation of Germany (to play via and event as either west or east Germany).

**Comment by simsulla** [comment]
I like this idea. But the current setup with for example part of Germany as an integral part of the US, etc. is unrealistic. So we chose a different solution by in the next release 2.00, these "mandates" and "occupations zones" will be puppet countries, and playable form start with a special provisional government (i.e. usually Military Administration), eventually becoming "independent". 
The more generic case of releasing a core and then playing it. Is available in the mod and vanilla Vic2.
