### ISSUE TITLE
Resolution Issues

### ISSUE THREAD

**Issue by ClaudezAlex** [simsulla/nwomod#1157]
By the 1366*768 resolution, cannot select the last education reform. Can you adjust the height of the cassettes, so it might fit in? Thanks!

**Comment by simsulla** [comment]
Is this for the current github release or the latest public release 1.13?

**Comment by ClaudezAlex** [comment]
the latest yet
sorry for not posting in real time
i'll upload a screenshot

**Comment by simsulla** [comment]
Thanks for the bug. Will fix in the next release.

**Comment by ClaudezAlex** [comment]
Thanks! ;) 
This version? (8hr ago?)

**Comment by simsulla** [comment]
It's not corrected yet. It will be as part of the future 2.00 release.

**Comment by ClaudezAlex** [comment]
Hmm...okay :)
