### ISSUE TITLE
Start up issue

### ISSUE THREAD

**Issue by nwohelp** [simsulla/nwomod#1163]
Whenever I launch the game is loads like the default game, i could see my old saves from an old version of the mod like a year ago before i deleted the nwo folder i had. I'm on windows 10 game version 3.04

**Comment by simsulla** [comment]
you probably haven't installed it proparly. Under victoris 2\mod what folders and files do you have? You should have a NWO folder (with all the mod files in it) and a NWO.mod file.

**Comment by nwohelp** [comment]
Im a dumby who didnt move the folder out of the install folder. Sorry for wasting your time great mod
