### ISSUE TITLE
Adding North Vietnam in the 1946 start date

### ISSUE THREAD

**Issue by DullishCrab94** [simsulla/nwomod#1167]
Im sorry if this suggestion is in the wrong place but i have two suggestions i was wondering if you could add North vietnam in the 1946 start date instead of it being vietnam i was wondering if you could do the same for yemen by making it north yemen in 1946 start date

**Comment by simsulla** [comment]
What game mechanics are you looking for - the unification?

**Comment by DullishCrab94** [comment]
Yeah i was hoping you could do west germany,north vietnam,north yemen i feel that these will make more sense to have during the cold war
