### ISSUE TITLE
East Berlin on west side of Berlin?

### ISSUE THREAD

**Issue by tavich** [simsulla/nwomod#1170]

**Comment by arandomperson5000** [comment]
I really don't know what this issue is about, both West and East Berlin are represented as just one single province called Berlin in NWO for gameplay reasons.

**Comment by tavich** [comment]
I haven't played this mod for some time but @simsulla put this on the milestone for 2.0 so I'm assuming it's not fixed yet but if I remember correctly East Berlin was shown on the southwest side of Berlin with West Berlin above it.

**Comment by arandomperson5000** [comment]
![20180413234051_1](https://user-images.githubusercontent.com/20518264/38760626-788966ae-3f74-11e8-84e2-32814fb4b3f5.jpg)
In the current version of NWO there is just a single Berlin province, no East or West Berlin provinces, I think what may have happened is that you played an earlier version or perhaps saw an event or decision picture displaying a map of the divided Berlin during the Cold War with a few errors.

**Comment by tavich** [comment]
Hmm. I'll give it another go and try to find out what I was talking about.

**Comment by arandomperson5000** [comment]
Okay fixed the issue now in version 2.00 Pritzwalk wont be renamed to East Berlin via event.
