### ISSUE TITLE
Small Countries Are Always losing money or are in debt

### ISSUE THREAD

**Issue by DullishCrab94** [simsulla/nwomod#1171]
Now sorry if I'm spamming but The New World Order Economy is wonky your always losing money no matter what you do its easier to go into the positives as a Great Power like the Soviet Union or The USA but if you play as a small country like Bulgaria or Vietnam it is impossible to make money you always end up going bankrupt or need loans to survive could you try to fix this so it is easier to play as smaller countries

**Comment by DullishCrab94** [comment]
Simsulla if you see this could you please fix Nwos Economy so you can play as smaller nations

**Comment by simsulla** [comment]
will look into it.

**Comment by arandomperson5000** [comment]
Merged with the issue of monetary problems to prevent cluttering
