### ISSUE TITLE
Non Great Power nations in NWO always losing money 

### ISSUE THREAD

**Issue by DullishCrab94** [simsulla/nwomod#1174]
Sorry to bother you again with this but I noticed this in both the 1946 and 1992 start dates any nation that is not a great power and even a few great powers have this money problem they always seem to lose money no matter what you do which means soon you will end up being bankrupt i haven't had this problem in CWE maybe you could use CWE's economy so you can startup a lot easier as those non great power nations

**Comment by simsulla** [comment]
Will look into it as part of the next release.

**Comment by arandomperson5000** [comment]
Merged into issue #1201
