### ISSUE TITLE
How to adapt mod to the latest version of game? 3.04

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#1185]
Hello. I know it's the wrong place to ask, but I really need to know how to adapt mod to 3.04?

**Comment by Liegnitz** [comment]
they mod should be able to run with 3.04

**Comment by samwoodzadrot** [comment]
Well, it runs with 3.04 but when I'm pressing on decisions game crashes. (Not NWO*)

**Comment by Liegnitz** [comment]
there's a bug with a decision then afaik

**Comment by samwoodzadrot** [comment]
But it works with 3.03 version. 
Or then how to fix it?

**Comment by simsulla** [comment]
There where a couple of changes I needed to do to make the mod work both with 3.04 and 3.03. 
I think the only change I did was in some graphics files. This is the commit 
https://github.com/simsulla/nwomod/commit/bf31f6a6acad97970c646bf961ea2270cc6cc37c

**Comment by samwoodzadrot** [comment]
Hm. Thank you very much!
