### ISSUE TITLE
Change regime in sphered country event error

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#12]
I got Change regime in sphered country event while playing for Soviet Union in the first year of the scenario. The sphered country was Finland. There was two choices:
 1) Demand regime change (in this case - Democracy to Proletarian Dictatorship). When I hovered my mouse over it, it showed no popup.
 2) Let them have there own regime. When I hovered my mouse over this one, it showed that Finland will get "Soviet Union demands regime change" event. As a result I lost 50 influence points I had, but it stayed in my sphere.

**Comment by simsulla** [comment]
This has been corrected in the current release - 0.9.906.
