### ISSUE TITLE
Polish Cores

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#126]
Poland has a core on Mogilev (948) instead of Lida (938).

**Comment by simsulla** [comment]
There is no Polish core in either 948 or 938, nor should there be.

**Comment by Liegnitz** [comment]
![2016-01-22_00002](https://cloud.githubusercontent.com/assets/16386550/12522280/1397dae0-c150-11e5-94f5-0fedae7bef6a.jpg)

That is weird because they are all over there and I haven't changed the game files whatsoever.

**Comment by simsulla** [comment]
Sorry, I see. It is after greater Poland decision. Reopening.
