### ISSUE TITLE
More mistakes in Brazil

### ISSUE THREAD

**Issue by cesarcurado** [simsulla/nwomod#13]
First of all, you forgot to rename the incorrect Brasilia to something else in localisation.
I suggest the name "Poços de Caldas". Province id is 2446, btw.

Because of Rio Grande do Sul's cores inside Brazil, other countries will declare war on Brazil a lot to liberate the cores. Since the idea of a independent RGS died in the regencial period of the Empire of Brazil, it makes no sense to keep the cores in the late 40s and up

A few suggestions now.
Vic2 uses empire-era names for the brazilian provinces, and many of these name have changed.

Desterro (2461) should be Florianópolis, named after president Floriano Peixoto in 1891.

Sabará (2442) should be Belo Horizonte. Sabará is a small town and BH is one of the largest cities in the country and the state capital.

Dourados (2416) should be Campo Grande.  Campo Grande is much bigger and is the the state capital, also closer to the ingame province.

Tarauacá (2549) should be Acre. Acre is the name of the state where the province is. Tarauacá is the 4th most populous city in the state of Acre.

And finally, Forte São Joaquim (2532) should be Boa Vista. It is the state capital of Roraima, while Forte São Joaquim is an old fort which once existed in the region and now lies in ruins.

Thanks for the mod.

**Comment by simsulla** [comment]
Thanks for the bug report :+1: 
2446 renamed to Poços de Caldas.
Will keep the Rio Grande do Sul corese for "vic2 historic" reasons.
Will change the names.
