### ISSUE TITLE
Danzig

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#141]
Should the Free City of Danzig still be in the game by the time? Seems wrong to me

**Comment by simsulla** [comment]
Agree, but long term (i.e. when hoi4 gets out) we are going to make a hoi4 to NWO converter, and then Danzig may very well have a role in the mod.

**Comment by Liegnitz** [comment]
That sounds grat alway wanted to play NWO in the world before WW2 in the late twenties to beginning of the thirtees, but the thing with Danzig is it gets liberated way too often by Germany or Russia and once even GB (at least in my games).

Maybe making it impossible to be liberated like the CSA in vanilla would be an option until hoi4?
