### ISSUE TITLE
Lebanon join greater arabia

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#143]

**Comment by Stupinator** [comment]
what's the issue?

**Comment by simsulla** [comment]
It does not according to an error report on the paradox forum. As it is primary culture christian Arab and not Sunni Arab.

**Comment by Stupinator** [comment]
not joining the greater arabia is accurate. primary culture christian arab is not.

**Comment by simsulla** [comment]
Acctually I tend to agree. The current shia/sunni nature of arab politics, supports this. Instead there will be an alternative pathway to incorporate Lebanon, earlier (when arab politics was mor secular - Nasser....) as part of UAR (see #91)
