### ISSUE TITLE
Megali Idea (Greece) not working properly.

### ISSUE THREAD

**Issue by recc42** [simsulla/nwomod#145]
When you use the Megali idea decision you get your cores on turkish land but you don't get a casus belli to get them, also i think the decision is bugged because it says (*) you have to be on a sphere of influence and it only works when you are NOT in a sphere of influence.

**Comment by simsulla** [comment]
Agree. Will remove that requirement.

**Comment by simsulla** [comment]
The decision is correct it is just that the Vic2 popup text is incorrect, it states "is in sphere" even if the decision is set to "part_of_sphere = no" as requirement. 
You do get the cb (acquire_core_state always = yes) as long as your ruling party does not have pacifism as policy.
