### ISSUE TITLE
interface color

### ISSUE THREAD

**Issue by Stupinator** [simsulla/nwomod#149]
the colors on the interface are too dark to see anything properly.

**Comment by simsulla** [comment]
Let's take a specific view and I will modify it to make it more readable, and then we will use it as guiding for further improvements. What view is the most "unreadable" to you?

Note: the dark theme correlates to the upcoming theme in hoi4 and will remain.

**Comment by Stupinator** [comment]
that would be the research view.

**Comment by simsulla** [comment]
Less contrast for NWO fonts - need if ok, do this for all fonts. Tech window - black text -background made brighter to better see the text.
