### ISSUE TITLE
Some provinces are colonial though set to be civilized

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#17]
Example of colonial state.
![image](https://cloud.githubusercontent.com/assets/10263809/11834382/415198f0-a3cc-11e5-91ba-c1fd4cb2f7cf.png)
But set to be civilized
colonial = 0

**Comment by recc42** [comment]
did you get help with this? do you want the whole world to be set to be civilized or just some specific places?

**Comment by simsulla** [comment]
Please have a look. I don't know why they are colonial. 1992 the whole
world (except some colonial areas like South Sudan) is civilized.

**Comment by VictorWeikum** [comment]
Have you tried giving more colonial points to all the countries in this trouble? I'm playing for China and it has -332/112

**Comment by simsulla** [comment]
States (regions) are defined in map/region.txt
But colonial points only matter if you colonialze...

**Comment by simsulla** [comment]
will decade this issue to wont fix...

**Comment by VictorWeikum** [comment]
Colonial points are also needed to make colonies states. With them China could make them states when there is enough bureaucrats of chinese culture. A crappy way to solve this problem, but still a way

**Comment by simsulla** [comment]
It is done per province. colonial = 0 (civilized)

**Comment by yf22** [comment]
I have commited a tool to export core data from history files to excel,which may help.If it is not enough,I would write another to export colonial data to excel list.
