### ISSUE TITLE
Chrashes everytime I select a nation and press play

### ISSUE THREAD

**Issue by felipekgamer** [simsulla/nwomod#173]
In the mod version 1.0.3

**Comment by simsulla** [comment]
Do you have the right version of Victoria 2 herat of darknes 3.0.3?
Have you downloaded the complete NWO zip file?
Do this;
1 .Remove the old NWO installation (mod/NWO folder mod/NWO.mod) 
2. Redownload the mod
3. Unzip to tne mod folder. You will have a mod/NWO folder mod/NWO.mod file.

**Comment by felipekgamer** [comment]
I don't know what happened, because I always opened the file and copied the files directly, but know it worked, could you explain to me?

**Comment by simsulla** [comment]
:) I am closing the issue
