### ISSUE TITLE
The game is crushed when it is loading 'adapting history' ?

### ISSUE THREAD

**Issue by walter1111** [simsulla/nwomod#174]
I have just installed New World Order mod v1.03 for Victoria 2, After I choose a country, the game would crush to desktop when it is loading 'adapting history'. How to solve this problem?

**Comment by simsulla** [comment]
Do you have the right version of Victoria 2 herat of darknes 3.0.3?
Have you downloaded the complete NWO zip file?
Do this;
1 .Remove the old NWO installation (mod/NWO folder mod/NWO.mod) 
2. Redownload the mod
3. Unzip to tne mod folder. You will have a mod/NWO folder mod/NWO.mod file.

**Comment by walter1111** [comment]
I use Victoria 2 heart of darkness 3.03.

I download the mod from this website:
https://github.com/simsulla/nwomod/archive/v1.0.3.zip

is the nwo mod that I download correct? is it a complete one?

**Comment by simsulla** [comment]
Yes the zip is correct. And vic2 version is correct.

**Comment by walter1111** [comment]
I've remove the mod and download and install it again. But the game is still crushed when it is loading 'adapting history'

**Comment by simsulla** [comment]
Did you clear the cache? I.e remove the C:\Users\???\Documents\Paradox Interactive\Victoria II\NwO\gfx and map folders.

(??? is your windos user name)

In the logs (C:\Users\???\Documents\Paradox Interactive\Victoria II\NwO\logs) what does the setup.log say (the last lines)?

**Comment by Liegnitz** [comment]
Also try to verify the game files by steam, so you have NSPY as checksum.

**Comment by walter1111** [comment]
For the setup files in logs, The last line is:
[provincemanager.cpp:737]: Finished creating province collision data.

**Comment by simsulla** [comment]
Yes, you have Vic2 v3.01, it should be v3.03. You need to patch your Vic2.
