### ISSUE TITLE
AI Superpowers Sphere

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#176]
When the AI controlls the European Union it doesn't adds smaller nations with European Cores into it's Sphere of Influence. It keeps staying at 100 and Friendly status, even when no other nation attempts to sphere the samller nation. 
I saw the same happening with the North American Union and some Caribbean Minor States.

**Comment by simsulla** [comment]
Have you tried, saving and then reloading the game? I have seen the same. Suspect it is a core Vic2 bug/feature

**Comment by simsulla** [comment]
I will close this iseu with some minor corrections to the defines.lua, hoping that this will address the core Vic2 bug/feature, of geting 100 in influence but not sphering. 
Setting MAX_INFLUENCE = 101, i.e. surpassing the required 100 hopefully making the AI sphere. Please reopen issue if you find the same problem with 1.0.4.
