### ISSUE TITLE
formation of Mercosur

### ISSUE THREAD

**Issue by lucaslima101** [simsulla/nwomod#185]
UNASUR and Mercosur aims to bring together all Latin America, from Mexico to Argentina, then tods countries that will receive the cores of Mercosur? and Mercosur with this a bug or bad frmação a country attaches the new nation at the time of formation.

thank you

**Comment by simsulla** [comment]
Mercosur should form UNASUR (South American Union). You need  (continent = south_america) and (Mercosur or Andean Community) to form UNASUR (South American Union). Forexample as Brazil first you form Mercosur. Than as Mercosur form the South American Union.

I do not understand your bug report?

**Comment by simsulla** [comment]
Pleas reopen if you feel my explanation is insufficient.
