### ISSUE TITLE
Return to democracy in South America

### ISSUE THREAD

**Issue by Chratos** [simsulla/nwomod#21]
When the governments turn into presidential dictatorships i can't turn back then to democracy even making all the reforms to turn back the elections and freedom of expression. I really don't know another way to do that whitout making giant rebelions againt the dictatorship.

**Comment by simsulla** [comment]
We need to ad a generic presidential_dictatorship event chain allowing the player to move in steps toward democracy in 10-20 year period. Any one that want to dig into modding NWO please start on the event chain. I have it on the "to-do sometime in the future" list.

**Comment by simsulla** [comment]
There will be a decision chain for this;
step 1. new_constitution - create a new constitution, reducing militancy by promising a future presidential plebiscite.
step 2. presidential_plebiscite - first step towards accepting the will of the electorate.
step 3. transition_to_democracy - back to democracy
Tech and militancy will drive these changes.
