### ISSUE TITLE
space technology?

### ISSUE THREAD

**Issue by walter1111** [simsulla/nwomod#232]
There is space race between USA and USSR during the cold war. Space technology also become more important nowadays and in future. Is it possible for the mod to add some features about space technology, space industry and space race?

For example, if we have high space technology, we can see the locations of all armies of our enemies or even the whole world, have some economic or military buff, etc.

**Comment by simsulla** [comment]
The space race is in the mod as events, but not as techs or invention paths. Fog-of-war is not modable I am afraid. However will look into making "Space tech" invention as spinoff to researching base-"technologies"

**Comment by simsulla** [comment]
Limited fix. Added some techs.
Anyone that want to work on the space tech is more than welcome to do so. Such enhancements will get into the mod.
