### ISSUE TITLE
Ghost armies left over after winning KMT civil war

### ISSUE THREAD

**Issue by repaxan** [simsulla/nwomod#237]
After winning the chinese civil war, I'm having some PRC "ghost" armies left over in the mainland China, the same way it happens sometimes in normal Vicky 2.

this does stay after it turns me from KMT into China as well.

**Comment by simsulla** [comment]
I believe this is a core Vic2 bug. If PRC (or KMT if PRC is winning) are in the mist of mobilizing when loosing the war the mobilization continues, in-spite of the nation no longer existing.

**Comment by simsulla** [comment]
Will introduce a concept of developing nations (national value nv_development). On effect of being a developing nation is no mobilization, which will remove the ghosts, and also address some other dis-balances (like Israel vs Egypt) and for most better describe modern warfare (from the Korean war and onward) where war material is the limiting factor not manpower.
