### ISSUE TITLE
Demographic transition events

### ISSUE THREAD

**Issue by myownrule** [simsulla/nwomod#239]
Starting in the 1992 bookmark, the demographic transition and fertility rate events only fire once and once the negative fertility modifier is gone, it doesn't get replaced and the population starts growing again

**Comment by simsulla** [comment]
The demographic transition will be setup and then removed depending on geographical location. The Fertility rate event fires every 20 years or so setting modifiers that lasts a subset of that time, resulting in an more or less accurate growth over the 20 year period. Do you have a save game I could have a look on?

**Comment by myownrule** [comment]
I'm getting 20-30k pop growth as japan in 1996.
Here is a save from the 1st of january a couple of days before the fertility modifier expires:
https://www.dropbox.com/s/0qzv85e8byu14sw/Japan1996_01_01.v2?dl=0

**Comment by simsulla** [comment]
A the time of the save, you loose 2,5k pops/month. And your provinces have the modifier "self-fulfillment-values" causing people not having children. The demographics event kicks in when the country modifier fertility timer expires. In every 20 years, so around 2012. I will reduce the positive pop growth effect of some of the reforms.
