### ISSUE TITLE
Israel Higher Education Rate 1992

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#240]
By 除非是250
这破mod1992以色列开局0高等教育率，全国犹太人都是文盲，非洲黑叔叔的文化水平都能碾压。而且没有本土，巴勒斯坦地区是殖民地

![image](https://cloud.githubusercontent.com/assets/10263809/13561709/8169f00a-e430-11e5-8833-b2010a064b26.png)

**Comment by simsulla** [comment]
In part Literacy higher education increase rate #273. Else no idea why Israel summed literacy 1992 is wacko!!?

**Comment by simsulla** [comment]
![image](https://cloud.githubusercontent.com/assets/10263809/14326778/c3fd72e0-fc2f-11e5-82c5-25dabe687af8.png)

**Comment by championzhao** [comment]
NWO\history\provinces\soviet\2687 - Amderma.txt

owner = SYR
controller = SYR
add_core = SYR
trade_goods = fruit
life_rating = 15
terrain = hilly_farmland
colonial = 0
1992.1.1 = {
owner = ISR
controller = ISR
add_core = SYR
life_rating = 15
colonial = 0
}

**Comment by simsulla** [comment]
from #346
