### ISSUE TITLE
Mod not initializing/default Vic 2 map start

### ISSUE THREAD

**Issue by psidaipr** [simsulla/nwomod#243]
When the mod first initializes, it creates the texture quads and its own NwO folder, but when it finally loads, it's just the default Victoria 2 game start. I have uninstalled the mod and reinstalled and it does the same thing.

**Comment by simsulla** [comment]
1. Do you have Victoria 3.03 (or 3.04)?
2. Have you installed NWO in the game mod foled (NWO folder and NWO.mod file)?

**Comment by psidaipr** [comment]
I have 3.03 installed.

NWO folder and .mod file are in the mod folder.

**Comment by simsulla** [comment]
what does the game.log and setup.log say (the logs are in ...Documents\Paradox Interactive\Victoria II\NwO\logs)

**Comment by psidaipr** [comment]
[game.pdf](https://github.com/simsulla/nwomod/files/163484/game.pdf)
[setup.pdf](https://github.com/simsulla/nwomod/files/163485/setup.pdf)

**Comment by simsulla** [comment]
I see you are running V2 v3.03, good, but loading vanilla - as you say. 
So, your download unzip must be corrupt. What is the content of the NWO.mod file? 
Please re-download and unzip again,,

**Comment by psidaipr** [comment]
I figured it out, it seems for the Steam version it needs to be in the mod folder located in the Steam folder rather than the mod folder located in My Documents > Paradox Interactive > Victoria 2.

**Comment by Dank-memester10171** [comment]
I have the non-steam version this fix doesn't work, what should i do in this case?

**Comment by simsulla** [comment]
You  install the mod files (NWO.mod and NWO folder) in the mod folder of your Victoria 2 installation. 
Where is your Victoria 2 installation?

**Comment by Dank-memester10171** [comment]
I have already done that; my installation folders are Madz folder/Games/Victoria2
But the graphics still render that way
I'm running 3.03 if that helps

**Comment by simsulla** [comment]
What files/folders do ypu have in 
Madz folder/Games/Victoria2/mod?

**Comment by Dank-memester10171** [comment]
Both of the nwo files and the pdm mod files and that's all

**Comment by simsulla** [comment]
Check your logs (you can open them with notepad) can you see any indication of why the game does not load. For you (Madz) probably the logs usually are in C:\Users\Madz\Documents\Paradox Interactive\Victoria II\NwO\logs

**Comment by Dank-memester10171** [comment]
I apologize for the late reply but i just recently cleared my hard drive so i have a fresh install all ready. Do i extract directly to the mod folder?

**Comment by simsulla** [comment]
The downloaded zip file contains a nwomod folder with a NWO folder and a NWO.mod file in it. It is the NWO folder and NWO.mod file you place in the mod folder in the Victoria 2 installation folder.

**Comment by simsulla** [comment]
closing please reopen if you feel that the issues has not been addressed.

**Comment by Dank-memester10171** [comment]
Regardless of how fresh a mod download is every install seems to fail in it's own way. Either through never loading all the way up or making it to the main menu then crashing. Or crashing when i try to boot up the game even with the vanilla graphics. It appears as if always without fail, the graphics never load the way they are supposed to. Even with the simple directions of "extract to mod folder." could this just be the mod? Or am i missing a step?

**Comment by simsulla** [comment]
You don't have the right version or are installing incorrectly.
Let's start with verifying your installation.
1. Can you play vanilla Vic2? What version is displayed in the lower left corener? It schould be v.3.03 or v.3.04.
2. Are you able to play some other mod like PDM?
3. Have you downloaded the NWO zip file? What is the name of the zip file. Where have you extracted the NWO.mod file and NWO folder?

**Comment by Dank-memester10171** [comment]
Yes i can it is 3.03
Yes along with vickymod and such. 
Yes i have downloaded both the "nwo-master" and "nwo 1.05" (i am away from my computer these are just general) i tried both with complete reinstalls of vicky both were unzipped to the mod folder

**Comment by simsulla** [comment]
The vic2 nwo wiki (and paradox forum thread) contains link to the download file. It is called _nwomod-1.05.zip_.  Do **not** clone the repo and try and play from master (head). Then what you play is undefined. When you get to your PC, please check what you are using..

**Comment by Dank-memester10171** [comment]
I have not done that i have made sure to reinstall vicky everytime for a clean start. 
I tried the "nwomod-1.05.zip. That did not work either.
