### ISSUE TITLE
  formation of Mercosur

### ISSUE THREAD

**Issue by lucaslima101** [simsulla/nwomod#245]
the Mercosur and composed of all the South American countries, but Mexico and panama also part of this union, then these should be integrated apises also at the time the new nation is formed

Thanks!!!!!!!

**Comment by simsulla** [comment]
Isn't Mercosur a South American block? Mexico, New Zealand are observers but not members.

**Comment by lucaslima101** [comment]
more participate in board meetings and are indirectly linked to Mercosur

**Comment by simsulla** [comment]
Mexico i just an observer. There are Associate states mostly in the Andes. The model as it is in NWO now is that you first form your primary union (Andean or Mercour), then form the South American Union.
![image](https://cloud.githubusercontent.com/assets/10263809/13661318/f84837be-e691-11e5-921f-b0ba22bd34ea.png)

For Mexico, at the moment it is part of NAFTA. I am open to give Mexico an alternative "Latin strategy", that would endup uniting with Mercosur countries as part of a "super-super-union" of Latin America. But need IRL reference for what that alt-history path would be (like greater Central Amreica including Mexico????)

**Comment by lucaslima101** [comment]
that the alternative of Mexico go to the two sides would be a great idea
both South American Union or NAFTA, would give a greater degree of
alternatives within the game

2016-03-10 3:33 GMT-03:00 simsulla <notifications@github.com>:

**Comment by lucaslima101** [comment]
creating a race for control of the Americas, a major NAFTA or a big South American Union.



It would be really cool!

**Comment by simsulla** [comment]
Mestizo is that race. 

For Mexico what should AI Mexico do? It has to choose path, NAFTA or SU.

**Comment by lucaslima101** [comment]
Therefore, I will give as an example the United States and Brazil, which put Mexico in its area of influence wins Mexico as part of their marriage, may be part of the two or both NAFTA SU

**Comment by lucaslima101** [comment]
this would be a good addition to the game

**Comment by lucaslima101** [comment]
will add this update in the mod?

**Comment by simsulla** [comment]
Ok, Mexico AI will do a now default to NAFTA. But if it gets into the sphere of a Mercosur or South American Union it may instead go for that block (btw - the same should apply to the Central American Spanish peaking countries).

**Comment by lucaslima101** [comment]
great, this will make the game much more dynamic

**Comment by simsulla** [comment]
Corrected in 1.05. Not: only possible to incorporate central america and Mexico as South American Union. Not possible as Mercosur. As Mercosur form SU then expand into Central America.
