### ISSUE TITLE
CANZUK (Commonwealth) Union

### ISSUE THREAD

**Issue by CANZUK** [simsulla/nwomod#251]
Not an issue per se, but I've been enjoying NWO and threw together a set of changes that let the UK (or an ANZ/CAN GP) align with its former dominions instead of the EU, and figured you might be interested

https://www.dropbox.com/s/a5zg33dp7u3yfm2/Commonwealth%20NWO.rar?dl=0

Changes:

- Split White Anglo into Anglo-Canadian, Australian, New Zealander, White American and White Anglo (which is now mostly diaspora in the Caribbean and Africa) to avoid the Commonwealth accepting Africans and Americans
- Split Black Anglo into Black Anglo and Afro-American
- Merged Scottish, Welsh and English into British again
- Made Union decision chains less cluttered by moving some allow conditions into potential
- Added the Commonwealth of Nations, a CANZUK union
- Modified the NAU, Pacific and EU decisions so a nation going for CANZUK (and its spherelings) can't simultaneously go for a different union

Possible future changes:

- Liberal, Progressive or Socialist governments accepting White/Black Anglo and potentially including South Africa (already only Black and White Anglo) and, at a stretch, other Black Anglo countries.

**Comment by CANZUK** [comment]
Addendum - there's a vanilla bug with pop assimilation where the luxury needs group is arranged backwards so none of the bonuses apply until 90% luxury needs, and I noticed that isn't fixed in your pop_types file. If you want to fix it, it should go from luxury_needs = 0.1 to luxury_needs = 0.9 rather than the other way around.

**Comment by simsulla** [comment]
When I have time I will have a look, on your changes. I like the Commonwealth idea. I can see the rationale in splitting white Anglo, but why merge Scottish, Welsh and English into British. Making the Union decision chains less cluttered makes sense.

The bug with pop assimilation will be fixed in 1.0.5.

**Comment by CANZUK** [comment]
Was mostly to keep the number of cultures lower so my crappy computer didn't struggle overly hard, it's not an essential component at all.

Feel free to get a better flag and better decision images if you do decide to incorporate the Commonwealth, they're currently uninspired at best.

**Comment by simsulla** [comment]
Of time constraint need to put this off till 1.06
