### ISSUE TITLE
Event bug

### ISSUE THREAD

**Issue by Ares020** [simsulla/nwomod#257]
I've been trying to make the mod work for hours now, but I don't see a way to fix my issue, so I'm in need of your help...
It starts just as it should and everything is fine, except for the event texts. It just shows EVT_[NUMBER]_DESC in the text box :(
I've already tried downloading it from another source, completely reinstalling the whole game, using the 3.04 beta, changing the language, clearing my cache and changing the directions to nwomod but nothing seems to work :(

**Comment by Liegnitz** [comment]
Have you changed the language via Steam or on the settings.txt? 
It only works when doing it on the settings.txt

**Comment by Ares020** [comment]
I have changed it both on Steam and in the settings.txt and when starting the game without the mod it is in english, but when starting the mod it stays german :O

**Comment by Liegnitz** [comment]
The mod also has a settings.txt did you change that too, make sure you change both.

**Comment by Ares020** [comment]
I can't believe that it was this simple! Works fine now! Thanks a lot, you saved my holiday :)

**Comment by Liegnitz** [comment]
No problem :)

**Comment by simsulla** [comment]
Resolved
