### ISSUE TITLE
Military Composition

### ISSUE THREAD

**Issue by Drasila** [simsulla/nwomod#262]
I have read the wiki looking for the best military composition and i found it, but i didn't undestand quite well the army composition ( the navy is easy), can you explain it better to me?

**Comment by simsulla** [comment]
So, this is a "bug" report for the wiki page :). I will update the description as part of the 1.0.5 release. 
But the simple answer is "Experiment - and suggest the optimal formation (and if you find it unrealistic, please report it as a bug)

**Comment by simsulla** [comment]
The wiki has been updated with a better explanation of the NWO military system.
