### ISSUE TITLE
Reunion of Cyprus Decision

### ISSUE THREAD

**Issue by JoshuaBD** [simsulla/nwomod#263]
Other split nations (notably Korea and Germany) have decisions to reunite the nations if you have both halves sphered, but Cyprus does not.

I'd like a peaceful of doing so without needing to simply invade one of my spherelings.

**Comment by simsulla** [comment]
Cyprus is different. East and West Germany had German majority populations. North and South Korea, majority Korean. This is not the case for Cyprus.
