### ISSUE TITLE
The Warsaw Pact and Soviet Union always diband by 1965

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#264]
By Sooawesome36
2) The Warsaw Pact and Soviet Union always diband by 1965. It ruins immersion and breaks a lot of the fun
By Simsulla
2. Do you have a save from like 1964 that I could investigate. There are a couple of paths to breakdown of the USSR, like militancy or having to back down in the cold war.

**Comment by simsulla** [comment]
Need save file from reporter

**Comment by VictorWeikum** [comment]
Some crazy shit happened to me as well. While I played for Cuba (which I decided to stay democratic), Soviet Union renamed itself into Russia and became a democracy, but did not lose any territories, except for Baltic republics. They separeted about a half-year before. SU gone into war with Lithuania and the US to install communism on L. It did not end with SU turning into democratic Russia with liberal government.

Before all that a number of countries stopped beign satallites of the SU. Now Bulgaria, East Germany and North Korea are satellites of Russia.

It all doesn't seem unreal (can't say about chances, I only played this version once), but I think that SU should've not renamed into Russia even becoming a democracy, if it doesn't get dissolved (need to make SU a country with cores or a communist name of Eurasian Union). And the war with L. should've stopped, of course. 

Here are saves for analyse:
https://onedrive.live.com/redir?resid=54A943E8FE4717B8!76328&authkey=!AGlZNCp90sw4IzU&ithint=folder%2c

**Comment by simsulla** [comment]
TheReaper,
3. I think the 9.00 militancy trigger for the Soviets' collapse should either be removed or heightened, because as it is you can be blatantly winning the Cold War on every front and control half of Europe and then suddenly collapse without warning because you forgot to keep an eye on your militancy. (I think this might also be why the USSR keeps collapsing so soon when the AI plays it). Maybe make it so that Consciousness AND Militancy both have to be high?

**Comment by simsulla** [comment]
@VictorWeikum on your comment. This relates to using SOV instead of RUS cores for the Soviet Union. I will add your comment to Soviet Cores #310

**Comment by simsulla** [comment]
Will keep the militancy trigger as that after other corrections kicks in early 1980s. Added Brezhnev Era event reducing militancy.
![image](https://cloud.githubusercontent.com/assets/10263809/14759350/7df9d3bc-0920-11e6-8b97-36c7ec499d32.png)
