### ISSUE TITLE
increase the playing time - 2100

### ISSUE THREAD

**Issue by lucaslima101** [simsulla/nwomod#270]
It would be more interesting if u increase the mod of playing time for 200 years, and even acrecentasse random events related to lack of raw material in the world in the future

**Comment by simsulla** [comment]
We can move the end date to a even number 2100. But no pans for even longer play, as the tech tree needs extending and no plans for that at the moment.
Raw material shortages in the timespan 1946-2100. Don't know which RGO that IRL is likely to become in shortage of?

**Comment by lucaslima101** [comment]
also to give better enjoy the game
I got it, thanks
