### ISSUE TITLE
Should be realistic Nuclear War weapons and atomic extinction

### ISSUE THREAD

**Issue by semiimes** [simsulla/nwomod#280]
Hi guy, can you make ? Is it possible?

**Comment by simsulla** [comment]
This has been discussed in the NWO paradox forum thread: https://forum.paradoxplaza.com/forum/index.php?threads/new-world-order-mod.823674/page-192#post-20693187

Quoting some exchange by simsulla:

_Currently there are two ways you may use nukes;
1. Tactically: if the war is going south for you (i.e. your provinces are occupied), you may use nukes tactically - if you have nukes, making the enemy troops become in disarray, for a while.
2. Nuclear Peace: If you have the nuclear trident (ICBM's) you may threaten with mutual destruction, thus forcing a status quo peace (also only if the war is going bad for you).
How does it work in ultimate mod?_

The defensive military and deterrent effects of nukes are in the mod. What Ultimat has is offensive nukes targeting civilians. Historically (NWO shall be realistic ;)) this was on the table in the 40s and 50s. But then it was limited tactical, not an all out Armageddon strike as an viable offensive. In addition Armageddon just destroy game play, and in particular lets individual players in a multiplayer setting do disruptive things offence - which is not god game design. 

However, I would consider limited tactical nukes. But that is difficult do mod else than what is already in the mod. With that said, once hoi4 is out and we see how they did nukes there, I'll revisit the request.
