### ISSUE TITLE
Spratly Island not port Province

### ISSUE THREAD

**Issue by LordNotix** [simsulla/nwomod#289]
I am unable to build a port on Spratly Island due to it not being a "Port Province"

**Comment by LordNotix** [comment]
Shenzhen (2681) and Chaozhou (1949) also appear to have this issue.

**Comment by simsulla** [comment]
Chaozhou (1564) is in the middle of China. No port.
Corrected Shenzhen (2681).
Moved Spratly Island port to water tile. It has a port.
