### ISSUE TITLE
Southeast Asia Population Growth Not Great Enough

### ISSUE THREAD

**Issue by YoureAwesome** [simsulla/nwomod#291]
Population growth in Southeast Asia (Indochina, Indonesia, Philippines, Malaysia, Singapore, etc.) is not great enough; population from 1946 consistently does not match countries' respective populations in 1992.

**Comment by YoureAwesome** [comment]
Possible solutions include raising the life rating of provinces in SEA from 30 to 35.

**Comment by simsulla** [comment]
It should be part of the population trends. Will uses this ticket for another round of pop growth tuning.
