### ISSUE TITLE
Bank Factory Template?

### ISSUE THREAD

**Issue by allen9212** [simsulla/nwomod#294]
The bank factory template in production_types doesn't get used. I thought that a factory using clerks for thoroughput is a good idea for the end game when western europe gets >60% literacy and too many clerks. These clerks are then dumped into other factories where they go over 20% and be useless because they dont affect thoroughput.

**Comment by simsulla** [comment]
Originally it was put in the game as a credit producer. I like your ide, to having a bank factory employing clerks and giving pop a late game need for "credit" produced by the bank - i.e. need for housing loans.... Label it as enhancement.

**Comment by simsulla** [comment]
This relates to #398
