### ISSUE TITLE
Nerfing China and India

### ISSUE THREAD

**Issue by LordNotix** [simsulla/nwomod#295]
It might be nice to add some flavour to Communist China, USA and Indonesia by having an event chain to simulate the US's Rubber Embargo on China.

It should have 1 end in which China changes some of the resources of Yunnan to growing rubber.

Perhaps it could start with the US embargo, increasing China's import costs.
Then Indonesia has an option to sell China a large amount of rubber, in exchange for money and increased influence/relations with China and decreased with US.
Whether it's accepted or not China could then have the option to begin trying to grow it themselves (At an initial efficiency hit)

If you want any more info: http://www.tandfonline.com/doi/abs/10.1080/09592290801913700

**Comment by simsulla** [comment]
Great idea. Please make the event chain. It will get into the mod.

**Comment by simsulla** [comment]
Will change the content of this issue to contain two points
1. Nerfing China by more general US embargo on Communist China.
2. Nerfing India by start of game Raj heritage of "deindustrialization".
