### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Ed-Balls** [simsulla/nwomod#3]
1. Select New World Order 0.9.13.1 in Victoria 2 Heart of Darkness 3.03 Launcher
2. Game Launches handily dandily, and as soon as it gets to 'Initializing Map', it outputs this error.
3. http://i.gyazo.com/816beb161f826bf5813b33564ab70b2e.png
File Exception! 
File exception:
Exception in discfile.cpp, line 83. Description: Could not open file:
 map/../nwomod/NWO/map/definition.csv

This occurred on 0.9.11.1 as well, checking off 'Read Only' on the files and Running the Launcher as administrator did not stop this issue.

Thank you for the beautiful mod, you're doing god's work, thank you in advance for fixing this start up issue.

**Comment by Ed-Balls** [comment]
Deleted all Mapcaches in Documents, Created Quads for Vanilla with v2game.exe. 
Deleted nWo folder in ParadoxPlaza/Victoria2/Documents. 
Deleted all trace of NWO from computer.
Redownloaded NWO, put it in my mod folder again.  
Came up with exact same error. 

Vanilla game works fine.

**Comment by Ed-Balls** [comment]
Reinstalled the game 
Got a friend to give me his /My Documents/Paradox Interactive/Victoria II/NwO/
Got another version of Victoria 2, updated it to 3.03
Paradox says it has something to do with the 'time' file inside the map cache, but I can't delete that, because NWO won't get to the Quad creation before it crashes.

Pretty desperate for fixes.

**Comment by jimhoobing** [comment]
Ed-Balls  Try make new folder name nwomod at your vic 2 installation, and place your mod there.
And edit your NWO.mod, change the path into path = "nwomod/NWO".
http://www.victoria2wiki.com/NWO

**Comment by simsulla** [comment]
Issue corrected in the latest release. 

If you check out the mod directly from the Git Repo and install it in mod/NWO, 
you will get an error like;
Exception in discfile.cpp, line 83. Description: Could not open file: map/../nwomod/NWO/map/definition.csv

1. Either edit the mod/NWO/map/default.map
#definitions = "../nwomod/NWO/map/definition.csv"
definitions = "../mod/NWO/map/definition.csv"

2. Alternatively you can (as I do when I develop), have my checkout in Victoria 2/nwomod,
and then update the mod/NWO.mod setting path = "nwomod/NWO"

**Comment by simsulla** [comment]
Duplicate: see NWO STARTUP AND INSTALLATION PROBLEMS #46
