### ISSUE TITLE
How to form India?

### ISSUE THREAD

**Issue by Stalhrahm** [simsulla/nwomod#315]
I tried playing as Hyberderbad and India was released in 1947 like it historically did, but when I play as the RAJ I never get the event until 1970 or so. What can I do to fire the event at the time given? It seems the event chain doesn't work as the RAJ when I play as them. I'm using the patch for the beta as well.

**Comment by simsulla** [comment]
Where you still around 1947-48 a UK puppet/vassal? If not you are the Dominion of India, and remains so (as was envisions in the 20s by some in the UK as a future for India, similar to other dominions)
