### ISSUE TITLE
Soviets to influence the outcome of event chain for communism in Italy

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#323]
by Dish of fish
Is there an event chain for communism in Italy? If so, how can I as the Soviet Union support it?
By Simsulla
There is an extensive event chain in Italy for potential communist take over in the 40s/50s. But at the moment not possible for the Soviets to influence the outcome. I will create an issue for enabling the Soviets to marginally influencing the outcome by using national focus and encouraging communists in Italy.

**Comment by Yefimov** [comment]
When not Darkest Hour's-style with event for USSR?
- full support
- support
- ignore
