### ISSUE TITLE
KMT flee to Taiwan with Chinese pops migrating

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#331]
by officialsunday
Secondly, when the Republic of China gets the event to flee to Taiwan, I think there should be a pop increase on Taiwan to simulate the flight of the anti-communists, who fled mainland China to Taiwan with Mr Chiang. Of course, rather than Hokkien culture, they should be of Chinese culture.

**Comment by wzh190015** [comment]
Most of the pops they brought to Taiwan are famous generals,powerful bureaucrat and warlord(maybe not so powerful after arriving Taiwan)and influential scholars.So I think the pop is not only increase in quantity but also in quality

**Comment by yf22** [comment]
No need to increase the population growth as it is possible to force pops to relocate from mainland.

**Comment by simsulla** [comment]
My idea was to move some soldier/officer pops from Nanjing area to Taiping. Creating a POP bump for ROC, correlating to the migration during that period. It would also enable ROC to maintain a sizable army.
