### ISSUE TITLE
New tag for West Germany？

### ISSUE THREAD

**Issue by yf22** [simsulla/nwomod#339]
At the momment,the West Germany share the same tag with the reunioned Germany,causing several problems
1 West Germany (or FRG) has the entire DDG territories as its cores,allowing it to declare war on DDG
anytime while the DDG cannot do the same to FRG.
2 The problem with cores also give rise to the revanchism in FRG

**Comment by simsulla** [comment]
There is a Sonderweg decision that removes GER core on DDR. See decitions/Germany.txt. No FRG needed.
