### ISSUE TITLE
Merge Chinese NWO with English NWO

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#340]
The idea is to minimize the work needed to maintain the Chinese version, by incorporating some of the changes in the Chinese version in head (like Arial font in .gfx, .gui) . Then in best case only the actual font files and localization need maintaining in the Chinese version. 
We would create a Chinese branch, and push any bug fix in the master to the Chinese branch. Then at master release, create a Chinese branch "pre-"release, for completion by championzhao78 and others before publishing the corresponding Chinese release at Baidu.

**Comment by yf22** [comment]
Unfortunately it would be impossible as the Chinese edition in fact replaced the English localisation because there is no way to let the game support a new language.

**Comment by simsulla** [comment]
Added description to explain my thinking..

**Comment by yf22** [comment]
It would be great.

**Comment by championzhao** [comment]
So cool,It would help  Chinese players, thank you
