### ISSUE TITLE
AI not use casus belli to take core state(s)

### ISSUE THREAD

**Issue by nightfirexiv** [simsulla/nwomod#341]
cb_types (acquire_core_state) 

it does not work for the AI (against not sphered nations)
have tried it this with the basic game (acquire_core_state)  casus. what works
the Issue is the line i think:

NOT = { THIS = { ai = yes } part_of_sphere  = yes } # the ai shall not attack a sphered nation.
		
That is my suggestion:
OR = {
			THIS = { ai = no }
			part_of_sphere = no
		}

**Comment by yf22** [comment]
The problem is that we should not use multiple conditions under one NOT as it means none of the conditions should be met.The AIs as they are,they cannot declare the war with this CB in any circumstances.It is of necessity to add an AND.

**Comment by nightfirexiv** [comment]
"Annex Core Country" need the same correction
