### ISSUE TITLE
3D Graphics and Graphics UI

### ISSUE THREAD

**Issue by yf22** [simsulla/nwomod#345]
At the momment,the following can be achieved
1 Replace a 3D unit model with a 2d image plane (e.g counters)
2 Replace any of the static models on the map except railways with another 3D mesh.(e.g forts ,naval bases,train stations)
3 Create an 3D object that can be displayed in a certain province which can be enabled or disabled via events and decisions.(Paradox intially was to use this on the Effier Tower in Paris and the Big Ben in UK,however it was canceled.I think it could be used to display nuclear attacks on the map)
The syntax is set_province_flag = [object name]

Do you need 3d graphics for NWO？If you do,list all the requirements and I will then provide necessary 3d models as well as textures.
But it would take some time.

**Comment by simsulla** [comment]
yf22 if you could work on the graphics it would be absolutely fantastic! 

1. Unit: current 3d models are ww1:ish, please replace them. 
2. Map 3d models: The mod could do well with some modernization. In particular the city model. 
I see forts as air bases. 
Current city models are really not good.. 
![image](https://cloud.githubusercontent.com/assets/10263809/14409506/47abbe3e-ff15-11e5-9b3b-a972fd5c9854.png)
3. Dynamic objects: It is a great ide. We could add set_province_flag =.. in the nuclear war events, and with timer remove it. Unless you have the models second priority.

Keeping the Prime Directive of historic realism in mind, you have totally free hand on graphics in NWO. 
:+1:

**Comment by yf22** [comment]
The problem is that I cannot modify any animated object like units without a game crash.So I replaced them with counters in my own mod（which is still a 3d mesh from ck2 with modified texture）
Do you want to maintain their current appearance or replace them with 2d graphic？
ps:Besides the units,all the other requirements is possible.

**Comment by simsulla** [comment]
Start with 2. and 3. And we will get back to 1. To me iconified land units are ok, like in hoi2.

**Comment by simsulla** [comment]
Will use this issue to address some other 2D graphics complaints that has been raised by some users.

**Comment by simsulla** [comment]
Any progress on the 3D Graphics and Graphics UI #345?

**Comment by simsulla** [comment]
No feedback. Closing issue. Please reopen if you intend to work on it.
