### ISSUE TITLE
Rename proletarian_dictatorship to People's Republic

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#348]
By Zero
1 China had not a proletariat dictatorship in 1992 and it lead a huge error that China will filled communism
in parliament，than very easy to social reform。It is not realistic
2 Tuanpai as a conservatism or liberalism，Taizidang as a conservatism more suitable，Chinese communism have many little folk factions，like Maoist Trotskyism and Anarchist，Although they have a lot of contradictions，They have a consensus: CCP is a regime of bureaucratic capitalism， in general they are called as the New Left and the CCP’s supporters make a difference
By simsulla
1. and 2. the alternative to proletarian_dictatorship is "western" democracy. I believe most players of NWO including the Chinese government views China as a peoples democracy. I will rename proletarian_dictatorship to People's Republic.

**Comment by yf22** [comment]
Actually the official name is the people’s democratic dictatorship.It is still a proletarian dictatorship according to the consitution.And the concept of state system and the system of government are quite different.So there is no need to change the localisation,and in fact,it is incorrect.

**Comment by simsulla** [comment]
And it will stay a proletarian_dictatorship. Only the localization will change. Many communist regimes called them selves People's Republic or Democracies. In case of China the name of the country is People's Republic, as for many other see https://en.wikipedia.org/wiki/People%27s_Republic. To me it seems like a more fair name than ... dictatorship, a term more suited for various juntas.
