### ISSUE TITLE
Remove race as culture denominator and assimilation rate

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#356]
by 逗逗爸 
I try to adjust the assimilation chance, and use China, Australia, France were tested respectively, work is well, Are you interested in test it?

`
[pop_types.txt](https://github.com/simsulla/nwomod/files/216383/pop_types.txt)
`

**Comment by simsulla** [comment]
waiting feedback on tests by Championzhou.

**Comment by simsulla** [comment]
This is a screen shot from Americas 2099 - late game. Assimilation is far gone and unrealistic as "donimating-race" has assimilated all
![image](https://cloud.githubusercontent.com/assets/10263809/14927803/65ee51a6-0e54-11e6-937e-17e66db341a5.png)
However something seems strang as "local" dominating groups tends to assert a hold on regions, or have extremely pointed migration? Like in China, also 2099
![image](https://cloud.githubusercontent.com/assets/10263809/14927869/c61b1866-0e54-11e6-8fe7-a9fc8cdd9862.png)

**Comment by VictorWeikum** [comment]
That's because you represent skin colors as cultures in the mod. I'd recommend to remove them from the game, or give unique modifires of assimilation rate to some cultures like in the original game. -1000% for black anglos for example.

What happend in China actually is realistic. In reality China used artificial mesures to assimilate southern peoples into Han, such as proclaiming their languages "dialects" and not teaching them in schools. It didn't work well enogh though and now southerners slowly and peacefully getting what theirs back.

**Comment by simsulla** [comment]
The "new world" cultures following race lines is a political mine-field. But culture is a way to mod "identity politics" (like 90% of African American being democrats, and increasing attention to the Hispanic vote. But also other places like Bolivia - Santa Cruz being against Morales who has strong native american support.).

**Comment by simsulla** [comment]
Not sure what to do with this issue. Maybe reality is something along the lines pops tend to only marginally assimilate into local old world cultures - instead what happens is an assimilation into something else - a new common identity (a statist identity, think about superstates like the EU). In Britain immigrants are much more likely to be "British" than English and more likely to be pro EU than (local)nationalist. What is happening today seems to be what happens in old imperial Rome - tribes eventually where assimilated into a new imperial language based identity of Romans and Greeks. And those Romans did not correlate to the old "latin tribes" that initially build the empire but pops how had been assimilated into the empire (Philip the Arab, the Illyrian Emperors.. eventually non of the emperor where old latin. Eventually emperors even took pride in having Punic origin - Carthage the old mortal enemy of Old Rome!). This is difficult to mod in Vic2, don't know how to solve it... One could have new super state identities that have higher assimilation rates (like european for EU, maybe mestizo for the Americas, the different black linguistic cultures for Africa).

**Comment by heythereguys** [comment]
I have an idea for the Americas and Oceania.
Why don't we assimilate immigrants into their own race-based cultural groups? For instance, Chinese, Koreans and Viets could become "Asian Anglo", Nigerians and other Africans could become "Black Anglo", Indians and Pakistanis could become "Subcontinental" and Mestizos/White Spanish could become "Hispanic" when in an anglo country like Australia and the USA.  Maybe even an assimilated MENA culture for these countries. These minority racial cultures could also exist in the UK, and have an option to become accepted cultures as soon as London became a white minority city IRL.

I'd also definitely support union cultural groups, except in the various Muslim-world Unions and Eurasia (which would be a bit less integrative and mixy-mashy culturally and more ethnically-conscious, I imagine. Also potentially the Pacific Islands Federation and Latin America, because I don't see a need for a new common identity emerging there). I think ASEAN would make a new cultural identity as a part of the "ASEAN way" descision, and while it would be Malay-influenced I don't see Indonesian being anything more than an accepted culture. North America too could get a cultural identity, seeing as by the point North America gets any sort of political union it'd realistically be an ethnic ball-pit- perhaps "Americano"? It has a nice feel to it for starters, and while Mexicans aren't gonna take over the USA they could realistically influence American English with those sorts of quirks like Germans and Yiddish did.

**Comment by heythereguys** [comment]
Also, pls stop the slow white portuguese takeover of Brazil in every single game. It's annoying, seeing as basically everyone in Brazil has higher birth rates than the whites do and minus mass eviction I can only see one demographic trend resulting from that.

**Comment by simsulla** [comment]
The problem is that Vic2 only supports assimilation into the primary culture. So it is not possible to assimilate by culture group or some other grouping to any thing else than the primary culture (in case of Brazil Brancos (White Portuguese). The only workaround is to make the (as a game event/decition) mixed identity (mestizo in latin america, pardos in Brazil) the primary culture.

**Comment by simsulla** [comment]
Will use this as issue for the enhancement of removing "race" as cultural separator in the mod - with some special exceptions when race is denominates race based voting blocks like in the US.

Some posts from the forum:
**simsulla**
One aspect of NWO that has given rise to a lot of critique is the use of (quasi-)races as cultures. Although in some cases culture (and political affiliations - which is the Vic2 game mechanics that is used) does follow (rough) racial lines (afro american are such example) those are exceptions that should not base design. In addition using race creates problems with regards to assimilations, as assimilation would be into a "mixed race" (US President Obama is a mixed race example). Vic2 does not support that
Simsulla in retrospect regret this design decision, but have not done anything about it as it requires a lot of work. 

So the questions is what should these cultures be in the Americas? My current thinking is that native american/aborigines cultures will be kept. But race cultures (black, white, mestizo) should be something else. Remember that "culture" together with "cores", "religion" are factors to mod political forces in Vic2 so they have and should have complementary roles.

What are the cultures of Brazil? What are the Cultures of the US, Canada and Latin American nations?

**austrianemporer**
It really depends. Brazil has an unique race system where discrimination happens but racism (obvious ones) don't happen. (http://www.economist.com/news/inter...ing-influence-brazil-country-whose-population) The US is a melting pot, it has been for centuries. There has always been populist backlash against immigration but always, eventually, immigration triumphed. The US should have a slight bonus to assimilation for that representing the fact that over the decades, the children of the children of the parents have mostly integrated into American society. The Irish, Italians, Greeks, etc used to be considered "non-white" but now they are considered white, many of the Japanese immigrants from the 1800's have assimilated, etc. I am not clear about South America or Canada. 

**simsulla**
So what should the cultures of the US be? Only Anglo(-american)?
 
**austrianemporer**
That is a difficult question to answer. There will always be certain minorities that will not consider themselves Anglo- American, no matter what even after integration and assimilation efforts, some will still remain. Afro- American and maybe Asian- American, Indian- American, etc (basically, people that, despite intermarriage once, will still be considered "minorities") are minorities in the US and should be accepted at some point. Thats the basic general overview but then, America has produced people like Ben Carson, who looks black, but can be considered an Anglo- American rather than Afro- American. Therefore, I think, if a pop is getting luxury needs, is happy (low militancy and consciousness), and is a minority, it should assimilate into the Anglo- American culture. I just don't know if that's possible with accepted cultures. I've seen assimilation of accepted cultures but that was once and never happened again so I don't know if its possible to mod that in. 

**Crash301**
The way I see it with the American cultures, I think Afro-American should of course be an accepted culture (at least by the 60s), and since they are both distinctly "American" and distinct from "Anglo" Americans (or any other subsets), assimilation to Anglo-American should not be a necessity. For the purposes of the game, as long as you have equal rights, it wouldn't make any difference gameplay-wise. If anything, if it's possible to make African or otherwise black immigrants inclined to switch to Afro-American instead of Anglo-American, that would be preferable.

As far as other cultures, Asian American can be included, though given things like income and the relatively small population, they can be assimilated into Anglo-American, with some population of Chinese, Vietnamese, Japanese, etc in California, New York, and big cities to represent cultural enclaves.

As for Hispanics, it's rather complicated by the fact that Hispanics can be black, white, mixed, basically they're no one race, so if we disregard race, we can keep them as Mestizo (which originally meant a mixture of Native American and Spaniards), perhaps an assimilation to anglo-American (if they never become assimilated.)

We'll also have areas of Native Americans (Navajo Nation in Arizona, Sioux in the midwest, others, particularly Cherokee in Oklahoma.) If we are going to go the full route of accepting any legally accepted cultures, then they should be accepted, though they do have a history of forced assimilation. I'm not quite sure what to do with them, if someone with more knowledge would like to give their thoughts on this (and everything else), that would be great.

**simsulla**
Leaving race and instead focusing on culture, yes Ben Carson is a nice example. and also in the opposite direction, Obama is an example of a person with no Afroamerican culture (his mother was Anglo and his father Luo). According to the US census he is mixed race - but politically he is defined/define him self as Afroamerican - i.e. assimilated into afroamerican culture. Unfortunately Vic2 only supports assimilation into the primary culture.

Removing race, this is a suggestion for cultures in general (not only in the Americas)

1. Native cultures - by language or religion (Irish, Serb, Croat, Shia arabs, Druz are defined by "ancestral" religion)
2. Neo cultures - by language (English - Anglo, Spanish - Latino, Portuguese - Brazilian, Afrikaans - Afrikaner)
3. Neo subculture - by voting block (it is this rule makes Afro-american a separate culture as they vote persistently by race in elections.).

**austrianemporer**
Technically, you can also assimilate into an accepted culture but it doesn't apply because the game favors the primary culture. 

Both 1 and 2 are viable. 3 is hard to say, race has been a declining factor in politics for decades and is only coming back now in a temporary surge. In a century, perhaps racism will be gone in some places as humans gradually become more "progressive".

**simsulla**
Yes, this is why culture in NWO should not be race based. Having "progressive values", as part of game play has been a key ambition in the mod. I hope it gives it a fair representation within Vic2's limitations ,where "progressive" values, in a broader sense include views on alternativ family structure, LGBT rights, feminism and views on immigration. AND the mod should also feature the consequences of POP's and society assuming progressive values, with in Vic2's limitations.

However cultures / ethnicity should be in the mod, in particular as we want to model as part in political forces defining society, and looking on voting affiliation in elections from Gallup polls afroamerican vote as a group, 
Black (non-white) % vote for Democrats (before 2000 no separation)
Code:
2012 95 (89)
2008 99 (90)
2004 93 (83)
2000 95 (87)
1996 82
1992 77
1988 82
1984 87
1980 86
1976 85
1972 87
1968 85
1964 94
1960 86
1956 61
1952 79
There is a clear race bias in voting among blacks. This is a reson for them as a separate culture. 
By contrast "whites (including hispanic "white") vote non-racial (i.e. are split among the Rep and Dems).

**Comment by simsulla** [comment]
**Dveduu**
Does the reverse hold true- Does Islamization promote assimilation into the muslim cultures?
**simsulla**
Assimilation of Muslims into a primary with Islam as state religion should be possible, as well as seculars to the state religion (though at a very slow pace).

**Comment by simsulla** [comment]
For Latin America
![image](https://cloud.githubusercontent.com/assets/10263809/25273838/d92e815c-268d-11e7-860d-050f36272dc5.png)

For US -American English, Canada - Canadian English, Brazil - Brazilian Portuguese. Thus Brazil would become much less diverse.
Some race cultures will be kept - i.e. when race is a significant factor in voting patterns (like Afro American will remain) .

EDIT: A goal is to move towards a 1:1 core(or sub-super-state core):culture relation. Keeping religion as an language overriding culture separator - with the culture common religion secularization as a pathway to assimilation into the primary culture.

**Comment by arandomperson5000** [comment]
For the U.S I do think it is possible that additional cultures could be added along with American English for example Southerner as there is still a quite strong cultural divide between the northern and southern U.S today 150 years after the civil war ended which could make the overall cultural landscape of the U.S in NWo similar to that of vanilla Victoria 2.

**Comment by simsulla** [comment]
Yes, one could use the [dixiecrats electoral performance 1948 ](https://en.wikipedia.org/wiki/United_States_presidential_election,_1948)as an indication of size of the dixie population (making a guess for States' Rights Democratic Party support in the southern states where they ran as third party).

**Comment by simsulla** [comment]
New Latina American culture map...
![image](https://cloud.githubusercontent.com/assets/10263809/25565539/e9e14ed4-2dc8-11e7-9d1c-1358bdfb5c06.png)
and
![image](https://cloud.githubusercontent.com/assets/10263809/25565543/f2af2004-2dc8-11e7-9134-10e4627985be.png)
