### ISSUE TITLE
Doubt about administration

### ISSUE THREAD

**Issue by Drasila** [simsulla/nwomod#361]
Seems like putting the administration spend bar on max does not incentivate more bureaucrats like in vanilla, is that true? So to get full administration efficiency i will have to manually incentivate them? And if so, how much bureaucrats in each province will i need?

**Comment by simsulla** [comment]
Sorry missed your question (bug report)
Optimal is 1% + 0.2% per social reform. 
If all reforms are taken c.9% of pop. Will fix bureaucrats promotion in 1.06
