### ISSUE TITLE
Allow Communist nations to form/join Eurasia

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#363]
TheReaper
2. I think it should be possible to create Eurasia as a proletarian dictatorship - If the Soviets survive until 2020 and research the prerequisite technologies, it makes sense for them to be able to reform their state to adapt to new technologies and globalization, and if the entire point of Eurasia is for a post-Soviet Russia to be able to remake the USSR, then a renewed communist Russia should definitely try to form it.

**Comment by VictorWeikum** [comment]
It would be Soviet Union then. The original point of it was to unite communist states of the whole world during the global revolution. United only 15 republics though.

**Comment by simsulla** [comment]
By forming Eurasia as communist it will be possible to make the Soviet Union rice form the dead :)
