### ISSUE TITLE
I changed the final data mod. I can?

### ISSUE THREAD

**Issue by Sussudio** [simsulla/nwomod#379]
Hello! First I want congratule for your amazing mod. I changed the final data mod of 2092 to 2999, I will have any problem? I will change the savegame too? How? Thanks!

**Comment by simsulla** [comment]
If you change to 2999 you need to update all common/countries end date for political parties. See #270 changes for which files.

**Comment by Sussudio** [comment]
Thanks! I will have normal events and newspapers until 2999?

**Comment by Sussudio** [comment]
certainly, what are the changes in version 1.05 ?

**Comment by simsulla** [comment]
it was in #350.
See https://github.com/simsulla/nwomod/commit/87d1e4b5339c175bf8ce187e151719b13294f0a4

**Comment by Sussudio** [comment]
When the party expires in 2092 don´t have somthing wars, newspapers, events, decisions... Is this?

**Comment by Sussudio** [comment]
I have change all countries data end politic parties to 2999.

**Comment by simsulla** [comment]
Then you can continue the game.

**Comment by Sussudio** [comment]
Very thanks by Spain! ;)
