### ISSUE TITLE
Rename Aristocrats

### ISSUE THREAD

**Issue by Yefimov** [simsulla/nwomod#380]
I really hate these guys.
Why should we see "aristocrats" in XXI? You changed "priests" to "teachers", let change "Aristocrats" to, IDK, "RGO's director".

And maybe make bureaucrats in Proletarian DIctatorship as a rich class (and they make work of Aristocrats and Fabricants).

**Comment by simsulla** [comment]
Aristocrats are RGO bound. In a modern industrial society they would be modern farmers, as the rural laborers have been replaced by tractors and machines in any industrial society, composing no more than 1-2% of the total population. Farmers/miners are instead working largely in service professions. Service professions are not moddable in a good way in Vic2. I will rename Aristocrat "Land owner".

**Comment by Yefimov** [comment]
Nice idea, but... What about socialism? I mean, there are usually no right for owning any land in socialism.
Maybe you should make message event what tells to player that after the revolution all "land owner" become a new bureaucrats or smth like this.

In fact, you can make a lot of events about economic regulations after the revolution.

**Comment by simsulla** [comment]
You bring up a good point. To some extent it exists for capitalists under kommunism. They are demoted. This demotion should become more brutal and also apply to landowners (aristocrats). No capitalists and landowners have economic cosequenses well in line with irl communism. Will create issue for this #395
