### ISSUE TITLE
Infamy Wars

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#384]
I got jingoistic playing for netherlands. Even conquesting defensless carribean island states it was a poor choice. When I got 35 badboy, first Russia attacked. I hoped they won't get through Europe, but then the USA and France started their own containment. I've capitulated immediatly then.

But with no troops and having to pay reparations to both, I still had another attack from UK. Maybe containment should making badboy zero, what do you think?

**Comment by simsulla** [comment]
Really getting f-d up by the rest of the world if you break "international rules", is a good frame for playing. You can still conquer but have to do it carefully. Also don't see haw to mod in a good way, as just if on high bad boy (infamy) on any peace removing it would make containment way to weak.

**Comment by VictorWeikum** [comment]
I was just pleasing the electorate, they chosed populists, not me) What I meant is more than one successful containment leaving you with no troops is not logical at all. So when it's done, realistically, your badboy should be zeroed and all your containment wars stopped. Unless they added other goals to these wars.

**Comment by simsulla** [comment]
Looking for real world example of containment wars. War on Nazi Germany; If Germany had made a separate peace with the Soviets when they realized they lost on the eastern front, agreeing to disarm and give up taken territory in the east. Would the Western Allies then stop attacking them? Not a chance in hell, because the Nazis where badoys.
A better solution is that a containment war leads to dismantle your empire war or as a World War (in Vic2 3.04) or Great War where great powers allies against you. PDM has some type of cb's for this. 
Maybe that is something to look on.

**Comment by VictorWeikum** [comment]
I meant it's strange to attack a country with no armies. Plus, Soviets and Anglos were allies in one war against nazi Germany. Ok, I'll study this subject and aslo see to if it's possible to merge wars.

**Comment by guisbm** [comment]
would be cool if u pass 25 infamy or more the great power have a event to declare a war on you and that would become a great war

**Comment by VictorWeikum** [comment]
I've got an idea. In PDM mod there are great wars. If you lose one, and you're a GP, your country gets dismantling treaty. It has a very interesting consequences. Let's implement it to NWOs containment wars, with some changes. For example, instead of releasing all vassals, all vassals from other continents should be released, and all provinces you don't have cores on - released or transferred to core holders.

http://popdemandmod.wikia.com/wiki/Great_Wars#Dismantling_Treaty

**Comment by VictorWeikum** [comment]
`
country_event = {
trigger = {
badboy=1 #percentage from 25 set as 0.00 to 1.00
}

option = {
any_greater_power = {
war = {
	target = FROM
	attacker_goal = { casus_belli = dismantle_cb }
	#defender_goal = { casus_belli = [casus belli] }
	call_ally = yes
}
}
`

**Comment by VictorWeikum** [comment]
http://popdemandmod.wikia.com/wiki/Infamy_Wars

**Comment by simsulla** [comment]
NWO shall support both 3.03 or 3.04. So don't use 3.04 only "world war".

**Comment by simsulla** [comment]
Something like the PDM "Great Wars" should also exist in NWO. Pop Demand Mod PDM uses government type "democracy" to restrain warabillity. To restrained maybe. Looking in hoi4 we have a concept of "fractions" based on ideology (socialist, liberals, conservatives are all democratic parties). 
I would like to have a fraction concept in NWO as well. Where "western Democracies" is one fraction. Nations within a fraction can't do war on each others. If you get to much infamy the "fraction" would go to war with you. But not sure how to balance it in a good way and it requires a lot of rework. Will make this into an enhancement issue.

**Comment by simsulla** [comment]
Added Infamy Wars and Great war. All credit to the PDM developers, Naselrus, Rylock et.al.
