### ISSUE TITLE
Problems with some event CBs(Soviet Union)

### ISSUE THREAD

**Issue by imperialbrf** [simsulla/nwomod#39]
When your puppet states start to break up from you as the soviet union you get two options:

One is to just let em go and the other gives you a puppet cb over them.

This puppet CB didn't work for Polan,Hungary,Czechoslovakia and East Germany.

And later when the baltics broke up by event you are supposed to be able to get conquest on them it didn't work with Lithuania.

**Comment by simsulla** [comment]
The Baltics fixed. The satellites, need some testing.
