### ISSUE TITLE
Please add cores for form the Great Colombia and La Plata.

### ISSUE THREAD

**Issue by Sussudio** [simsulla/nwomod#391]
Hello, you can add cores in ecuatorian, colombian and venezuelan provinces for form the Great Colombia and cores to argentinan, chilenan provinces for form La Plata?

**Comment by simsulla** [comment]
(strange I could have sworn I answered this questin!).
Great Colombia and La Plata cores exists in the mod to support coveting PDM, vanilla save games to NWO (as of 1.06). To have "actual cores" in NWO the nation must be plausible in a modern context (NWO "Prime Directive"). To our understanding neither Great Colombia or La Plata is. Please provide references to modern movements for establishing them if they exists.
