### ISSUE TITLE
unions and communitys

### ISSUE THREAD

**Issue by nightfirexiv** [simsulla/nwomod#392]
andean_community.txt
xac_ambition need by
		allow = {
                        NOT = { exists = XSU }
			NOT = { exists = XMS }
because otherwise creates a loop (the country join and abadon the ambition) once the Mercosur or Andean community was founded
the same for the mercosur.txt
	xms_ambition
                   allow = {
			NOT = { exists = XSU }
			NOT = { exists = XAC }

asean.txt
end_xan_ambition
needs a 
		potential = {
			NOT = {tag = XAN}
because the Asean union should not be able to resolve itself and lose the cores!?
this could be the case with the Eu and the North American Union etc.

south_american_union.txt
	xsu_ambition 
           potential = {
                #NOT = { has_country_flag = in_trade_block }
 becaus otherwise mercosur not can join or create the south american union
       xsu_form_union needs 
effect = { 
      add_accepted_culture = white_portuguese
because if mercosur (Brazil) create the south american union white poruguese is replaced with mestizo as primary culture

apology for this complicated kind, but unfortunately I am not familiar with Branches and Pull requests

here the attached and edited data
[andean_community.txt](https://github.com/simsulla/nwomod/files/233732/andean_community.txt)
[mercosur.txt](https://github.com/simsulla/nwomod/files/233733/mercosur.txt)
[asean.txt](https://github.com/simsulla/nwomod/files/233734/asean.txt)
[south_american_union.txt](https://github.com/simsulla/nwomod/files/233735/south_american_union.txt)

**Comment by simsulla** [comment]
@nightfirexiv top job :+1: Will go into 1.06.
