### ISSUE TITLE
Chinese Mainland issues

### ISSUE THREAD

**Issue by officialsunday** [simsulla/nwomod#393]
1. Fujian, the releasable nation is spelled as "Fujan" in the mod.
2. When Guangxi, Guangdong and Fujian are released, there is a Chinese exclave in Qinzhou, which looks quite weird. Maybe add it as a core of Guangxi or Guangdong instead?
3. Canton (and maybe even Shaozhou) should be added as cores of Guangdong, seeing that "Canton" is basically the Anglicised version of "Guangdong"

**Comment by simsulla** [comment]
Fixed
