### ISSUE TITLE
Under communism demote aristocrats(land owners) and capitalists

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#395]
From issue #380. You bring up a good point. To some extent it exists for capitalists under kommunism. They are demoted. This demotion should become more brutal and also apply to landowners (aristocrats). No capitalists and landowners have economic cosequenses well in line with irl communism.

**Comment by Yefimov** [comment]
Some russian mods just remove all aristocrats and capitalist (to peasants and workers), but it's really stupid, because bolsheviks used directors and other bureaucrat stuff for control.
