### ISSUE TITLE
Large state funds will increase pressure for social reforms

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#397]
If the gov accumulates funds, pops will demand more benefits. The social benefits incur significant costs. This will contribute to preventing large accumulation of state funds end game by some nations.
Also with tech and invention the supply cost for military goods should explode.

**Comment by VictorWeikum** [comment]
It's also possible to make events for implementing social reforms and to make upper house giving more yes votes depanding of treasury size.

**Comment by VictorWeikum** [comment]
trigger = { money = x }

option = {social_reform = [reform]}

Reforms are listed in common/issues.txt

**Comment by VictorWeikum** [comment]
option = {
               upper_house = {
	                                 ideology = [ideology]
	                                 value = [n]
                }
}
