### ISSUE TITLE
Majority of Pops Should Promote to Clerks, not Craftsmen

### ISSUE THREAD

**Issue by YoureAwesome** [simsulla/nwomod#398]
Pops currently have a high tendency to promote to craftsmen. However, historically industrialized nations had many people moving to service jobs and becoming "clerks" in the game's time period. Factories should rely more on clerks rather than craftsmen.

**Comment by simsulla** [comment]
What you really want is to re-balance the factories to require more clerks. Will consider it. As well as increasig the importance of capitalist and land owners (aristocrats).

**Comment by simsulla** [comment]
related to #294
