### ISSUE TITLE
A (kinda) partitioned Germany

### ISSUE THREAD

**Issue by cesarcurado** [simsulla/nwomod#41]
If "west" Germany becomes communist and East Germany exists, there should be a way to let both unite as a single communist state.
In the current state, if you use the "Install Communism" casus belli on Germany and win the war, Germany becomes a proletarian dictatorship and goes into your sphere, with GDR flag and all, and east germany still exists as a country.

It would be neat to be able to choose between having the communist united Germany a sphereling or as a full puppet for an infamy hit, too.

**Comment by simsulla** [comment]
yes, will add it.
