### ISSUE TITLE
National focus and ngo focus

### ISSUE THREAD

**Issue by nightfirexiv** [simsulla/nwomod#411]
The ngo focus (foreign policy) don't work. When loading a save game , where you had such a focus enabled, the focus is missing. The party loyalty for the foreign country also does not change. 
I think the focus is a good idea and it would be great if it works.

**Comment by simsulla** [comment]
The focus is preserved over saves, but not clear how the "loyalty" works. I don't see any effect with the vanilla loyalty increase either....

**Comment by simsulla** [comment]
should add Big Tent #447

**Comment by VictorWeikum** [comment]
In vanilla loyalty gives more votes for parties of chosen ideology

**Comment by simsulla** [comment]
Not sure... I belive it (as the name indicate) make pop's more loyal. I.e. they do not swap ideology, event though they ought to by issue preference. So it does not per se give more votes.

**Comment by VictorWeikum** [comment]
That's the thing - make people vote for parties, which ideology is another. So most people can be socialists, but thanks to loyalty they're going to vote for liberals.

**Comment by simsulla** [comment]
I will close this issue, as far as I see loyalty work, but it is a very blunt tool, just making pops not change party. I have increased the "effect" tenfold to vanilla.
