### ISSUE TITLE
About Brazil's government

### ISSUE THREAD

**Issue by MillanAstray** [simsulla/nwomod#413]
In 1946 Brazil was not a dictatorship, the 'Estado Novo'(Vargas Dictatorship) endend in 45, later in 1951 he was elected president again,now democratically, then he commits suicide. 
Another thing, Vargas was Populist from the PTB(Partido Trabalhista Brasileiro) party, he was opposed to the UDN(União Democrática Nacional), ironically  UDN is the party in power in Brazil in the beggining of the scenario.

Sorry for any English mistake and thanks for this great mod!

**Comment by simsulla** [comment]
The elections happened [1945 in Brazil](https://en.wikipedia.org/wiki/Brazilian_general_election,_1945).

**Comment by MillanAstray** [comment]
Yes, I know it. But in the game Brazil begin as a dictatorship and only turns into a democracy after the Vargas Suicide event that happens only in the 50's. Brazil should start as a democracy and the Vargas event should only fire if PTB is in power.

**Comment by simsulla** [comment]
Sorry, misread your post. Will correct.
