### ISSUE TITLE
Sovietunion after the collapse seemed to have lost little if any prestige

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#42]
Also, Sovietunion after the collapse seemed to have lost little if any prestige, which seemed odd considering their entire empire had just collapsed.

**Comment by VictorWeikum** [comment]
If you mean Soviet Union it should depend on how it becomes a democracy - through collapse and dissolution into 15 republics it was composed of, or through reform into a democratic and confederal union (see
https://en.wikipedia.org/wiki/Union_of_Sovereign_States
https://en.wikipedia.org/wiki/Soviet_Union_referendum,_1991
)

**Comment by simsulla** [comment]
If the Soviet Union " Regime bends under dissent " it will loose 200 in prestige.
