### ISSUE TITLE
Release Nation problems

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#421]
[–]Savolainen
This is a job for /u/simsulla. It's when you select the Release Nations tab? It's definitely a problem with some country files.
permalinksavereportgive goldreply
[–]PopChoc 
Yep, it's the exact moment when I click the tab
simsulla
Don't have the ability to test the game at the moment. What version of NWO? What country did you test?

**Comment by simsulla** [comment]
Unable to reproduce. Closing
![image](https://cloud.githubusercontent.com/assets/10263809/15092099/e0a3a39a-145f-11e6-89a5-d887b639b4fb.png)

**Comment by simsulla** [comment]
EmpireMagnis,
So I was playing as la France, and when I clicked release nation tab it crashed, not sure for other nations; all I know is it crashes for France.

simsulla
Now I am able to reproduce, France 1946 start date.

**Comment by VictorWeikum** [comment]
I had this once, but then I reloaded and everything was fine, could be a core bug.

**Comment by centriccracker** [comment]
Assign Britain and France a new tag?

**Comment by simsulla** [comment]
For Britain this has already been done (ENG->GBR)

**Comment by simsulla** [comment]
Somehow (don't know how - unable to reproduce. Both as UK and France it is possible to release nations both with the 1992 and 1946 start dates.
