### ISSUE TITLE
Some text is broken

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#43]
Some provinces are named after their IDs and the decisions and events have names like "EVTOPTB2000" and the descriptions are missing. The vanilla decisions and events are still fine. Anyway to fix this?

**Comment by simsulla** [comment]
Strange, do you have an example of a province lacking name?

**Comment by Liegnitz** [comment]
Province 2688 in Bosnia, 919 & 916 in Palestine

**Comment by simsulla** [comment]
Unable to confirm: EVTOPTB2000 does have text. From localisation/text.csv
EVTOPTB2000;An excellent opportunity to promote local harmony!;...¨
919 is named Tel Aviv.
![image](https://cloud.githubusercontent.com/assets/10263809/12038543/62b1bede-ae59-11e5-8ad2-1f30ddcf7019.png)

It looks like your installation is incorrect. Please try clearing your cache.

**Comment by Liegnitz** [comment]
This issue appeared because the games language was german not english. Simply changing the language to English in the Settings.txt solved it.
