### ISSUE TITLE
Nerfing Japan and Brazil

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#432]
**By Moridin997**
2. The economy is much better now. However, some countries seem to be disproportionately good. Brazil and Argentina are often strong enough to become GP in the 1950's. Japan also skyrockets into 3rd place some 5-10 years earlier than it probably should.

**By simsulla**
2. 5 years early for japan is good enough. Argentina was a strong nation post ww2, that then was unable to live up to its potential IRL. If someone want to work on events or modifiers for a Argentinian game play, please do it will get into the mod. On Brazil, I agree they get to strong to fast. Probably they needs to get nerfed like China and India. If there any Brazilian players with ideas or views on why Brazil has taken time to develop into the world power of today, please let me know and we will see what can get into the mod.

**By Moridin997**
2. Japan becoming a GP so fast hinders the USA. Eastern Asia should be fertile ground for proxy wars between USA and USSR/PRC. That doesn't happen because Japan will out-compete the USA for those spheres and then, because Japan is militarily average, it won't commit to any conflict with the far stronger Communist GPs. Those 5 years overlap with the French withdrawal from Indochina (and sometimes the Korean War) and are necessary for the USA to be able to sphere those countries before other GPs, so that conflicts can happen in the region...

**Comment by guisbm** [comment]
in Brazil after 1945 we had period know as populism the president didnt give a lot of shit about economy and after that we had a military dictatorship and the militarys also did give a shit about the economy, but i dont know how to make this a part of the game

**Comment by MillanAstray** [comment]
You could nerf the brasilian industry. In my game with Brazil, in 1950 my industry was already in the 3rd place. This is totally unrealistic, Brazil always have problems with industrialization, and in the 50's the industry was very small.

**Comment by simsulla** [comment]
Japan will get a prestige penalty reducing their standing, as well as (if moddable ) military industry penalty.

Brazil (and any other debeloping country), will get a reoccuring event to increase gov party/ideology support by resucing admin and industrial efficiency. Benefit less militancy and more gov support. Downside hidered industrialization.
