### ISSUE TITLE
Pacifism CB restrictions

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#433]
It's strange that with pacifist government you can't start a war for democracy in another country, but can conquer/sphere/make puppet it. Feels like it should be to the contrary.

Also, peacekeeping mission failure should probably give free CB.

**Comment by nightfirexiv** [comment]
I would recommend a part of the cb of PDM or HPM. I pack an example in the attachment 
(I do not know what it looks like with the permission if parts thereof are used)
[cb_types.txt](https://github.com/simsulla/nwomod/files/254024/cb_types.txt)

**Comment by simsulla** [comment]
Point taken on incorporating cb functionality from PDM... but that makes it from a bug into an enhancement.

**Comment by simsulla** [comment]
Victor, please reopen if you feel like correcting.
