### ISSUE TITLE
Transfer of Hong Kong event keeps on popping up

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#434]
@Moridin997 don't see how this can spam. You mean the event "Transfer of sovereignty over Hong Kong" right? There is a check for China that it 
Code:
NOT = { has_country_flag = the_return_of_hong_kong }
the_return_of_hong_kong is set regardless of the UK response.

ClosetedImperialist
Transfer of Hong KONG event keeps on popping up, as the UK I am refusing always, giving me a ton of prestige. What's going on?

**Comment by VictorWeikum** [comment]
fire_only_once = yes

**Comment by simsulla** [comment]
but it is a triggered event... fire_only_once = yes has no effect...
