### ISSUE TITLE
Radicalism and granted reforms

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#440]
Their descriptions say that they vote according to popular demands.

![20160511234918_1](https://cloud.githubusercontent.com/assets/10763931/15227545/71643690-1890-11e6-8e3c-145c5f0de406.jpg)
![20160511234953_1](https://cloud.githubusercontent.com/assets/10763931/15227546/7164a44a-1890-11e6-9304-0298c8ea7ed0.jpg)

**Comment by VictorWeikum** [comment]
Sorry if it's already corrected, I want to play this session to the end.

**Comment by VictorWeikum** [comment]
All movements have constant -24 granted reforms modifier despite no reforms have been granted in decades
![20160512232421_1](https://cloud.githubusercontent.com/assets/10763931/15230456/682df666-189e-11e6-818a-65cad327ce45.jpg)

**Comment by simsulla** [comment]
Populists  and traditionalists should never vote yes to political reform. This is by design. 
Will tune radicalism in the common/defines.lua to lessen the effect of "granted reforms" as there are a lot more of them in NWOthan in vanilla V2.
