### ISSUE TITLE
Political reforms suggestions

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#441]
- [x] 1. Promotion of democratic patries should increase support of Liberals, Socialists and Proggressivists
- [x] 2. Restriction of non-democratic parties should either decrease support of Traditionalists, Populists and Communists or ban them from elections at all (maybe it should be two distinct steps).
- [ ] 3. Decentralisation - completely new branch of reforms, from centralized unitary state to confederation. Should only be possible in democracies. Formed unions should be confederations. The more decentralized, the less patriotic militants. Populistic crowd of major culture should favor centralisation.
  
  a. Centralized unitary state - upperhouse only ruiling party
  b. Decentralization - -20% taxes, upperhouse population vote
  c. Provincial self-rule - -40% taxes, upperhouse population vote
  d. Federation - -60% taxes, upperhouse two by state
  e. Confederation - -80% taxes, upperhouse two by state

**Comment by simsulla** [comment]
Nice suggestion. Not sure how to mod 2. 
If you want to make these reforms please do. I am fine with removing the internet reforms as they are two late game and narrow. This would give you a graphics spot to place this reform set.

**Comment by VictorWeikum** [comment]
Please make me an assignee for issues you want me to close. I don't have much time because of many things in real life, but sooner or later I'll script them.

**Comment by simsulla** [comment]
I have created a github nwomod organization. Will transfer the nwomod repository to it. Will bring you on as a developer, and assign issues to you. But it will take some time as there are a lot of links to simsulla/nwomod that will have to change to nwomod/nwomod. Will do the transfer sometime before the 1.07 release.

**Comment by VictorWeikum** [comment]
How does religious rights work? They don't seem to do anything

```
religious_rights = { #How does this work?
		next_step_only = yes
		state_religion = { 
		}
		no_state_religion = { 
		}
		secularism_religion = { 
		}
	}
```

**Comment by VictorWeikum** [comment]
I think upper_house should be defined not by "decentralisation", but by a separate reform set. Canadian confederation have rich_only upperhouse and jeffeson_method for lower_house elections. How much reform set's slots do we have? And why does voting system tied so strictly to countries?

```
voting_system = {
		next_step_only = no
		first_past_the_post = {
			rules = { largest_share = yes }
			allow = { 
				OR = { 
					tag = AAB tag = AZB tag = BAH tag = BAR tag = BNG tag = BLZ tag = BEU tag = BOT tag = CAN tag = CYI tag = IVC
					tag = COI tag = DMC tag = ERI tag = ETH tag = GAB tag = GAM tag = HND tag = JAM tag = KEN tag = KUW tag = LEB 
					tag = LUA tag = STL tag = LIB tag = MAR tag = BUR tag = MAL tag = MLW tag = MSY tag = MIC tag = NGE tag = NIU 
					tag = OMA tag = PAL tag = SKN tag = SVG tag = SAM tag = SNG tag = SOL tag = SEY tag = SRL tag = SWA tag = TAN
					tag = TOG tag = TAT tag = TUV tag = UGA tag = ENG tag = USA tag = VIR tag = YEM tag = ZAM
				}
				NOT = { vote_franschise = none_voting }
			}
		}
		jefferson_method = {
			rules = { dhont = yes }
			allow = { 
				OR = { 
					tag = ALB tag = ARG tag = AUS tag = BEL tag = BRZ tag = BUL tag = CAM tag = CPV tag = CHL tag = CLM tag = CRO tag = CZH  
					tag = DEN tag = TIM tag = ECU tag = EST tag = FIN tag = GUA tag = HUN tag = ICL tag = ISR tag = JAP tag = KOS tag = LUX 
					tag = MAC tag = MOL tag = MON tag = NET tag = PRG tag = PEU tag = POL tag = POR tag = ROM tag = SCO tag = SER tag = SLO
					tag = BOH tag = SPA tag = URU tag = WAE
				}
				NOT = { vote_franschise = none_voting }
			}
		}
		proportional_representation = {
			rules = { sainte_laque = yes }
			allow = { 
				NOT = { 
					OR = { 
						# first_past_the_post
						tag = AAB tag = AZB tag = BAH tag = BAR tag = BNG tag = BLZ tag = BEU tag = BOT tag = CAN tag = CYI tag = IVC
						tag = COI tag = DMC tag = ERI tag = ETH tag = GAB tag = GAM tag = HND tag = JAM tag = KEN tag = KUW tag = LEB 
						tag = LUA tag = STL tag = LIB tag = MAR tag = BUR tag = MAL tag = MLW tag = MSY tag = MIC tag = NGE tag = NIU 
						tag = OMA tag = PAL tag = SKN tag = SVG tag = SAM tag = SNG tag = SOL tag = SEY tag = SRL tag = SWA tag = TAN
						tag = TOG tag = TAT tag = TUV tag = UGA tag = ENG tag = USA tag = VIR tag = YEM tag = ZAM
						# jefferson_method
						tag = ALB tag = ARG tag = AUS tag = BEL tag = BRZ tag = BUL tag = CAM tag = CPV tag = CHL tag = CLM tag = CRO tag = CZH  
						tag = DEN tag = TIM tag = ECU tag = EST tag = FIN tag = GUA tag = HUN tag = ICL tag = ISR tag = JAP tag = KOS tag = LUX 
						tag = MAC tag = MOL tag = MON tag = NET tag = PRG tag = PEU tag = POL tag = POR tag = ROM tag = SCO tag = SER tag = SLO
						tag = BOH tag = SPA tag = URU tag = WAE
					}
				}
				NOT = { vote_franschise = none_voting }
			}			
		}
	}
```

**Comment by simsulla** [comment]
Victor, please reopen if you feel like correcting
