### ISSUE TITLE
Korea War

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#443]
EmpireMagnis
Again, the Korean war is honestly nothing in this mod. North Korea doesn't have time to prepare and China never joins in. As well as: if NK is released before SK, then the war never happens. In addition, why is the wargoal 'Install Communism'? That doesn't help NK at all, shouldn't it be 'Restore Order', or 'Conquer'?

**Comment by EmpireMagnis** [comment]
Hey, decided to help you out here.
Here is the work I've done so far, just revising the Korean map to make it more accurate. All the Black-White provinces are new ones.
![new korea map](https://cloud.githubusercontent.com/assets/19353850/15263276/7699ad56-191d-11e6-8db2-18f4422db7bf.png)
![new korea map names](https://cloud.githubusercontent.com/assets/19353850/15263280/7b3c0b2e-191d-11e6-81d8-e9104900a8de.png)
I'll try to work on more to add them into the map.

**Comment by EmpireMagnis** [comment]
So I've seem to encounter a problem when updating the map, it seems to crash when loading Quad 1307. I've already tried deleting the map cache. However that doesn't seem to fix it. Any ideas?

**Comment by simsulla** [comment]
New provinces is a lot of work, so I would start with one province, get that to work, and then move on with others. Besides the map and NWO/history/provinces file(s), thes file needs editing in NWO/map
climate.txt:
continent.txt:
positions.txt:
region.txt:
The map needs updating and color mapped (exactly).

The NWO/history/provinces will be overwritten by the generator so don't sped time on details. Just give me the total population and I will provide it to the generator. 
 
btw . why do you feel additional provinces would address the root problem of the Korean War not playing out correctly in the mod?

**Comment by EmpireMagnis** [comment]
Well the only file I didn't edit was the position.txt, because it can be really tedious and I just wanted to see if the provinces work. I just copied and general history from an adjacent province, again, to see if it works.
But I edited everything else, I followed a guide. All the new colors I used were unique.

Here is a file of what I've done, you can just slip these files in and see if you can fix it?
[kk.zip](https://github.com/simsulla/nwomod/files/264608/kk.zip)

**Comment by simsulla** [comment]
@EmpireMagnis, the new Korean provinces will get into the mod, but as part if issue #532. 
This issue will try and address the Korean war.

**KOREA WAR**

- SUN (Soviet) and CHI decition to give NKO weapons, for influence. CHI to SOI NKO. US decition to give SKO weapons.
- NKO aquire core states (Busan, Daegu? and Seol) on SKO. SKO status quo. SKO in US SOI - check SOI nation (NKO) ability to start wars.
- US interven to protect SOI. default behaviour: ?? What is criteria to intervene? Is this configurable.
- war will end with status quo i US win -> when truce expire (has_first_korea_war_flag) US war on NKO aquire SOI core (SKO on NKO): new allied war (involve core allied and SKO and US).
- CHI intervene to protect SOI. NKO/CHI goal status quo. US/SKO goal take NKO.

**Comment by simsulla** [comment]
In the korea_war_second_phase when the US attacks North Korea, South Korea may not join US.

**Comment by EmpireMagnis** [comment]
Shouldn't North Korea's war goal be unite the nation, as well as South Korea? Instead, just add a timer, where as if so many years have past you'll get an event for an armistice. Two choices: 1."We have no choice", or "We will continue to fight". The AI will generally pick 1, but have like a 5% chance that they'll pick 2.

**Comment by simsulla** [comment]
Ok, changed North Korea to civil war against the South. With just a timer to me it is not mod technically possible, to have US and China properly involved in the war.

**Comment by EmpireMagnis** [comment]
Well maybe not a timer, but more or less an event will fire at when the armistice happened irl. With the two choices I stated before.

**Comment by EmpireMagnis** [comment]
And I'm wonder what should happen if RoC wins the civil war with the PRC, will they just not get the event?

**Comment by simsulla** [comment]
added some verifikations to prevent incorrect execution.

**Comment by EmpireMagnis** [comment]
Mhm, so when will the new provinces be added?
