### ISSUE TITLE
Putins Russia

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#444]
See Democratic Russia -> EU #442

**Comment by VictorWeikum** [comment]
There is an event "Khodorkovsky arrest", where Russia may become presidential dictatorship with 50%. Will edit it.

**Comment by VictorWeikum** [comment]
It's 70% chance, must be your correction. Left presidential dictatorship there, as early Putin was more like socialist then populist. No country can join the EU, if it's not a democracy. Will replace this with chain of events about Putin's Russia, but got to make events about 90's first.

**Comment by VictorWeikum** [comment]
To do:

- [ ] 1. Khodorkovsky case - instead of regime change give flag "Putin's Russia"
- [ ] 2. Rig elections - United Russia wins, upperhouse only ruiling party
- [ ] 3. State controls almost all TV and gazettes
- [ ] 4. The tandem, internal opposition, Medvedev goes liberal
- [ ] 5. Massive media campaign in the internet in 201*
- [ ] 6. United Russia switches to populism, or huge jingoism boost.

**Comment by simsulla** [comment]
Of test reasons I prefer 100% chances. It is much, much easier to test then you know what event track the game will take in a test run. in particular it makes trouble shooting a lot easier.

**Comment by VictorWeikum** [comment]
Ok, I'll give 100% chances, although it hurts the mod's variativity.

**Comment by simsulla** [comment]
Added event for transition from Jeltsin to Putin
Democratic Russia
![image](https://cloud.githubusercontent.com/assets/10263809/15634346/dda0edc4-25c1-11e6-893c-fe7478fd9ff2.png)

Republic Russia
![image](https://cloud.githubusercontent.com/assets/10263809/15634349/e3cdb40c-25c1-11e6-98cc-5f1284ca52a2.png)

**Comment by simsulla** [comment]
Event text 
EVT_8014274_DESC;During Yeltsin's presidency (1991-1999) oligarchs became increasingly influential in Russian politics; they played a significant role in financing the re-election of Yeltsin in 1996. With insider information about financial decisions of the government, oligarchs could easily increase their wealth even further. Is it only a strong man in Kremlin that can stop the plunder by oligarchs like Khodorkovsky and Berezovsky. Shall we elect Vladimir Putin to lead a Kremlin purge of the oligarchs?;;;;;;;;;;;;x;;;;;
EVT_8014274_A;End the plunder of Russia by the Oligarchs;;;;;;;;;;;;x;;;;;
EVT_8014274_B;Democracy has its price;;;;;;;;;;;;x;;;;;

**Comment by simsulla** [comment]
Commites with Democratic Russia -> EU #442
