### ISSUE TITLE
Big Tent ideology

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#447]
There will be new ideology added to the game - being mutually exclusive with conservatives - Big Tent to house "Big Tent" political parties, that has a diverse ideological framework, allowing for "Blue-Red states" america, as the Republican will be a Big Tent party - properly colored red.

![image](https://cloud.githubusercontent.com/assets/10263809/15258296/10b5ac3c-194b-11e6-8070-f8d44b0f6044.png)

**Comment by VictorWeikum** [comment]
United Russia is also a big tent.
