### ISSUE TITLE
90's Russia events

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#448]
To do:
- [ ] Post-Soviet territorial disputes
- [ ] Union of Sovereign States and Commonwealth of Independent States
- [ ] War of laws and Federative aggreements - possible satellite republics, Ural republic, bigger Ural republic, possible independent Chechnya, Tatarstan and Gagauzia
- [ ] Constitutional crisis
- [ ] Yeltsin-Gaidar reforms
- [ ] Union State (of Russia and Belarus)

EDIT (by simsulla): moved here from #444 
- [ ]  Khodorkovsky case - instead of regime change give flag "Putin's Russia", which will block joining EU
- [ ]  Rig elections - United Russia wins, upperhouse only ruiling party
- [ ]  State controls almost all TV and gazettes
- [ ]  The tandem, internal opposition, Medvedev goes liberal, possible Putin's retire
- [ ]  Massive media campaign in the internet in 201*
- [ ]  2012 elections, possible Putin's retire
- [ ]  United Russia switches to populism, or huge jingoism boost. Events on Crimea, Novorossia, Russian-populated areas of neighbour countries.
- [ ]  2018 - regime switch to dictatorship or revolution

**Comment by VictorWeikum** [comment]
- [ ] Trump trash decesion - move 28% pops to Canada (ai_factor=0; no alarm by default)

**Comment by VictorWeikum** [comment]
Is it possible to make events for countries that doesn't exist? I'm thinking about making events for some post-Soviet republics about their referendums, triggering their independence and giving former union republics "unite the nation" CB against them

**Comment by VictorWeikum** [comment]
- [ ] 202* breakup of Russia: many states seeking uniting the nation, or seeking independence. Possible confederation. US, EU and Chinese intrusions to keep Russia whole (nobody wants nukes on black market).

**Comment by VictorWeikum** [comment]
Post-Soviet migration (due to fall of iron curtain)

**Comment by simsulla** [comment]
Victor, please reopen if you feel like addressing this issue. I am closing out issues not worked on for half a year.
