### ISSUE TITLE
1.05 full walkthrough bugs

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#450]
I played the mod completely, and got most of bugs playing for France/EU since 2045.

All screenshots with descriptions here: https://onedrive.live.com/redir?resid=54A943E8FE4717B8!78498&authkey=!ACDwWg-SSxKhFgU&ithint=folder%2cjpg

Here's the list of descriptions:

- [ ] 120% of populists vote yes, Churov can do better))
- [ ] The only union formed to 2045 is the EU
- [ ] Algeria fought against Libya for freedom of Islamic State, which became presidential dictatorship. Wat?
- [ ] Huge support for the reform, but traditionalists and populists don't vote for it at all.
- [ ] Nobody gets Luxury Needs
- [ ] When you accept someone in the Union, then they threaten an international crisis, you release them and what the hell is going on? Great power is a satellite oif another great power and is not in the list of great powers!
- [ ] Mauritania joins two unions, one of them is south african, but Mauritania is in the north-west
- [ ] National liberation movements get radicalism from nowhere
- [ ] Provinces Brought Under Control event is ineffective
- [ ] The game thinks that everybody except French and Bretons are immigrants in the EU
- [ ] Granting Independence to satellites takes prestige and influence, instead of giving it
- [ ] 25 millions of people want elections for poor, and they still don't vote for it in upperhouse
- [ ] Unions shouldn't be allowed to have oppression policy
- [ ] Finally they vote for the poors. Traditionalists and populists still don't. Communists should vote for poor as well.
- [ ] Dominant religion in the Union or in the state?
- [ ] Should wars to liberate unions be allowed? Should releasing unions be allowed?
- [ ] Port in province Senj, which does not contact water.
- [ ] Whats the point of taking the decision "a Comminitu of Equal Nations"?
- [ ] Chile gone crazy, probably after Mercosur formation
- [ ] Patriots "freed" Gulf Council, leaving only the capital of Saudi Arabia.
- [ ] Many countries gone crazy
- [ ] Naxatile India forces appeared with no country on the map, during massive civil war in India. Probably appears in provinces with naxatile india cores during communist rebellions.
- [ ] Reform events happen too rare, when you have so much money in treasury
- [ ] Some statistics bug in politics window
- [ ] Support disenfranchised will doubtly be supported by socialists, or liberal socialists. And the crowd will doubtly demand such reform.
- [ ] When radicalism exceeds 100, movements pops become rebels, but if militancy is low, they fastly move back to movements. Exceeding 100 should increase militancy.
- [ ] 9000 soldiers, 12000 of them died, how is that?
- [ ] Gagauzia is in Europe, while the game says it's in Asia.
- [ ] Event about unions changes gender reforms
- [ ] Factory upgrade cost is too small
- [ ] At the and of the mod only EU expanded seriously (I played for it), Northamerican union did not expand after formation (US+Canada), Mercosur (Brazil) got Venezuela and Paraguay
- [x] The game continues after the end, but there is no parties!

**Comment by simsulla** [comment]
The game continues after the end, but there is no parties! Resolved in 1.06.

**Comment by VictorWeikum** [comment]
Not sure if granting independence to satellites should give prestige. I guess it should if nationalists become majority in satellite state and you agree to release them when they ask.

**Comment by simsulla** [comment]
There are lots of bugs here I forgot, mixed with comments questions. Maybe create separate issues for the confirmed errors.

**Comment by simsulla** [comment]
closing... see previous comments
