### ISSUE TITLE
Nuclear Peace Text

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#451]
The text of the event seems to be broken as seen in the picture.

_ requested us to agree... (who?), Nuclear Peace between Germany and Germany;

![20160517124848_1](https://cloud.githubusercontent.com/assets/16386550/15319998/654b276e-1c2e-11e6-8b9c-9017876288da.jpg)

**Comment by simsulla** [comment]
This is a core feature. The text is "Nuclear Peace between $FROMCOUNTRY$ and $COUNTRY$". So the event receiver will have $COUNTRY$ to what ever name the country has. And  $FROMCOUNTRY$ to Germany.
