### ISSUE TITLE
1992 start date

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#452]
When I click on the 1992 start date North Korea is ranked 7th and Japan 14th, but when actually playing North Korea is ranked somewhat lower and Japan is a GP and ranked 4th. Other nations seem to show up wrong too. (Europe, Asia)

**Comment by simsulla** [comment]
This is a Victoria core feature. At load "prestige" is one of the key factors determining rank - overshadowing total rank which game time is the decisive factor. Checkout the 1946 start date you see that some of the GP's are bound to loose there GP status as it is prestige based.
