### ISSUE TITLE
NWO 1.07 beta test

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#453]
@Liegnitz, @VictorWeikum, @EmpireMagnis, there is a NWO 1.07 beta release. Please download and test it . And submit issue if you find bugs.
["New World Order v1.07-beta" # 2016-06-18](https://github.com/simsulla/nwomod/archive/v1.07-beta.zip)

**Comment by Liegnitz** [comment]
Did it. Anythin specific to test out?

**Comment by EmpireMagnis** [comment]
Currently playing a game as Iran in the Cold War start date. So far no major bugs, however I've seen some strange behavior in the AI with this update.
- For some reason, PRC has disbanded/got removed their entire army. Now they are like rank 56. And doesn't seem to want to build their army
- The PRC seems to also have little to no industry after conquering RoC
- DPRK conquered RoK, which doesn't happen at all.
- Soviets let Yugoslavia and Bulgaria form
- Italy is trying to be Romans again and has become quite aggressive.

_I'll edit this more as I progress in my game._

**Comment by simsulla** [comment]
Will

- [ ] Look on why Soviets let Yugoslavia and Bulgaria unite

- [ ] Why Italy always treas and become "Greater".

**Comment by VictorWeikum** [comment]
Desided to test 1992 scenario for Russia, as this is the part of the mod I want to enhance. Found a number of bugs from the start.

Screens: https://onedrive.live.com/redir?resid=54A943E8FE4717B8!80836&authkey=!AOnUe_K-Y1SBnyE&ithint=folder%2cjpg

- [ ] Accepted cultures of Russia should be: nothing at all or Ukrainian and Belarusian. Cultures of republics and autonomies of RF can be added through event "Federal treaty".
- [ ] Armenians have no chances to win this in the mod (while they won in reality). Total rework of post-Soviet conflicts is needed.
- [ ] Too many socialists for Russia of 1992, where people were mostly Liberals.
- [ ] Russian armies have attrition at 1992 start, player always have too split them, which is annoying
- [ ] Russian army placed at chineese province
- [ ] National composition of Nenets autunomous okrug is totally inaccurate. see [https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%9D%D0%B5%D0%BD%D0%B5%D1%86%D0%BA%D0%BE%D0%B3%D0%BE_%D0%B0%D0%B2%D1%82%D0%BE%D0%BD%D0%BE%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D0%B0#.D0.9D.D0.B0.D1.86.D0.B8.D0.BE.D0.BD.D0.B0.D0.BB.D1.8C.D0.BD.D1.8B.D0.B9_.D1.81.D0.BE.D1.81.D1.82.D0.B0.D0.B2](url)
- [ ] Inaccurate state borders in Russia. Need to be redrawn. If ~80 states is too much for the game, we can make in-game states from groups of Russian regions. But let's not put state borders through a region.
- [ ] Some provinces are territorially too big, need to ensure their occupation would take longer than usual.
- [ ] No capitalists in democratic Russia. Only encouriging helped.
- [ ] "Transition of Hong Kong" event made it independent. After which it was annexed by PRC forcefully. Same happended with Macao. Possibly a feature, not bug (alternative history option)
- [ ] 199* crimean events doesn't work right (this one should be for Ukraine, not Russia)
- [ ] Spain in war with Britain, could be a feature, not a bug
- [ ] Text under buttons in "Russian oligarchs" event
- [ ] Wrong ethnic compositions in Canada, for example, there are a lot of Ukrainians in this province [https://yandex.ru/images/search?img_url=http%3A%2F%2Fwww.askpins.com%2Fpics%2F122%2Fwhich-provinces-have-majority-of-canadas-french-speakers.jpg&text=Canadian%20ethnic%20map&noreask=1&pos=0&lr=19&rpt=simage](url)
- [ ] Big tent color is too much like socialist
- [ ] Too many unlikely wars
- [ ] ambon_timor nationality isn't properly named
- [ ] Bougainville seems independent and fine, while in reality there was a war.
- [ ] Big tent has progressive description
- [ ] National composition of Tuva is totally inaccurate, see [https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%A2%D1%8B%D0%B2%D1%8B#.D0.9D.D0.B0.D1.86.D0.B8.D0.BE.D0.BD.D0.B0.D0.BB.D1.8C.D0.BD.D1.8B.D0.B9_.D1.81.D0.BE.D1.81.D1.82.D0.B0.D0.B2](url)
- [ ] States drawn terribly, this province (Bilibinsky) is torn apart from its state by another one
- [ ] Strange Karelia cores, whole Kola state should have Karelian cores, or none of it.
- [ ] Totally inaccurate Sevastopol national composition, see [https://ru.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%A1%D0%B5%D0%B2%D0%B0%D1%81%D1%82%D0%BE%D0%BF%D0%BE%D0%BB%D1%8F#.D0.9D.D0.B0.D1.86.D0.B8.D0.BE.D0.BD.D0.B0.D0.BB.D1.8C.D0.BD.D1.8B.D0.B9_.D1.81.D0.BE.D1.81.D1.82.D0.B0.D0.B2_.D0.BD.D0.B0.D1.81.D0.B5.D0.BB.D0.B5.D0.BD.D0.B8.D1.8F](url)
- [ ] Afghanistan has no ruiling party after theocracy was installed
- [ ] Some reforms have no description/effect
- [ ] Kurdistan was supported by a great power, but did not gain independence (a really good change in 3.04 btw)
- [ ] "The girl from" where? Anyway, whole event about child care in modern world should be changed.

**Comment by simsulla** [comment]
I will comment on the observations and in relevant cases create issues or raise questions when I don't understand. The intent is to close this issue and have individual issues per problem. Please comment if you feel that some problem you raise has not been covered.

**Comment by simsulla** [comment]
**EmpireMagnis**
* For some reason, PRC has disbanded/got removed their entire army. Now they are like rank 56. And doesn't seem to want to build their army.
 _I have observed this as well. Probably a core bug. #501_

* The PRC seems to also have little to no industry after conquering RoC
 _By desing_

* DPRK conquered RoK, which doesn't happen at all.
 _this may happen_

* Soviets let Yugoslavia and Bulgaria unite
_ historic possibility. Less likely but may happen. By design,_

* Italy is trying to be Romans again and has become quite aggressive.
_ Issue #492_ 

* Countries require UN peacekeeping, yet there is no rebels anywhere in the nation.
_criteria are - don't see how this can happen_
```
		OR = { 
			AND = { num_of_revolts = 1 NOT = { num_of_cities = 3 } }
			AND = { num_of_revolts = 2 num_of_cities = 3  }
			AND = { num_of_revolts = 3 num_of_cities = 9  }
			AND = { num_of_revolts = 4 num_of_cities = 18 }
		}
```

* India has no army when released ( India blindly attacks Pakistan and Hyderabad with no army.
)
_unanble to reproduce_

* Afghanistan always invading Pakistan for the freedom of silly tribal areas.
_seems like AI decision. No action_

* Countries spam alliance request unless you lower your relation with thus nation.
_created issue #502_

* Communist GP's never support communist countries during a crisis. It ends up making a smaller communist nation in a big communist nation.
_seems like AI decision. No action at this time, it is very difficult to guide GP actions in crises_

* For some reason, when you tax fully the poor, they get none of their needs.
_observed this as well earlier - but now unable to reproduce,_

*  In the event to release or keep puppet Japan, you lose them either way because they become GP
_yes that is the way it is._
 
* Operation Unthinkable was a joint operation by all the western allies (UK, USA, France, Canada, ect.), yet only the US enters and UK and France don't wish to join.
Correct but no plans to address at the moment. Needs some type of new cb. Enhancement issue #503.

**Comment by simsulla** [comment]
**VictorWeikum** 
Thanks for testing. Btw all liks you posted except the screen link are bad.

* Accepted cultures of Russia should be: nothing at all or Ukrainian and Belarusian. 
_It is_

* Cultures of republics and autonomies of RF can be added through event "Federal treaty".
_suggest taking this as part of the "federal treaty" work item._

* Armenians have no chances to win this in the mod (while they won in reality). Total rework of post-Soviet conflicts is needed.
_Occasionally Armenia wins, there are modifiers that strengthen them._ 

* Too many socialists for Russia of 1992, where people were mostly Liberals or Liberal Socialists.
 Russian armies have attrition at 1992 start, player always have to split them, which is annoying
 Russian army placed at chineese province
_Created issue #504_

* National composition of Nenets autunomous okrug is totally inaccurate.
__Created issue #507_

* Inaccurate state borders in Russia. Need to be redrawn. If ~80 states is too much for the game, we can make in-game states from groups of Russian regions. But let's not put state borders through a region (Komi Republic in this case)  Some provinces are territorially very big, need to ensure their occupation would take longer than usual.
_Will take region issues as part of issue #495_

* No capitalists in democratic Russia. Only encouriging helped. In reality there was enough grey capitalists in 80's, who became legal in 90's
_By design, simulating that Russia lacked a vital segment of competence in the society in early 1990s._

* "Transition of Hong Kong" event made it independent. After which it was annexed by PRC forcefully. Same happended with Macao. Possibly a feature, not bug (alternative history option)
_yes_

* 199* crimean events doesn't work right (this one should be for Ukraine, not Russia)
_Created issue #505_

* Spain in war with Britain, could be a feature, not a bug
_Uncontrollable ai. needs to be adressed by cb constraints. No plans for it at the moment._

* Text under buttons in "Russian oligarchs" event
_that is just explanations. No action_

* Wrong ethnic compositions in Canada, for example, there are a lot of Ukrainians in this province 
_You need to repost your link. Are they still Ukrainian speakers?_

* Big tent color is too much like socialist
_By design. Republicans are red._

* Too many unlikely wars
_Issue #427_ 

* ambon_timor nationality isn't properly named
_Issue #506_

* Bougainville seems independent and fine, while in reality there was a war.
_There is no event for Bougainville independence, so this is the game engine working. No action._

* Big tent has progressive description
__Created issue #508_

* National composition of Tuva is totally inaccurate, 
__Created issue #507_

* States drawn terribly, this province (Bilibinsky) is torn apart from its state by another one
 Strange Karelia cores, whole Kola state should have Karelian cores, or none of it.
_Will take region issues as part of issue #495_

* Totally inaccurate Sevastopol national composition
_Created issue #507_

* Afghanistan has no ruiling party after theocracy was installed
_Created issue #509_

 Some reforms have no description/effect
_Created enhancement issue #510_

* Kurdistan was supported by a great power, but did not gain independence (a really good change in 3.04 btw) (I was playing on 3.03, need to check on 3.04)
_ok_

 "The girl from" where? Anyway, whole event about child care in modern world should be changed.
_will take it as part of #510_

**Comment by VictorWeikum** [comment]
@simsulla link are okay, it's github's bug. Copy them and paste to your browser's adress field. 
On Ukrainians in Canada - depands how you define culture of a man. According to government of Canada, of the 1,251,170 who identify as Ukrainian, only 144,260 (or 11.5%) can actually speak either the modern Ukrainian language or the archaic Canadian Ukrainian dialect.
