### ISSUE TITLE
Voters Ideologies (1946 scenario)

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#457]
Why are the voters ideologies so extremly liberal in Western Nations, but the peoples ideologies not? As far as I know there were rather Conservative countries in power than liberal ones.

**Comment by simsulla** [comment]
This may be is an effect of reforms/no reforms. Voters are engaged pops, that want something changed. When do you observe this - surely in the beginning of the game pops are mostly rural conservative (unless they are "government" supporters supporting whatever party is in power)?

**Comment by Liegnitz** [comment]
Actually right at the start. Might be because liberals are the ruling party though. Adding another question, shouldn't be those liberals in France, GB, USA and GER when it is created rather be conservatives? Liberal weren't that popular before '68.
![unbenannt](https://cloud.githubusercontent.com/assets/16386550/15400682/a7bd6c64-1dec-11e6-8fa7-cdf4385822f3.PNG)
(This is France)

**Comment by simsulla** [comment]
This is because 1946 "the people's ideologies" include a lot of pop's not voting, and France only have registered voting.
