### ISSUE TITLE
NWO STARTUP AND INSTALLATION PROBLEMS

### ISSUE THREAD

**Issue by Keneki** [simsulla/nwomod#46]
Every time I start up the game. It loads fine, but after a few minutes of gameplay, the game just crashes or freezes. I'm not sure what's causing it, as all the other mods I play Vicy 2 on work perfectly fine. Yet this one continuously crashes on me.

**Comment by simsulla** [comment]
Arr you playong on Mac OS X?

**Comment by Keneki** [comment]
No Windows 8.1

**Comment by Mrenrisco** [comment]
I have the same issue. I can start the game but when I choose any country to play the game crashes. 
I'm using windows 10 :/  but even with the compatible mode the mod does not work.

**Comment by simsulla** [comment]
You have Victoria 2 3.03 right ? If you have installed the 3.04 beta patch you also need to patch your NOW mod (search for 3.04 among tickets for a patch link)

**Comment by Keneki** [comment]
I have 3.03 however even with patching it, it just loads normal Victoria 2. I even tried updating to the new beta for Victoria 2 but that didn't do anything either. I'm so confused on why it doesn't work even when I check the box in the mod list before starting vicky 2.

**Comment by simsulla** [comment]
I suggest you reinstall the mod. Remove NWO folder and NWO.mod, Download the zip file and install the mod again. 

No need to patch as you are running 3.03.

**Comment by simsulla** [comment]
Renamed the ticket NWO STARTUP AND INSTALLATION PROBLEMS.

**Comment by tatuhey** [comment]
Hello, I'm using patch 3.03 and windows 10. the game crashed after reaching "Loading database II" and stopped working

**Comment by simsulla** [comment]
3.03 is normal Victoria 2 HOD. It works so something is wrong with your installation. try this
1. remove mod/NWO and mod/NWO.mod. Clear your cache.
2. Verifyt that vanilla Victoria 2 works
3. re-download  the NWO mod zip file, and extract it in mod.It should work.

**Comment by tatuhey** [comment]
okay, I think everything would be fine now. a few weeks ago I messed around my services.msc and fucked myself. I just managed to reverse it now, and the steam redownload the directx that seems to be missing http://prntscr.com/9j25vd

it works now, sorry about that and cheers mate

**Comment by Mrenrisco** [comment]
Oh thank you simsulla, i can play the game now :+1:

**Comment by Bachalia** [comment]
Hey, i'm using Win10.

Every time i go play with the mod, in the "initializing maplogic" appears one error "File exception: Exception in virtualfilesystem.cpp, line 662. Description: Sistem can't find the specified file" and when i click on "ok" the "v2game" stop working.

**Comment by simsulla** [comment]
What version have you installed? Have you downloaded the zip file and
extracted NWO folder and NWO.mod in the Victoria 2 mod folder?

**Comment by simsulla** [comment]
NirelKitsune commented #107
first excuse my bad english.

So it turns out that was trying to play with the mod is not installed normally, but when I start the game and I choose a country he simpleste error and closes. I reintalei the mod and play, but nothing works the first time you open the game with the mod that is for the part of adapting the story and closes, then simply close when I choose a country

**Comment by simsulla** [comment]
1. Check the prerequisites; Do you have Victoria2 3.03 (the latest) or Victoria2 3.04 (beta patch)?
2. If, yes; did you download the zip file form one of the download links?
3. If, yes; did you unzipp it properly in your mod folder. You should in the mod folder have one file "NWO.mod" and one folder NWO.
(4. If you played the mode before, did you clear your cache?)

**Comment by NirelKitsune** [comment]
1- Victoria 2 3.03
2- yes
3- yes
4- I installed it like the mod Pop demand, so I delete the files from the cache folder

**Comment by simsulla** [comment]
And when you installed the mod you removed any old NWO files in the mod folder, right?
What version of the mod are you trying?

**Comment by NirelKitsune** [comment]
right, 1.0.2

**Comment by Keneki** [comment]
Okay so I patched Victoria 2 and I'm reinstalling NWO,

**Comment by simsulla** [comment]
Will close as other venues are used (like reddit, youtube or the paradox forum)

**Comment by medfares1801** [comment]
for me the game work but stop in creating world in nwo mod delete the cache but it do anything and sorry for my bad english

**Comment by simsulla** [comment]
I need to look in your logs. Make a zip file of your C:\Users\YOU\Documents\Paradox Interactive\Victoria II\NwO\logs folder, after you tread to start the game. Send me the zip.
