### ISSUE TITLE
Retexturing the South China Sea Islands

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#467]
They don't look good in their current form. They are to angular.

**Comment by simsulla** [comment]
![image](https://cloud.githubusercontent.com/assets/10263809/15449906/5ecda21c-1f8b-11e6-817c-2cff926d32dd.png)

**Comment by EmpireMagnis** [comment]
You can't do anything since the islands are too small.

**Comment by Liegnitz** [comment]
@EmpireMagnis Don't think so. There are some islands as small as the ones in the picture in Oceania, South Eastern India and in the Pacific (Midway)
