### ISSUE TITLE
The Raj - India

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#468]
Is there a decision or event to form India as the Raj? Because I am currently in 1972 as the Raj and declined some of the events to reform fast. Will I remain the Raj or eventually become India at some point?

**Comment by EmpireMagnis** [comment]
I'm pretty sure there is a chained event that makes you India in the first decade,

**Comment by simsulla** [comment]
There is early in the 1940s an event to end the Raj. But after that no more options. 
 If the Raj survived it would have been as the Dominion of India (including Pakistan....). As it is structured now "The Raj" (tag RAJ) is an "anglo" dominion. So this calls for some "alt history" thinking.

 I am open to suggestion for a decision/event chain for what should happen with the Raj.

**Comment by Liegnitz** [comment]
@EmpireMagnis Yes I know, that there is an event, I first choose to take it, but then India inherited me and the game ended, so I reloaded and avoided it :)

@simsulla I can't say something too specific, because I am not familiar with the situation in India, but I think a event chain starting in the mid/late 50's starting nationalists to demonstrate against the Anglo-Overlordship demanding a unified India (with Pakistan & the Indian Minor States), causing increased militancy, conciousness, lower production output and emigration. This causes a more liberal opposing movement. This would go on until the 60's wheres the player can decide to either go the nationalist way and unify India, with only Indian as accepted culture which would cause tensions in Pak&Bangladesh and as some kind of dictatorship, whereas the more liberal way would also unite India with  Pak&Bangladesh, but rather as democracy, with Indian&Bengali Muslim and Shia also accepted. (causing less tensions). Just a thought.

**Comment by VictorWeikum** [comment]
@Liegnitz @simsulla an event where you can choose to become India beign the Raj should switch the player to play as India.

**Comment by simsulla** [comment]
Playing as Raj relay isn't an option in NWO. You will be perpetually have to fight hindu muslim rebellions.
