### ISSUE TITLE
The Benelux Union as a formable country in NWO.

### ISSUE THREAD

**Issue by DutchDylan** [simsulla/nwomod#473]
The Benelux Union is a union of the three European nations: The Netherlands, Belgium, and Luxembourg, the name originating from a combination of the first letters of each nation's name. 

Between the independence of Belgium and the end of  World War 2 there already was cooperation between these three nations which laid the foundation of the Benelux, a desire for a customs union between the three nations was even present early in that timeperiod. 
In 1841 Luxembourg desired for one and in 1869 there were serious talks about it, with in 1870 the halting factor being a new Belgian government. 
In 1905 the desire for a customs union once again gained popularity with in 1907 a commision being set up to investigate/research the economic capabilites of cooperation between the Netherlands and Belgium, eventually the outbreak of World War 1 made economic cooperation impossible. 
In 1932 the Ouchy Convention took place which was a trade agreement between the three countries and the foundation of a customs union, due to oppostiton of the UK and the USA the treaty never was implemented.
After World War 2 the Benelux came to exist as we know it today, while in exile in 1943 the governments of the three countries signed a monetary agreement in which they fixed the exchange rates of each other currencies and wiped each others debt, shortly after in 1944 they signed a customs agreement.
In 1955 the Benelux Parliament was set up consisting of 21 Dutch, 21 Belgian, and 7 Luxembourgian representatives and came into force on 1959. The parliament consults and advices the three governments on EU issues and affairs.
In 1958 a economic union was set up with its implementation in 1960, this agreement led to the free movement of goods, people, capital and services throughout the Benelux.
In 1965 the Benelux Court of Justice was set up and came into force on 1974 in Brussels, unifying the law and the jurisdiction of the three countries, it has the competence/authority to answer the questions regarding the laws within the Benelux.
In 2000 Belgium and the Netherlands jointly hosted the Euro 2000(European soccer competition) and in 2007 placed a bid together with Luxembourg for the 2018 one.
In 2004 the Treaty of Senningen was signed enabling police forces to carry out its work anywhere within the Benelux. The sharing of information between police forces was easened, and overall increased effiency of the police.
In 2014 the Benelux countries improved their diplomatic cooperation by combining their diplomatic embassies and having their representatives represent the whole Benelux where possible. 

As you can see there's a pretty big gap between the Benelux Court of Justice and the Treaty of Sennigen, this is where the EU(mainly france) halted further Benelux integration. The EU catched up in terms of cooperation the Benelux was at at that point and from that point further integration was at an EU level and not at an Benelux level anymore. Realistically speaking if a Benelux country was to be formed out of the three Benelux nations further integration should take place within that gap and the forming of that nation should take place near the end of that gap, from a player standpoint it will also become very difficult to remain a great power in that period of the game so for gameplay purposes it should definitely be before the 90's.

Gameplay implementations ideas:

-The Benelux countries should start off with higher relations of each other than they currently do, 100 or 150 should be fine, the current low relations between the countries don't accurately represent the Benelux cooperation already established at that point. The Netherlands should also start of with a sligther higher influence level in Belgium and Luxembourg, this to represent the advantage the Netherlands would have over other European nations due to the already established Benelux union.

-One of the three nations needs to be a great power and has to have the other two nations in its sphere of influence for the event/decions tree to work. This represents the Benelux countries not being dominated by the EU as major influence for a union.

-The event/decions tree should work alongside the EU event/decions tree since both coexist together in our timeline and the Benelux was not a halting factor for European integration, although the EU were a halting factor for 'Benelux integration'(see above) it respected the agreements/treaties between the Benelux nations. 

-Benelux popup events should be added representing the developments of Benelux Integration as described as above, granting minor prestige to the Benelux nations and increasing the opinion with small amounts between them. This would help keep a player in great power status and keep the relations high between the countries.

-Benelux decisions should be added allowing the formation of a Benelux nation, only the country which has the other two countries in its sphere should need to enact these decisions, this is to prevent the other countries lacking the tech and not being able to join in time for the end of the time gap. Decisions that could lead up to the formation of the Benelux could be unified public transport, a shared currency, a shared army, and finally a shared government. The 'country_flags' for these decisions should be different to enable the Benelux to still join the EU after it is formed.

-The final decision that forms the Benelux should instantly integrate the other two countries into the Benelux when enacted, the requirements for the decision should be that the other two countries have a relation of near 200 and are in the sphere of the country attempting to form the Benelux.
Furthermore the country attempting to form the Benelux should have enacted the other special Benelux decisions and would need to have researched the techs deemed necessary ('second cold war culture' tech?).

-The Benelux once formed should have Dutch as primary and Flemish and Walloon as accepted cultures, this represents the two official languages of the Benelux, Dutch and French. Dutch and Flemish cultures represent the first official language Dutch which makes up 82% of the populace while Wallloon which represents French makes up for 14%, the remaining 4% are minority langauges which are rcognized but not official languages. For gameplay purposes German and French should not be accepted cultures, to prevent players blobbing into France/germany.

-In our timeline all three countries are a constitutional monarchy which were a minor halting factor Benelux integration, none of the three countries willing to give up their monarch for the other if a country was formed out of the Benelux. Ingame this could be represented by a popup event when the Benelux is formed which prompt the player to abolish/discontinue all the monarchies (Benelux becomes a democracy, minor militancy increase for all pops), choose one of the monarchies to become the main one (medium increased militancy for the pops which monarch wasn't chosen), or keep the monarchs at the regional level of each former country (Stay a government of the realm, minor militancy for all pops).

-For if the government type changes to a populist dictatorship the countryname should be displayed as "United Netherlands" and have Walloon removed as an accepted culture, this is to represent the Dutch majority gaining the upperhand and trying to restore the historical United Kingdom of the Netherlands which controlled what is now the Benelux back in 1830. Optionally, if the government changes to a communist dictatorship the name should be "Union of Low Countries"/"Low Countries Union", this is an alternate name for the region of the Benelux and I thought it would add some flavor personally. If the Benelux somehow becomes a monarchy it should be name "Kingdom of the Benelux"/"Benelux Kingdom", otherwise for any other normal government the name "Benelux" should just be fine.

-The flag for the Benelux for when a Monarchy, Democray of Government of the Realm should be the current flag of the Benelux, for when it is a populist dictatorship it should be the Dutch flag with the upper stripe in orange instead of red to represent the Greater Netherlands idea. The flag for a communist dictatorship should be based of the flag of the CPN and the CJB, I could make all these flags for you ofcourse.

-The names for politcial parties could be standard with exceptions for the following few: Greater Netherlands(Populists), Christian Conservatives(Conservatives), EAP(Environmental Awareness Party - Progressive), Freedom Party (Liberal), Socialist Alternative(Socialists), Union of Workers(Communists). Names are based of of current existing parting represting their political ideology.

-Lastly I would recommend changing the region Luxembourg is in from Nordrhein to Wallonia, from a gameplay perspective it would be easier to manage that way, and historically speaking it was administered as part of Wallonia during the times of the United Kingdom of the Netherlands.

Edit: For my sources they were mostly the Dutch wikipedia pages on the Benelux and the Benelux countries, the Dutch versions contained more information than the English ones.

**Comment by simsulla** [comment]
Well written, Benelux qualifies to get into the mod.

**Comment by Liegnitz** [comment]
Shouldn't German be accepted? I see your point, but be aware that luxembourg is mainly German, which might trigger a lot of crisises.

Another thing is, do you want that other nations can form it when they have all the cores of Benelux in their sphere, similar to the SGF in the vanilla version?

**Comment by DutchDylan** [comment]
Firstly, thank you for these suggestions Liegnitz they cover some topics I hadn't really thought about too indepth, If Simsulla approves of these suggestions they could improve how the Benelux plays.

Secondly, the official working languages are Dutch and French since they make up most of the population of the Benelux, the other official languages of the countries within the Benelux (Luxembourgish, German and Frisian) are spoken by too less to be an official working language. In real life this doesn't have much problems since the people from the Netherlands and Flanders both speak Dutch and the people from Wallonia and Luxembourg both speak French, ingame the Dutch speaking population is represented as Dutch and Flemish to differentiate the cultures differences between the two, and the french speaking populations is represented as Walloon so it differentiates the cultural difference from French. For Luxembourg it is represented by French, German and European, perhaps this could be changed so the majority population is a new Luxembourgish culture? This makes sence since in real life Luxembourgishpeople feel they are different/distant from both French and German people, then the new Luxembourgish culture could be added to the accepted cultures to represent the French speaking population in Luxembourg and to prevent crisises from happening.

Thirdly, about others countries being able to form the Benelux when they have the three low countries in their sphere makes sense but at the same time it does not. The thing holding back further integration between the Benelux countires was that the integration was taking place on a European level instead of at the Benelux level, there was no reason for the other more powerful European countries to let further integration happen on a Benelux level since they wanted more integration on a European level. However it would make sense from a player prespective to form the Benelux to easen the influence game (only influencing one instead of three seperate country), perhaps there should be an event or a decision for the country that holds all three of them in their sphere to allow futher integration for the three countries. The AI should then always decline this to represent the integration taking place on a European level, but the player could then just accept it if he/she desires to easen the influence game and have a easier time forming the EU.

**Comment by simsulla** [comment]
Agree Benelux is a player option. A separate Luxembourgish culture is maybe to granular. It is only an official language as of 1984.

**Comment by DutchDylan** [comment]
Well I would argue that the people of Luxembourg would feel Luxembourgian and not German, which would be represented by their culture. The same as people from Flanders feel Flemish and not Dutch. The thing is Flemish is not an official language but Dutch is in the Flanders region of Belgium, then by this reasoning Flemish should be Dutch in Flanders too. Making Luxembourgian a seperate culture from German could indicate the cultural and linguistic differences just as Flemish does with Dutch.

And since the timescale for the NWO mod goes till somewhere after 2050 I would also argue that Luxembourgian being a seperate culture makes more sense for that timeframe because there's more playtime between 1984 and the enddate than from 1946 till 1984 :P 

Btw maybe a minor prestige event in 1984 for Luxembourg could pop up saying stuff about it being an official national language from that point on, for flavour?

**Comment by simsulla** [comment]
Benelux will be part of 1.13.
But the integration will be more straight forward - i.e. one decision to form Benelux . Benelux then on it's part can become part of the EU. 
We will use **prestige** more than relation as criteria for the formation. Thus the Netherlands will have a challenge, Stay a GP, and maneuver the outcome of the Indonesian revolution without loosing to much prestige.

**Comment by DutchDylan** [comment]
Prestige certainly makes sense as a criteria for the formation, as well as the rotation being a good solution to the monarch question. 
Would you require any modding help for implementing this into the mod? I gotta admit that I'm not up to date with the latest developments of the mod (been running a personal modded 1.07), but since the issue was submitted by me originally I feel committed to help.

**Comment by simsulla** [comment]
The text you wrote up for your proposal is excellent. If you have some work - even rudimentary -with extra events that would flavor the Benelux track - please send them to me and I will see if I can integrate it into the mod.  Event, decision description texts (not only for this issue) helps the most.
