### ISSUE TITLE
Islamic State in a SoI doesn't make sense

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#475]
ISIS should be "unspherable" IMHO. In my game Japan sphered them, which means that no neighbour country would ever attack them. Actually Japan even helped them once, which doesn't really make sense.

Perhaps an event that happens whenever a great power gets to friendly. Like "beheading heathens" or "destroying ancient artifacts". It would add -200 relations and -400 influence.

**Comment by simsulla** [comment]
Well, that depends how the Islamic state would develop - they could tone down the most extreme elements, evolve to something of a "Sunni-Iraq and Syria. I am a little bit hesitant to add special treatment with regards to sphering. However if you or anyone want to mod please do. It will get into the mod. .

**Comment by simsulla** [comment]
Closing, no action. See my previous comment
