### ISSUE TITLE
WTC attacks can happen before it is erected

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#476]
WTC attacks (id=8015800, events/usa.txt) can happen even when WTC was not erected (decisions/tallest_buildings.txt).

Also, in my game WTC was built somewhere around 2020-2030, which is way too late. Similar problem was with other "tallest buildings" - they were either built never or way too late.

**Comment by simsulla** [comment]
Will correct the WTC so it is built earler. But for the rest this is "player" entertainment - having decisions to take, so an approximate timeline is good enough.
