### ISSUE TITLE
AI can't handle USA-Afghan war

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#477]
USA-Afghan war took around 10 years before I eventually ended it via tag switching. USA could simply not get access to Afghanistan. The AI is too stupid to deal with invasion of a landlocked nation.
Perhaps an event to invite USA's allies to join the war?

Similarly USA-Iraqi war took more than 5 years, but USA actually managed to win this somehow, mainly because Iraq was attacked by someone else.

**Comment by simsulla** [comment]
Know issue. One solution would be to "force" Pakistan to take part in the war and be US proxy. Will do that.
