### ISSUE TITLE
Max number of bureaucrats in a province

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#478]
There should be a hard limit for number of teachers in a province. One of my states reached 18% of teachers by 2050!

I think promotion/demotion chances of every pop to teachers should be changed to something like this:
modifier = { factor = -100 state_scope = { clergymen = 0.08 } }

**Comment by simsulla** [comment]
This bug report is incorrect. There is a limit to the number of teachers (clergymen). Farmers and craftsmen will not get promoted if there are to many teachers.

I will change another thing thou. Double the upper limit of number of bureaucrats. More bureaucrats in modern society, has the side effect that it strains country budgets late game, to some extent reducing the country money hording late game.
