### ISSUE TITLE
My game don't work

### ISSUE THREAD

**Issue by antoniotavares2705** [simsulla/nwomod#48]
File exception
Exception in discfile.cpp,line;83. description: could not open file:map/../mod/NWO/map/definition.csv

**Comment by simsulla** [comment]
Have you installed the mod from one of the download links in the forum or
wiki. You schould have downloaded a zip file.

It looks like you checked out the github repo directly. If you do that you
need to follow the instructions on the wiki.

Also if you use victoria 2 3.04 beta patch, search github issues with text
3.04 for additional patch files needed.
