### ISSUE TITLE
Huge shortage of oil seeds

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#482]
In my game there was a huge shortage of oil seeds starting from 2000.
Even sphering big-producing countries did nothing. I had to straight out conquer some african provinces, which boosted global production thanks to my RGO efficiency techs.

Perhaps small changes to oil_seeds_canned_food_factory - make it less likely for AI to build it and make it less efficient?

**Comment by simsulla** [comment]
oil seeds shortage is ok, as it is substitute with other like rice. The factory always produce canned food. 
I have not seen that the AI builds factories excessively. Please reopen the issue if you find this AI unblalance.
