### ISSUE TITLE
Suggestion: european as the primary culture in XEU

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#483]
When becoming XEU, the primary culture should be changed to "european" and previous primary culture should be added as accepted.

I think this makes sense, as the United Europe would promote pan-europeism instead of local traditions. Besides what's the point of having distinct european culture when even a unified Europe in 2100 ends up with less than 1M pops.

**Comment by simsulla** [comment]
Agree. Set to enhancement.

**Comment by VictorWeikum** [comment]
Also, joining country's primary and accepted cultures should be added as accepted for the union.

**Comment by simsulla** [comment]
the problem is that that is not mod-able. There is no mod command to access culture, the only way is hard-coding. So the solution would be for all superstate hard code primary/accepted cultures.
