### ISSUE TITLE
Suggestion: new NF "State propaganda"

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#484]
Consider adding new focus, that increases assimilation rate.

Maybe possible only with certain laws (Publishing rights: Censored or Firewall?) and after the discovery of some technologies (Globalisation?).

Subsequently there could be several events, with pops reactions to it: increased/decreased mil/con, loss/gain of support for the ruling party, even bigger surge of populists, etc..

It would reflect general propaganda that modern countries tend to push.

**Comment by simsulla** [comment]
Like the suggestion. However not sure if assimilation is a possible national focus effect. I believe it is not, so will close as not possible. If you find it is possible, and want to create please reopen issue and add the NF.

**Comment by VictorWeikum** [comment]
What is "focus"? Do you mean national value? In PDM Freedom NV adds 25% or so to assimilation rate

**Comment by simsulla** [comment]
Not national value. Focus is policies that is put in place for states (like party locality).
