### ISSUE TITLE
Restoring oil_field province modifier

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#485]
Upon changing the ownership of a province with "oil_field" modifier (provinces like Trondheim or Riyadh) this modifier should be restored.
In my game (NET->XEU) inheriting Norway caused small problems with supply of oil because of this.

**Comment by simsulla** [comment]
This is a generic issue with any province modifier (they are lost with changed ownership). The corrective action is to make a "reoccurring" check for all province modifiers.  Or better to let the original event re-fire. Will correct oil fields.
