### ISSUE TITLE
Changes to province names in Poland

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#486]
Some changes to Polish province names:
540 Stettin -> Szczecin
679 Kolberg -> Kolobrzeg
680 Koslin -> Koszalin
690 Danzig -> Gdansk
691 Tuchel -> Starogard Gdanski
692 Deutch Krone -> Pila
693 Elbing -> Elblag
696 Allenstein -> Olsztyn
681 Kustrin -> Gorzow Wielkopolski
699 Posen -> Poznan
700 Bromberg -> Bydgoszcz
682 Breslau -> Wroclaw
683 Liegnitz -> Legnica
684 Oppeln -> Opole
685 Kattowitz -> Katowice
719 Bialystock -> Bialystok

Also please change region names (these are slightly controversial, but still better than the current ones):
PRU_701 Posen -> Poznanskie
PRU_690 Westpreussen -> Pomorskie
PRU_546 Pommern -> Zachodniopomorskie
PRU_684 Upper Silesia -> Slaskie
PRU_682 Schlesien -> Dolnoslaskie
RUS_715 West Galicia -> Krakowskie

**Comment by Liegnitz** [comment]
I agree with the most of them, but this also has to be done then for Russia, Czechoslovakia, Romania, Greece, North Cyprus & many Arab and African Nations.

**Comment by simsulla** [comment]
There are a lot of name changes in definitions/end_of_colonialism.txt. Anyone want to add even more create a decision for changing names and add it there.

**Comment by Liegnitz** [comment]
When creating the decision also make sure that the entire region is under one countries control.

**Comment by simsulla** [comment]
Will take this as part of State/region redesign #532

**Comment by simsulla** [comment]
Province name will be anglicized and approximate.
Province borders no align within Voivodeships (one or more provinces per voivodeship)

This is a map of Polish states after the state reorg. Major metropolitan noted as red dots (Warsaw, Gdansk, Wroclaw, Katowice, Krakow).

![image](https://cloud.githubusercontent.com/assets/10263809/17300885/a4752238-5814-11e6-8463-7a1c8c25877b.png)

Two provinces are potential "claim" provinces (Masuria and Lower Silesia West Pomerania).  Lower Silesia West Pomerania would with Wroclaw qualify by itself as a state even without the potential claim (by Germany).
