### ISSUE TITLE
Peace Mission to resolve has_unclaimed_cores in building EU (and other super Unions)

### ISSUE THREAD

**Issue by ellyss** [simsulla/nwomod#488]
In my game (NET->XEU) I integrated West Germany pretty quickly. Few years later East Germany finally broke free and became "normal" Germany. But they couldn't take the decision "xeu_political_union" (decisions/european_union.txt), because they had cores within my (XEU) provinces. This doesn't realy make sense.

To be honest I think in general having "has_unclaimed_cores = no" as a requirement to many decisions leading to unifications causes too many problems.

**Comment by simsulla** [comment]
has_unclaimed_cores serves a good purpose, preventing territorial expansionist nations to join. Besides East Germany do you have some other examples?

**Comment by VictorWeikum** [comment]
I guess that Germany shoudn't be allowed to join the EU if East Germany exists

**Comment by ellyss** [comment]
Well, not that similar, but still:
-you either fully integrate IRE or ENG - they both have cores in Northern Ireland,
-it's nearly impossible to integrate SPA, because they have a core in Gibraltar.

**Comment by simsulla** [comment]
I will create an event chain that enables the "Union" to mitigate territorial conflicts - i.e. make one side give up there claims. 

1. Starting point is the decision to work for peace by the super Union like the EU.
2. A country with claims they do not control may now surrender them. Like Ireland on North Ireland.
3. If the owner of the conflicted provinces agree we have a peaceful resolution. Like the UK agreeing to peace on North Ireland.
4. If the disputed territory contains third-party cores, the nation will be released. I.e. a pathway for Gibraltar, North Ireland independence....
