### ISSUE TITLE
Port Direction

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#489]
Whenever building a port in a new region, there is no indication wich sea tile the port is in, which is important.

**Comment by simsulla** [comment]
I don't understand. How does this differ from vanilla V2? Screen shot?

**Comment by Liegnitz** [comment]
The vanilla version had those small lighthouses and piers to indicate which sea tile the province borders. This is the exact position where the ports where built. Your mod doesn't have such an indication.

![20160528215043_1](https://cloud.githubusercontent.com/assets/16386550/15629627/4a6a1240-251e-11e6-8278-215a916cfd5b.jpg)
![20160528214846_1](https://cloud.githubusercontent.com/assets/16386550/15629638/b025c976-251e-11e6-8a92-8119d6f3b14c.jpg)
