### ISSUE TITLE
Colonial Provinces - Asia

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#491]
There are still some colonial provinces in China and almost entire India is colonial. Is this on purpose?

![20160528214436_1](https://cloud.githubusercontent.com/assets/16386550/15629652/fca9b91a-251e-11e6-8f83-533a6e29cdd1.jpg)

**Comment by DutchDylan** [comment]
It is supposed to be intentional, on his Reddit thread he said something along the lines of it representing the countries not being fully developed.

**Comment by simsulla** [comment]
Yes and no.
India intentional (part of nefing then). China (Yunnan and the Red Basin), no, it is a known issue #17. Closing this as a duplicate.
