### ISSUE TITLE
Region borders

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#495]
**endosys**
Well wouldn't it make sense for regions to be more organized with modern day boundaries in mind? For example, adding Batumi to the Georgia region or reorganizing regions in Poland and Germany so they don't overlap.

**adriankowaty**
For example, Cieszyn (Tesin) should be in Moravia region, Gorlitz in Saxony instead in Silesia. Polish part of Ostpreussen should be separated and renamed to Masuria. Westpreussen should be renamed to Pomerania, and Pommern into West Pomerania. Posen region should be renamed into Greater Poland, Krakow should be moved to Galicia-Lodomeria (which should be separated from Soviet Part and renamed into Lesser Poland), Kustrin should be moved to Posen (Greater Poland) region, Polish Brest should be separated from Belarusian part and renamed into Podlachia, and the last two regions should be merged and renamed Masovia.

**quoms**
Batumi should stay where it is. Turkey's borders are an absolute hackjob and the region setup in eastern Anatolia represents this well; recall also that Adjaria enjoys a fiefdom-like level of autonomy even within modern Georgia (for reasons relating directly to its belonging to the real-life Kars "region").

In Europe, if there's a good reason to shift the regions around, then maybe. But I would err on the side of keeping things as they are. After all, borders last long past their expiration date. Pre-WWI borders in Poland and the Cold War-era border in Germany are visible today in all sorts of ways - economic development, electoral outcomes, religiosity, you name it.

**TypicalRain**
Well Bilibinsky shouldn’t be part of ‘Tyumen’. :p They are quite far apart after all...

Having Kyzyl be part of Tomsk instead of Western Mongolia would be nice.

Boguchansky, Evenkia, Taymyr would be better in Irkutsk
While Kazachinsky, Turukhansky, Norilsk, Dikson could be in Tomsk.

Faizbad and Khorug should be part of Badakhshan. Those are the areas which are actually make it up not the rest of Tajikistan.

Viipuri should be renamed to Vyborg and be part of Ingria.

**simsulla**
In some cases regions are split by design. Since in V2 when you go to war to conquer you claim a state not provinces. So fore example having Batumi as a separate region within Georgia makes it possible to mod a conflict there. Also Adjaria (Batumi) is an autonomous region in Georgia. Same for Kyzyl, where region design enables Chinese claims. Tannu Tuva (Kyzyl) is also an autonomous region... the list goes on.

**Comment by Liegnitz** [comment]
Since NWO will be successing to HOI4 I'd make the regions close to those in HOI4. About the naming, this can be done easily with decisions.

**Comment by simsulla** [comment]
Point taken. For the English version, English names are in most case preferable. We need to find a balance between historic compatibility (hoi) and modern administrative regions.

**Comment by Liegnitz** [comment]
The problem is administrative regions changed quite often in history. For which Poland is a good example. So my proposal would be to go with geographical and historical regions first.

**Comment by EmpireMagnis** [comment]
I can't quite understand, we are using HoI4's map or exporting the mod to HoI4?

**Comment by simsulla** [comment]
We use v2 map. But borders has to cater for a pre-ww2 situation. For example Poland-German border
![image](https://cloud.githubusercontent.com/assets/10263809/15754036/9e90cd4c-28f6-11e6-94c5-789e2ec7478d.png)
As you see the --- line (polish regions, does not overlap with the pre WW2 German. 

There are other cases as well (with significantly worse differences like India) where there has been lots of administrative redividing. 
Overall the preference are modern borders as this makes good pop statistics much more easy to get. But (like in case of India there are huge 1946-1992 differences).

**Comment by EmpireMagnis** [comment]
But what does this have to do with HoI4?

**Comment by Liegnitz** [comment]
Basically you will be able to convert your HOI4 save to NWO.

**Comment by EmpireMagnis** [comment]
We'll see how the Hearts 4 border gore goes with this mod.

**Comment by simsulla** [comment]
I am hoping they used a real map projection in hoi4, then the mapper tool will automatically map hoi4 provinces to Vic2.

![image](https://cloud.githubusercontent.com/assets/10263809/15797598/5a32af84-2a1e-11e6-9284-3e8848154ef1.png)

**Comment by simsulla** [comment]
Duplicate of State/region redesign #532
