### ISSUE TITLE
Migration of farmers and laborers 

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#497]
TypicalRain
What I meant though was that when the population decline started happening that the Tuvans were almost wiped out not the Russians. :eek: Both populations in the state were going down but since only non Tuvans were immigrating into the state they were reduced to a few thousand. This also happened to local Minorities like Komi and Yakuts. Is that merely a by product of me educating those populations to much?

simsulla
Maybe it is because Tuva is a state/region capital in Russia, and thus that province will attract migrants. I will try and fix the Tuvan migrating by making framers/laborers much less likely to migrate. For very small minorities (Komi, Yakuts) dilution is hard to avoid.

**Comment by VictorWeikum** [comment]
I'm planning to add cultures of republics and autonomies of Russia as accepted. But it will completely stop their assimilation, which is non-realistic too.

**Comment by simsulla** [comment]
Nice idea, a scenario of a more Federated Russia. But surely if for example Tatarstan gets real autonomy (becoming a vassal) would halt Russification. It seems realistic.
