### ISSUE TITLE
EAU becomes EU

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#50]
When playing for Russia, after discovering polarized world, player can form EAU and it can form EU on the next day. Also, democracies should be allowed to join EAU, at least if Populists, Traditionalists or Socialists are in power. I can resolve this issue myself.

**Comment by VictorWeikum** [comment]
Also, enlargement of a union seems to be broken. How is it supposed to work?

**Comment by VictorWeikum** [comment]
Also, change regime in sphered country event doesn't appear more than one time in the whole game. Also, install democracy/etc. justification of war is not avaliable for unknown reason

**Comment by VictorWeikum** [comment]
I will resolve this issues after playing throgh the whole scenario.

**Comment by VictorWeikum** [comment]
EU should have cores on these at 1992 - https://commons.wikimedia.org/wiki/File:EC-EU-enlargement_animation.gif#/media/File:EU12-1992-93_European_Union_map.svg

**Comment by simsulla** [comment]
You report several issues in one. Please report one problem or request per issue. I will break this issue into several - moving the comments there..

**Comment by simsulla** [comment]
On the "install democracy/etc. justification of war is not available for unknown reason" - please create a separate issue with details
