### ISSUE TITLE
Russia province national composition

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#507]
**VictorWeikum**
National composition of Tuva is totally inaccurate
National composition of Nenets autunomous okrug is totally inaccurate.
Totally inaccurate Sevastopol national composition

**Comment by simsulla** [comment]
Sevastopol national composition is correct as is. +1% is well within the margin of error.

**Comment by VictorWeikum** [comment]
@simsulla As of 1989 (closest year when census took place):

Russians 74,4%
Ukrainians 20,7%
Belarusians 1,9%

In game it's 54% Russians and 46% Ukrainians

**Comment by VictorWeikum** [comment]
Note that Sevastopol is a separate administrative entity in both Ukraine and Russia

**Comment by simsulla** [comment]
This is an artifact of Sevastopol being the provincial capital, so all state_capital_only pops (soldiers) end up in that province. Exclude the soldiers and landowners and the stats get right. This will be addressed by the state corrections State/region redesign #532. I suggest closing the issue.

**Comment by simsulla** [comment]
as well as #583 . Closing
