### ISSUE TITLE
Italian parties

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#512]
**Paul93** 

1946:

-Conservative: Democrazia Cristiana (DC)
In reality, it was a centrist party (heir of the Partito Popolare Italiano) ranging from social conservatism to social liberalism, but I think it could be represented as conservative giving that the laws adopted when one choose for republic in the '46 referendum are very advanced (irrealistically advanced, indeed). It was the most important Italian party during the Cold War.

-Liberal: Partito Liberale Italiano (PLI)
In reality, it was quite conservative in social matters (in the '46 referendum PLI supported the monarchy), but from Malagodi's chairmanship became strongly free marketist and more libertarian. During the seventies it drifted from center-right to center.

-Reformist: Partito Socialista Democratico Italiano (PSDI)
Founded just after the war by the moderate faction inside the PSI (Socialists), it had occupied the center-left position (social liberal) in the Italian political spectrum. The apex of its influence was the election of Saragat as President of the Republic.

-Socialist: Partito Socialista Italiano (PSI)
An historical Italian party rebuilt after the war that drifted from left to center-left, on social democratic positions for most of the time.

-Communist: Partito Comunista Italiano (PCI)
In reality, it drifted from revolutionary to democratic positions just after the foundation of the republic, despite the official support offered to the USSR. In 1956 it left the Cominform. In late seventies it founded the Eurocommunist movement along with French and Spanish communist parties, definitely breaking with soviets. It was the second political force in Italy just after the DC. Despite being historically incorrect, it could be categorized as “hardline communist” for game reason.

-Traditionalist: Partito Nazionale Monarchico (PNM)
A minor party that supported the return of the House of Savoy from the exile and the reinstatement of a constitutional monarchy.

-Populist: Movimento Sociale Italiano (MSI)
The heir of fascism in Italy, on a variable position regarding social reforms and against political reforms.

In 1992 a great corruption scandal (called “Tangentopoli”) came out. Many political parties from right to left were involved and the subsequent inquiry (called “Mani Pulite” – Clean Hands) revealed a web extended up to the former Prime Minister (B. Craxi). The failed attempt to cover up the entire story killed definitely the Italian first party system (in Italy also called “First Republic”). Nearly every party was wiped out and new emerged.

1992:

-Conservative: Forza Italia (FI)
Berlusconi’s party, famous for continuing our national tradition of scandals and corruption. Conservative in social and political matters and free marketist, it was the main political force during the 1992-2011 period.

-Liberal: Unione di Centro (UDC)
The heir of the right wing of DC, on a slightly conservative position and usually in the center-right coalition. Far from being as influent as DC.

-Reformist: La Margherita
The heir of the left wing of DC, on a slightly reformist position and usually in the center-left coalition.

-Socialist: Democratici di Sinistra (DS)
The heir of the moderate faction of PCI, it was the major social democrat party prior to the foundation of PD.

-Communist: Rifondazione Comunista (RC)
In reality, a social democrat party. Categorized as communist only for game reasons.

-Traditionalist: Alleanza Nazionale (AN)
The heir of MSI, which drifted from right to center-right during the nineties. In reality, a moderate party.

-Populist: Lega Nord (LN)
In origin a small extremist and separatist party, it became the major populist force in Italy only in the last years.

The 2008 Crisis has put a considerable strain on Italian national debt and as bid-offer spread on our bonds went up, under the pressure of the European Central Bank, Berlusconi was forced to resign. New parties gained popularity and others united together in order to remain competitive.

2011:

-Conservatives: Popolo della Libertà (PDL)
In reality, it existed only four years (2009-2013) and then returned to previous denomination (Forza Italia), but for game reasons is an acceptable name.

-Liberal: Scelta Civica (SC)
Formed to support the “technocratic” government of Monti after the resignation of Berlusconi, it survives nowadays as a centrist party.

-Reformist: Movimento 5 Stelle (M5S)
In reality a quite populist party with a left leaning platform, but it could be categorized “reformist”.

-Socialist: Partito Democratico (PD)
In reality, it was founded in 2007 by DS along with many minor parties of the left wing and gradually shifted from center-left to center.

-Communist: there is no more communists in parliament since 2008. If you strongly desire a name, I could say “Sinistra, Ecologia e Libertà” (SEL) but is quite a nonsense.

-Traditionalist: Forza Nuova (FN)
It is a tiny neo-fascist party, founded in 1997. It is the only Italian party truly committed in something definable “traditionalist”.

-Populist: Lega Nord (LN)

For future, you can consider a shift to the right of PD, towards liberal positions, the emergence of a new “socialist” party (like “Sinistra Democratica”), the end of Berlusconi’s hegemony on the right wing (maybe a new party like “Alleanza Liberal Popolare”) and the rise of a traditionalist faction anti-immigration and anti-globalization (like, I don’t know, “Fiamma Nazionale”).

**Comment by VictorWeikum** [comment]
Spanish or Italian?
