### ISSUE TITLE
nuclear missiles in Cuba

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#515]
**DutchDylan**
I was playing as the Soviet Union and when I got the event to plant nuclear missiles in Cuba I got this event shortly after, the third option declares war on a non-existent nation and immediately ends after one day. I'm not sure this is a bug or this 'war' triggers something for the event chain but it's still odd so that's why I wanted to report it.
![image](https://cloud.githubusercontent.com/assets/10263809/15799806/553f9082-2a69-11e6-9c5c-32d271d34fe7.png)

**Comment by EmpireMagnis** [comment]
This goes for a lot of "(WW3)" events

**Comment by simsulla** [comment]
@EmpireMagnis need specifics. 
I have corrected the quarantine event.
