### ISSUE TITLE
Crimean association

### ISSUE THREAD

**Issue by VictorWeikum** [simsulla/nwomod#517]
validator says everything is allright, but `create_vassal` doesn't work. Tried putting `release` before it - only Kerch province becomes CRI. Same effect when using three lines `96* = { secede_province = CRI }`
Simferopol and Sevastopol simly do not transfer to CRI. But when UKR chooses independence for CRI, everything is allright.

Any ideas?

**Comment by simsulla** [comment]
What do you whant to do? As UKR release CRI as a vassal? Then
`release_vassal = CRI

**Comment by VictorWeikum** [comment]
@simsulla fixed. Also fixed Russian influence on CRI. Need to make Crimean Tatar a standalone culture from Tatar, so it would be possible to simulate their returning from exile. Also need to fix Sevastopolian national composition, as it is not accurate. As of 1989 (closest year when census took place):

- Russians 74,4%
- Ukrainians 20,7%
- Belarusians 1,9%

**Comment by simsulla** [comment]
Victor, please reopen if you feel like addressing this issue. I am closing out issues not worked on for half a year.
