### ISSUE TITLE
Minor population adjustments

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#521]
**Banat** (Temesvar & Resicabánya): according to the closest census (1956) there were more minorities living there: https://mediterranee.revues.org/523#tocto2n3

**Trieste**: Has and had a significant Slovene minority around 10 %. https://en.wikipedia.org/wiki/Province_of_Trieste#Languages

**Alsace**: Germans should also be in the Metz area, but significantly lower than in the Strasbourg/Colmar states. 10%-15% should show the minority perfectly.

Why are there so many White French in Bordeaux?

**Comment by Liegnitz** [comment]
Basically every province in Romania, that was part of the Kingdom Hungary before, should be inhabited by a Hungarian minority

**Comment by simsulla** [comment]
There are Hungarians in ex-Hungarian lands in Romania
![image](https://cloud.githubusercontent.com/assets/10263809/16883993/419d4cbc-4ac7-11e6-9cdf-4821178fa087.png)
Will correct the Banat, Trieste and Alsace
Remove the white french in Bordeaux - those are, among others "Pied-noirs"
