### ISSUE TITLE
Albanian People

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#525]
Not all Albanians are Muslims, in 1944 there were 70 % Muslim and 30 % Christians (Orthodox&Catholics). Nowadays most Albanians are Secularized, due to the anti-religious communist government.
https://en.wikipedia.org/wiki/Religion_in_Albania#Religious_demography

**Comment by VictorWeikum** [comment]
Albanian has a very interesting history of nation forming exactly because of it's religious plurality.
[](https://en.wikipedia.org/wiki/Religion_in_Albania#/media/File:Albania_confessional_map_with_regions_circa_1900.PNG)

**Comment by Liegnitz** [comment]
Exactly, could make some events to display the suppression of religion and its diversity.

**Comment by simsulla** [comment]
Of performance (keeping don number of pops) there is one religion per culture (+secular). The way to think abut it is if religion is a important self identity a linguistic group will split in different cultures along religous lines (serb, croat and bosnian/muslims is an example). So to have christian albanians we need a separate culture. Is Albania divided along religious lines? Your comments would suggest no.

On secularization I belive the general secularization ongoing in communist countries already covers this. Will check if maby ther is a block on muslims for this effect.

**Comment by Liegnitz** [comment]
Well, the northern- and soutern territories are mostly Christian, whereas the areas around the capital are mostly inhabitated by Muslims. Since Albania is rather small and it has very little population its not as important to add too much of such flavour to it.

**Comment by simsulla** [comment]
Will not divide the Albanians - but will make Albanian province correlate to potential religious dividing lines. The Orthodox South will be a separate 'state/region' #532 facilitating Greek claims.

![image](https://cloud.githubusercontent.com/assets/10263809/16712527/2f801474-468a-11e6-9d0e-c7f54077ca04.png)
