### ISSUE TITLE
Crash on "Adapting History"

### ISSUE THREAD

**Issue by KRKavak** [simsulla/nwomod#528]
Every time I choose a country it crashes on "adapting history". I've cleared the map cache again and again, even moved NWO to its own install so I could launch the game without the mod launcher. I am using version 3.04 and the Gamersgate version of Victoria II. I have a check-sum of ABRB.

**Comment by simsulla** [comment]
Mod launcher is ok to use.

What version of NWO are you using?

Do you have your system.log and your game.log. 
In the system.log what is the "V2 Version"?
In the game log what is the last lines saying?

**Comment by KRKavak** [comment]
I am using the latest GitHub version

System.log says "[main.cpp:400]: V2 Version Jan  4 2016 : 17:36:07"

Game.log says in its entirety:
"[history.cpp:268]: Executing History from -1.1.1 to  2.1.1
[history.cpp:268]: Executing History from 2.1.1 to  1946.1.1
[citypool.cpp:128]: Initialized cities with total 1728 meshes of typical buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[history.cpp:268]: Executing History from -1.1.1 to  2.1.1
[history.cpp:268]: Executing History from 2.1.1 to  1946.1.1"

**Comment by simsulla** [comment]
Is this a cut and past error, because you are double executing history "**Executing History from**..".
This is my log:

```
[history.cpp:268]: Executing History from -1.1.1 to  2.1.1
[history.cpp:268]: Executing History from 2.1.1 to  1946.1.1
[citypool.cpp:128]: Initialized cities with total 1728 meshes of typical buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[controlcommands.cpp:89]: Human Player set as primary local
[frontend.cpp:725]: 

		[[ Launching SINGLEPLAYER-game ]]
	Start-date: 1946.1.1
	Country: The United Kingdom

```

**Comment by KRKavak** [comment]
It is cut and paste. I may have made an installation error in that other directory.

Another attempt, launched through the mod, produced this:

[code]
[history.cpp:268]: Executing History from -1.1.1 to  2.1.1
[history.cpp:268]: Executing History from 2.1.1 to  1946.1.1
[citypool.cpp:128]: Initialized cities with total 1728 meshes of typical buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[citypool.cpp:151]: Initialized cities with total 64 meshes of special buildings.
[controlcommands.cpp:89]: Human Player set as primary local
[frontend.cpp:725]: 

		[[ Launching SINGLEPLAYER-game ]]
	Start-date: 1946.1.1
	Country: The USA
[/code]

Version number is the same.

**Comment by simsulla** [comment]
Your log is ok, as you selected different nations forth and back. I don't have a clean install so can't confirm your ABRB check sum at the moment.
