### ISSUE TITLE
"realistic" military organization

### ISSUE THREAD

**Issue by ss-10** [simsulla/nwomod#529]
I would like to see a realistic military organization
Like being able to move brigades separately away from thier division and being able to change the division that a specific brigade is attached to
Ps: I can provide more info if this interesting for you.
Btw, great job on the mod I really love it 😍

**Comment by simsulla** [comment]
Tnx. 
In Vic2 the basic unit is "regiment"(brigades). Vic2 Regiments(brigades) are organized in armies. Divisions are virtual subdivisions within a Vic2 army.  The limitations of Vic2 applies to NWO.
So I am sure I understand, you are able to change as it is today..
