### ISSUE TITLE
Mod Crashes when launching at "Creating textures 23, 1895 or 2140"

### ISSUE THREAD

**Issue by 1235789546** [simsulla/nwomod#530]
Hello again! It's been almost a month. I had to create a NEW issue because my last one was closed. Anyways, i got another idea! But i don't know if its possible for you to do it. I need you to upload for me a folder called "NwO" (the one that gets created once you run the mod in "My Documents/Paradox Interactive/Victoria II") to put it in MY "my documents/paradox interactive/victoria II" directory. As i NEVER reach the menu in ANY version of NWO, i need that folder in its "complete form" (that is, after the mod reached the menu without problems and with all texture quads created). Could you PLEASE do that?

**Comment by simsulla** [comment]
Old issue is #419. My version is a future beta 1.08, so can't help you with that. I suggest you vic2 and NWO on a friend computer and see if it works there. Your mod crash is not a NWO issue (#419). For the map cache check at reddit or the paradox forum if some one else has a 1.07 cache dump to share.  But I am hesitant if this is a way forward.

**Comment by 1235789546** [comment]
Okay. But never mind, upload the folder i mentioned you (doesn't matter if it is from version 1.08). When you upload to the public the next version of NWO (1.08) it will be usefull.

**Comment by VictorWeikum** [comment]
@1235789546 here is 1.07 folder from my documents - https://1drv.ms/f/s!ArgXR_7oQ6lUguAALGz4Q0O4vyL9ew

**Comment by 1235789546** [comment]
Thanks! I'll give it a try...

**Comment by simsulla** [comment]
reopen if not resolved.

**Comment by 1235789546** [comment]
hello
