### ISSUE TITLE
State/region redesign

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#532]
**Background:**
In NWO there are a lot of split states. For the computational load on the game in reality this means two states. Vic2 casus belli system only supports claiming states not provinces. So sub dividing states is done artificially by cores (and events). Further more there are bugs in vic2 whne you make pops state_capital_only when in the game individual provinces change owner; so in a sence vic2 assumes that all provinces in a state has the same owner. 
In hoi4 there are in totla c.13000 provinces, and 740 states. In NWO there are 3282 provinces and 650 states (regions). Including split states significantly more. hoi4 provinces are extremely light weight. Depending on number of pops nwo provinces are heavy weight.

**State Redesign**
The idea is to change the NWO state design as follows;
1. All pop types are state_capital_only, except farmers (and laborers). This makes nwo province more light weight. Together with the strict urbanization migration this would keep the number of rural province pops constant through out the game.
2. states are redefined so one state only has one owner. major urban centers are selected as state capitals. I South Africa Guateng would be a state, not as currently part of Transvaal.
3. cores (including event/decision changes) must always cover full states. So upon release nation you always loose full states. 
overall we could increase both the number of provinces and states in NWO.

**Comment by VictorWeikum** [comment]
Optimization is always good, but some nations are so small they cover only one province. Does this mean there will be a one-province state?

**Comment by simsulla** [comment]
In hoi4 some states are one province (like Gibraltar). But if possible the preferred situation is to have several provinces per state.

**Comment by simsulla** [comment]
I am working on the new state design issue #532 . Come as fara as Brazil in the alphabet.
This is the proposed new state division for Brazil.
![image](https://cloud.githubusercontent.com/assets/10263809/16362174/5e816644-3ba7-11e6-89a1-2c303724df89.png)


There are tre types of states

1. Major metropolitan areas (stars on the map - and blue color). This is the state capital - magnet of pop migration and destination of migration from other provinces in the state.
2. Disputed (or potentially disputed) territory states (pink color on the map). This as states will control states in it's completeness. No split states in-between countries.
3. Capital state - The capital province (red Brazilia on the map) must be the capital of a state - or we get a strange effect of farmer/miners only living in the capital.

Together with the state redesign we will also correct the map to have borders correlating to reals world level 1 and level 2 administrative divisions.

Another example. Belarus with two states; Minks and Grono(Polish ares in the period before WW2). 
![image](https://cloud.githubusercontent.com/assets/10263809/16362233/375a1f64-3ba9-11e6-870e-5f53e292b8cc.png)

**Comment by VictorWeikum** [comment]
Cool. Belarus is a unitary state and there is no reason to believe it'll change. I'm gonna make 4 states required to become federation

**Comment by Liegnitz** [comment]
@simsulla The Brasilian map looks good, the only thing i found, was that there might be territrial disputes with Paraguay, so the state north of it should be pink i guess.

Anyway keep up the good work.

**Comment by simsulla** [comment]
Good point, will add a province for Paraguayan claims

**Comment by VictorWeikum** [comment]
Please make Soviet autonomies (unless one never claimed independence/full autonomy) and other post-Soviet disputed territories to be states.

**Comment by Liegnitz** [comment]
No split states, ot even by event/decision  
That would make quite a few one province states in Europe e.g. Uzhhorod, Cernauti, Izmail, Danzig, Oppeln, Gibraltar, Luxembourg, Trieste, Novy Sad, Tesin... and more.

**Comment by simsulla** [comment]
Will merge Region borders #495 with this issue

**Comment by DutchDylan** [comment]
In addition to the province redesign as mentioned in #560 do you think a region redesign could be made for the Netherlands as well? I would suggest to have the regions similar to the [NUTS-1 regions](https://upload.wikimedia.org/wikipedia/commons/f/ff/Landsdeel.png) of the Netherlands with a [small redesign](https://upload.wikimedia.org/wikipedia/commons/3/34/Nederlandgebieden1.JPG) to have the Zeeland/middelburg province grouped together with the southern region so all regions would have 3 provinces associated with them ingame.

**Comment by simsulla** [comment]
Also see Upper Silesia #574

**Comment by zachary123212** [comment]
Should major metropolitan regions include city suburbs or greater metropolitan areas? Take this image: 

![Combined Statistical Areas of the United States](https://upload.wikimedia.org/wikipedia/commons/4/40/Combined_statistical_areas_of_the_United_States_and_Puerto_Rico_2013.gif)

Should the US be divided roughly along the lines of some of these areas, as opposed to states (to better simulate POP migration to and away from cities)?

**Comment by simsulla** [comment]
- Being  a major metropolitan makes a province qualify to be a state capital - i.e. have a state. But it needs to be big enough (for example Fargo NC is not big enough). 
- Rural provinces (i.e. any province that is not a state capital) are assigned state according to administrative divisions (in US state borders when possible).

This is the US after the "state" redesign. As you see California , Texas and Florida has been split up.

![image](https://cloud.githubusercontent.com/assets/10263809/17201170/619605c6-548c-11e6-81a0-d5ce656b7053.png)

**Comment by simsulla** [comment]
Will close this issue and extend Province Names and Geography #549 with modifying province geography.

**Comment by simsulla** [comment]
Strictly a "state" in Vic2 is a "holder of factories - (and state only pops)". This is the way provinces become more light weight. 
So, what qulaifies being a state? In my mind "large metropolitan areas" does. Pointed out those centers as red circles for the US in the map below. 
We have to draw the line some where for what size is required for the metro area, that satisfies performance and playabillity. The "empty-mid-west" simply does not have any large enough metros. At the same time some states have several. So, California has been divided,  Texas has been divided and Florida has been divided.. 

NWO mods the major sift in society were rural and small towns are dying, and pops move to these super metropols. 

![image](https://cloud.githubusercontent.com/assets/10263809/17270788/95b4a1c4-566b-11e6-9db9-462945feac2d.png)
