### ISSUE TITLE
Poland as parliamentary democracy

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#536]
by adriankowaty
One question about polish democratization event chain: as I noticed, you've divided democracies into presidential and parliamentary ones. Event chain changes goverment into presidential form, but in reality Rzeczpospolita Polska is a parliamentary democracy and president of our country has very little influence on politics. Almost whole law is constituted by Sejm and Senat.
For further imformations, look at our Constitution (if you are able to understand polish):
http://www.sejm.gov.pl/prawo/konst/polski/kon1.htm

What about Poland in '89 turning presidential democracy instead of parliamentary one?[/QUOTE]

**Comment by VictorWeikum** [comment]
Germany is a parliamentary democracy as well. Also there are mixed models. Maybe there is a point to rename parliamentary democracies into democratic monarchies to make things easier? Or you have some ideas on political regimes?

**Comment by simsulla** [comment]
True originally "Parliamentary Democracies" where monarchies. But it is also the regime type for colonies that keeps the close relation with the motherland. 
The "game-mechanical" reason is to enable two type of flags under democracy.  Then if the gov form is "parliamentary" or "presidential" is flexible.

Some example of different flags with democratic gov;
Example Gabon
![image](https://cloud.githubusercontent.com/assets/10263809/16360896/83750190-3b7a-11e6-965b-54603c76e067.png)
![image](https://cloud.githubusercontent.com/assets/10263809/16360899/91b854be-3b7a-11e6-9c2d-42da0d498ca9.png)

**Comment by simsulla** [comment]
did some update of Polish flags as well
Parlamentary Democracy
![image](https://cloud.githubusercontent.com/assets/10263809/16886188/04b5af4a-4ad3-11e6-8a06-55bbb7a6ed19.png)
Presidential Democracy
![image](https://cloud.githubusercontent.com/assets/10263809/16886191/091ec332-4ad3-11e6-9c36-5e3f8792a1e1.png)
Communist
![image](https://cloud.githubusercontent.com/assets/10263809/16886200/0e90b866-4ad3-11e6-912d-05eab883624d.png)
