### ISSUE TITLE
Romani People 

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#537]
Add more Roma to Hungary please and also increase the birthrate of them. According to Hungarian sources every 5-6 child born there is of Romani descend. Also by 2050 15 % of Hungary's population is said to be Romani.

The birthrate changes about the Romani pop should of course be equal to all countries. 

See here:
https://en.wikipedia.org/wiki/Demographics_of_Hungary#The_Roma_minority

**Comment by simsulla** [comment]
Good wiki link.  I have been searching for TFR stats for romani people but unable to find any good stats. 
There is support in NWO for "high growth cultures" at the moment Haredim Jews and Mennonites (Amish). Probably Romani people should also be added.

**Comment by simsulla** [comment]
The Council of Europe has mad an estimate of number of Roma (Romani) people. The total low 6,206,900, high 16,313,700 and medium 11,260,300. Varying greatly in-between countries. The official count being 1 809 631 with several countries lacking statistics.  In NWO we will try and use the medium estimate but in provinces with large Romani pops be closer to the high estimate. 
This is total figures per country
![image](https://cloud.githubusercontent.com/assets/10263809/16708489/e84a860a-45f5-11e6-8106-5207c6e7f406.png)
Romani are however not even distributed some provinces have significatn numbers (>15%, >25% indicated in the map).
![image](https://cloud.githubusercontent.com/assets/10263809/16708795/63d39ad8-45ff-11e6-828c-861683ddb3c2.png)

**Comment by simsulla** [comment]
![image](https://cloud.githubusercontent.com/assets/10263809/16712299/9138896e-4683-11e6-9a2e-93e7f1555e44.png)
