### ISSUE TITLE
Please re-add HoI3 support to the converter

### ISSUE THREAD

**Issue by force200** [simsulla/nwomod#539]
Some people stil play HoI3. It's not fair to deny them the option of a CK2>EU4>Vicy2>HoI3>NWO grand campaign.

**Comment by centriccracker** [comment]
It'd be easier to just extend Vic2's timeline altogether then to have it support HOI3, HOI4 saves. You know, vanilla VIC2 (1836-1936) then extended with NWO (1936-2100)

**Comment by force200** [comment]
oh, I didn't see that feature.

**Comment by simsulla** [comment]
Will close this issue, as I have no plans for hoi3 support. If someone like work on it please reopen the issue.
