### ISSUE TITLE
Province Names and Geography

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#549]
Due to the recent province changes, some of them might need a new name, because the cities they are named after are probably in another province now. Also the name position needs to be adjusted. See Issue #526.

**Comment by simsulla** [comment]
will make it as part of the general State/region redesign #532

**Comment by simsulla** [comment]
This issue will also include the (continuous huge  work of ) correcting province borders to correlate with real world provinces. Will start with a couple of bigger countries, and then create a new issue post 1.08.

**Comment by simsulla** [comment]
some issues has reappeared
- rural provinces gets emptied on pops.
- blank space" in Siberia.

**Comment by Liegnitz** [comment]
some provinces are now awfully big, getting the warscore takes in some cases very long, especially Italy and Finland, maybe split them further up?

**Comment by simsulla** [comment]
Yes that is the long term plan to add additional provinces (lots of them).
