### ISSUE TITLE
China Civil War

### ISSUE THREAD

**Issue by Mrenrisco** [simsulla/nwomod#55]
I have three things to point:
1- Recently I watched a video of a gamer playing with the capitalist China and although he had been able to win the civil war, all the next events were related to the People's Republic of China. I mean he was playing with the capitalists, China was in a democracy and all the events were associated with the victory of the communism.
2- Even china being capitalist the Soviet Union gave to her a region and a lot of techs. I know it was what happened in the real history, but it wouldn't make more sense the if URSS gave to Capitalist China just the region or if she acquired a permanent casus-belli for the region ? 
3- In the same gameplay the civil war of Korea began, with an event the player was able to force the north Korea to become a capitalist and democratic country, just like China and South Korea, but the war continued anyway. It doesn't make sense.

**Comment by simsulla** [comment]
1. corrected where I found commie events.
2. corrected
3. corrected
