### ISSUE TITLE
Japan, the Kuril Islands, Southern Sakhalin, and the Sankaku Islands

### ISSUE THREAD

**Issue by DutchDylan** [simsulla/nwomod#558]
I was reading a bit up about Japan and stuff to see what I could do in a Japan playthrough and to see what was represented ingame through either events or decisions. 

Getting straight to business, Japan seems to have cores on the southern Kuril Islands in the 1946 start but from what I've read [here](https://en.wikipedia.org/wiki/Sakhalin#Second_World_War) it seems like Japan claimed Southern Sakhalin and the full Kuril Islands till 1950 in which it signed the [San Fransico treaty](https://en.wikipedia.org/wiki/Treaty_of_San_Francisco#The_fate_of_Japanese_overseas_territories_and_Taiwan) in which Japan renounced their sovereignty over these territories except for the southern Kuril Islands. Futhermore the treaty also determined that the various minor island groups near Japan were to become U.S. trusteeship, some later on were returned to Japan after a revision by the US and those wo were returned already have cores on them ingame. The treaty also renounces their claims over some more territory formerly part of their empire.

Ingame the situation is different than it was in reality, could there perhaps be an event added which represents the treaty of San Francisco? I would suggest for such an event pop up to have multiple options in which a player could choose which claims he would like to renounce and which not, an option in which the player renounces none of their claims should probably put them far over the infamy limit and depuppet/desphere them so that any other nation could declare war on them or it could immediately start a war between the US and Japan. Either way if Japan loses the war(s) following that event option Japan should only hold cores on their main 4 islands, Ryuku could possibly be made an independent country or be ceded to China in such a situation. Perhaps even in such a situation Hokkaido could be made an independent country because they wanted to weaken Japan even further? Hokkaido beforehand could have had cores and culture similar to Bavaria in Germany but after a containment war like that against Japan it could be made independent and the country could adopt Ainu as an accepted culture, so if later on it became part of Japan again stuff like crisises and rebels would work correctly.

The other options could range from renouncing less cores, renouncing more cores, or renouncing like it was historically was. Renouncing a bit less than historically would probably give some infamy and if the player decides to not renounce even more it should give a hefty amount of infamy (but still not enough to pass the limit), renouncing historically should either give no or a minor infamy loss and renouncing even more should give a greater infamy loss. If Japan renounces their claim over the southern Kuril Islands it should probably give the Soviet Union some prestige and raise relations/influence to show that Japan fears its might (and possibly for a player to easen a Japan commie playthrough attempt), likewise if Japan chooses to not renounce its claims over the full Kuril Islands and Southern Sakhalin (and possibly northern Sakhalin if a player would be allowed to claim that during the renouncing decisions) instead of only the southern Kuril Islands, it should slightly lower the prestige of the Soviet Union and decrease the influence/relation to them.

For gameplay sake, Japan should probably start out with cores on only their 4 islands and they should gain cores on territory depending on the outcome of the San Francisco event instead of starting with cores on all their territory and them losing cores depending of the outcome of the event. It would also probably be better if Japan follows a historical path that it has no cores on the various islands that the US later returns, it would be better if it gains cores on them again when the historical events fire to return them. This to prevent the negative relation modifier for the US owning their cores.

Lastly China has cores on the southern Ryukyu islands ingame and this represents the Sankaku Islands dispute (as far as I'm aware :P), but from what I've [read](https://en.wikipedia.org/wiki/Senkaku_Islands_dispute) it's not the [southern Ryukyu Islands](https://en.wikipedia.org/wiki/Senkaku_Islands_dispute#/media/File:Senkaku_Diaoyu_Tiaoyu_Islands.png) that are disputed but some uninhabited islands close to Taiwan and abover the western part of the Ryukyu Islands. Would it be better if China had no cores starting on the southern Ryukyu islands ingame but that it would gain cores on them through the 'greater China' decision? It would seem that since the islands are uninhabitated they would serve no purpose for vic2 ingame and adding them as a province in game is unnecessary (compared to the south chinese islands which are inhabited).

I will add some pics here later to visually show what I mean with the San Francisco events

The first event would look something like [this](http://puu.sh/pZgLH.jpg) with the first option following the historical route and the second opening a new event screen to from where to choose various options for an ahistorical route.

The second event would be like [this](http://puu.sh/pZhLb.jpg), with the various options giving various amount of [infamy](http://puu.sh/pZhOf.jpg).

The reason why the options names are_like_this is because I've named them through the event file and not through the csv file :P

**Comment by Liegnitz** [comment]
I don't see why the US would want to cede strategic important territory to a potential Communist China, an ally of their foe the USSR. Also the US did not recognize the PRC as legitimate China, but the ROC, so there might be a chance that the US wouldn't ratify the treaty at all.  

Otherwise adding some more falvour to Japan sounds awesome. :smile:

**Comment by simsulla** [comment]
I like the idea of making Japan game play more dynamic. Please go ahead and start modding :). I would suggest keeping JAP start cores, and then remove/add them depending on decision.  Provinces with no cores makes scripting a bit tricky. On Japan's "options", remember they start as a [US puppet](https://en.wikipedia.org/wiki/Occupation_of_Japan) - i.e. they will take the historic route and follow the directives by the US. When creating the 1946 "province owner" it was an alternative to have Japan as US owned directly, like Germany.  

Diaoyu/Senkaku Islands (of mod tech reasons south Ryukyu island) drives tension between China and Japan, making the AI behave realistic. 


ps. maybe an independent ainu Hokkaido is a bit to much alt-history.

**Comment by DutchDylan** [comment]
Ah yeah I see, I personally think it was a good choice to make Japan a puppet instead of mkaing it fully US owned. This way a player can play from the earliest startdate as Japan instead of from the second startdate, while we are on the topic of Japan, in #432 I saw that Japan needed a nerf. From the 1946 startdate Japan basically has zero score in both military and prestige while it has a industry score of around 60 which brings it to rank 6 on the industry rank, perhaps the US could own the factories so that those factories don't count towards Japan's industry score? And to make sure Japan doesn't get too high of a score for military, should Japan maybe get a 'disarmed' modifier (the on you get when you lose a great war) for a few years in the beginning of the game?

For Hokkaido, I took the idea from [the Republic of Ezo](https://en.wikipedia.org/wiki/Republic_of_Ezo), although the northern island doesn't seem to have any sort of big independence movement nowadays, a Great power could be interested of setting up an independent Hokkaido as a puppet state to weaken Japan (Kind of like a Great power could do to Germany with Bavaria). But like you said Japan was occupied by the US and it was almost in total control of Japan, I will keep that in mind and try to find a balance between historical accuracy and player 'free roam ability'. I will start modding on the event tree I talked about and such but how would you like me to submit my modding so you can review it?

**Comment by DutchDylan** [comment]
[This](http://puu.sh/q0KV5.txt) is what I have so far, the link is to a modified txt file of 'japan.txt'. It has comments on places where it needs text in the cvs file or just notes about what was modified and if it gets approved, I would still suggest that japan only starts with cores on their main 4 islands and that it would get cores on the appropiate islands through the added and modified events. The reasoning behind this would be that Japan renounced their claims on the Ryukyu and other Ogasawara islands in the treaty of San Francisco and they were planned to be included in US trusteeship, instead the US gave them back to Japan anyway since it was in their interest to have a strong democratic ally in the east. This is also why I modified it so that these sialnds will not be granted to Japan if it falls under Soviet influence and becomes a communist country.

**Comment by simsulla** [comment]
Very nice work :+1: 
- To submit changes - use github - make a pull request with your changes (including for review)
- I ran the Validator (please always run the Vice Validator to check your changes before making a pull request). No errors :+1:  beside localization (and pictures needed - I can help with those).

**Comment by DutchDylan** [comment]
Ah thank you, I actually don't have a lot of experience with using Github so I will probably will need your help later on, but thank you for letting me contribute to this mod.

**Comment by simsulla** [comment]
vice->[vic2 Validator](https://forum.paradoxplaza.com/forum/index.php?threads/a-validator-for-victoria-ii.490803/)

You have your own clone of the repo wher you made your changes. Then here is a description how to make a [pull request](https://help.github.com/articles/creating-a-pull-request/).

Then I review your "pull request" changes, and commit them to the nwomod repo. You do a update on your clone and all is in synch.

**Comment by DutchDylan** [comment]
Ah oke thank you for the information.

For the vic2 Validator, I actually don't have a paradox account and now that I'm trying to make one I'm having some problems with registering my Steam account. It's already registered while this is my first time on the forums.. But nonetheless I've modded the stuff and it's on my clone repo, everything seems to work but it lacks the validation. I've just done a pull request could you still review it?

**Comment by simsulla** [comment]
Top job :+1: your changes are now in the nwomod master.

I had to manually merge your pull request due to merge conflict of the nwo_events.csv localisation file. Think it was due to your encoding (but not sure). The localization files has to be edited with ANSI encoding.
![image](https://cloud.githubusercontent.com/assets/10263809/16892947/c497c8e6-4b25-11e6-8ce3-d7d5145c8349.png)


Here is a link to download the [Vic2 Validator v1.13.3 Released: 27 February 2016](https://drive.google.com/open?id=0B0i_pAZe5kNUUjY1aF96d0MtNlU) (all credits to **Jamie550** )

**Comment by simsulla** [comment]
(regenerate history files with no JAP cores)

**Comment by DutchDylan** [comment]
Yeah, I edited the localizations files through excell since it was the default program it opened them in, now that I see it can open them through Notepad+ too I will use that one from now on, that way I can edit them with ANSI encoding too like you said. Also thank you for the direct download link, my problem with my account is fixed so I should be able to go on the forums from now on.

Btw does the '(regenerate history files with no JAP cores)' indicate something I should/forgot to mod?

**Comment by simsulla** [comment]
You did not forget anything. I just need to also fix the generator as in all NWO files under history is generated by the "Generator", and validate that the generated is compatible with changes.

Will close this issue now. Congratulations your first direct contribution to NWO :+1: .
Looking forward to more :)

**Comment by DutchDylan** [comment]
Ah I see, well I'm excited to work on future contributiond to this mod!
