### ISSUE TITLE
Infamy and immigration

### ISSUE THREAD

**Issue by DutchDylan** [simsulla/nwomod#559]
I noticed this in another mod and would suggest for it to be in NWO as well, in the Concert of Europe mod there's a negative immigration modifier for the infamy level and so the immigration decreases when infamy increases. I searched in the mod files of the original mod to see where this effect was coded and I found that in 'static_modifiers.txt' under 'badboy' there was a 'global_immigrant_attract' with a value of -0.04 assigned, incase you decide to add it that's how the original modder did it.

**Comment by simsulla** [comment]
I would beg to disagree. Immigrants choose destination primarily based on proximity, welfare and culture. Grand politics (infamy) has very little (close to nothing) to do with it.
