### ISSUE TITLE
Extra province Netherlands in the Zuiderzee

### ISSUE THREAD

**Issue by DutchDylan** [simsulla/nwomod#560]
The map in NWO differences from our world map that the Netherlands doesn't have [Flevoland](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Flevoland_in_the_Netherlands.svg/264px-Flevoland_in_the_Netherlands.svg.png) as a province, in our timeline [various plans were made to drain the Zuiderzee](https://nl.wikipedia.org/wiki/Zuiderzeewerken#Eerdere_plannen) and eventually [one was chosen](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Zuiderzeewerken_-_Lely_plan.jpg/800px-Zuiderzeewerken_-_Lely_plan.jpg). The plan was only partly executed since there was no real need for extra farmland for living space after the creation of Flevoland.

Could it possible for Flevoland to be added as a province on the map? Althought it wouldn't make sense that Flevoland would be part of the Netherlands from the 1946 start but a solution could be that either Flevoland would be an uncolonised province and the Netherlands after 'creating' it colonises the province and increases the liferating province to a normal level (which would be low so no country colonises that province), or the Netherlands already has it but the name of Flevoland is Urk to represent the small island that preceded Flevoland and after the 'creation' it would be renamed. Probably after both decisions the province should get a small boost in immigration and population growth for a limited time to make sure the province does not stay underpopulated.

Possibly there could a possiblity for a player to further drain the Zuiderzee like originally intended but since there realistically/historically was no need for it this should probably be left out.

**Comment by simsulla** [comment]
Changing the map dynamical is un-modable. Making it colonial would not work, as any other power also could colonize the province.  
I could make/move Breda 387 province to Urk. And then by hava decision to develop Urk to Flevoland.

**Comment by DutchDylan** [comment]
Well would making the province uncolonised with a life rating of very low (or zero) not work? The Netherlands could gain the province through an event which also increases liferating.
But thank you for making the provinces like in real life, that's a nice addition.
