### ISSUE TITLE
I'm playing on macbook air yosemiite 10.10.5, the mod doesnt start

### ISSUE THREAD

**Issue by phoenixfryre** [simsulla/nwomod#568]
I moved the mod files (both .mod and folder) into my mods folder, cleared the map cache folder and logs folder, chose the NWO mod on launcher but it opens to my normal vic2 hod game

**Comment by phoenixfryre** [comment]
No matter did all of that again and it works fantastic job on the mod. :):)

**Comment by simsulla** [comment]
:)
