### ISSUE TITLE
Argentinian Issues of 1946

### ISSUE THREAD

**Issue by Rendellan** [simsulla/nwomod#569]
Hello! I played as Argentina in the start-date 1946 and I found a few historical problems. I will enumerate them.
1. The argentine elections should start on February 24th, and Peronismo shouldn't be called like that, because it was, at first, an alliance between different political parties. There's also another issue, but I don't know if it can be solved... Elections were after 5 years, not 4 like it does in Victoria 2.
   https://en.wikipedia.org/wiki/Argentine_general_election,_1946
2. Patagonia, Chaco, Formosa and Misiones shouldn't be provinces. They were national territories that couldn't vote.
   https://upload.wikimedia.org/wikipedia/commons/0/06/Mapa_de_las_elecciones_presidenciales_de_1946.png
3. Argentina starts with no technology, something that is not accurate. I've been doing some research and I think which ones should be enabled.
4. There are misplaced industries. Argentina had a factory called Fabricaciones Militares (Weaponry Factory), founded in 1941, and Fábrica Argentina de Aviones (Aeroplanes), founded in 1921. Both of them should be in Córdoba.
   https://en.wikipedia.org/wiki/F%C3%A1brica_Argentina_de_Aviones
   https://en.wikipedia.org/wiki/Fabricaciones_Militares
5. We have coal! Is in a southern place called Rio Turbio. It used to be important. (I always thought that it was weird that in vanilla Vicky there was only one province with coal in the whole South America, and not many iron mines.)
   http://www.ferrocarrilesenelconosur.co.uk/Resources/MapRFIRT.jpg

I have some modding knowledge, and I think I could change some of the stuff that is wrong, create events and such. Oh, and I'm Argentinian too! That also helps :)

**Comment by simsulla** [comment]
Please go ahead and mod. On the tech it is relatively blunt (it is done by the Generator) - army level 0, 1... not tech by tech. So you need to judge if Argentina qualifies to increase all techs one level.

**Comment by Rendellan** [comment]
Yeah, I think Argentina should have all technologies level 1. We used to be an advanced country in those ages. I am trying to do an event chain for peronism, based on my point of view, of course, peronism is a very controversial thing that happened to my country. Also, I've already tweaked some provinces' productions and factories and colonial states.

**Comment by simsulla** [comment]
Rendellan I will close this issue as no modding has been done for half a year. Please feel free to reopen and make the suggested changes. It will get into the mod.
