### ISSUE TITLE
Permission to put in South Kasai

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#571]
I was wondering if I could get permission from the creators of this mod to put in South Kasai into this mod.If I do get permission I will edit the the map  by reshaping the Lusambo province to better fit SOuth Kasai's borders.I would also rename the province to Bakwanga as it is the capital and largest city of the Kasai Orientale Province. Lusambo is also located in this province too.

**Comment by simsulla** [comment]
Granted :), please do.

**Comment by arandomperson5000** [comment]
Okay I'm finished all the edits however I clicked on the commit to master button once when I was finished was I meant to do that.

**Comment by simsulla** [comment]
make a [Pull Request](https://help.github.com/articles/creating-a-pull-request/) to push your changes to the master.

**Comment by simsulla** [comment]
but looking on your changes, more than just adding history/countries/SUK - South Kasai.txt is needed to create the country.
You need;
- SUK flags
- Add SUK to common/countries.txt
- Add SUK to common/countries/South Kasai.txt

**Comment by arandomperson5000** [comment]
Okay I sent a pull request with a zip file containing all the work I've done on South Kasai.

**Comment by simsulla** [comment]
This pull request is strange. You requested me to "update" UI-enhancement from **master**. Which is ok, but has nothing to do with South Kasai :)

I think you missed committing your changes to your clone (looking in https://github.com/arandomperson5000/nwomod/tree/master/NWO/common there are no South Kasai changes). 

This is my work flow (and your will be very simillar with the additional pull request)
**Prerequisites:** you have the github Windows client installed.
1. Clone the nwomod repo (done only once)
![image](https://cloud.githubusercontent.com/assets/10263809/17011929/dacc18ce-4f12-11e6-9700-7c042f3b02b7.png)
I clone it into my Victoria 2 installation folder (so nwomod is on same level as the mod folder)
![image](https://cloud.githubusercontent.com/assets/10263809/17011942/091002a4-4f13-11e6-8087-80c01c6f8f21.png)

2. in mod/NWO.mod ic change the path of NWO.mod to nwomod
`path = "nwomod/NWO"` 
(also change the file NWO/map/default.map)
`definitions = "../nwomod/NWO/map/definition.csv"`
(these changes to NWO.mod and NWO/map/default.map will not be commited)

3. make my changes...... la la la... start Vic2 and test them, run the Vic2 Validator.

4. Now, looking in the  github Windows client I see changed files.
If tested ok, commit always using the issue as comment (ignore NWO.mod and default.map).
![image](https://cloud.githubusercontent.com/assets/10263809/17012038/153f84ae-4f14-11e6-97ae-666b705f7996.png)

5. Now you want to make a pull request to push this to the master). You can use the github web page for that.

See if you are able to get this flow working - else I will take your zip file and make a separate commit. 
Great work on South Kasai :+1: 
(_sorry for pushing for a working github flow.. but having acquired git knowledge will be useful in your professional life and you can become a full fledged NWO developer if you want to do more work on the mod_ )

**Comment by simsulla** [comment]
Have a look on the last commit I needed to do some additional corrections. Usually I run the Vic2 Validator to verify that all is good.

**Comment by simsulla** [comment]
South Kasai #571 added to NWO.
 Great work The Sneaky Top Hat / @arandomperson5000 welcome as NWO develper :+1:
