### ISSUE TITLE
Alsace Pop 1992

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#575]
There should be still a German Majority in Strasbourg and Colmar.

**Comment by simsulla** [comment]
Do you have a reference, for number of % German speakers in Elsass in the 1990s? My understanding is that the number is dwindling.

**Comment by Liegnitz** [comment]
It was dwindling yes, but since new bilingual schools were opened, more people embrace the old German dialect again. A survey of the "Office pour la Langue et Culture d’Alsace" said that in 2001, 61 % of the Alsacien people said they are able to speak alsacien perfectly, in 1997 it were 63 %. In 2012 a survey said that at least 76 % of the Alsacien people are able to communicate with it. So in 1946 & 1991 the amount of Germans there needs to be higher. source:
https://de.wikipedia.org/wiki/Elsass#Sprachen_und_Dialekte

**Comment by simsulla** [comment]
Ok, will settle for 63% german (number from 1997 according to the survey)

**Comment by Liegnitz** [comment]
And the 1946 start date?

**Comment by simsulla** [comment]
Strasbourg and Colmar 95% German (ref: Regional Language Policies in France during World War II)
