### ISSUE TITLE
Polish in Belarus

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#576]
According to  this: https://en.wikipedia.org/wiki/Grodno_Region#Demographics_.282002.29 and this: https://en.wikipedia.org/wiki/Poles_in_Belarus there is a Belarusian majority in Grodno & Lida, but only a big majority of Poles. (1992 start). Also there aren't that many Russians.

**Comment by simsulla** [comment]
In the next relase the Grodono Region is divided in two provinces (red line in the map).
North (Grodono) has a larger fraction poles than the whole region. less than 50% though 1992.

![image](https://cloud.githubusercontent.com/assets/10263809/16939239/0466b444-4d80-11e6-8381-8f608e0247ea.png)
