### ISSUE TITLE
Israel Province Population, 1992

### ISSUE THREAD

**Issue by zachary123212** [simsulla/nwomod#579]
When looking over the map in the 1992 bookmark, I noticed some inaccuracy in the populations of Israel's provinces

I'm using [this](http://unstats.un.org/unsd/wsd/docs/Israel_wsd_brochure.pdf) as a source (it's from 1990)
- Tel Aviv (which encompasses both Tel Aviv and Central districts) should have a population slightly higher than 2,127,000 (not 4,640,000)
- Negev should have a population of around 574,000 (not 722,800)
- Haifa (which encompasses both the Haifa and Northern districts) should have about 1,461,000 people (seems close enough)
- Jerusalem should have a population of about 578,000 (not 241,680)

As for Gaza and the west bank:
- [This](http://www.census.gov/population/international/data/idb/region.php?N=%20Results%20&T=13&A=separate&RT=0&Y=1990&R=-1&C=WE) source states that the 1992 population for the West Bank should be above 1,253,000 (not 723,000)
- [This](http://www.census.gov/population/international/data/idb/region.php?N=%20Results%20&T=13&A=separate&RT=0&Y=1990&R=-1&C=GZ) source states that the 1992 population for Gaza should be above 646,000 (not 428,880)

**Comment by simsulla** [comment]
In part this is due to state only pops being counted in the state capital province (Tel Aviv), reducing the pop of all provinces except Tel Aviv. The generator should be better and compensate for this. But will create separate issue for that #583
