### ISSUE TITLE
Somalian Civil War

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#585]
I do think this civil war should be expanded upon as it lasted for over twenty years  and it is still ongoing.However a lot of things have happened in Somalia since then.I would like to get  permission to create a commit depicting this event as the current event for the Somalian Civil War only increases militancy and the conscience of it's population which doesen't represent the way how Somalia almost fell into complete anarchy in the early 1990s divided between 10 factions.

Edit
Anyways about the Somali Civil War I have completed the first stage of it which will the Somali rebellion against Siad Barre in the 1980s,I haven't worked on it for a couple of days.

**Comment by simsulla** [comment]
Please do :+1:

**Comment by simsulla** [comment]
What is the status of this issue?

**Comment by arandomperson5000** [comment]
I apologize for the exceptionally long hiatus on this issue, I had managed to create an entire event chain for the Somali rebellion and early 1990s part of the civil war, and also created several countries like Galmudug to serve as autonomous regions since Somalia adopted a federal Constitution in 2012 giving its states a very large amount of autonomy. The Ogaden War will be the next part I will be working on however I didn't managed to start it yet.

**Comment by arandomperson5000** [comment]
While I've previously this discussed this at the forums, I wouldn't still rule out the possibility of adding in new releasable countries in Ethiopia since in the civil war there were many armed separatist groups such as the Afar Liberation Front and the Ogaden National Liberation Front present throughout Ethiopia. Even the Tigrayan Liberation Front considered separatism as a last resort. Also I would consider the option of  a breakup of Ethiopia in alternate civil war in which Ethiopia lost the Ogaden War to be quite possible as the Ethiopian military had suffered very heavy losses especially in equipment during the Ogaden War. Had the Ethiopians lost the Ogaden War, it would have been very likely that Ethiopia could have collapsed into anarchy similarly to Somalia however unlike Somalia, Ethiopia could collapse because of its diverse ethnic groups rather than the tribal society of Somalia.

Sources
https://www.google.ie/url?sa=t&source=web&rct=j&url=https://www.rand.org/content/dam/rand/pubs/reports/2006/R3347.pdf&ved=0ahUKEwip4unfu5jSAhXpL8AKHdNHAm8QFghHMAk&usg=AFQjCNGyNKNikDO1NR5aIqDxgXROQwJXJA&sig2=HewYksop14QJxcnkgR9-aQ
http://www.bbc.com/news/world-africa-16620783
http://www.cfr.org/ethiopia/ogaden-national-liberation-front-onlf/p13208

**Comment by simsulla** [comment]
Sure, Oromia exists in the mod and one could add more.

**Comment by simsulla** [comment]
Probably Al Shabab belongs as part of this issue. No need for separate issue #1064

**Comment by arandomperson5000** [comment]
For my original plan for the Somalian Civil War event chain, I was going to use tags I've created for the warlords in the early 90s phase of the civil war, however I've changed my mind on that instead using tags for the autonomous states I've created.

**Comment by arandomperson5000** [comment]
As a part of this event chain I'm planning on creating a modifier for Somali piracy during the civil war however I'm not sure what it effects will be. Do you have any suggestions on it.
