### ISSUE TITLE
1.08 beta -Misc bugs and issues

### ISSUE THREAD

**Issue by Puppysif** [simsulla/nwomod#586]
*Soviets
-Bugs:
---The collapse of the Soviet Union follows this path:
-The Baltic states declare independence.
-A couple months later, the Soviet Union becomes a wonderful democracy, and its colour changes to green. In name, it still remains the Soviet Union. And is not Russia. At all. 
---
Issues:
-For the very first couple years of the game, the Soviet Union is somewhat strong. They could easily hit Europe hard and win. However, the Soviet Unions economy under the AI rapidly collapses, and following this, the Soviet Military collapses as well.
-The Soviet Union usually enters into quite a few wars against PRC/Republican China(Depending on which one won the civil war), India, and sometimes the U.S. Every single war drives the Soviet Union further down the hole. Simply setting up the Soviet Union to war against China(Even if China will be crushed. Always.). it will simply destroy whatever remains of the Soviet Union.
-The Soviet Union simply is outclassed by USA/ENG/FRA, either of these alone or together in Industry and military strength during the early to mid 1960s. The Soviet Union simply utterly and completely collapses far to early.  Not counting the constant warring that can have it die sooner. 

*U.A.R
-After the U.A.R Civil War is finished, the enlarge U.A.R decision vanishes.

*Populists
-Issues; Populism always gains power way to early in the game. I can see Populist parties in Britain, Germany, Italy, Japan, and even America by the 1960s gaining power quite often. This leads to repeated wars between FRA/ITA, GER/POL, etc.

*U.K
-Biug: Upon the destruction of the United Kingdom, they decide to take the "Become England" decision. However, only the flag changes to that of ENG. They still remain the U.K in every other facet.

*Russia:
-Issue: Upon the formation of Russia(Usually forced, though it did form in early versions), they always go to war against Ukraine for Crimea. Ukraine usually kills Russia. 

*India/The Raj
-Bugs
A: - Pakistan gains independence. The Raj is sort of sitting their. Pakistan enters into a war against India. However, India does not exist. Pakistan is stuck in a eternal war against a country that does not exist, with no way to make peace.
B: I have noticed that Pakistan really kills India early game. Be it Pak/American alliance, PAK/Soviet, or simply Pak/CHI. They kill India. And repeatedly go to war against India every couple of years, or India takes the leap. I noticed India has a tendency to stay in the stone ages for quite awhile. If they get a break, they industrialize and surpass everything. But sometimes. - Pak tends to free Hyderaal, which leads that are to becoming a GP/SP. Fun stuff.

*Islam/ISIS
-Issue: Their are far to many spam events of "The Saffia" event. Then following this, I.S.I.S gains cores nearly everywhere. Then I.S.I.S forms, and usually takes all of Syria/Yemen/Elsewhere. ---

*"Nationalization" 
Bug?: -Throughout the course of one of my latest games, quite a few countries went communist. Whenever a country went communist, a "This country has nationalized, gain cacus belli" against it ocurred. Now, America/Britain/I/Everyone always got this event. So always, whenever a communist country popped up, it was always at constant war with the world. ./Strange enough, this happened to Bulgaria as well. And Bulgaria was invaded. All of these countries that were invaded had no foreign investment in them. At all.

Misc Issues:
Their is a lot of "Crisis, nobody cares, -50% spam." - Imagine getting one of these constantly. Constantly. -I, as Japan, invaded Indonesia. Constant spam.

U.K/USA/FRA/ITA/SPA relations always break down. France usually ends up going its own way, and warring with Spain(Liberate countries), or Italy. USA/Brit usually hate each other. Soviets stay neutral and die off. India dies or if it manages to hang around, rapidly industrilizes in a bit. China is a hit and miss. Sometimes they become a world power, the other half they repeatedly go into bankruptcy. Constantly. So you have CHI/SOV/INDI being duds, and FRA/ITA/SPA being a constant warzone, with the U.K/USA constantly hitting each other as well. South America/Asia at large and everywhere else never changes. 

Misc Ideas
*Market Communism/Etc.
-For Communist countries that "Evolve", is it possible to have their communist parties economic policies change from planned economy to state capitalism? - 
*Non Aligned movement - Countries can declare through a decision to formally join. Removes from all spheres, removes all influence from any great powers down to normal, auto repeats every month/Time is sphered until the Cold War ends/India becomes a GP/Etc.

**Comment by simsulla** [comment]
This is tesed on the github clone (pre 1.08 state), not 1.07 download right?

**Comment by Puppysif** [comment]
The issues described above range across multiple playthroughs of both the current Github Beta version, and 1.07. I apologize for not being more clear last night.

Soviet Union:
1.07 - The Soviet Union generally seems to last a bit longer. However, the Baltic states usually become independent by the 70s, 80s, and in one rare instance, the early 2000's. In the event the Soviet Union collapses, nothing else leaves the Soviet Union. As such, you have a green Russia that has only lost the Baltic states. Their seems to be less war with the United States, however, wars with China and India are still somewhat frequent. 
1.08 - The Soviet Economy completely collapses by the late 60s/early 70s, the Baltic states become independent, and the Soviet Union turns green and becomes a democracy. However, the soviet Union never becomes Russia. 
---The A.I seems to never subsidize its factories. 
Moreso, the Soviet Union usually goes to fourth or fifth place. West Germany, Italy, the U.K, China, Japan, virtually every single other country surpasses it in industry within the first five to ten years of the game. The massive military it has doesn't seem to help either. The Soviet Union always lags behind in tech, literacy, well, everything. 

China:
1.07: The Peoples Republic of China normally wins the war.
1.08: Republican China seems to win more often, and following this, enters into frequent wars with the Soviet Union. The Soviet Union then proceeds to occupy every single province of Republican China. What happens here then is that China becomes a third rate power, and these repeated wars with the Soviet Union causes the Soviets to collapse sooner. Republican or Communist China also go into frequent wars against India and the United States as well.
Both:
-Any wars against China by the Soviets, America, or Manchuria usually end up in a "Liberate country" wargoal being added by the A.I. Every substate region of China usually gains its independence early on.
-China never conquers Tibet. 

Manchuria:
1.07/1.08: In the event the Soviet Union releases Manchuria later on after keeping it, or if they release it as a satelite early on, Manchuria becomes a bit of a nasty issue. Nine times out of ten, they become a Great Power, and usually remain in the 8th spot for the whole game. They never actually manage to build a massive industrial base, but they always build the worlds largest army(8th to fifth place.). Following this, they completely wreck American/Soviet influence in the Far East, and quickly become dominant.
-Manchuria also enters into frequent wars against China. The chinese/Soviet wars are enough to keep the Chinese as a civilized, third rate power for the entire game. Manchuria simply reinforces this, times five. 

-Islamic Issues(1.07/1.08).
-The constant event spam of "Islam rising/Radical/Suppression" is annoying, as well as a bit ahistorical for it to be so rampant early on.

https://en.wikipedia.org/wiki/Operation_Cyclone
https://www.washingtonpost.com/news/worldviews/wp/2014/12/08/the-taliban-indoctrinates-kids-with-jihadist-textbooks-paid-for-by-the-u-s/
---Israel also started supporting the more radical aspects of Islam back in the 80s in order to weaken the secular Palestinian groups organizing at the time. 
---So this shouldn't exactly become a major issue until the late 70s/80s at least. Perhaps we could simulate Egypts role as a leader in the Arab world? The Egyptian/Saudi backed by American conflict? I'll try to work on some events when I have time.

Islamic State: 
-A couple issues. One, they get cores everywhere. All over Syria, Egypt, Russian Caucasus regions, Iraq, Yemen. Then they form and take out all of Syria save one province, and nearly all of Yemen. Now, then they instantly get a whole bunch of armies, and easily conquer everything in site. 
The second issue is that when they form, the war between them and their enemies is a tad weird. For example, Syria is at war with the Islamic State. The Islamic State however has no war goal against Syria. The Syrian War goal against the Islamic State is to humiliate them. It be a tad better to have them having a wargoal to retake all their lost provinces? --- 

Yugoslavia:
1.07/1.08: Attempted to reintergrate them as the Soviet Union. Get a puppet caucasus belli. Following this, the Yugoslavian republics that are puppets of Yugoslavia do not reintergrate, but simply become independent.


Cuba:
-America always goes to war against Cuba to restore democracy/Puppet the moment it goes communist.. They always win as well. Soviets never do anything.

Rare Raj/India:
Never forms. Substates remain independent. Remains a third rate power in eternal debt. Pakistan stuck in a eternal war against a nonexistant India. 
/In the event India forms, Pakistan/SOv/USA tend to steamroll them. Pakistan has a liberate wargoal to free Hyder. Hyder becomes a Secondary/GP. Easily kills India.


Misc Issues:
Nationalization Issue: - See above. Version 1.08. - Constantly, everyone in the map gets a "Declare war to restore democracy.". When every single country on the map goes to war against Cambodia, Nicaguria, and a bunch of African minors, ehh. 
Crises: (1.08/1.07). Kurdistan usually becomes a major issue throughout the game. Nine times out of ten, their are crises in Iraqi Kurdistan, and Iranian Kurdistan. Nine times out of ten, they will accept the proposal of whatever AI Great Power upon the start of the crisis to free Kurdistan. Nowhere else in the game do crises become a big deal(Unless I as Japan hit Malaysia). It be nice if the A.I actually tends to not instantly accept whatever the offer side offers upon Day 0/1.
---Would it feasible to lock crises until late in the game until this issue is resolved?
---Crisis Event spam. Repeatedly getting the -50%, nobody cares anymore crisis spam is a tad annoying.  I tend to get that constantly.
Populism: Populism is way to big of a force in this game. By the early 1960s, Populist regimes rise in Italy, France, West Germany, Japan, the U.K, and from time to time in America. Constantly claiming cores/Etc.

Now, all of the above was tested in version 1.08, and these are all issues I have found as late as last night. In 1.07, India appears to become a Great Power quite fast. In 1.08, India seems to be more of a third rate power, constantly being killed by Pakistan. 

In general:
-America remains largely isolationist. Outside of scripted events, America enters into no wars.
-The Soviet Union enters into frequent wars against India, China, and these wars cause it to die sooner.
-Italy and France hate each other.
-Everyone seems to hate Spain. Itay and France in particular. They always go with a liberate wargoal. I have however noticed that their are frequent wars of containment against Spain - Though Spain has done nothing at all, nadda. Spain remains largely isolationist, save for trying to hit France with a liberate wargoal if France ever weakens.
-West Germany is largely isolationist. However, they will go for Poland if a Populist party does rise, and the Cold War is over. (Populism always rise to power. Everywhere. Fall and rise, rinse and repeat.)
-France hates Italy. And Spain. And the U.K. And America. Military wise, they are the dominant power in Europe(Besides the Soviet Union, which will never interfere. Though in V1.07, the Soviet Union may rarely steamroll all of Europe in one big war.)
-Did I mention everyone seems to hate each other/Remain isolationist alot?
-Very little war that is not scripted besides SOV/CHI/IND and USA/UK SPA/ITA/FRA wars. 
-Oh. The World Economy likes to tank. A lot. Russia/Sovs remain the number one supplier in oil/Fuel, followed by Arabia...Always as well. 


./In 1.07, India/CHI(If it survives) always surpass everyone else and become the 1/2 GPs. Europe is, not a issue. Everyone likes, outside of their set countries they hate, to leave everything alone. Africa is prettymuch a quiet zone, as well as the Middle East. Etc.

**Comment by simsulla** [comment]
Thanks for the bug report Puppysif, 

Soviet Union:
On USSR, both scenarios are possible - i.e. Russia may be able to keep the some of it's empire. 
On AI, I not sure I believe that is what is happening. Rather my hypothesis is that Russia goes bankrupt and then some of there industry is removed. That most of USSR's industries was little more than fasades correlates with reality.

China:
I han't seen your 1.08 scenario in my test games, though it is possible. The reconquest of Tibet by PRC is event driven. In an alt reality maybe KMT would have settled with taking Chamdo and vassaling Tibet. No such event at the moment though.

Manchuria:
In 1.08 Soviet don't have the event option to release Manchuria. I have never seen the scenario you depict (independent Manchuria). Is Manchuria created by user action?

Islamic Issues:
It starts in the 70s. That is historically accurate,as some time is needed till they gain electoral strength in elections in the 90s-till today. But I will make the event a bit less frequent.
Egypt's leading role is very much in the mod (with UAR). But also it's decline once it fails.

Islamic State: 
Will correct. Issue #590

Yugoslavia:
I believe this is core vic2 functionality, if you puppet a nation with puppets, it loses those. 

Cuba:
Will correct, special case Cuba, for the rest lets chance decide.

Rare Raj/India:
Don't see that... My last test game
![image](https://cloud.githubusercontent.com/assets/10263809/17290729/42ee129c-57e0-11e6-9b7f-0fd3c3b37841.png)

Misc Issues:
Will make the democracy wars on nationalization less frequent.
Crises are reworked in 1.08, making them be preventedby UN intervention. This should mitigate the issue. Will fix the event spam.

In general:
Spain is fascist, and after WW2 was a bit of paria under Franco, that is why they get infamy. Politically Spain needs to handle this, and pursue politics carefully. You mention several "generic AI issues", I will delay release a couple of days and see if I can tune the game somewhat.
Many of the things you report is "ai generic" and difficult to address. Maybe it is better to create a lot of small issues focusing on specific cases, that can be more easily. I prefer individual issues per bug.

ps. corrections to your bug reports are partly committed as updates to the issue that caused the bug..
