### ISSUE TITLE
Crash Around 1990-2010

### ISSUE THREAD

**Issue by TheWrongGuy** [simsulla/nwomod#6]
Game encounters "win32 exception" and crashes to desktop sometime in these decades.
Happened in a EvW game as the RoC and in a NWO game as Germany and stopped me from playing any further.

**Comment by simsulla** [comment]
What version are you playing? 0.9.105+? If so, do you have a save game
shortly before the crash that I can have a look on. In my test game (1946-
as Bhutan "debug assert"), I am unable to reproduce the crash.

**Comment by TheWrongGuy** [comment]
Ah no I was still on 0.9.104. I will update now.
