### ISSUE TITLE
Localization and namings

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#606]
**pesgores**
Golan Hights should be Golan Heights
**adriankowaty**
Grodno's state is misnamed - it's called Gordno in game.
**Dveduu**
-Quite a few typos in the terrorism event chains: "Emprosin the terrorists" "Try an prevent then reqruting" "Agitation dies down - this is a releef"

**Comment by Liegnitz** [comment]
Port Arthur, Luxembourg & the Austrian Regions too.

**Comment by simsulla** [comment]
**Enlil**
This is minor, but there are a lot of spelling errors in the Saudi events like "Embrosin the terrorists" or "stop them from requiting"
