### ISSUE TITLE
Climate Change

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#622]
Having recently read a couple of news articles about climate change,I wondered if there was any events in this mod to represent climate change,if not I could add them as climate change is a very big problem we are currently facing today and it is predicted to only get worse.

**Comment by zachary123212** [comment]
On a basic level, perhaps this could be simulated by a global climate change variable that increases based on factors (e.g. global output of coal-based factories (if this can be measured)). At certain value thresholds, different provinces could begin to receive harmful event modifiers (e.g. coastal Bangladeshi provinces get immigration push, severely reduced life-rating, and RGO shrinkage due to flooding, ).

**Comment by simsulla** [comment]
Climate Change has ben up for discussion earlier in the [thread](https://forum.paradoxplaza.com/forum/index.php?threads/new-world-order-mod.823674/page-102#post-19901727). My question was the extent of impact it would have in the relatively limited time frame of NWO (till 2100).

**Comment by arandomperson5000** [comment]
For the impact of Climate Change,here are several of the main consequences of it.
1.Desertification
As global warming is happening ,it causes inland water sources in deserts and semi arid like oases and inland lakes to evaporate quicker than they could sustain and makes them disappear quicker than usual with little to no hope of recovery like in the past. This destroys water source which people and animals living in these regions depend on for survival.Along with overgrazing the desert expands into areas which were previously had more inhabited and fertile.This process causes the area's inhabitants to flee into more fertile and habitual areas putting an increasing pressure on those areas. This could be represented by a series of events which start from a date like 2010 for example  with a deathdate at the game's end, not unlike some events found in Darkest Hour. The events would then add a modifier on a particular province close to or in a desert  where pops will start to flee to more habitual provinces creating refugee camps. Militancy and consciousness would increase to a high level since it is almost certain that there would be conflicts over access to water. However heavily industrialised countries like China and India face a shortage of drinking water caused by industrial pollution.Maybe you could add an event for a shortage of water which in in turn triggers a cb  allowing you to invade other countries to get access to their water supply.

2.Flooding
As the icecaps melt thanks to increasing industrialisation sea levels are predicted to rise by several meters by 2100. This will cause major flooding along the coastline areas of the world especially lowland areas like New York City.To represent this in game I would suggest making a series of events which has certain startdates and deathsdates at the game's end.This will cause people living in coastal areas to flee to more inland areas which are more protected against floods than coastal areas. Over time this could cause a disastrous effect on the in game economy as important urban coastal provinces with a credit rgo become less profitable to the economy as the pops required to harvest this rgo immigrate to more inland areas causing a shortage.

3.Extinction
Global Warming is a large factor in causing large number of animal species to go extinct or be endangered along with other factors like overhunting and increasing human encroachment on their natural habitats. Perhaps an event may be created to represent this by telling us that an iconic animal species has gone extinct thus increasing pop militancy and consciousness a little bit.

I apologise for this being so much of a textwall but having read a analysis why hasn't Nigeria collapsed yet in spite of it's ethnic tensions and the failure of other british created federations in the twentieth century like the West Indies Federation and looked at couple of pages from crw flags detailing several separatist movements and their flags around the 1960s. I would ask you if it possible to implement a event where Nigeria is split up into multiple countries resulting from a defeat in which Biafra won its independence causing a sudden increase in confidence of separatist movements and a doubt that Nigeria could survive as a state since it was only created as a political entity in 1914 by Frederick Lugard it's first colonial governer by the merging of the Northern and Southern Nigerian protectorates, also consider that many pre colonial states like the Sokoto Caliphate weren't conquered until the 20th century much later than other areas in the Scramble for Africa and that even when Sokoto was conquered its islamic emirs still were able to keep their positions as a system of indirect rule created by Lugard in the Northern Nigeria protectorate much like the Princely States of India,

**Comment by simsulla** [comment]
Please create a separat **Somali Civil war** issue and move your Somali comments there.

On North-South split of **Nigeria** belongs in a separate issue not in "Climate Change".

On Climate Change, I like the idea pleas make events. On the 2.Flooding and 1.Desertification  do you have references with specifics? Natural disasters (historic) as such already are in the mod, it would be nice to add more fictitious to reflect future natural disasters.

**Comment by arandomperson5000** [comment]
For the references you asked above 
here are several references for 1. Desertification and  2 . Flooding
1. Desertification
http://www.greenfacts.org/en/desertification/

2 . Flooding
http://ocean.nationalgeographic.com/ocean/critical-issues-sea-level-rise/

If you want any more sources and references for both of these issues I will get more for you.

**Comment by simsulla** [comment]
**simsulla**
A little bit more on Climate Change....
Climate Change has been suggested before. The "Prime directive" of the mod is Realism. For future events (like Climate Change, Peak Oil etc.) it is difficult to no exactly what will is the future "Reality".

So let me explain the way I go about predicting the future (like Climate Change, Peak Oil etc.). I search for reports (scientific and factual) on the subject preferably from the 1990s or earlier. Then I look on how accurate those projections where for c2010s, and take this into account when I read there current projection for the future. So when taking their current projection for the future I will assume they are as wrong as they where in their 1990s projection :)

I have done it for Energy production (oil, coal, gas) using BP's excellent Statistical Review of World Energy. They/BP (interestingly enough) underestimated both production and consumption in the 1990s as compared with de-facto today. Using there future estimates (with said skepticism) in total I don't belie we will see any Peak "Energy" within the NWO timeframe to 2100 (though some types of oil products may  peak - those in terms of energy will be substituted by others - like Shale Gas, Tar Sands - and of-cause there may be a peak energy later after 2100.).

I have not read up on the Intergovernmental Panel on Climate Change (or som other climate change report) and done this evaluation for Climate Change. If someone is interested and want to maka a similar analysis (for-example take the IPCC's report from  the 1990 and 2010s and compare). Your findings will determine how Climate Change is modded.[/QUOTE]

**simsulla**
Ok, reading up on the IPCC (Intergovernmental Panel on Climate Change).

In IPCC 1990 summary for policy makes they write, from Working Group II
(i) an effective doubling of CO2 in the atmosphere between now and 2025 to 2050 for a 'business-as-usual' scenario;
(ii) a consequent increase of global mean temperature in the range of 1.5°C to 4°-5°C;
(iii) an unequal global distribution of this temperature increase, namely a smaller increase of half the global mean in the tropical regions and a larger increase of twice the global mean in the polar regions; and
(iv) a sea-level rise of about 0.3-0.5 m by 2050 and about 1 m by 2100, together with a rise in the temperature of the surface ocean layer of between 0.2° and 2.5°C. 
Working Group I was a bit mor conservative and for a 'business-as-usual' scenario has estimated the magnitude of sea-level rise at about 20 cm by 2030 and about 65 cm by the end of the next century. Working Group I has also predicted the increase in global mean temperatures to be about 1°C above the present value by 2025

Ok, so now we are a quarter into there prediction, so what are the factual changes.
(ii) seems to be a bit of overestimation (from Nasa global climate change) the temperatur 1990-2015 has risen c0.32C.
(iv) sea level rise satellite data per year from 1993 to 2009 indicates 3.3 mm. Also here it seems like they over estimated the seal level rise. 
It seems like tended to overestimate sea rice and temperature change. 
IPCC also discuss economic effects in terms of farming output, RGO's in vic2 terms. But I have been unable to find any data indicating an accrual global output reduction in the period 1990s-2015 (using data from FAO (UN Food and Agriculture Organization)) attributed to the factual global change in climate. 

For the record my knowledge here is very superficial so if anyone knows more I will easily be corrected :rolleyes:. 
However as it stands now using 1990-2015 as the measure for factual effects I don't see climate change as a major factor in the mod except as occasional natural disaster events that may be added - that could be attributed to climate change.

**Comment by simsulla** [comment]
Natural disasters are in the mod - and more may be added separably. The political aspect of "Climate Change" will be implemented as a a series of treaties and conferences with the effect of increasing consciousness and progressiveness.
