### ISSUE TITLE
Nigeria Split Up

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#624]
Having read a analysis why hasn't Nigeria collapsed yet in spite of it's ethnic tensions and the failure of other british created federations in the twentieth century like the West Indies Federation and looked at couple of pages from crw flags detailing several separatist movements and their flags around the 1960s. I would ask you if it possible to implement a event where Nigeria is split up into multiple countries resulting from a defeat in which Biafra won its independence causing a sudden increase in confidence of separatist movements and a doubt that Nigeria could survive as a state since it was only created as a political entity in 1914 by Frederick Lugard it's first colonial governer by the merging of the Northern and Southern Nigerian protectorates, also consider that many pre colonial states like the Sokoto Caliphate weren't conquered until the 20th century much later than other areas in the Scramble for Africa and that even when Sokoto was conquered its islamic emirs still were able to keep their positions as a system of indirect rule created by Lugard in the Northern Nigeria protectorate much like the Princely States of India

Anways I wouldn't min d if you decided to close this issue if you find it too unrealistic.

**Comment by simsulla** [comment]
Great job on divided Nigerian states.
Questions:
1. What is the references for the flags?
2. You choose not to have a south united as South Nigeria, any reasoning? 
3. In particular as a consequence the South does not contest the christian/muslim "mixed" "Central Nigeria" state that in Nigerian elections often vote "christian"?

**Comment by simsulla** [comment]
I created a bunch of colonial (realm) flags, to enable using the ARE and YOR cores for North and Southern Nigeria.

![image](https://cloud.githubusercontent.com/assets/10263809/17837711/a36ee22e-67ba-11e6-9813-281fab88831a.png)

**Comment by arandomperson5000** [comment]
1.I had found most of the flags on crw flags.The flags in question comes from the Flags of Aspirant Peoples an atlas and colour chart published in 1994 by the Flag Society of Australia and the Flag Research Center.The Arewa flag is based off the flag of the a propsed Hausa state in 1966 however I did felt it was an appropriate non colonial flag for the Muslim north as the Hausa and the Fula peoples are often grouped together as the Hausa-Fulani since they had a close relationship with each other ever since the Fulani jihads of the early 19th century.For Benin(Nigeria) it was briefly established as a puppet state of Biafra when it took over control of the Mid-Western region from Nigeria in 1967, however it only lasted one day as the Nigerian military quickly recaptured it.For the Oodua flag I was a bit divided on whether to use the Yoruba ethnic flag or the Oodua liberation front's flag however I chose the ethnic flag as it better represented the Yoruba as it is much older than Oodua liberation front's flag as it dated back as far as the 1960s, the Oodua liberation front was only created in the 1990s.

2.Historically there was no movement advocating for an independent united southern Nigeria. While there is a Muslim North there is no such thing as an Christian/Animist South as while it is mostly true in the areas around the former Biafra and the Niger Delta, the Yoruba inhabited parts of a country are much more divided than the rest of Nigeria, roughly 35% of Yoruba adhere to Christianity while 55% follow Islam as their religion and 10% follow traditional religion.Also I do believe that there is great distrust between the Igbo and the Yoruba since the Yoruba were one the ethnic groups that were involved in defeating Biafra in spite of expectations that the Yoruba will fight alongside Biafra against Nigeria.I believe this has created a stab in the back perspective towards the Yoruba by the Igbo. Not to mention at the time of independence was divided into 3 federal and autonomous regions the Igbo inhabited Eastern,Yoruba inhabited Western and Muslim inhabited Northern regions.IN 1967 further divisions were set up including the splitting of the Edo inhabited Mid Western region from the Western region. However I do feel that a unified Southern Nigeria could exist as a form of union even though there was no real life movements proposing it.It would make for a good alternate history and it  is plausible as it only dissolved in 1914 a few decades before the mod's start so a few Nigerians could have remembered it and it could exist as another country Eritrea disappeared as a distinctive region for almost half a century  when annexed by Ethiopia however it returned when it gained its independence in 1991 after the downfall the Derg regime in Ethiopia.Also the idea of an independent state composed of union between the British colonies in West Africa existed as early as 1919 when the National Congress of British West Africa was founded which actively promoted this idea.
3.I'am a little bit confused on what that question is trying to say.

**Comment by simsulla** [comment]
**Aldarwolf**
Some potential powers are really lacking in events. My friend did a Nigeria run and she said there was basically nothing for what usually became a super power later on. Nigeria has a history of ethnic tension, civil war, military coups, violence against neocolonialism, among other things. You should really develop Nigeria since they're usually a great power and are the ones that form the African Union. You should review some of the nations that have potential to be super powers and include some events, it gets really dry to play the game without those sort of things.
**simsulla**
definitely it needs a much more entertaining game play. I will reopen issue Nigeria Split Up \#624 with your note.
