### ISSUE TITLE
Life-Ratings as TFR

### ISSUE THREAD

**Issue by zachary123212** [simsulla/nwomod#626]
I've noticed that most provinces in Africa seem to have their vanilla life-ratings. The vast majority of them are low (so that they could not be colonized until later), with the exception of provinces that were owned by African or European nations in the 1836 bookmark. Should this be changed and, if it should, how should life-rating be calculated?

**Comment by simsulla** [comment]
Really don't know, this is a difficult one, as increasing the life rating makes the provinces more productive. Which may not accurately reflect the situation in many African countries. Maybe one could use a conservative approach using population density as guiding factor together with terrain to what the life rating should be,

**Comment by zachary123212** [comment]
For the rest of the world, life rating seems to be as follows:

- USA Cities: 50-60
- Some Major European Cities (and Riyadh): 40
- Typical Eurasian, North American, Caribbean, and Southern South American provinces: 35
- 1836-colonized Africa: 35
- Typical Central American and Northern South American provinces: 25-30
- Deserts in Saudi Arabia: 20
- Non 1836-colonized Africa: 10-15

This feels fairly inconsistent, and I think we need a general schema for determining what a province's life-rating should be. If we're going with population density, then should most of India and China have their life-rating's increased?

**Comment by simsulla** [comment]
What game mechanics do we want to achieve by changing it? More RGO's in Africa, so Africans are richer??

**Comment by zachary123212** [comment]
Population growth seems like the most important effect. Higher life ratings could help to model the enormous population growth in Africa over the 20th century and, more specifically, in cities like Lagos, Cairo, etc.

**Comment by simsulla** [comment]
But other areas Europe, East Asia have low or negative growth should they then have low life rating? 
What I wrote earlier on pop density is not really correct as RGO productivity in modern times is not a function of labor but a function of industrialized farming and mining.

**Comment by zachary123212** [comment]
The European and East-Asian TFR satisfaction modifiers should override most province population growth that might be caused by higher life-ratings. In fact, I think that the life-ratings of most world cities should be increased (to 40 at the minimum, higher for cities that received more growth), to account for the fact that their population did increase considerably over the 20th century (while rural population declined). See [this page.](http://data.worldbank.org/indicator/SP.URB.TOTL?end=2015&start=1960&view=chart&year=1991)

For Africa, I propose that the life-ratings of most provinces be set to 25-30 or so (Central American life-rating), with urban centers slightly higher (35, maybe). Perhaps as part of the process of being a developing country, each african country would face events that increase the life-rating of urban centers (and increase immigration attraction to that province), until eventually their average life rating is at the same or similar level to the european countries.

Detecting urban centers could be done in one of two ways (that I can think of):

1. Regional capitals are automatically considered urban centers, and are therefore selected for an eventual life-rating boost
2. At the beginning of the game, the game gives a pre-ordained list of provinces (that we deem to be urban centers) a permanent modifier called "Undeveloped Urban Center" that doesn't do anything. When the country develops, a recurring event will look for a random province with that modifier, increase life-rating and immigration attraction (replace with "Developed Urban Center"), and remove the previous modifier. When no controlled province has the "Undeveloped Urban Center" modifier, national development is finished.

**Comment by simsulla** [comment]
Please go ahead and mod.

Detecting a urban province is can be done with the command;
is_state_capital = yes
and then level by;
total_pops = xxx

btw to my knowledge life_rating has nothing to do with pop growth.

**Comment by zachary123212** [comment]
Life rating has a lot to do with population growth; it's the reason that provinces will grow at all without tech or reforms. [I just took this screenshot to show.](http://i.imgur.com/vbZ56EW.png). Should I implement the first or second method I described (I personally prefer the second)?

**Comment by simsulla** [comment]
You are right! How can I have missed it. Yes life_rating has to do with pop growth!
From common/defines.lua
	MIN_LIFE_RATING_FOR_GROWTH = 30,
	LIFE_RATING_GROWTH_BONUS = 0.0001,
How about using the life_rating to mod the demographic transition?
So in Africa, Asia, Latin america etc... any province is given a high life rating. When the demographic transition happens (due to a number of factors literacy, secularism) we reduce the life_rating to below MIN_LIFE_RATING_FOR_GROWTH, leaving only other modifiers to determine growth. 
One could have temporary periods with higher life_rating to simulate the postwar baby boom.

**Comment by zachary123212** [comment]
The problem with that is that life-rating is permanent. If a country dips above and below the requirements for the demographic transition, their life rating could be reduced multiple times. Additionally, the problem with assuming that state capitals are urban regions is that, since the last update, there are many single province regions (because of foreign cores) that don't have any urban region in them. The problem with considering something to be an urban region just because of total_pops is that it ignores provinces which would only grow later in the 20th century, and may have started out rather small in population. What should I do?

**Comment by simsulla** [comment]
Let's use life_rating for the demographic transition and province specific high growth cases. 

So, never mind the urban provinces growth bonus. That is taken care of by migration (if you look in pop types you will see that all the "conflict state" capitals are exempt form migration bonus.. it is hard coded).

life_rating commands changes the life_rating. And if we have a province event that triggers on a certain level of literacy, majority religion secular, continent (possibly muslim majority or per culture majority) and year would reduce the life rating in the third world. Europe and the West (+ Japan) starts with lower ratings,  

We could change the LIFE_RATING_GROWTH_BONUS, MIN_LIFE_RATING_FOR_GROWTH   to better fit the required growth. To find out how the trigger needs to be configured one need to play around with the  triggers and fit it to real world stats.

Look in population_trends.txt for a good starting point for a trigger.

**Comment by simsulla** [comment]
Ok, so this issue will be used to redesign the demographic transition. Basis is that **high** lifer_rating in NWO means less-developed provinces. **Low** life_rating more-developed provinces. 

Settings:
> 	BASE_POPGROWTH = -0.02, -- % per month:  per year: -21% reflects death rates with no aging
>	MIN_LIFE_RATING_FOR_GROWTH = 0, -- ORIG 30
>	LIFE_RATING_GROWTH_BONUS = 0.001, -- % per month * life_rating (TFR/10)

**Comment by simsulla** [comment]
Factors influencing population growht
religious_policy - atheism decrease growth. Moralism increase. -0.001 - 0.001
gender_rights - feminism decrease growth, but increase factory_throughput - -0.01
lgbt_rights - decrease pop growth and pop_militancy - -0.01
child_care - increase growth - 0.002
health_care - increase growth - previously mentioned other effects is instead included under gender_rigths. - 0.002

**Comment by simsulla** [comment]
Ok, so the demographic transition will be more or less re-designed totally. The old static model where it was predestined to have a transition will be gone. Instead it will be up to the player how to manage the situation. The overall trend to lower birthrates will be difficult to avoid (but possible).

In the new demographic setting lifer_rating correlates to the TFR (x10) - [ Extra Deaths]
![image](https://cloud.githubusercontent.com/assets/10263809/21592421/aea8b8f6-d10d-11e6-9895-b0592ab7e6db.png)

This graph shows the "transition. The x-axis is literacy. 
![image](https://cloud.githubusercontent.com/assets/10263809/21592393/6a923cf0-d10d-11e6-992d-7dc7b40b210c.png)

As literacy (in NWO higher "secular" education) increases in a province fertility decreases. 
As a player you will need to balance your education efficiency (in the end literacy) with a desire to have natural population growth.

**Comment by simsulla** [comment]
**simsulla**
Struggling with this for days now, it turns out to my enormous disappointment that the condition life_rating does not reflect the current life_rating (set by demographics life_rating effects which changes whatever currently is set) but the one originally set in the history files - i.e at start. So even though we script up the decay there is no way to know when we hit the bottom (say TFR c.1.5) and we should stop decreasing the life_rating. That is the prerequisite for the dynamic system I want to create.  :(

**Comment by simsulla** [comment]
So in the end F**ed up this big time. 
Replaced a working model with static hadcoded life_rating per core. Need to do something about it in the future.
