### ISSUE TITLE
Regions in Yugoslavia + Provinces in Bulgaria

### ISSUE THREAD

**Issue by Madhate** [simsulla/nwomod#627]
Why are regions in Yugoslavia so messed up? Please take a look at them.

Also Plovdiv is not that far south. That would be Kardzhali. Plovdiv is more center

**Comment by simsulla** [comment]
Will change the name to Kardzhali.
In Yugoslavia almost all states reflect territorial conflicts
![image](https://cloud.githubusercontent.com/assets/10263809/17612487/9ebf21c2-6052-11e6-89f6-4b3e28698a0d.png)

------------------
**Yugoslavia**
- Slovenia, Croatia, BiH, Kosovo, Montenegro, Macedonia should be able to split.

------------------
**Croatia**
- Istria, Krajina should be able to split,  and we have Italian claims in Dalmatia.

**Serbia**
- Voijvodina, Kosovo

**Macedonia**
- Albanian north west

**BiH**
- Rep Srpska
- Herceg-Bosna

------------------
**Voijvodina**
- Croat, Hungarian claims

**Kosovo**
- Mitrovica (Serb)
