### ISSUE TITLE
Greek - Macedonian dispute

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#629]
See this: https://en.m.wikipedia.org/wiki/Macedonia_naming_dispute

**Comment by simsulla** [comment]
what do you think should happen besides bad relations?

**Comment by Liegnitz** [comment]
I am unsure, since Greece would probably veto a Macedonian EU membership if it remains Republic of Macedonia. Maybe make it possible to change Macedonia to F.Y.R.O.M before it is able to join.

**Comment by simsulla** [comment]
Can't change country name else than by regime change in Vic2. From my limited understanding, at it's core Greece fears Macedonian irredentism. And there action is to try an make the Macedonian "not-Macedonian" by formal name recognition actions. One way would be to start with Macedonia a populist Republic 
With this flag
![image](https://cloud.githubusercontent.com/assets/10263809/17675997/9f95f1f2-632c-11e6-91c3-a1750320b13f.png)

and then become a democracy if they yield to the Greece demands.
With this flag
![image](https://cloud.githubusercontent.com/assets/10263809/17676002/a57120ec-632c-11e6-8f0d-67859d50c6ca.png)

if they do not yield they get claims on northern Greece. And Greece get cp install democracy,

**Comment by Liegnitz** [comment]
Sounds good. I think AI Macedonia should give in to the Greek demands, as far as I can tell.
