### ISSUE TITLE
India can't "restore to order" minors who are cores

### ISSUE THREAD

**Issue by LordNotix** [simsulla/nwomod#63]
India doesn't seem to be able to use the "Restore to Order" casus beli against any Indian Minors that exist despite the minors only having Indian Cores.

**Comment by simsulla** [comment]
When India is released the Princely Indian states are puppets of India. You can't start a war on your own puppet,

![image](https://cloud.githubusercontent.com/assets/10263809/12048432/6c4e333c-aedb-11e5-9ffa-454a600b8e67.png)

**Comment by LordNotix** [comment]
Okay, I had restarted the game and seen that it had updated the status about them being a Puppet of India. Initially it did not appear that relationship existed.
