### ISSUE TITLE
Nerfing China too brutal

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#651]
**Corpsemania**
Another bug I think,is that after unification I got a total of -25% tax efficiency,which made my tax income negative,the higher tax rate I set,the more money I lost.As the consequence I went bankrupted over and over again,and cannot do anything until the modifier ends in 1960.

Corpsemania: 回复 simsulla :version:1.08;PRC;modifier:corruption(-20%)+colonial heritage(-5%)

**Comment by simsulla** [comment]
This is part of nerfing china a bit to make game play more realistic, but it should not make  a game  as China impossibly difficult.

**Comment by Liegnitz** [comment]
Maybe give less tax eficency in high pop tiles. this would also nerf bigger cities if you want.

**Comment by simsulla** [comment]
Actually I am unable to reproduce this for PRC. KMT has corruption but that was a major issu for them.
Playing as PRC maintaining budget is challenging but possible
![image](https://cloud.githubusercontent.com/assets/10263809/18172721/f3b590ca-7066-11e6-8bc9-418a544941e1.png)

KMT if they lost are in a significantly more difficult position as they will end-up with the Chinese debt only having Taiwan if they lost the civil war. Thy have to go bankrupt to clear-out the debt, and then start fresh again.
