### ISSUE TITLE
Greater Mexico

### ISSUE THREAD

**Issue by necasarycoot72** [simsulla/nwomod#656]
"The reconquista" decision for mexico does not give you cores on california and oregon

**Comment by simsulla** [comment]
Will correct California. Oregon was not part of Mexico, according to this map from wikipedia.
![image](https://cloud.githubusercontent.com/assets/10263809/18061320/9a2709d0-6e22-11e6-9f21-c8e9c41503fd.png)

**Comment by necasarycoot72** [comment]
If that's the case then why do i get cores in idaho and Wyoming

**Comment by simsulla** [comment]
Ah, need to restructure some US states as well..
