### ISSUE TITLE
Indonesia - East Timor interaction causes the game to crash

### ISSUE THREAD

**Issue by tatuhey** [simsulla/nwomod#664]
I tried inviting Singapore and East Timor as Indon, then a few days later after they accepted, the game crashes

correction,
I have no problem inviting Singapore in, the game crashes straight up after I invited East Timor

2nd correction,
the game crashes too after if you annex East Timor, by ASEAN (previously Indon).

it seems there is a problem with East Timor and Indon interaction

**Comment by simsulla** [comment]
Thanks for the bug report.
