### ISSUE TITLE
Greater Canada 

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#665]
Canada does not have a claim greater decision, so I thought it would be a good idea for canada to have decision to get cores on Alaska, Saint Pierre or even New England

**Comment by simsulla** [comment]
Are there any 20th century basis for such claims? US don't have "greater US" claims either. Those countries that have "greater" claims usually have some type of historic (last 200 years or so) or ethnic reason for those claims.

At the moment no plans.

**Comment by Necessarycoot72** [comment]
Sorry I wasn't clear enough.

https://en.wikipedia.org/wiki/Alaska_boundary_dispute

http://legal.un.org/riaa/cases/vol_XV/481-540.pdf

**Comment by simsulla** [comment]
To do that one would need to make the "Alaska pan-handle" a separate state and then add a greater decision for Canada. 
If you want to make such decision please do. I will put it into the mod.
