### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jrobertsgb** [simsulla/nwomod#682]
The game crashes instantly when I'm using NWO (vanilla and DoD work fine), it crashes to desktop after the intro video but before the game starts into the loading screen, none of the logs have anything in them so I'm not sure where to start.

**Comment by simsulla** [comment]
Are you playing the latest version? 1.??
1. remove old NWO installation completely and reinstall the mod.
2. clear your cache

**Comment by simsulla** [comment]
1.10 is just out.

1. remove your old installation completely.
2. clear your chace (the NwO cache)
3. Install the new version NWO 1.10. Vic2 3.03 and 3.04 is supported.

02.09.2016, 23:32, "Joseph Roberts" <notifications@github.com>:

**Comment by jrobertsgb** [comment]
In case it made a different, what is the difference of the 'zho' release? I did delete the cache and mod entirely, but that might've been it.

**Comment by simsulla** [comment]
zho is the chinese release (as indicated by link name and flag ;) ). Why are you downloading that?

**Comment by jrobertsgb** [comment]
@simsulla Presumably because I'm a derp and didn't read properly, just clicking on the first download link on the releases page.
