### ISSUE TITLE
United Ossetia

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#690]
quote from the wiki 
"South Ossetian secessionist authorities demand independence or unification with North Ossetia"

**Comment by simsulla** [comment]
This is already in the mod via national reunification. Nort Ossetia must be independent,

**Comment by Necessarycoot72** [comment]
I just played as south Ossetia and north Ossetia and there is no event event when north Ossetia is independent (not sphere, not vassal)

**Comment by simsulla** [comment]
There is a decision - form_union_nation.
But looking on it Ossetians are not set to have union core. Will make the south ossetian the union core for them.
