### ISSUE TITLE
greater kurdistan

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#692]
https://www.google.com/search?q=greater+kurdistan+wikipedia&safe=active&biw=1745&bih=890&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiSpPO-m_bOAhUEGh4KHbPFCtUQ_AUICSgC

**Comment by simsulla** [comment]
Please be a bit more specific. What organisation is making some specific extra territorial demand. Most areas with Kurdish population already have Kurdish cores.

**Comment by Necessarycoot72** [comment]
wrong link: https://commons.wikimedia.org/wiki/File:Great_Kurdistan;_Kurdish_nationalists_claim.jpg

**Comment by simsulla** [comment]
That is just a discussed image. I find no source for it in the wiki references. What Kurdish organization is behind the demand?

**Comment by simsulla** [comment]
As greater Kurdistan by extension de facto already is in the mod, and with no references for additional claims I will close this issue. Please request reopening if references appears.
