### ISSUE TITLE
United Baltic Duchy

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#698]
https://en.wikipedia.org/wiki/United_Baltic_Duchy

**Comment by simsulla** [comment]
Post WW2. No, not realistic. However as part of the converter UBD may exist.

**Comment by Necessarycoot72** [comment]
converter?

**Comment by simsulla** [comment]
[The Converter ](http://simsulla.org/#converter)takes old Vic2 or Hoi4 saves and convert them to NWO saves. Nations that exist in Vic2 (incl. Pop Demand Mod) like UBD, will also be in the _Converter Patch for NWO_.
However with the current version of NWO the Converter does not work and the [_Converter Patch for NWO_](https://github.com/nwomod/nwomod-converter) has not been releases.

**Comment by Necessarycoot72** [comment]
thats pretty cool
