### ISSUE TITLE
czechoslovakian reunification

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#707]
I played as the czech republic did not have a decision to reunite czechoslovakia. (maybe a bad install )

I read some articles and supposedly the communist party at the time of the dissolution did not let the people vote if they wanted to stay or not. (take it with a grain of salt) 70% of people in czechoslovakia wanted did not want the country to spit. 

http://inserbia.info/today/2015/05/czechoslovakia-czechs-and-slovaks-launch-campaign-for-referendum-on-reunification/

https://ceskoslovensko2018.wordpress.com/partneri-a-sponzori/

**Comment by simsulla** [comment]
Does this have any real political support or is it just "polling" and a website....

**Comment by Liegnitz** [comment]
Couldn't find much to the topic either. The only thing I found were Polish-Czech border conflicts an article about the Sudetengermans stop claiming land this list: https://en.wikipedia.org/wiki/List_of_irredentist_claims_or_disputes

No claims or conflicts where the Czechs are the aggressors is on that list.

**Comment by simsulla** [comment]
Will close this issue. As a player I believe not having this decision is OK, as a player, as you start the game as Czechoslovakia, And if you don't want to break up. Just keep the union.
