### ISSUE TITLE
Casus Belli

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#710]
I can't get an annexation CB against some nation e.g. Brunei and Malaysia while I can get one for Great Britian. Furthermore I cannot take any of their territory in a peace deal.

**Comment by simsulla** [comment]
They must be independent and only have one state left.

**Comment by Liegnitz** [comment]
They are independent, but the only things I can do are humiliation, puppeting and cutting down to size. They are independent, but in Britians sphere if it's that what you mean.

**Comment by simsulla** [comment]
A AI nation can't attack a sphered nation. As human player it should be possible.

**Comment by Liegnitz** [comment]
Yeah but I couldn't annex any of their territory when they whre sphered.

**Comment by Someone137** [comment]
#731

**Comment by simsulla** [comment]
Solved in #731
