### ISSUE TITLE
Internal Migration

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#711]
There is no migration between "old core states" and newly conquered ones. When conquering Tibet, Chamdo and Aksai Chin, even after 40 years not a single Chinese lived there.

**Comment by simsulla** [comment]
Will balance a bit, but in general it should not be possible to swamp single state provinces with migrants.

**Comment by Liegnitz** [comment]
How about increasing assimilation and increasing migration a bit more, so when the original country regains control they assimilate the new minoriy faster?

**Comment by simsulla** [comment]
will consider it, but tuning migration is the main candidate...

**Comment by simsulla** [comment]
**Dveduu**
Also, is migration from cities to rural areas completely removed? I keep trying to purge non-accepted citizens, but it just drops my population in these areas.

**Comment by Liegnitz** [comment]
It was meant as part of tuning, by increasing assimilation when a nation has a core on one province, but also increase internal migration, to give the owner a chance to make it a real part of his country.

See the Kazakhstans pop as an example. Before the dissolution of the Soviet Union many cities and regions had quite a huge amount of Russian pop living there, but after its fall those people assimilated or moved to Russia proper.
