### ISSUE TITLE
Colossus of Rhodes

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#717]
"On December 2015, a group of European architects announced plans to build a modern Colossus bestriding two piers at the harbor entrance, despite a preponderance of evidence and scholarly opinion that the original monument could not have stood there. The new statue, 150 metres tall (five times the height of the original) would cost an estimated $283 million, funded by private donations and crowdsourcing. The statue would include a cultural center, a library, an exhibition hall, and a lighthouse, all powered by solar panels."

http://www.dailymail.co.uk/travel/travel_news/article-3296500/Wonder-world-Colossus-Rhodes-REBUILT-complete-museum-inside-light-beacon-seen-34-miles-away.html

http://www.popularmechanics.com/technology/a18877/architects-want-to-rebuild-colossus-of-rhodes/

**Comment by simsulla** [comment]
If anyone want to make this decision please do.
