### ISSUE TITLE
military score 0 for India China

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#723]
**LordCzar117**
First off, I love this mod, commend the work you've done on it andam truly   amazed by the amount of accuracy and effort you've put into it.

Now the big problem I'm getting is that the AI seems to not have any armies being recruited. EX: I loved to see Pakistan win the Indo-Pak wars, but this feeling is kind off ruined when AI Pakistan will always beat AI India because India never spawns any troops. Even the event for India to retake cores fires and India is still sitting there with no units just getting destroyed. 
Same thing with China who wins the civil war and then just disbands all it's troops somehow having 0 as a military score. I'm certain I'm not the only one with this issue so it'd be great to get some feedback.

**Rioting Soul**
India won some unification wars and then completely disbanded its army. Sometimes it recruits a few more troops but then they get disbanded soon after. They have 0 mil score.

**Comment by Liegnitz** [comment]
Can confirm the India issue, they have no armies whatsover, when I (China) attacked them.
