### ISSUE TITLE
Support additional languages

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#73]
Use google translate to support additional languages.

**Comment by VictorWeikum** [comment]
Oh my God, no, don't do that, don't turn to the dark side! Google translate is awful! (except for, maybe, english-german and russian-ukrainian translations).

Translations should be done manually by native speakers. I can do Russian. But it's better to be done after anything else, and I have so many ideas for new events with historic and alternative choices for modern Russia and post-Soviet countries.

**Comment by simsulla** [comment]
Ok, point taken. Will put this work on hold for the time being.
