### ISSUE TITLE
The mod crash always after a few minutes

### ISSUE THREAD

**Issue by Sussudio** [simsulla/nwomod#734]
Hi simsulla! I played your mod since 1.06 version but now (1.09 and 1.10) the mod crash always. I have DH 3,03. What I can do?

**Comment by Sussudio** [comment]
The crash appear in the main screen and two minutes + o - after start the game.

**Comment by Sussudio** [comment]
I have seen that also happens with the vanilla version. I uninstalled everything (including documents folder) but still happens the same. Before I was going all right, what I can do? :S Your mod is the best of all games of Paradox.

**Comment by Sussudio** [comment]
Load very well but crash after two minutes.

**Comment by simsulla** [comment]
Try this.
1. Completely remove the mod/NWO folder.
2. Clear your cache (for NwO).
3. Verify that you can start vanilla Vic2 and all works.
4. Reinstall the NWO mod from the downloaded 1.10 zip file. 
5. Test......

**Comment by Sussudio** [comment]
Solved! Very thanks! :)
