### ISSUE TITLE
Grater Portugal 

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#750]
I was playing as portugal and and I wanted to conquer Spain. So wanted to find the area with the most portuguese. I look at Galicia and I was shock by the amount of portuguese in the area at 61 and 57% of pops in the area are portuguese. So at a gameplay point of view, is it possible to add a decision to add portuguese cores to Galicia 

If you must have a referencehere are some weak one's
https://en.wikipedia.org/wiki/Galician-Portuguese
https://en.wikipedia.org/wiki/Greater_Portugal

**Comment by arandomperson5000** [comment]
I do believe that this is realistic enough to get into this mod as a decisions as it would make sense for a very nationalistic/populist Portugal to expand into Galicia on the basis of ethnicity and I do recall that is it a real political idea that exists but sources on the subject of Greater Portugal are quite scarce excluding the territorial dispute between Portugal and Spain over the small town of Olivenza,

**Comment by simsulla** [comment]
There is another mechanism (National Unification) that may be more appropriate. This requires that Portuguese is made into a union culture.  If Galicia get independence they may unite with Portugal as both are Portuguese cultures. This would then be the basis of a Lusophone community (including Brazil) formidable into Portugal. Not sure if that is realistic.

**Comment by Necessarycoot72** [comment]
Sorry it took so long. I was finishing my playthrough. So what exactly are the requirements for a National Unification?

**Comment by simsulla** [comment]
The culture must be a "union" culture, i.e. in common/cultures.txt the culture has union=POR (or whatever tag).

**Comment by Necessarycoot72** [comment]
thx
