### ISSUE TITLE
Climate Change 

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#753]
**simsulla**
Climate Change has been suggested before. The "Prime directive" of the mod is Realism. For future events (like Climate Change, Peak Oil etc.) it is difficult to no exactly what will is the future "Reality".

So let me explain the way I go about predicting the future (like Climate Change, Peak Oil etc.). I search for reports (scientific and factual) on the subject preferably from the 1990s or earlier. Then I look on how accurate those projections where for c2010s, and take this into account when I read there current projection for the future. So when taking their current projection for the future I will assume they are as wrong as they where in their 1990s projection :)

I have done it for Energy production (oil, coal, gas) using BP's excellent Statistical Review of World Energy. They/BP (interestingly enough) underestimated both production and consumption in the 1990s as compared with de-facto today. Using there future estimates (with said skepticism) in total I don't belie we will see any Peak "Energy" within the NWO timeframe to 2100 (though some types of oil products may  peak - those in terms of energy will be substituted by others - like Shale Gas, Tar Sands - and of-cause there may be a peak energy later after 2100.).

I have not read up on the Intergovernmental Panel on Climate Change (or som other climate change report) and done this evaluation for Climate Change. If someone is interested and want to maka a similar analysis (for-example take the IPCC's report from  the 1990 and 2010s and compare). Your findings will determine how Climate Change is modded.[/QUOTE]

**simsulla**
Ok, reading up on the IPCC (Intergovernmental Panel on Climate Change).

In IPCC 1990 summary for policy makes they write, from Working Group II
(i) an effective doubling of CO2 in the atmosphere between now and 2025 to 2050 for a 'business-as-usual' scenario;
(ii) a consequent increase of global mean temperature in the range of 1.5°C to 4°-5°C;
(iii) an unequal global distribution of this temperature increase, namely a smaller increase of half the global mean in the tropical regions and a larger increase of twice the global mean in the polar regions; and
(iv) a sea-level rise of about 0.3-0.5 m by 2050 and about 1 m by 2100, together with a rise in the temperature of the surface ocean layer of between 0.2° and 2.5°C. 
Working Group I was a bit mor conservative and for a 'business-as-usual' scenario has estimated the magnitude of sea-level rise at about 20 cm by 2030 and about 65 cm by the end of the next century. Working Group I has also predicted the increase in global mean temperatures to be about 1°C above the present value by 2025

Ok, so now we are a quarter into there prediction, so what are the factual changes.
(ii) seems to be a bit of overestimation (from Nasa global climate change) the temperatur 1990-2015 has risen c0.32C.
(iv) sea level rise satellite data per year from 1993 to 2009 indicates 3.3 mm. Also here it seems like they over estimated the seal level rise. 
It seems like tended to overestimate sea rice and temperature change. 
IPCC also discuss economic effects in terms of farming output, RGO's in vic2 terms. But I have been unable to find any data indicating an accrual global output reduction in the period 1990s-2015 (using data from FAO (UN Food and Agriculture Organization)) attributed to the factual global change in climate. 

For the record my knowledge here is very superficial so if anyone knows more I will easily be corrected :rolleyes:. 
However as it stands now using 1990-2015 as the measure for factual effects I don't see climate change as a major factor in the mod except as occasional natural disaster events that may be added - that could be attributed to climate change.

**Comment by arandomperson5000** [comment]
Should I close issue 622# Climate Change as this issue is exactly about the same thing.

**Comment by simsulla** [comment]
Sorry ... no I will move my comment to #622 and close this.
