### ISSUE TITLE
The Strategic Defense Initiative 

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#759]
This was an idea america had in the 80s to prevent nuclear annihilation but did not come to fruition. maybe make it a decision or have a event that gives the possibility for it to succeed?

http://www.coldwar.org/articles/80s/SDI-StarWars.asp
https://en.wikipedia.org/wiki/Strategic_Defense_Initiative
https://www.youtube.com/watch?v=XI-YkEIiUXY

**Comment by simsulla** [comment]
I like the idea. Maybe not as a viable program but more as a way to force expenditures on the Soviet Union by forcing them to take counter measures.
