### ISSUE TITLE
Cornish Nationalism

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#760]
So i was researching the british isles and found that cornwall has a desire for independence. There are several party who want the independence, and even a small terrorist group for the cause. Here are some quotes from the wiki.

The Cornish Nationalist Party was formed in 1975 by Dr James Whetter and is currently not registered to contest elections 

Cornish Solidarity were a non-partisan political pressure group that called for the recognition of the ethnic Cornish as a national minority. They are currently in "hibernation"

**Comment by simsulla** [comment]
Independent Cornwall seems way to unlikely. No plans for it in the mod.

**Comment by Necessarycoot72** [comment]
whoops forgot the url:  https://en.wikipedia.org/wiki/Cornish_nationalism
