### ISSUE TITLE
Cascadia. Possible country?

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#771]
Cascadia is a proposed country in west canada and in northwestern america. Maybe add it for more diversity in north america?

https://en.wikipedia.org/wiki/Cascadia_(independence_movement)

**Comment by arandomperson5000** [comment]
There is already flag files and localisation files for Cascadia but I don't know whether they Cascadia was removed due to it being too unrealistic.

**Comment by simsulla** [comment]
Cascadia is too unrealistic and thus not a candidate country for NWO. 
(it was in the mod previously as part of the "Converter" converting Vic2/PDM games to NWO... all those extra countries has/will be moved to a patch release)
