### ISSUE TITLE
Second Libyan Civil War

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#778]
**The Sneaky Top Hat**
I have also created a full event chain and countries for the Second Libyan Civil War which is currently happening right now cuasing Libya to be in complete anarchy. Anyways if there is anyone looking for sources on the Fezzan autonomy attempt in 2013 well here there are.
http://english.alarabiya.net/en/News/middle-east/2013/09/26/-Libya-s-southern-Fezzan-province-declares-autonomy.html
http://www.libya-businessnews.com/2013/09/30/fezzan-region-declares-autonomy/
http://atlanticsentinel.com/2013/09/southwest-libya-considers-autonomy-state-fragmentation-looms/

**Comment by simsulla** [comment]
What is the status of this issue?

**Comment by arandomperson5000** [comment]
I havane't converted the event chain to the current version of NWO and I also need to add new events for the Second Libyan Civil War regarding events like the failed 2016 Libyan coup d'état, the Taureg-Toubou conflict, the battle of Sirte and the rise of Haftar.

Also I'm considering whether to do a complete overhaul of the First Libyan Civil War with the National Transitional Council fighting against the Libyan Arab Jamahiriya. However implementing the NATO intervention would be difficult considering any side in a civil war can't' call allies, a potential solution to this problem would be changing the war goal of NTC from civil war to conquest.

Sources
http://www.ibtimes.co.uk/khalifa-haftar-who-former-gaddafi-general-moscow-wants-rule-libya-1600976
https://en.wikipedia.org/wiki/Battle_of_Sirte_(2016)
https://en.wikipedia.org/wiki/2016_Libyan_coup_d'%C3%A9tat_attempt
http://www.aljazeera.com/news/2015/06/tuareg-tebu-fight-proxy-battle-southwest-libya-150610115006475.html
https://news.vice.com/article/in-a-southern-libya-oasis-a-proxy-war-engulfs-two-tribes

Map of Current situation of the Second Libyan Civil War (source Wikimedia)
https://en.wikipedia.org/wiki/Libyan_Civil_War_(2014%E2%80%93present)#/media/File:Libyan_Civil_War.svg

**Comment by arandomperson5000** [comment]
I think there should be a decision in which Libya breaks up if both Cyrenaica and Fezzan are completely independent thus changing the tag of Libya to Tripolitania.
