### ISSUE TITLE
Casamance 

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#781]
**The Sneaky Top Hat**
4. I do believe that Casamance should be incorporated into this mod as that region in Senegal duffered a low level civil war from 1982 to 2014 between the Jola MSDF and     the mainly Wolof Senegal government. This conflcit started due to a sense of economical and polictal marginalisation by the Jola minority in Senegal caused by the Wolof     who dominate the nation as a whole. Not to mention Casamance is already a state in this mod.
    http://www.theweek.co.uk/64763/casamance-conflict-hopes-for-an-end-to-senegals-forgotten-war
    http://odihpn.org/magazine/the-casamance-conflict-out-of-sight-out-of-mind/
    https://en.wikipedia.org/wiki/Casamance_conflict

**Comment by arandomperson5000** [comment]
[Tripura,Casamance and Meghalaya.zip](https://github.com/simsulla/nwomod/files/518457/Tripura.Casamance.and.Meghalaya.zip)
Okay here is the zip file for the Tripura, Casamance and Meghalaya issues, I had previously created a pull request containg this file however  I had accidentally put in merge into chinese from master.
