### ISSUE TITLE
Plan Balkan

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#790]
Plan Balkan/ Dickie Bird was the first proposal by Lord Mountbatten to partition India that was completed and presented on the  15th to the 16th of April 1947.The main proposal of this plan was to that provinces should become first independent successor states rather than an Indian Union or the two dominions of India & Pakistan. As per this plan all the provinces viz. Madras, Bombay, United Provinces of Bengal, Punjab & North West Frontier etc. were proposed to be declared Independent. The states later would decide whether to join constituent assembly or not. This plan was not discussed in details with leaders of India and Mountbatten discussed just informally. He gave the plan a final touch and sent to London. Later when he moved to Shimla, Pandit Jawahar Lal Nehru joined him as a guest. Here the details of the plan were put by Mountbatten before Nehru. Nehru rejected the plan right away and told him that this plan would invite Balkanisation of India and would provoke conflict and violence. Consequently, Mountbatten cabled to England that this plan was cancelled. I'm not sure whether this plan is realistic enough to incorporate into this mod.

**Comment by simsulla** [comment]
Very interesting, do you have any reference where the detail of this plan is outlined?

**Comment by arandomperson5000** [comment]
Unfortunately sources on this subject are quite scarce here are some sources that I could find
http://www.gktoday.in/dickie-bird-plan-1947/
http://iasmania.com/cabinet-mission-plan-balkan-mountbatten-plan-indian-independence-act-of-1947/
https://books.google.ie/books?id=Es6x4u_g19UC&pg=PA119&lpg=PA119&dq=plan+balkan+india&source=bl&ots=Kgx397l3un&sig=Gzdy9olD_QuCscKNvaZ7pWoq9Ng&hl=en&sa=X&ved=0ahUKEwiBmrO949rPAhVnAcAKHWb6CkQQ6AEIVjAI#v=onepage&q=plan%20balkan%20india&f=false
http://archive.indianexpress.com/news/-mountbatten-redrafted-plan-for-nehru-/205851/
http://www.bl.uk/reshelp/findhelpregion/asia/india/indianindependence/indiapakistan/partition5/
https://books.google.ie/books?id=MUeyUhVGIDMC&pg=PA157&lpg=PA157&dq=plan+balkan+india+nehru&source=bl&ots=vWdQ21P9Xt&sig=4xcXmWyCgrPTrrXxKKvxDBtcaYs&hl=en&sa=X&ved=0ahUKEwjv857g49rPAhXCDcAKHUJxC5QQ6AEIPzAF

**Comment by simsulla** [comment]
Read all except the google books that was unavailable. All the sources are "ruminating" the same statement but none references the original plan  (internet in a nut shell ;) lot of repetition but little original work). But if there where some support for such plan it would be hyper-interesting for having in the mod.

**Comment by arandomperson5000** [comment]
I don't think there was any support for plan Balkan other than from Lord Mountbatten himself, the plan was developed in secret by Mountbatten so the general population of the British Raj wouldn't have known of this plan. V. P. Menon a civil servant of Mountbatten who advised Mountbatten to partition the Raj into India and Pakistan disliked the plan as he viewed it as too chaotic, Jinnah and Nehru hated it as it went against their visions of India and Pakistan as two single unified nations. Mountbatten made this plan to ensure continued British economic dominance of the Indian subcontinent, I think it  would have terribly naive of him to believe that as if this plan did happen the entire India subcontinent would be anarchy as mass migration, ethnic cleansing,rebellions and wars between the various former provinces and the princely states would mean that there would be little to no effort to develop the economies of these successor states due to war, therefore completely going against the intentions of Mountbatten. Also one has to think of what would happen if the disintegration of the military of the British Raj between these new states was allowed if this plan had come into fruition. Anyways most of what I have written is mostly speculation on what could happen if Plan Balkan was put into practice. It would be a very similar situation to the violent collapse of the Spanish Empire in the Americas as the new nation emerging from this empire largely fought one each other, dealt with rebellions and often broke up into smaller countries particularly during the early to mid 19th century for example the Federal Republic of Central America emerged from the first Mexican Empire in 1823 only to break just 16 years later in 1839 into the countries of Guatemala, El Salvador, Costa RIca, Honduras, Nicaragua and Los Altos,

**Comment by arandomperson5000** [comment]
![image](https://cloud.githubusercontent.com/assets/20518264/19837491/aab41aac-9eb2-11e6-91d4-d7e63af60e70.png)
Here is a map of the British Raj before the partition.
For Plan Balkan to be represented ingame I have this idea that provinces like Bihar and Bombay would do as their own separate countries however finding a flag for them would be a little bit difficult. However for provinces like Bengal and Assam they could be represented as countries that are already in the game like Bangladesh for Bengal. If Plan Balkan was to happen I would imagine all the provinces and princely states of British Raj declare themselves independent instead of forming a united India, Here is a list of the countries that could emerge if Plan Balkan was enacted in this mod.
Princely States
1. Mysore
2. Travancore
3. Hyberabad
4. Gwalior
5. Indore
6. The Princely States of the Central Indian Agency
7. Rajastan
8. Orissa
9. Tripura
10. Manipur
11. Sikkim
12. Jammu and Kashmir
13. The Princely States of Balochistan
14. Tribal Areas/Waziristan 
15. Bastar
16. Chitral

Former provinces of the British Raj
1. Punjab
2. Sind
3. Bombay Presidency
4. Central Provinces
5. United Provinces
6. Bihar
7. Assam (already featured as a country in this mod)
8. Bengal (Bangladesh could be used to represent and independent Bengal)
9. Madras Presidency (Could be represented as Dravidistan ingame as there were several movements advocating for an independent Dravidistan existing as early as the 1939 with the Justice Party founded by E.V.Ramasamy)

If Plan Balkan was to be enforced it could change the entire course of the Cold War maybe even the whole game up to 2090, without any strong state like India and Pakistan to oppose them, this would present China with a massive opportunity to boost its international standing by creating a sphere of influence around the former British Raj an area rich in raw resources and millions of people working in their respective RGOs which could be used to boost China's industry by a tremendous margin once either side in the Chinese Civil War has consolidated control over Mainland China. China could them emerge as a third superpower in the Cold War completely independent of the USA and the USSR especially after the Sino Soviet Split in the 1960s. I would expect outside powers would find it hard to set up a sphere of influence in the former Raj, the Soviet Union is completely cut off from the Indian subcontinent by Afghanistan and Iran and is busy managing affairs in Eastern Europe, the United States is too far away to have any impact on the countries emerging from the former British Raj and European influence is out of the question considering European Colonial influence is rapidly receding from Asia. The Former British Raj could become host to proxy wars that would be much more devastating than any proxy conflicts in the Cold War in real life.

As for Bastar and Chitral I would consider it suitable for them to be added as countries to this mod as there are already provinces that could do as their territory and they aren't exactly too small to be a country in this mod like the vast majority of the Princely States.

**Comment by arandomperson5000** [comment]
![20170128183945_1](https://cloud.githubusercontent.com/assets/20518264/22398966/39865402-e58a-11e6-9f85-8af0ecc127d3.jpg)
Given that countries in this mod don't need an exclusive region all to it self anymore and can own only a part of a region, would it be possible to revert the provinces currently owned by the princely states and the Raj at the 1946 startdate back to  a previous version to reflect more accurate borders in the British Raj. Also since some princely states in this mod are in fact amalgamations of smaller princely states fro example the Rajastan agency is made up of 5 princely states, would it possible to split these agencies into smaller princely states to present a more accurate but complex portrayal of the British Raj, if this were to be implemented into this mod it would make the layout of British Raj similar to the situation of India in the vanilla Victoria 2.

**Comment by simsulla** [comment]
Ok, yes we the boundaries should be correct, should return to more accurate boundaries, as far as province boundaries correlates to modern administrative boundaries.

**Comment by arandomperson5000** [comment]
![20170129122320_1](https://cloud.githubusercontent.com/assets/20518264/22403977/818debb8-e61e-11e6-9d2d-abf007a0186c.jpg)
I have just recently reshaped the boundaries to match up with the historical boundaries of the British Raj and I have added four new princely states Bahawalpur, Bastar, Chitral and Bahawalpur. Also would it be possible to split up princely states like Rajastan and Beroda into smaller princely states to present a more accurate simulation of the British Raj.

**Comment by arandomperson5000** [comment]
![20170129224000_1](https://cloud.githubusercontent.com/assets/20518264/22408677/9ade9f8a-e674-11e6-99d7-9a8c8821d33c.jpg)
