### ISSUE TITLE
Game freezes while "Adapting History"

### ISSUE THREAD

**Issue by LucanDaedrahunter** [simsulla/nwomod#793]
I downloaded this mod today and tried to play as Germany. I could load the game and even choose a nation, but when it reached the point "Adapting History" it freezes, I can even hear the ingame music, but I still just see the loading screen. I use the beta for Victoria 2 3.04 and use the mod version 1.10.
Is it a bug or does it take long to load?

**Comment by simsulla** [comment]
It takes long to load. 
Please do this
1. Clear your cache (the mod NwO)
2. Totally reinstall the NWO mod. Remove the old mod/NWO folder, and reinstall the mod.
3. Then start NWO, and let it take it's time.

**Comment by LucanDaedrahunter** [comment]
I tried what you have advised...it still "freezes" at Adapting History. Since you said that it takes long I waited...I waited for 30 minutes...nothing happened. Is it even longer?
I'm not sure what you mean with "Clear your cache". Do I have to delete the NwO folder in documents - paradoxInteractive - Victoria 2? Or is it somewhere else?

**Comment by simsulla** [comment]
It is correct, the NwO folder is the cache folder.
If yo also removed mod/NWO before reinstalling I don't know what is wrong,

**Comment by LucanDaedrahunter** [comment]
Ok, I try to completly reinstall Victoria 2 and after this I'll immediatly install NWO. Installing NWO is just putting the two folders in the downloaded archive into the mod folder right?

**Comment by LucanDaedrahunter** [comment]
Ok I tried it, I totally reinstalled Victoria 2. There was nothing Victoria related on my PC anymore...
It has still the same error. I think it has more something to do with the map. I mean, the music is there...
the mouse icon is like it would be ingame...it is just the map which won't show up and instead there is the loading screen.
Maybe it might be the problem that I use Victoria 3.04?

**Comment by Someone137** [comment]
Since you have downloaded the mod files 2 days ago, i assume you still have not updated the mod files with the map crash fix,
Try This:
Download the NWO/map/provinces.bmp file from Github and replace it over your current province.bmp file
clear cache and run again

**Comment by simsulla** [comment]
Someone137 you assume LucanDaedrahunter uses master at github.
I assumed LucanDaedrahunter was using the formal download at simsulla.org (v1.10).
LucanDaedrahunter which is it? :)

**Comment by LucanDaedrahunter** [comment]
I downloaded it at simsulla.org indeed. (I knew no other place where I could find it...). But I could try it out though...
If that doesn't work, would be there no other way? I really like what I have seen from this mod.

**Comment by simsulla** [comment]
Downloading the 1.10 zip is the correct way. Victoria 3.04 works.

**Comment by simsulla** [comment]
No more comments. Assuming this has been resolved.
