### ISSUE TITLE
Nordic Council

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#801]
The Nordic Council was created in 1952 to promote cooperation between all Nordic countries. Now i'm not saying it should be another EU but like NATO, in how you get a modifier to increase relation with other NATO maybe. there could also be a change in tech schools to have 

https://en.wikipedia.org/wiki/Nordic_Council
http://www.norden.org/en/nordic-council

**Comment by simsulla** [comment]
Well, defence alliances is very difficult to mod - and the viability of the Nordic "idea" given that all Nordic countries total political spectrum turned international after WW2 is highly unlikely. 

If you want to mod it please do. It will get into the mod. I will not make any effort however..

**Comment by Necessarycoot72** [comment]
ah OK. maybe add the enhancement tag maybe?
