### ISSUE TITLE
Martinique and French Guiana cores

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#804]
**The Sneaky Top Hat**
2.Certain provinces particularly some owned by France don't have any cores what so ever and it    is just listed as colonies in the 1992 start. I would like to know why provinces like Martinique          don't have any cores on it. I do understand why some provinces like Mayotte don't have cores       on them as a country would usually claim them as part a of an irrendentist decision like a             greater Comoros/ As for certain places like Martinique and French Guiana I know that there is     several separatist movements in real life advocating for the independence of those places             however they receive little support from the general population.

**Comment by arandomperson5000** [comment]
[Martinique and French Guiana cores.zip](https://github.com/simsulla/nwomod/files/551880/Martinique.and.French.Guiana.cores.zip)

**Comment by lucasprado51** [comment]
Hey, when the 1.12 will be disponible?
