### ISSUE TITLE
ports in the wrong places

### ISSUE THREAD

**Issue by Nemesis5002** [simsulla/nwomod#807]
At least I think they are in the wrong places, when starting a PRC campaign with the just released version 1.11 I noticed I created ships in the middle of mainland China which were quite stuck there. Also ships were created and a "factory building and port" were visible in the middle of the ocean in front of the coast of Oman. I haven't taken a screenshot, though if this doesn't occur in your version, I'll be happy to send one through. 

EDIT: also I just noticed, some places wich are definitely connected to the sea don't have the ability to build ports, places in Indonesia, as well as the Dutch Arnhem.

**Comment by simsulla** [comment]
Bug confirmed...
