### ISSUE TITLE
Mexican Drug War 

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#811]
**The Sneaky Top Hat**
2. There should be several events for Mexico on the 1994  Zapatista uprising and the Mexican Drug War to make Mexico more interesting to play as a country particularly       after the 1992 start. While the Mexican Drug War has mainly been a long intensity asymmetrical war, the number of deaths caused by the war is staggering about                 60'000 to 164'000 people have died as a result of the Meixcan Drug War. To represent this in the mod I would suggest adding a modifier in northern regions                         like Nuevo León which increases pop militancy, reduces population growth and increases emigration to more peaceful and wealthy regions. As for the Zapatista                     Uprising I am not quite sure on how  to represent it in this mod.

**Comment by arandomperson5000** [comment]
Here is the zip file for this issue
[Mexican Drug War and Chiapas Conflict.zip](https://github.com/simsulla/nwomod/files/572953/Mexican.Drug.War.and.Chiapas.Conflict.zip)
