### ISSUE TITLE
Space Programs

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#812]
This is a long shot if anything, and probably wont be added but I thought i'll ask anyway.

In the 1980's america wanted to make an "all american" space station doubly named freedom. The plan was to build the station from 1994 to 1997 with a crew living there and doing scientific research starting in 1995. But when NASA sent there first budget report to Congress they rejected the 14.5 billion dollar price tag. The plan was downed sized but conflicts continued. in 1987 the "all american" idea was drooped to lower cost, and the European space agency was brought in to add a module to the station but NASA  and the ESA had a hard time agreeing on what Europe's role was. On top of that scientists disliked the new plans for freedom because the budget cuts reduced freedoms science capabilities. By 1988 they finally reached an agreement. the U.S, Canada, Europe, and japan would all share space on freedom. The station would have a rotating crew of 6 Americans and 2 international astronauts. but more logistics and budgetary. More problem came up and despite years of planting and development space station freedom was canceled in 1990. With the cancellation of freedom it paved the road for the international space station and international cooperation in space 

https://er.jsc.nasa.gov/seh/history.pdf

https://launiusr.wordpress.com/2014/01/24/announcing-the-space-station-freedom-program-january-25-1984/

**Comment by simsulla** [comment]
Will rename Space Programs, as this enhancement should also cover other efforts in space like Chinas.

**Comment by simsulla** [comment]
Decisions
satellite - invention r7semyorka + GP 

man in space  - r7semyorka + rank 1,2 - invention man_in_space 
man in orbit - man_in_space + rank 1,2 - invention man_in_orbit
dual orbit - man_in_orbit + rank 1,2 - invention dual_orbit
space rendezvous - dual_orbit + rank 1,2 - invention space_rendezvous 
space docking - space_randevouz + rank 1,2 - invention space_docking

lunar orbit - space_docking + rank 1,2 - invention lunar_orbit
lunar landing - lunar_orbit + rank 1,2 - invention lunar_landing
mars orbit - lunar_landing + rank 1,2 - invention mars_orbit
mars landing - mars_orbit + rank 1,2 - invention mars_landing

space station - space_docking + rank 1,2 - invention space_station
