### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#813]
Did you stretch the map? When looking at Germany, Czechia and Poland it looks a bit strechted.

**Comment by simsulla** [comment]
The map is now EPSG:4326 standard projection - not the original obstructed vic2 map. In the original Vic2 map Europe is over sized.

With a real projection it is much easier to create correct real world province borders, localities of RGO resources. 

These are the two projections overplayed
![image](https://cloud.githubusercontent.com/assets/10263809/19916758/83e3514c-a0bd-11e6-8b5c-e93a5598b6b4.png)

**Comment by Liegnitz** [comment]
Ok, that makes sense. Thanks for the answer.
