### ISSUE TITLE
Several questions on Angola and the Democratic Republic of the Congo

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#814]
Here is a few things that made me start thinking of these countries in this mod.

1. I'm a little bit baffled on why is North Ovamboland a region in this mod, apart from Ondjiva being                                                  heavily damaged during  the Angolan Civil War there isn't any noticeable events,occupations or movements that happened in  it's history. I do understand why East Angola is a region as I think it represents the occpuied areas held by anti MLPA forces during the Angolan Civil War,

2. I would like to know the reasoning behind representing Kivu and Mwanza as regions in this mod. I know Kivu has been the site of much conflict and there was a brief separatist movement back in the 1960s I would still like to know why you decided to put Kivu as a region. For Mwanza though I'm not quite sure why did you put as a region in this mod although I htink it may has to do with the wargoals of Uganda during the Uganda–Tanzania War in 1978–1979.

3. How plausible would be a scenario if the Democratic Republic of the Congo was completely broken apart into smaller countries in the 1960s. Well after 1957 there was an explosion of political parties in the Belgian Congo from 0 to 50 within one year, the majority of them were political parties that were often based on ethnicity rather than a united Congo unlike the Congolese National Movement and the African Solidarity Party.  Examples of political parties in the DRC that are based on ethnicty include ABAKO, Union of Mongo and CONAKAT parties. I think ABAKO is particularity interesting as it advocated for and independent Bakongo State separated from the rest of the Belgian Congo especially between the years 1958 and 1965, if this aim had come true it would have been a revival of the Kingdom of the Kongo. If lets just say the DRC fails to establish control over both Katanga and South Kasai in this mod it could cause a similar situation to Nigeria in the DRC possibly triggering its breakup.

Sources about ABAKO
http://www.academia.edu/3844187/Joseph_Kasa-Vubu_ABAKO_and_Performances_of_Kongo_Nationalism_in_the_Independence_of_Congo
https://www.britannica.com/topic/Abako-Party

Note
Just to let you know I've posted a comment which explains what could happen if Plan Balkan was to enacted and I have also made a zip file concerning about the Martinique and Guadeloupe issue.
https://github.com/simsulla/nwomod/issues/790
https://github.com/simsulla/nwomod/issues/804

**Comment by simsulla** [comment]
1. To facilitate a possible future in history where Namibia (currently totally dominated by Ovambos) would claim southern Angola (North Ovamboland).
2. Kivu - Goma will develop into a major metropolitan region. Similar reasons for Mwanza as region.
3. I read the academic article _Joseph_Kasa-Vubu_ABAKO_and_Performances_of_Kongo_Nationalism_in_the_Independence_of_Congo_, but those forces in this case and other in sub-Saharan Africa did not manage to have there way. Though we may see some baKongo nationalism in the future at the moment thy in difference form the Ovamboland lack institutional power. What is the situation for baKongo nationalism today in the 2000s?


On #804 thanks :) for the contribution. will commit your code to master.

**Comment by arandomperson5000** [comment]
1. I like this feature as it is just one example of how the colonial borders drawn up in Africa by the European powers in the 1884 Congress of Berlin are slowly being dismantled whether it be the creation of superstates like the East African Federation. irredentist claims by countries such as Morocco or the creation of new countries like Biafra.

2. Thanks for letting me know on that, I never knew that both Kivu - Goma and Mwanza were developing into major metropolitan regions. 

3. It appears that a demand for an independent Kongo States still exists. Bundu Dia Kongo is a political/cultural/religious movement that was founded in the late 1960s by Ne Mwanda Nsemi. It has its own political party named Bundu Dia Mal and advocates for the restoration of the Kongo Kingdom which had existed from 1390 until 1914 when it was abolished by Portuguese colonial authorities as it was a Portuguese vassal and was the second country to voluntarily convert to Christianity after Ethiopia in 1483 with the arrival of Portuguese explorers to their lands. It doesen't have a good relationship with the government of the Democratic Republic of the Congo as many of its members have been shot by police throughout the decades both by Mobutu and Kabila while protesting against the government.

Here are sources that explain the Bundu Dia Kongo and the Kingdom of Kongo more in detail
https://www.britannica.com/place/Kongo-historical-kingdom-Africa
https://en.wikipedia.org/wiki/Kingdom_of_Kongo
https://www.justice.gov/sites/default/files/eoir/legacy/2014/08/04/COD103713.FE.pdf
http://www.globalsecurity.org/military/world/para/bundu-dia-kongo.htm
http://www.ibtimes.co.uk/eu-was-far-too-quiet-about-repression-its-implications-drcs-future-says-rights-group-1586820
https://www.hrw.org/news/2016/09/28/dr-congo-us-imposes-sanctions-2-officials
http://news.bbc.co.uk/2/hi/africa/6341731.stm
http://www.theatlantic.com/international/archive/2012/09/the-dividing-of-a-continent-africas-separatist-problem/262171/

**Comment by simsulla** [comment]
If you want to add Kongo - plz do.

**Comment by arandomperson5000** [comment]
![20170102211533_1](https://cloud.githubusercontent.com/assets/20518264/21596496/ebdabfaa-d133-11e6-8a56-776012bf06cc.jpg)
Here is a map I made using the Victoria 2 military plan designer to depict on what a hypothetical breakup of the Democratic Republic of the Congo might look like. 

Some Points that will help me to explain the map better to the reader of this comment.

1. The province of Maniema was briefly an autonomous republic of the Congo during the Congo Crisis, unfortunately there has been very few reliable sources on this autonomous republic although I do know that it was once supported by Katanga.

2. The Belgians unsuccessfully tried to prop separatist movements in Equateur and Kivu, in the case of Kivu, this province is quite isolated and far away from Kinshasha ,given the poor control the Congolese government have over Kivu, it's likely a separatist movement could have existed once that has been unreported and that Kivu was once the capital of several rebel government against Mobutu's government of Zaire during the late 1960s to his downfall in the First Congo War that ended in 1997. As for Eqauteur, it unsuccessfully tried to secede from the Congo in 1960 with armed militias from the Ngombe and Mongo peoples fighting each other, however this attempt was quickly quashed by the Congolese military. As in my previous point there is very little reliable information on what was the situation going on in these provinces during the Congo Crisis compared to South Kasai and Katanga.

3. North Kasai is self explanatory as a counterpart to South Kasai and Orientale could be represented as its own country or Congo Stanleyville. 

Sources
https://books.google.ie/books?id=S2emAAAAIAAJ&pg=PA53&lpg=PA53&dq=Laurent+Eketebi&source=bl&ots=_NenpafLM-&sig=zEfHAKW1BlKFhT3J5FSMk5MlYnM&hl=en&sa=X&ved=0ahUKEwi-uOG7u6TRAhVWOMAKHQ2oD7wQ6AEIHjAC#v=onepage&q=Equa&f=false
https://books.google.ie/books?id=F0LWCgAAQBAJ&pg=PA544&lpg=PA544&dq=Maniema+autonomous+congo&source=bl&ots=CvrPP8Wuvv&sig=-1MRUC1tYFufB4RL48baZbJssEs&hl=en&sa=X&ved=0ahUKEwj9z_3vuKTRAhUsK8AKHa6lDgIQ6AEIITAB#v=onepage&q=Maniema%20autonomous%20congo&f=false

Note
I apologise for having so few sources about these potential countries since aside from Katanga, Bas Congo and South Kasai there was very little reporting or documentation of what the situation in the other provinces like Equateur was.

**Comment by simsulla** [comment]
Remember the "Prime directive" of realism. So in trying to determine potential fragmentation states, start by looking on what military rebellions have there been in Kongo? What election results? What political movements where able to actually establish military control or have consistent electoral support - wanting session. What states really qualify?

**Comment by arandomperson5000** [comment]
The only states in the Congo that I could find that really qualify for the Prime directive of realism are Katanga, South Kasai and Kongo. For Katanga it qualifies because of its brief existence as a independent country from 1960 to 1962 and there were multiple attempts by armed rebel groups such as the FNLC to reinstate Katanga's independence through the Shaba Invasions in the 1970s and the creation of secessionist armed militias such as the now defunct Mai-Mai Kata Katanga that was created in 2011 only to surrender their arms in October of 2016. As for South Kasai it also successfully seceded and lasted as an independent state from 1960 to 1962 although the secessionist movement has really quieted down since then with no reported armed militias fighting to reestablish an independent South Kasai or establish an independent Kasai containing the whole region of Kasai. As for Kongo, it already has a clearly established national identity due to the Kingdom of Kongo that had existed from the late 14th century to 1914, its dissolution by Portugal in 1914 is almost 3 decades from the 1946 start making it quite likely that some people still remembered the Kingdom of Kongo, the national identity established by the Kongo Kingdom clearly still existed when Belgium was decolonising the Congo in the late 1950s when ABAKO a Bakongo nationalist Party which declared its intentions to establish a Kongo republic in 1959 just after the Leopoldville riots, this idea had support from heads of state from neighboring countries such as Fulbert Youlou the firs president of the republic of Congo. I could not find any sources reporting on any secessionist movements in the other provinces, however there are some political parties like the Forces for Renewal party favour federalism however this is not even barely enough evidence to put in new cores for the rest of the provinces of the DRC.

Sources
https://en.wikipedia.org/wiki/Shaba_I
https://en.wikipedia.org/wiki/Shaba_II
https://en.wikipedia.org/wiki/Front_for_Congolese_National_Liberation
https://en.wikipedia.org/wiki/Mai-Mai_Kata_Katanga
https://en.wikipedia.org/wiki/Katanga_insurgency
http://www.bbc.com/news/world-africa-23422038
http://news.xinhuanet.com/english/world/2011-12/22/c_131321802.htm
http://af.reuters.com/article/drcNews/idAFL8N1CI26X
https://en.wikipedia.org/wiki/Kingdom_of_Kongo
https://www.britannica.com/place/Kongo-historical-kingdom-Africa
http://www.sahistory.org.za/article/kingdom-kongo-1390-1914
https://en.wikipedia.org/wiki/Mouvement_National_Congolais
https://en.wikipedia.org/wiki/Forces_for_Renewal
https://en.wikipedia.org/wiki/List_of_political_parties_in_the_Democratic_Republic_of_the_Congo

**Comment by arandomperson5000** [comment]
![20170205223917_1](https://cloud.githubusercontent.com/assets/20518264/22630544/0fcd9254-ebf4-11e6-87a0-4f47067e965e.jpg)
