### ISSUE TITLE
Béchar,Tindouf and Gibraltar regions fix

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#815]
A minor fix that adds the new regions of Béchar and Tindouf and Gibraltar to this mod due to split states issues with the Greater Morocco decision and British Gibraltar.
[Béchar,Tindouf and Gibraltar regions fix.zip](https://github.com/simsulla/nwomod/files/571314/Bechar.Tindouf.and.Gibraltar.regions.fix.zip)

**Comment by simsulla** [comment]
Thanks for the fix. But issue #820 mitigates this problem.
