### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by akvofajro** [simsulla/nwomod#817]
Some questions...

1-It would be possible to change the purchase priority of the game to:
First: Internal Market
Second: Common Market
Third: World Market
Fourth: National Stock
Ps: That way it would be more realistic, the pops and factories would only resort to the stock if there were not in the world market

2-I still do not understand how "economic sanctions" works, after generating the casus beli I must declare war? After declaring war, should I attack the enemy?

3-In 1993 there was the Brazilian constitutional referendum to determine the form of government of the country, could it be included in the game?
https://en.wikipedia.org/wiki/Brazilian_constitutional_referendum,_1993

**Comment by simsulla** [comment]
1. Don't think this is moddable.
2. Need to investigate. 
3. Yes, that is a fun add-on.  

For 2. and 3. could you please create separate issues. It is easier for me to keep tracek, 2. may be a bug, and 3. is an enhancement.
