### ISSUE TITLE
Mass Migration for Country in State of War

### ISSUE THREAD

**Issue by xgjp** [simsulla/nwomod#818]
Hi, I noticce that POPs do not migrate away from their country if they are at war, when in reality people flee their country when at war.
![v2_3](https://cloud.githubusercontent.com/assets/9093950/20060407/fb1783ec-a535-11e6-949d-325ba83d34c3.jpg)
![v2_2](https://cloud.githubusercontent.com/assets/9093950/20060410/ff266890-a535-11e6-862b-069b36247662.jpg)
@simsulla

**Comment by simsulla** [comment]
Though I understand the requirements, There are to many side effects of increasing emigration significantly in war. Think about France being at war game start 1946 and then the pops would all the sudden emigrate. One would like to have "emigration to neighboring country". But that is not possible to mod in Vic2.  

One could consider the "location = { NOT = { controlled_by = owner } }" for migration, and then in the state_capital adding a similar emigration factor it it is not controlled by the owner.
