### ISSUE TITLE
Yugoslav Wars enhancement ideas

### ISSUE THREAD

**Issue by TheNerdGamer** [simsulla/nwomod#819]
Here are a few ideas that I reckon would make the Yugoslav (And especially,Bosnian) Wars a more interesting and realistic experience overall:

1..It would be a good idea to add a small province named Brčko to link up the two halves of Republika Srpska,seeing that such a corridor existed historically and played an important role during the Bosnian War,allowing supplies from Serbia Proper to reach the Krajina and Banja Luka areas.
https://en.wikipedia.org/wiki/Brčko_corridor

2..A partition of Bosnia between Serbia and Croatia should be a possible outcome of the war.Historically,talks held between Tudjman and Milosevic led to an unofficial  "agreement" by which Bosnia would be partitioned,allotting 65% to Serbia, 20% to Croatia  and 15% to the Muslim Bosniaks.
Meeting #1 (controversial):  https://en.wikipedia.org/wiki/Kara%C4%91or%C4%91evo_agreement
Meeting #2:  https://en.wikipedia.org/wiki/Graz_agreement

3..The various peace plans suggested by the west throughout the Bosnian war should all be potential resolutions for the conflict,with the AI of the warring parties being likely to accept certain plans based on the situation in the field (province occupation,bankruptcy,etc.).This would create a lot more variety when it comes to solving the conflict.https://en.wikipedia.org/wiki/Peace_plans_proposed_before_and_during_the_Bosnian_War

4..Historically,between 1992-3, relations began to sour between Croat and Bosniak forces for various reasons,finally culminating in full-scale fighting between the two forces mostly in the area surrounding Mostar.This fighting finally ended in 1994 with the west brokering an agreement by which the Croats and Bosniaks agreed to federate.This could all be simulated by having Herceg-Bosna starting as a Croatian puppet,becoming independent  around early 1993 and then being annexed by Bosnia in early-mid 1994. https://en.wikipedia.org/wiki/Croat%E2%80%93Bosniak_War

5..If possible,there should be a way to represent the decisive mass exodus of Serbs from Krajina following Operation Storm in 1995.Of a total of approximately 600,000 Serbs that lived in Croatia at the dawn of the 1990s, over 350,000 proceeded to leave Croatia as a result of the war.This could potentially be represented by Croatia receiving an 'Operation Storm' decision if the war continues into 1995 and Zagreb remains unoccupied.This decision would annex Krajina and relocate a large portion (65% or more?) of Croatia's Serb population to various areas across Republika Srpska and Serbia Proper. 
https://en.wikipedia.org/wiki/Operation_Storm

**Comment by simsulla** [comment]
Like the suggestions. marked as enhancement request.

**Comment by simsulla** [comment]
1. I see your point but I am afraid Brčko corridor does not warrant yet another province. 
This is the current layout with provinces
![image](https://cloud.githubusercontent.com/assets/10263809/24042893/4b3b7cea-0b14-11e7-87d0-ee1a935c203d.png) 
![image](https://cloud.githubusercontent.com/assets/10263809/24043033/dc689d92-0b14-11e7-8b7b-cc4fccde0d7f.png)
