### ISSUE TITLE
Real world Admin regions to define States

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#820]
**vinbzz**
I love play the NWO, but i see that in Brazil, the state São Paulo and the state São Paulo Campinas,are one only state, maybe you know about that,but i just wanna help 
**simsulla**
Yes, but in the current version of NWO, a "state" is based on major metropolitan areas and surrounding country side. So some major (real world)states like São Paolo, Texas, California have more than one NWO state. 
My plan though is to revert this as it has gotten a lot of criticism.

TODO:
- In migration have a list of provid that are major metropoles or potential major metropoles. 
- Redesign regions.txt
- Revert the split state settings in cb's to allow ethnic wars for sub-set of provinces. Maybe make it more versatile.

**Comment by erwinjoy** [comment]
Please create republic sunda in west java region..
This movement exist in netherland Aggression To create federal republic

**Comment by simsulla** [comment]
So, will close this with initial commit formulating states with real world regions. Will continue merger of one-provinces as we move along.

**Comment by simsulla** [comment]
The states have in part been updated to correlate with real world administrative divisions. The previous design decision to have states as "major urban areas" will be abandoned due to extensive criticism (that functionality - a province being a major urban center, will be implemented by terrain some time in the future). 
The addaptation of states to real world adminisratice regions is on going.
Example Brazil
![image](https://cloud.githubusercontent.com/assets/10263809/21632459/f6c2b53a-d246-11e6-97b6-220471b0675a.png)
The US
![image](https://cloud.githubusercontent.com/assets/10263809/21632473/0b02bd92-d247-11e6-8d56-d58a64d0f011.png)
