### ISSUE TITLE
Issues and ideologies

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#822]
I am also playing around with some thought on doing rework of the politics of NWO, making pops solidly oriented on issues, and only to a minor degree on ideologies them selves. 
The ruling party ideology then affects moving (conditions: [party_issue] = x, move_issue_percentage) issues in an ideological direction.

**Comment by erwinjoy** [comment]
You must create new ideology for indonesia..our ideology is PANCASILA or five pillars...

**Comment by simsulla** [comment]
Ideologies in general should be global. Pancasila is very Indonesian. Also>80% of the electorate supports "Pancasila" parties 2014 according to wikipedia. 

There is an ideology that might be suitable to enclose Pancasila - that is "Big Tent" that contains different aspects of many ideologies under one umbrella, that is unique per nation..

**Comment by simsulla** [comment]
This issue will be addressed together with #83

**Comment by simsulla** [comment]
merge issue into #882
