### ISSUE TITLE
A suggestion for immigration

### ISSUE THREAD

**Issue by JohnLockers** [simsulla/nwomod#824]
I have an idea of how the immigration system can work. Immigration will be to a select few cities, but emigration should be from all provinces within a country. This way, rural localities will decline in population to simulate global trends towards urbanization. Additionally, this strategy will protect minorities from being quickly destroyed, and instead they can be gradually assimilated over time depending on governmental policy. Currently minorities don't last very long and entire supposedly rural countrysides flood with immigrants.

**Comment by simsulla** [comment]
The "urbanization" model of immigration is already in the mod. As well as urbanization.
