### ISSUE TITLE
Fall of communism

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#825]
**Kinds**
I have bug of event "fall of communism" where of i have conquer middle of europe with USSR in 1952 , not banquerut or other bad thing, i don't understand why ...

**Comment by simsulla** [comment]
Soviet_Union1953_09_04.v2

**Comment by erwinjoy** [comment]
USA Win the cold war but in event text USA was lose...
Is this a bug?

**Comment by simsulla** [comment]
What event?

**Comment by simsulla** [comment]
Will close this issue and let it be part of Dissolution of the eastern bloc #643
