### ISSUE TITLE
Second Chechen War, Dagestan War and Caucasus Emirate

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#826]
Looking throughout the event file Russia I feel like the event for the Second Chechen War is unfinished as when the event is triggered it's options do nothing as for the War of Dagestan it could be represented as an Islamic theocratic Dagestan fighting fro independence against Russia which will be happen in September 1999 after the First Chechen War is triggered. This event will be one of the triggers for the Second Chechen War. This should be quite easy to mod in the game however as for the Caucasus Emirate though I'm not sure whether to represnet as an islamist rebels or and independence movements or as ISIL since this terrorist organisation wants to create an Islamic emirate across the Northern Caucasus however in recent years many of it's leaders have been killed by Russian forces which has caused them to join ISIL as a desperate attempt to save the last remnants of this terrorist group.
Sources

**Comment by erwinjoy** [comment]
They are nationalist movement not isis

**Comment by arandomperson5000** [comment]
While they were almost certainly a nationalist movement when the group was founded, in recent years however due to massive leadership losses with two leaders of the group being killed in 2015 alone the Caucasus Emirate has fragmented although the group hasn't entire dissolved some of its commanders have pledged alliegence to IS which does show that the Caucasus Emirate is very weak at the moment and it could possibly collapse in the near future. Also despite its name the Caucasus Emirate does not claim the entire Caucasus area as its own territory but instead claims Muslim populated sections of the Northern Caucasus currently owned by Russia. 
Here is a link to a map of their claims
https://upload.wikimedia.org/wikipedia/commons/0/00/Caucasus_Emirate.svg
Source
http://mackenzieinstitute.com/caucasus-emirate-3/
http://www.css.ethz.ch/en/services/digital-library/articles/article.html/1acf3832-b8b9-4570-82c9-fb368ce7162f
http://www.longwarjournal.org/archives/2015/08/new-leader-of-islamic-caucasus-emirate-killed-by-russian-forces.php
https://www.google.ie/amp/www.rferl.org/amp/27949343.html

**Comment by arandomperson5000** [comment]
[Chechnya, Dagestan and Northern Caucasus.zip](https://github.com/simsulla/nwomod/files/676184/Chechnya.Dagestan.and.Northern.Caucasus.zip)
Ok here is the zip for this issue, I have also included a slight edit on the Casamance file in the History/countries folder that reverts its primary culture back to jola before the retrofit for generator 1,1 commit was made. Also I'm a little baffled why you had edited Barotseland's government to be set as a presidential dictatorship, the reason why I had made Barotseland originally as a parliamentary democracy
is that the Litunga (Lozi Monarch) is still quite prestigoius and powerful within the traditional area of Barotseland in Zambia and so that is why I thought the Litunga would be likely to be Head of State over an independent Barotseland.

**Comment by simsulla** [comment]
On Barotseland- sorry my bad. The generator creates the history files, so I probably just copied Zambias settings and overwrote yours.
