### ISSUE TITLE
Problems with Testing Issue #804

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#827]
[flags.zip](https://github.com/simsulla/nwomod/files/590686/flags.zip)
[NwO.zip](https://github.com/simsulla/nwomod/files/590687/NwO.zip)

**Comment by simsulla** [comment]
You have added the flags, ok. But there has to be more changes (countries.txt...) to create new countries

**Comment by arandomperson5000** [comment]
I apologize for not giving a description of this issue I was a little bit tired and was late in the night when I had created the issue. Anyways the problem is that when I tired to test the files for issue #804 at first it crashed on maplogic bu I managed to fix this problem however the next time I tried to run it, the mod crashed at processing flags. I'm completely stumped on how to solve this problem I have tried checking if if they're the correct size (93x64) and if I had typed any wrong letters in the tga file. but it keeps crashing. I believe that some of the flags may be corrupted. I have posted my Nwo documents folder and flags folder so that anyone could try to figure out whats wrong with flags.  I had pasted the folder containing the folder for #804 into my NWO mod folder if anybody is wondering

Full zip for issue #804 
[Martinique and French Guiana cores.zip](https://github.com/simsulla/nwomod/files/592622/Martinique.and.French.Guiana.cores.zip)
.

**Comment by simsulla** [comment]
The flag file GUM.tga is missing.

ps. and in your full set you have edited a old version of cultures.txt (perhaps this applies to more files)

**Comment by arandomperson5000** [comment]
Ok thanks for letting me of the missing flag file and the oudated cultures.txt

**Comment by arandomperson5000** [comment]
So far I have been unable to fix the problem but I've provided an updated version of the zip with the GUM.tga and a newer version of the cultures.txt that will hopefully be more stable than the one I have currently right now.
[Martinique and French Guiana cores.zip](https://github.com/simsulla/nwomod/files/593337/Martinique.and.French.Guiana.cores.zip)
