### ISSUE TITLE
Rebellions are not happening

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#83]
Rebellions are not happening:

On the militancy and rebellion. There are rebellions in the mod (communist and Islamist). But they are rare. This to me is a bug. But I have been unable to figure out why this decent and militancy does not transform to military uprising.

**Comment by simsulla** [comment]
In the NWO mod rebellions do happen but rarely. Militancy and rebell support is off the chart, but still this does not transcend into brigades ready to join the rebellion.  

![image](https://cloud.githubusercontent.com/assets/10263809/13167378/d682ad72-d6d2-11e5-8c0f-b425926dd03f.png)


Obvious configs in defines.lua parameters, are set correct as far as I see.
Example: MIL_TO_JOIN_RISING = 8 

Do you have any ideas why this dies not happen?

**Comment by James9883** [comment]
I was playing as the Soviet Union and I noticed that East Germany had a rebellion and Bavaria got released. Do you want me to upload the save, so you can see what caused the rebellion(and then amplify the affect, so that other nations have rebellions)?

**Comment by simsulla** [comment]
Please do :)

**Comment by James9883** [comment]
Here is the save game: https://drive.google.com/file/d/0B6emFPP0GHFvbGMxWFF5RWJ6TVk/view?usp=sharing
I think something other than militancy could be causing the rebellions to not occur, because I noticed that some had 10 militancy, but no rebels would spawn.

**Comment by James9883** [comment]
I just got Jacobin rebels as the US, with only 1.15 militancy. I let them win to see what would happen, and they replaced a liberal government with a conservative government. Do you need the save file for this rebellion too?

**Comment by simsulla** [comment]
Rovolts do happen, but not frequent enough. So a revolt at 1.15 is possible. A screenshot like this is good enough
![image](https://cloud.githubusercontent.com/assets/10263809/13276374/e04b8d3e-dabe-11e5-9ee7-51d4fd3c2b6f.png)
The problem is the revolt frequency. In head (1.0.4) I think I have done some corrections that will address some of the issues. But still "massiv-colonial-uprisings" is still not happening, these are the ones I miss from a game play perspective, primarily

**Comment by James9883** [comment]
Here is a screenshot of it, I found that it was linked to high unemployment in my country.
[img]http://i.imgur.com/jnkBsJK.jpg[/img]

Off topic: I played for a few more years and formed the North American Union, are there any plans to make it form later in the game(2020 is too early, in my opinion, but nevertheless it still is very fun to form it and the EU)?

**Comment by simsulla** [comment]
I am struggling with the rebellions #84
Why does rebel power not grow? 
I have added indian nationalists to rebel_type.txt identical with the one used in PDM.
But still not rebellion.
This is a sample from NWO.
![image](https://cloud.githubusercontent.com/assets/10263809/21954112/c4366a08-da48-11e6-9d42-823e5e403a7e.png)

This is from PDM (or vanilla) indian rebellion
 
![image](https://cloud.githubusercontent.com/assets/10263809/21954118/ea9547dc-da48-11e6-8c9b-7b65a8bd5413.png)

Rebells get no power and of all the possible brigades, no one is willing to join the rebellion!

Late in the game however - we do see rebellions
![image](https://cloud.githubusercontent.com/assets/10263809/21954124/1e7d3f82-da49-11e6-8d0c-b45b44a52a15.png)

**Comment by simsulla** [comment]
YEEEEEAAAAA!
Finally progress on this issue.
In commit 83cd3cb786ee0fc241de30a93cf36658462126a5 Rescale money to 1/100. 1gold=100000oz (Nixon last dollar peg), we re-scaled money to 1/100 of previous value for goods. 

This, it seems impact the rebell power negatively. Did an experiment scaling down to 1/10 reduced reb power increase somewhat but not totally. 

This is the test case. Run the event
`country_event = { # Decolonialization
  id = 15420
  title = EVT_fullindependence_NAME
  desc = EVT_fullindependence_DESC
  picture = "colonialism_end"
  is_triggered_only = yes

  option = {
    name = EVT_fullindependence_A
	any_pop = { militancy = 10 }
  }
}`
Run the game for a couple of days. Then one sould observe significant rebel power
![image](https://cloud.githubusercontent.com/assets/10263809/21962293/ac3186b0-db22-11e6-86cd-e642d2f8790b.png)

**Comment by simsulla** [comment]
This is not straightforward to fix, as reverting the cost x 1/100 makes the mod CTD due to to large sums in the gui (_I think..._).

ps. also in the latest 1.12 it is observed that militancy evaporates in a couple of days. This does not happen in 0.4 (411e285d4df1b05d9bbf88ccd8018d1f43e3c0ae).

**Comment by simsulla** [comment]
Will mode this issue to the 1.13 release. The rebels are back 👍 
![image](https://cloud.githubusercontent.com/assets/10263809/24489413/98f0be7e-151d-11e7-8353-608eac393fd5.png)

**Comment by simsulla** [comment]
Dveduu said: ↑
Also I keep gettting spammed by OPEC events (every country that joins OPEC gives me the OPEC alert, it seems).

**Dveduu**
Now my game is freezing. I'd upload the game but it says it won't let me.

**simsulla**
On the freeze (ctd) I am I see similar issues. In my test game around 2008 (but if I see right the isues apear earlier in Czech Rep. that gets enormous amounts of money (1992-).
![image](https://cloud.githubusercontent.com/assets/10263809/24521037/ee35121e-158a-11e7-860a-e739edf5335e.png)

Dveduu, do you have a save file I could have a look on?

The reason originally to lower the price range to c0.1£ was to avoid these issues (and a side effect of that bug fix the rebellions stopped working). 
Now the prices are around 10.0£. I will make a test with them around 1.0£ and see if the ctd is avoided.

**Comment by simsulla** [comment]
c1£ does it. Will commit and close this issue.
