### ISSUE TITLE
Several proposals for the Morgenthau Plan and the status of the Rhineland in the Monnet Plan

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#831]
The provisions of the Morgenthau Plan
1. Demilitarization of Germany. 
It should be the aim of the Allied Forces to accomplish the complete demilitarization of Germany in the shortest possible period of time after surrender. This means completely disarming the German Army and people (including the removal or destruction of all war material), the total destruction of the whole German armament industry, and the removal or destruction of other key industries which are basic to military strength.
2. Partitioning of Germany. 
(a) Poland should get that part of East Prussia which doesn't go to the USSR and the southern portion of Silesia as indicated on the attached map, (Appendix A).
(b) France should get the Saar and the adjacent territories bounded by the Rhine and the Moselle rivers.
(c) As indicated in part 3 an International zone should be created containing the Ruhr and the surrounding industrial areas.
(d) The remaining portion of Germany should be divided into two autonomous, independent states, (1) a South German state comprising Bavaria, Württemberg, Baden and some smaller areas and (2) a North German state comprising a large part of the old state of Prussia, Saxony, Thuringia and several smaller states.
There shall be a custom union between the new South German state and Austria, which will be restored to her pre-1938 political borders.
3. The Ruhr Area. 
(The Ruhr, surrounding industrial areas, as shown on the attached map, including the Rhineland, the Kiel Canal, and all German territory north of the Kiel Canal.)
Here lies the heart of German industrial power, the cauldron of wars. This area should not only be stripped of all presently existing industries but so weakened and controlled that it can not in the foreseeable future become an industrial area. The following steps will accomplish this:
(a) Within a short period, if possible not longer than 6 months after the cessation of hostilities, all industrial plants and equipment not destroyed by military action shall either be completely dismantled and removed from the area or completely destroyed. All equipment shall be removed from the mines and the mines shall be thoroughly wrecked.
It is anticipated that the stripping of this area would be accomplished in three stages:
(i) The military forces immediately upon entry into the area shall destroy all plants and equipment which cannot be removed.
(ii) Removal of plants and equipment by members of the United Nations as restitution and reparation (Paragraph 4).
(iii) All plants and equipment not removed within a stated period of time, say 6 months, will be completely destroyed or reduced to scrap and allocated to the United Nations.
(b) All people within the area should be made to understand that this area will not again be allowed to become an industrial area. Accordingly, all people and their families within the area having special skills or technical training should be encouraged to migrate permanently from the area and should be as widely dispersed as possible.
(c) The area should be made an international zone to be governed by an international security organization to be established by the United Nations. In governing the area the international organization should be guided by policies designed to further the above stated objectives.
4. Restitution and Reparation. 
Reparations, in the form of recurrent payments and deliveries, should not be demanded. Restitution and reparation shall be effected by the transfer of existing German resources and territories, e.g.
(a) by restitution of property looted by the Germans in territories occupied by them;
(b) by transfer of German territory and German private rights in industrial property situated in such territory to invaded countries and the international organization under the program of partition;
(c) by the removal and distribution among devastated countries of industrial plants and equipment situated within the International Zone and the North and South German states delimited in the section on partition;
(d) by forced German labor outside Germany; and
(e) by confiscation of all German assets of any character whatsoever outside of Germany.
Should the Morgenthay Plan currently in the mod be edited to fit the provisions or is it just fine as it is.
As for the Rhineland I do know that France wanted to detach it from Germany after WW2 and wanted it to either become a part of France or be under a international zone governed by the United Nations quite similar the International authority for the Ruhr. Also the Rhenish republic was a short lived puppet state of France which existed from 1921 to 1924 that had control over the Rhineland as a part of along term process to completely destroy Germany as a Great Power by France however due to economic sanctions by the US and the UK against France in response to this process the French economy collapsed and swiftly abandoned the project.
Sources
https://fdrlibrary.org/documents/356632/390886/findingaid_morgenthaupapers.pdf/6c4a2806-e5fe-487d-b884-3bb3785da285
http://query.nytimes.com/gst/abstract.html?res=940CEFDE1439E033A2575AC2A9679D946295D6CF&legacy=true
https://en.wikipedia.org/wiki/Rhenish_Republic

**Comment by simsulla** [comment]
The mod starts 1946.1.1 - after the [Potsdam Conference](https://en.wikipedia.org/wiki/Potsdam_Conference) Aug 1945. The Morgenthau plan was on the table before the conference. Anthony Eden and others opposed it believing it would in effect kill 40% (26 mil!) of the German population by leaving them without means to support them selves. It was however endorsed by Roosevelt, Churchill and others.  The fact that it was on the table tells a lot. 
The fact that it is after the Potsdam Conference takes it off the table for nwo.
