### ISSUE TITLE
Martinique and Guiana and Mexican Drug War zip files.

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#832]
[Martinique and French Guiana cores.zip](https://github.com/simsulla/nwomod/files/601825/Martinique.and.French.Guiana.cores.zip)
[Mexican Drug War and Chiapas Conflict.zip](https://github.com/simsulla/nwomod/files/601827/Mexican.Drug.War.and.Chiapas.Conflict.zip)

I finally managed to solve the flag with the Martinique and Guiana issue zip. It turns out that the flags for Montserrat had the wrong tag in their tags as it was meant to be MTS however instead I typed out MST.
As for the Mexican Drug War I removed the immigration and emigration push from the event modifier for the Mexican Drug War as when I had tested it out, over 24000 people emigrated out of Mexico in just one month! I had also decreased the militancy as it was escalating so quickly, far too quickly to stimulate the Mexican Drug War in this mod as it reached 6.0 in just 3 months, if that ever happened in real life Mexico could have a potentially large civil war on its hands. The two events for the Zapatista rebellion I've created are quite broken right now, the second option in both of these events are missing when I had tested out the events ingame. I then ran the validator on the file containing these two events all what it said is that there was an illegal closing bracket on the brackets of the second options. I'm absolutely stumped on how to solve this problem, I have tried to fiddle around the brackets to see if I could get it to work but to no avail. Would you be kind enough to look into this problem and try to solve since I guess you have a better understanding of making event than me.
Okay here is what the Validator said the error was.

**Parse Failure**
Path: event/mexico.txt
Approximate location: Line 93, column 1
Error: Illegal Closing Bracket

**Parse Failure**
Path: event/mexico.txt
Approximate location: Line 117, column 3
Error: Illegal Closing Bracket

And here is the text for the two events about the Zapatista rebellion

country_event = {
  id = 8009511
  title = EVT_8009511_NAME
  desc = EVT_8009511_DESC
  picture = "chiapas_conflict"
  fire_only_once = yes

  trigger = {
    tag = MEX
    year = 1994 NOT = { year = 1995 }
  }

  mean_time_to_happen = { months = 33 }

  option = {
    name = EVT_8009511_A
	any_pop = { limit = { culture = native_american_minor } } militancy = 8.0 consciousness = 5.0 }
  }

  option = {
    name = EVT_8009511_B
	1681 = { secede_province = CIP } 
	1682 = { secede_province = CIP } 
        create_vassal = CIP
  }
}

country_event = {
  id = 8009512
  title = EVT_8009512_NAME
  desc = EVT_8009512_DESC
  picture = "chiapas_conflict"
  fire_only_once = yes

  trigger = {
    tag = MEX
    year = 1996 NOT = { year = 1997 }
  }

  mean_time_to_happen = { months = 2 }

  option = {
    name = EVT_8009512_A
	any_pop = { limit = { culture = native_american_minor } } militancy = -4.0 consciousness = -2.0 }
  }

  option = {
    name = EVT_8009512_B
	any_pop = { limit = { culture = native_american_minor } } militancy = 5.0 consciousness = 3.0 }
  }
}

**Comment by simsulla** [comment]
will close this as the files are attached to the relevant issues #811 and #804
