### ISSUE TITLE
Turkish Irrendentism

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#834]
Having read a couple of articles on the history of Turkey I have discovered that at the time of its creation the Republic of Turkey had originally claimed territories in parts of Syria and Iraq that were outlined in the Misak-ı Millî (National Pact) in 1920 however these goals were later abandoned as by 1923 the Turkish nationalists were beginning to get overextended and the British and French force in both Syria and Iraq seemed to strong to fight against in the Turkish War of Independence. Turkey later signed the Treaty of Lausanne with France and Great Britain that recognised the sovereignty of the Turkish republic however it was forced to give up the claims to parts of Syria and Iraq except the Mosul Viyalet when Turkey continued to claim it as part of its de jure territory until 1926 when it reluctantly gave up the claims to the Mosul Viyalet in an agreement with Iraq under the supervision of the League of Nations. In recent years however with the rise of Recep Tayyip Erdoğan and his party the Justice and Development Party, Turkey has once more looked interested in claiming those regions once more or to gain influence over these areas as for example there are tensions between Turkey and Iraq on who shall control the city and what actions will be done to its inhabitants and the Rojava has recently stalled their offensive on Raqqah in protest of the continuing Turkish offensive on Raqqah.

Map of a de jrue Turkish nation as outlined in the National Pact (made by Foreign Policy magazine)
![image](https://cloud.githubusercontent.com/assets/20518264/20652279/4c803eaa-b4ee-11e6-94d2-d245376d6aea.png)

Sources
http://www.independent.co.uk/news/world/middle-east/iraq-ready-for-war-with-turkey-over-who-should-control-mosul-a7394071.html
http://www.aljazeera.com/news/2016/11/iraq-turkey-tension-rises-battle-mosul-161102062236590.html
http://foreignpolicy.com/2016/10/23/turkeys-religious-nationalists-want-ottoman-borders-iraq-erdogan/
https://www.britannica.com/topic/National-Pact-Turkey-1920
http://www.dailysabah.com/politics/2016/11/23/ypg-turns-its-back-on-us-threatens-to-shut-down-raqqa-operation-1479922147
http://foreignpolicy.com/2016/11/27/raqqa-will-put-trumps-deal-making-to-the-test/

**Comment by simsulla** [comment]
Nice suggestion, the Turkish involvement in Iraq and Syria shows a commitment to Turkmens in the area.
https://en.wikipedia.org/wiki/Battle_of_Mosul_(2016)#Turkish_desire_of_involvement
https://en.wikipedia.org/wiki/Syrian_Turkmen#Turkish_military_intervention_in_Syria

**Comment by arandomperson5000** [comment]
Added a commit for this issue, however I'm keeping the Turkish irrendentism issue open is because when I had tested it, in the 1946 startdate somehow Turkey hadn't any political party leading the country and din't have any armies at all, despite all the commands in the file for both political parties and armies for Turkey.
![20170202211938_1](https://cloud.githubusercontent.com/assets/20518264/22568958/a4b25f58-e98d-11e6-94bc-f24241288037.jpg)
