### ISSUE TITLE
Santa Cruz Bolivia separatism

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#838]
I apologize for posting so many issues that could add to your agony while working on this mod so I rather intend the issues that I have posted to be sort of my own personal checklist for this mod. Anyways on to the issue I was rather curious why Santa Cruz is a region in this mod as I found out that in recent years particularly in 2008 when Evo Morales was elected president of Bolivia support from the mainly well off European descendents living in the highlands of Santa Cruz for more autonomy or even independence from Bolivia due to what they perceived as an economic burden posed by the indigenous lowlanders to their region. Organisations like Media Luna were founded to campaign for autonomy in Santa Cruz, it appears that 2008 was the year when the movement was at the strongest point however it has seemed it has declined since then.
Sources

**Comment by simsulla** [comment]
Yes, Santa Cruz as a state/region is formulated with that game scenario in mind. https://en.wikipedia.org/wiki/Santa_Cruz_autonomy_referendum,_2008 sets some background on this development. The text you reference supports the Bolivian government in this conflict by being loaded _mainly well off European descendents_ and biased _they perceived as an economic burden posed by the indigenous lowlanders_ to there benefit. And would fit if you play as Bolivia, but as Santa Cruz a different portrayal of the situation would be more accurate :).

**Comment by arandomperson5000** [comment]
It is interesting to see that the four Bolivian departments of Santa Cruz, Beni,Pando an known as the Media Luna are now autonomous because of the 2008 referendums. On an interesting note Bolivia's neighbor to the southwest Chile has a politically embarrassing issue on the moment over treatment of the Mapuche people. Ever since the conquest of Araucanía by Chile from 1881 to 1884 the Mapuche population of that area has been dispossed of their lands that they had previously owned for centuries and was given to settlers primarily from the Northern parts of Chile and Europe, however since the return of democracy to Chile in the 1990s the Mapche, now largely confident in their goals have done a series of large scale protests, arson attacks and violent land occupations of land belonging to settlers and their descendents by claiming the land was originally owned by them and they're just taking it back. The response by the Chilean government has been largely described as completely inadequate to solving the problem, they have either completely ignored the problem in certain areas or very harsh when they arrest Mapuche suspects in isolation without charges according to an anti terrorism bill that was introduced when Pinochet still ruled Chile which has been criticised by the international community as overly harsh and questions the level of democracy that truly exists in the country. This has led to demands by organisations such as Coordinadora Arauco-Malleco for autonomy for the Mapuche peoples by the Chilean government. Also in Venezuela there is growing separatist movement in Zulia State which has always maintained a unique regional identity largely separated from the main Venezuelan identity as a largely conservative and very religious Catholic population. During his presidency Hugo Chavez has more than once accused several governors of Zulia States to try to secede from Venezuela although these claims are rather untrue as many of the accused governors were right wing and have denounced Chavez's government.
Sources
http://www.e-ir.info/2013/05/20/on-separatism-in-latin-america/
http://www.latinnews.com/component/k2/item/31098-venezuela--ch%C3%A1vez-blames-us-for-zulia's-separatism.html
https://news.vice.com/article/violent-conflict-landowners-chile-mapuche-indigenous
https://panampost.com/valerie-marsman/2015/01/30/7-key-facts-to-understanding-chiles-mapuche-conflict/
https://en.wikipedia.org/wiki/Coordinadora_Arauco-Malleco
http://www.coha.org/the-mapuche-struggle-for-autonomy/
https://nacla.org/news/chiles-mapuches-call-regional-autonomy
http://unpo.org/demo/article/18550
