### ISSUE TITLE
How to install on macOS?

### ISSUE THREAD

**Issue by aryamanarora** [simsulla/nwomod#841]
@simsulla Do I just drop the `NWO` folder and `NWO.mod` into the mod folder? The start dates aren't appearing for me...

I'm using vanilla Vic2 from the App Store, if that helps.

**Comment by erwinjoy** [comment]
Nwo need Hearth of darkness expansions

**Comment by aryamanarora** [comment]
@erwinjoy Aww man, okay thanks.
