### ISSUE TITLE
Quebec Independence referendums

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#849]
[NWO.zip](https://github.com/simsulla/nwomod/files/640664/NWO.zip)
Noticed there wasn't any event for the Quebec independence referendum in 1995 which had a very narrow margin between the yes and no vote so I made a event for it and fixed up several dates for the events regarding the Quebec independence movement. The number of provinces that Quebec controls if the yes vote wins the 1995 Quebec referendum could be adjusted to a smaller number according to local preferences but I'm still not sure whether to do it or not.

A potential map of Canada and a seceded Quebec partitioned according to local preferences, with Montreal, Northern Quebec, the Eastern Townships, and the Pontiac region remaining with Canada
(Wikimedia)
![image](https://cloud.githubusercontent.com/assets/20518264/21029447/a68d2a6a-bd91-11e6-8595-c161a5ae18db.png)
As for the other separatist movements in Canada I don't think they have enough support from the local population of the areas they're trying to secede to be put cores for them into this mod whether it be movements wanting their provinces to be independent, autonomous or annexed into other countries like the US. On an interesting note movements demanding autonomy for the people of the First Nations(Or Native Americans in the U.S) have grown rapidly in recent years in both numbers and power such as for example in 1999 Nunavut was created as a territory for the Inuit of the Northwest Territories although this decision has been criticised as a complete waste of money by some Canadians, one even described as a Bantustan. This had led to movements being created in many states of Canada demanding more autonomy for their respective First Nation. Another interesting note is that during the late 19th and early 20th centuries there were several proposals to unite some Caribbean Island colonies of Great Britain like the Bahamas and the Turks and Caicos Islands with Canada due to their friendly historical ties with Canada however it appears those ideas have long since died down with only a couple of discussions happening within a few social circles today.

https://en.wikipedia.org/wiki/Quebec_referendum,_1995
https://en.wikipedia.org/wiki/Quebec_sovereignty_movement
https://en.wikipedia.org/wiki/Nunavut
https://en.wikipedia.org/wiki/List_of_proposed_provinces_and_territories_of_Canada

**Comment by simsulla** [comment]
Great work. Added to the mod.

ps. the "Caribbean" is in the mod as is. Canada can integrate them by sphering them in the 50s.
