### ISSUE TITLE
Several Proposals for South Africa, Zimbabwe and Zambia

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#856]
Having done some research on the three respective countries of South Africa, Zimbabwe and Zambia I have found out noticeable events and potential alternate histories that could make these countries more interesting to play as.

South Africa
1. Unlike many other bantustans, Kwa Zulu Natal has a strong sense of nationalism among its Zulu population particularly around the area of Ulundi. One the biggest political parties currently and historically in Kwa Zulu Natal, the Inthaka Freedom Party has had a long history of conflict with its main rival the African National Congress over its Zulu politcal interests to the more pan African ideology of the ANC. As Apartheid was nearing its end in the late 1980s to 1994  conflict broke out in Kwa Zulu Natal with armed members and supporters of the Inthaka Freedom Party fighting their ANC counterparts causing a sort of a mini civil war that had soon cost over 10,000 lives by 1994. This conflict could do with its own event as there were fears of Zulu separatism in Kwa Zulu Natal and that the conflcit over there could get even larger making the political situation in South Africa at the 1992 much more interesting and tenuous.

2. Also at the end of Apartheid in the 1994 elections, some Afrikaners felt threatened with the inevitable possibility of majority Black rule in South Africa, this prompted far right wing Afrikaner groups like the Boerestaat Party to advocate for the establishment of a Volkstaat a sort of an Afrikaner state independent of South Africa. As expected the idea didn't gain that much support from the Afrikaner population with the vast majority of them rejecting the idea and instead being happy to live with majority black rule. However this hasn't stopped the establishments of settlements like Orania which are in essence mini Volkstaats considering the founders of these settlements want to create a mini homeland for the Afrikaner community and the overwhelming Afrikaner population in these settlements. It would not be entirely unrealistic to implement this in as either a event, decision or new country altogether.

3. Would it be realistic to have an event chain for an alternate more violent end to Apartheid in South Africa through a revolution or civil war. I know there was decades long insurgency in South Africa with the paramilitaries of groups like the ANC fighting the South African government that had killed more than 20,000 people however I am not quite sure whether an violent collapse of Apartheid is realistic or not.

Zimbabwe

1. I'm not quite sure on what to do with the Rhodesia cores at the 1992 start whether to remove them or not. I do know that by 1992 most of British descended whites had emigrated away to other countries like South Africa judging by how 60% of the Zimbabwean white population had emigrated to countries like South Africa. Also with the lack of political organisations advocating for an independent Rhodesia I would be in favour of removing Rhodesian cores form the 1992 startdate.

2. I had previously discussed the issue of Matabeleland on the Paradox forums however I have found some new information that could add more depth to this issue. It appears the Ndebele separatist movement is actually mostly popular with the quite large Ndebele diaspora than the Ndebele in Matabeleland for example a very prominent pressure group advocating for Ndebele independence the Mthwakazi Liberation Front was actually founded in London and almost always holds its conferences outside of Zimbabwe. Another thing to mention is that while Ndebele nationalism is currently quiet in Matabeleland right now it could lightup in the future if Mugabe continues his economic and political policies that have left Matabeleland economically marginalised and even worse destroyed the economy of Zimbabwe, if this were to happen Zimbabwe could face a crisis on its hands that would threaten its territorial and political stability.

Zambia.

1. Unlike the Ndebele separatist movement, the separatist movements in Zambia advocating for an independent Barotseland are much more vocal and powerful. Barotseland was once a pre colonial kingdom that had existed in the Southwestern portion of Zambia that became a protectorate of the British Empire in 1890, Later in November 1899 it was amalgamated with Northeastern Rhodesia becoming the Barotziland-North-Western Rhodesia protectorate this was initially welcomed by the king of Barotseland at that time, however in 1911 it was amalgamated with Northeastern Rhodesia to form Northern Rhodesia this was less welcomed by the Lozi people than the previous amalgamation in 1899. The issue of Lozi independence didn't really heat up until when Zambia was preparing to get independence form the UK by 1964, in 1961 Lozi nationalists send a petition to London demanding the independence of Barotseland however this fell on deaf ears, it wasn't until 1964 when the Barotseland agreement was signed which gave Barotseland autonomy within Zambia and renounced the Lozi monarch's special relationship to the British Crown thus paving the way for Zambia's independence later that year. However this agreement was later dissolved at a national referendum in Zambia which saw the majority of voters against the agreement while it 60% support in Barotseland. Lozi nationalism soon quieted down until the 1980s when Zambia moved towards multiparty democracy and the establishment of the Lozi dominated East Caprivi bantustan in Namibia, especially sine 1991 with the downfall of one party rule in the country Lozi nationalism has spiked up significantly with multiple militant groups advocating for the independence of Barotseland being formed for example there have been multiple shootouts involving Lozi nationalist groups and government forces and the main leaders of the Barotseland separatist movement have been jailed since last year by the government.

Sources
http://www.sahistory.org.za/dated-event/least-150-people-die-clashes-between-anc-and-ifp
http://www.sahistory.org.za/archive/chapter-1-introduction-0
https://en.wikipedia.org/wiki/Inkatha_Freedom_Party
https://www.britannica.com/topic/Inkatha-Freedom-Party
http://allafrica.com/stories/201602100932.html
https://www.vice.com/en_uk/article/orania-afrikaners-south-africa-white-tribe
https://en.wikipedia.org/wiki/Orania,_Northern_Cape
https://en.wikipedia.org/wiki/Freedom_Front_Plus
https://en.wikipedia.org/wiki/Afrikaner_Volksfront
https://en.wikipedia.org/wiki/Volkstaat
https://en.wikipedia.org/wiki/Herstigte_Nasionale_Party
https://books.google.ie/books?id=u9Lq_8Ozf5cC&pg=PA1119&lpg=PA1119&dq=Lozi+nationalism&source=bl&ots=z_IJqN8nN9&sig=9aLwQ1PFS7Lj8fw2r9AlKEPYjp8&hl=en&sa=X&ved=0ahUKEwiWo-KPt4PRAhWqJMAKHStwBGYQ6AEIODAE#v=onepage&q=Lozi%20nationalism&f=false
http://www.geocurrents.info/geopolitics/lozi-barotse-nationalism-in-western-zambia
http://unpo.org/article/19657
http://unpo.org/members/16714
http://www.bbc.com/news/world-africa-17546620
https://books.google.ie/books?
https://www.researchgate.net/publication/254362099_Ethnic_Separatism_or_Cultural_Preservation_Ndebele_Radio_under_Apartheid_1983-1994
https://books.google.ie/books?id=iTzZkKvshGsC&pg=PA236&lpg=PA236&dq=ndebele+diaspora&source=bl&ots=c0rztc1h1v&sig=a_vvmLvnyemXo0O01wJbRX5Qb_I&hl=en&sa=X&ved=0ahUKEwivnuT3u4PRAhXhJcAKHQvEDGQQ6AEIGjAA#v=onepage&q=ndebele%20diaspora&f=false
http://www.newzimbabwe.com/news-16858-Were+ready+to+fight,+Mthwakazi+leader/news.aspx
id=u9Lq_8Ozf5cC&pg=PA1119&lpg=PA1119&dq=Lozi+nationalism&source=bl&ots=z_IJqN8nN9&sig=9aLwQ1PFS7Lj8fw2r9AlKEPYjp8&hl=en&sa=X&ved=0ahUKEwiWo-KPt4PRAhWqJMAKHStwBGYQ6AEIODAE#v=onepage&q=Ndebele&f=false

**Comment by simsulla** [comment]
SA
1. added event for the Apartheid regim the option to give KwaZulu autonomy within South Africa. 
2. the Volkstaat was not a realistic proposal. 
3. A violent (or more violent - similar to Rhodesia) end to apartheid was possible to my understanding. But this is in the mod to some extent as militancy and that it does not play out more is due to issue #83. For now no plans for specific events at the moment. Feel free to create a separate issue and work on it.

 Zimbabwe
1. Will remove the RHO cores on Zimbabwe independence.
2. I responded to this in the forum earlier: _Initial in the struggle against UDI Rhodesia the dominating force was the matabele dominated ZAPU under Nkomo. However in the end he was out maneuvered by the charismatic and skillful Mougabe with his shona dominated ZANU (an interview with Nkomo in exile telling his story). So yes, Matabeland is a separate state as a rudiment for an independent Matabeleland. There are several such cases in Africa. No plans at the moment though to make these additional cores. EDIT; at this time (but maybe later). _.  

Zambia
1. Did some research on this earlier. I find no electoral support for this movement.  But as for Matabeleland it may be justified to have them in the mod.
 
If you want to add them I suggest creating two separate issues Barotseland  and Matabeleland for the two new nations, send me the files and I will add them to the mod.
