### ISSUE TITLE
Matabeleland

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#857]
This issue was previously discussed in other issues and at the paradox forums however I do think it should be added in as it is a potential geopolitical flash point that could happen in the future, the state of Matabeleland already exists in the mod and has considerable support from the Ndebele diaspora, All of these reasons I think would justify adding in Matabeleland cores into this mod.

**Comment by simsulla** [comment]
See #856

**Comment by arandomperson5000** [comment]
[Matabeleland issue.zip](https://github.com/simsulla/nwomod/files/667529/Matabeleland.issue.zip)
