### ISSUE TITLE
East Indies Federation event chain

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#859]
having looked at the events currently in the mod for the East Indies Federation I think it is seriously in need of new events that would stimulate its real life fate of either breaking up into over 15 different countries over tensions between the economic and political dominance of each island like Jamaica and Trinidad and Tobago or avoid this fate and has the potential to be a major regional power in the Americas.

**Comment by simsulla** [comment]
West Indies right?
Event 1002701 dissolves it. Don't understand?

**Comment by arandomperson5000** [comment]
Oops I got confused with East Indies and West Indies, so that meant I couldn't find the event regarding the dissolution of the West Indies Federation in the localisation files.
