### ISSUE TITLE
Weakness of Kuomintang for PRC

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#86]
By Galbatorix994 
I was playing as the PRC (1946 startdate) and I got an event that should probably be for the ROC,this event being called 'Weakness of Kuomintang' giving me me various negative effects.Also,after I completely annexed the ROC,there were over 500,000 nationalist troops left around China.

**Comment by iiffyy** [comment]
yes this happened to me as well in 1953 like 5 years after i defeated PRC i started getting PRC events like my capital moved to beijing and such

**Comment by iiffyy** [comment]
and now I just got a event for the korean war thats lets me back North korea but not the south and I and ROC
