### ISSUE TITLE
Graphic of last version

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#862]
Hello. I have a problem -  My the New World Order mod in 1080p is stretched and squashed.

Can you return graphic of old versions? Please. I can't play with this Graphic, when the game is streched.

**Comment by simsulla** [comment]
1080p? NVIDIA GeForce GTX 1080 or? 
You need to experiment with the settings.txt to fix this.

**Comment by samwoodzadrot** [comment]
So. I use GTX 745 (4GB). playing in 1080p. And I tried to do something with settings.txt, 
I used settings.txt from another mod as example, but nothing has changed.

**Comment by simsulla** [comment]
I suggest that you post this problem in the paradox forum or reddit. I don't have a  GTX 1080 so it is impossible for me to troubleshoot. Maybe some other player has a solution.

**Comment by samwoodzadrot** [comment]
I'm using a GTX 745 NOT GTX 1080.

**Comment by simsulla** [comment]
I don't have that card either :)

**Comment by samwoodzadrot** [comment]
Ah... Ok. I will reinstall windows and try again).
