### ISSUE TITLE
Israeli Palestinian conflicts from the 1992 start

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#864]
Having looked looked the events for Israel I noticed there was a lack of events 
events for Israel after the first Intifada event, considering the large number of conflicts they have involved in especially after 2000 such as the Second Intifada, the 2006 Lebanon War and the multiple conflicts with the Hamas governed Gazan Strip. I think these potential events could make playing Israel more exciting at the 1992 startdate.

https://en.wikipedia.org/wiki/Second_Intifada
https://en.wikipedia.org/wiki/2006_Lebanon_War
https://en.wikipedia.org/wiki/Gaza_War_(2008%E2%80%9309)
https://en.wikipedia.org/wiki/Operation_Pillar_of_Defense
https://en.wikipedia.org/wiki/Operation_Protective_Edge
https://en.wikipedia.org/wiki/Gaza%E2%80%93Israel_conflict

**Comment by arandomperson5000** [comment]
I have made a commit that adds a Jewish settler pop for the Gaza Strip that will tie into an event that will represent the Israeli withdrawal from the Gaza Strip. This issue will probably be done by either today or tomorrow.

**Comment by simsulla** [comment]
After these changes (and earler trigger corrections), the validator give these errors
![image](https://cloud.githubusercontent.com/assets/10263809/26022624/35797c46-37aa-11e7-9818-7c552b3347b1.png)
