### ISSUE TITLE
Great Powers list

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#867]
Hello. I propose to change the list of great powers in the game.
I believe that it is necessary to refer to the views of the analyst. For example - Stratfor.

Stratfor - Analytical Center. Predict: War in the Middle-East, the war in Ukraine and the strengthening of Russia around 2020.
Now they expect that Russia and China will break and this time Turkey, Poland and Japan will become a superpower.

So what I suggest - instead of India in the list of the Great Powers will be Turkey.
In the Turkish sphere of influence should be Azerbaijan and Northern Cyprus.

There is a problem with Ukraine. Due to the very large army at the beginning of the game, Ukraine eventually turns into a great power.

**Comment by simsulla** [comment]
GDP(PPP) decides the ranking of nations. With a reduction for initial puppets (Japan and the Raj in the 1946 start date).

![image](https://cloud.githubusercontent.com/assets/10263809/21570785/928205c4-cec9-11e6-98ed-d7695c963f5b.png)

 For the Stratfor - Analytical Center one have to look on the reliability of there previous predictions 1995-2005 and 2005-2015, before considering them a usable source to predict the future.
