### ISSUE TITLE
Venezuelan politics and flavour

### ISSUE THREAD

**Issue by Blaskowicz** [simsulla/nwomod#869]
Hello @simsulla !

As an avid fan of your mod, I can't but help that my local area (Venezuela) has some rather... awkward politics. The 1946 start has 2000s parties in power, and Venezuela was ruled by a presidential dictatorship (1945-1948), military dictatorship (1948-1958) and a bipartisan democracy (1958-1998) before Chavez came into power and became the figurehead of the Latin American Pink Tide (1998-2013) and subsequent shenanigans (2013-20??).

I've compiled a list of some parties and the closest in-game political leanings they hold, as well as some Wikipedia links about Venezuelan history, for flavour.

https://en.wikipedia.org/wiki/History_of_Venezuela_(1908%E2%80%9358)
- https://en.wikipedia.org/wiki/El_Trienio_Adeco
- https://en.wikipedia.org/wiki/Venezuelan_general_election,_1947

https://en.wikipedia.org/wiki/History_of_Venezuela_(1948%E2%80%9358)
- https://en.wikipedia.org/wiki/Marcos_P%C3%A9rez_Jim%C3%A9nez
- https://en.wikipedia.org/wiki/1958_Venezuelan_coup_d%27%C3%A9tat

https://en.wikipedia.org/wiki/History_of_Venezuela_(1958%E2%80%9399)
- https://en.wikipedia.org/wiki/Punto_Fijo_Pact

https://en.wikipedia.org/wiki/History_of_Venezuela_(1999%E2%80%93present)
- https://en.wikipedia.org/wiki/Hugo_Ch%C3%A1vez
- https://en.wikipedia.org/wiki/Bolivarian_Revolution
- https://en.wikipedia.org/wiki/Pink_tide

Political parties existing at the start of the game (1946):
- Liberal - Accion Democratica - https://en.wikipedia.org/wiki/Democratic_Action_(Venezuela)
(Free Trade, Interventionism, Secularism, Affirmative Action, Pacifism)

- Conservative - COPEI - https://en.wikipedia.org/wiki/Copei
(Free Trade, Interventionism, Moralism, Citizenship, Pacifism)

- Progressive - https://en.wikipedia.org/wiki/Democratic_Republican_Union
(Free Trade, Laissez-Faire, Secularism, Affirmative Action, Pacifism)

- Marxist-Leninist - https://en.wikipedia.org/wiki/Communist_Party_of_Venezuela
(Protectionism, Planned Economy, Atheism, Affirmative Action, Pro-Military)

Major parties that also exist at the 1992 start:

- Nationalist - Nationalist Civic Crusade - https://en.wikipedia.org/wiki/Nationalist_Civic_Crusade
(Protectionism, Interventionism, Moralism, Residency, Jingoism)

- Socialist - Movement for Socialism - https://en.wikipedia.org/wiki/Movement_for_Socialism_(Venezuela)
(Protectionism, State Capitalism, Atheism, Affirmative Action, Pacifism)

Major parties that emerge after 1992:
- Populist - Popular Will - https://en.wikipedia.org/wiki/Popular_Will
(Free Trade, Interventionism, Secularism, Citizenship, Pro-Military)

- Socialist - United Socialist Party of Venezuela - https://en.wikipedia.org/wiki/United_Socialist_Party_of_Venezuela
(Protectionism, State Capitalism, Secularism, Affirmative Action. Pro-Military)

---
Thanks, and if there is any way I can help or collaborate to add some flavour and detail on Venezuela (and SA in general), I'd be more than willing.

**Comment by simsulla** [comment]
Thanks.
If you have experience modding please clone the git repo make your changes and then make a pull request I your improvements will get into the mod. 

I will add the suggested parties to the mod. 

On the potential events, and you do not have experience modding you can still help me out greatly by writing event texts. For example:

Name: Punto Fijo Pact
Desc: The Punto Fijo Pact was a formal arrangement arrived ...
A: Enter into the pact.
B: Not necessary
And some not on what should happen upon making the choices, like increased militancy, prestige....

**Comment by Blaskowicz** [comment]
Sure! I know just a bit of coding, but I'll try to make it as descriptive as possible.

I would modify event 8017807 so that AI chances are 95 for option A and 5 for option B.

 - Name: **Punto Fijo Pact**
_year = 1958 NOT = { year = 1990 }
Government = Democracy
Mean time to happen = 1 month
Fire only once = yes_
Desc: After a decade of military rule by Marcos Perez Jimenez, the three leading parties of Democratic Action, COPEI, and the Republican Democratic Union established the Punto Fijo Pact, which, on paper, ensured that no party would possess absolute power in the State, and to uphold democratic values. This led to the suppression of both right-wing and left-wing parties, and the formation of underground Marxist guerrillas.
**A: Sign the pact!**
_AI chance: 95
Political parties set to "Promote Democratic".
Voting set to "Universal".
All pops in Venezuela who are not Conservative, Liberal, Progressive, gain 2 consciousness.
All pops in Venezuela who are Conservative, Liberal, Progressive, lose 2 consciousness and 2 militancy.
All pops in Venezuela who are Communist, Traditionalist, or Nationalist gain 4 militancy.
Set country flag "punto_fijo"._
**B: Let Democracy take its course.**
_AI chance: 5
All Pops in Venezuela gain 1 plurality and 1 consciousness_

 - Name: **Communist Insurgency**
![image](https://cloud.githubusercontent.com/assets/24849306/21579079/2877af4c-cf6b-11e6-923f-998570941c0b.png)
_year = 1962 NOT = { year = 1990 }
Government = NOT Socialist or Communist
Mean time to happen: 2 months
Needs country flag = "punto_fijo"
Fire only once = yes_
Desc: After the Pact of Punto Fijo, the Communist Party of Venezuela (PCV) was sidelined by the major democratic parties. Inspired by Fidel Castro and the Cuban Revolution, PCV established the Armed Forces of National Liberation, a guerrilla group, in order to make their presence felt against the now-establishment government of Democratic Action (AD), COPEI, and the Republican Democratic Union. At the same time, youth dissidents of AD split off to form the Leftist Revolutionary Movement (MIR), who not only engaged in low-intensity guerrilla warfare, but on kidnappings, assassinations, and sabotage of the country's oil industry.
**A: Crack down on these revolutionaries!**
_AI chance: 95
5% of all pops who are Liberal are now Communist
All Pops who are Communist gain 4 Militancy and 2 Consciousness
All Pops who are Socialist gain 2 Militancy and 2 Consciousness_
**B: Perhaps we should dialogue with them.**
_AI chance: 5
All pops in Venezuela lose 1 Militancy and gain 1 Plurality.
All pops who are Conservative or Liberal gain 2 Consciousness.
Prestige = -2_

---
Decisions:
 - Name: **Rafael Urdaneta Bridge**
![image](https://cloud.githubusercontent.com/assets/24849306/21579402/433a12ba-cf7b-11e6-9900-eac56f6d311b.png)
(image source: https://commons.wikimedia.org/wiki/Puente_General_Rafael_Urdaneta#/media/File:General_Rafael_Urdaneta_Bridge_view_from_the_lake_to_Cabimas_side.jpg)
Potential:
_Own "Maracaibo" province.
Year = 1950_
Allow:
_Have discovered "Highway Construction"
Have $20,000 in funds._
Effect:
_Funds: -10,000
Prestige: +5_
Desc: The General Rafael Urdaneta Bridge is located at the outlet of Lake Maracaibo, in western Venezuela. The bridge provides highway access between Maracaibo and the rest of the country; a trip that had previously required ferryboats across the lake. Made of reinforced and prestressed concrete, the cable-stayed bridge spans 8,678 metres (5.392 mi) from shore to shore. The five main spans are each 235 metres (771 ft) long. They are supported from 92-metre (302 ft) tall towers, and provide 46 metres (151 ft) of clearance to the water below.
---
I will add a few more events (1970 and beyond) in the coming days as I do some research. Are there any plans to have OPEC established in-game in any capacity?

**Comment by simsulla** [comment]
Opec is in the mod as of the next release.

**Comment by simsulla** [comment]
@Blaskowicz, sorry for missing this issue. I will fix it in the next release 1.13.
