### ISSUE TITLE
Germany - Allied Occupation Zone events not firing

### ISSUE THREAD

**Issue by TheHonouredWolf** [simsulla/nwomod#879]
I'm playing multiplayer with some friends of mine at the '46 start, and the Soviet Union player released Germany (Not DDR). Now we're at '58 and the event where the Allies end their control over the Occupation Zones seem to not have fired, as they still directly control everything.

Has the USSR releasing Germany instead of the DDR caused the events to bug out, so Germany won't be able to reunite without going to war against NATO?

**Comment by simsulla** [comment]
Yes, releasing Germany as the USSR before the allies ending the occupation destroys the event chain. What one could do is to have a communist Germany become DDR. But this is complicated as later in the game this is not at all an desirable outcome, i.e. a sole communist Germany  is a possibility - and as such you would like to get all other Germany events. 
So I am afraid releasing Germany as the USSR before the allies ending the occupation is not supported - and easy to correct mod technically. Close with no action I am sorry to say.
