### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gsickk** [simsulla/nwomod#885]
Hi! I'm experiencing a crash on startup while loading quad textures, how could I resolve this issue? I'm playing with the last version of the mod and the game and other mods do not give me this problem. Thanks

**Comment by simsulla** [comment]
Latest is that nwomod-1.12.zip?
Have you cleared the cash?

**Comment by gsickk** [comment]
i have tried to reinstall the mod and clear the cache but it's the same. Yes it's the 1.12.

**Comment by simsulla** [comment]
When you reinstalled the mod, did you remove the old NWO directory?

**Comment by gsickk** [comment]
Yes i removed it from the mod folder and i copied and pasted again.

**Comment by gsickk** [comment]
Help? Still not working

**Comment by simsulla** [comment]
ok, Victoria 2 3.03 or 3.04 with nwomod-1.12 works 
If you
1. Removed any old installation before installing the new one.
2. Cleared the cache before starting the game. 
At what point (what is the last load text displayed?) do you see a CTD?

**Comment by gsickk** [comment]
Yes to both the things. I'm trying do all the things again in order. The last text displayed is "Creating texture for Quad 689".

**Comment by simsulla** [comment]
Hm... have no idea what is wrong. Could you post your system.txt in the logs folder under the cache folder. It contains info on your graphics card.

**Comment by gsickk** [comment]
[systemsettings.cpp:184]: System memory (available/total):	2005/3998 MB
[systemsettings.cpp:185]: Page file (available/total):		5431/7996 MB
[systemsettings.cpp:186]: Virtual memory (available/total):	3996/4095 MB
[systemsettings.cpp:203]: CPU speed:						2094 MHz
[systemsettings.cpp:211]: Number of processors: 2
[systemsettings.cpp:216]: CPU type: x64
[systemsettings.cpp:295]: OS: Windows 7 Service Pack 1    Build: 7601
[graphicssettings.cpp:132]: Graphic Adapters: 
[graphicssettings.cpp:137]: 	0: Mobile Intel(R) 4 Series Express Chipset Family
[graphicssettings.cpp:154]: Checking for multi-sampling support:
[graphicssettings.cpp:180]: Using Adapter [0]:
[graphicssettings.cpp:186]: Succeeded to create a device [D3DCREATE_HARDWARE_VERTEXPROCESSING].
[graphicssettings.cpp:228]: Graphics device: Mobile Intel(R) 4 Series Express Chipset Family
[graphicssettings.cpp:229]: Graphics driver: igdumdx32.dll
[graphicssettings.cpp:230]: Driver version:  8.15.10 build 1883
[graphicssettings.cpp:248]: 


Dumping all gfx info:
DeviceIdentifier:	{D7B78E66-6902-11CF-D774-6310A7C2C535}
VendorId:	32902
DeviceId:	10818
SubSysId:	812191804
Revision:	7
DriverVersion.HighPart:	524303
DriverVersion.LowPart:	657243


[graphicssettings.cpp:298]: Instancing supported.
[graphicssettings.cpp:316]: Video memory amount: 1342MB
[graphicssettings.cpp:319]: Support for T&L found.
[graphicssettings.cpp:322]: MaxSimultaneousTextures: 8
[graphicssettings.cpp:323]: MaxVertexBlendMatrices: 4
[graphicssettings.cpp:324]: MaxVertexBlendMatrixIndex: 8
[graphicssettings.cpp:326]: MaxSimultaneousTextures: 8
[graphicssettings.cpp:327]: MaxTextureBlendStages: 8
[graphicssettings.cpp:328]: Support for Anisotropic filtering found.
[graphicssettings.cpp:331]: 	Max Anisotropic filtering: 16
[graphicssettings.cpp:332]: 	Anisotropic filtering set to: 0
[graphicssettings.cpp:336]: Vertex Shader version: 3.0
[graphicssettings.cpp:341]: Pixel Shader version: 3.0
[main.cpp:400]: V2 Version Jan  4 2016 : 17:36:07
[main.cpp:471]: Blobing files
[main.cpp:492]: Init Text Database
[internationalizedtext.cpp:1237]: Create table
[internationalizedtext.cpp:1239]: Create text database
[main.cpp:494]: Text Database Done
[main.cpp:522]: Creating application...
[main.cpp:582]: Init Application...
[eu3application.cpp:226]: Initialise Defines
[eu3application.cpp:233]: App Init
[eu3application.cpp:248]: App Init
[eu3application.cpp:274]: Cursors Defines
[eu3application.cpp:302]: Sound...
[dxmusic.cpp:40]: Init Music
[dxmusic.cpp:51]: Graph done.
[dxmusic.cpp:62]: Control done.
[dxmusic.cpp:73]: Seeker done 
[dxmusic.cpp:83]: Event done.
[dxmusic.cpp:93]: Basic audio done.
[dxmusic.cpp:95]: Music done.
[DirectSound.cpp:37]: Init DirectSound
[DirectSound.cpp:55]: Sound initialised with result 0
[DirectSound.cpp:65]: Coop Level Set. Result: 0
[DirectSound.cpp:88]: Sound Init Done
[eu3application.cpp:351]: Initialise Graphics...
[graphics.cpp:161]: Direct3D Created
[graphicssettings.cpp:664]: Usable res: 1024 768 60
[graphicssettings.cpp:664]: Usable res: 1280 720 60
[graphicssettings.cpp:664]: Usable res: 1280 768 60
[graphicssettings.cpp:664]: Usable res: 1360 768 60
[graphicssettings.cpp:664]: Usable res: 1366 768 60
[graphics.cpp:279]: Not using multisampling.
[graphics.cpp:302]: Creating device with: D3DCREATE_HARDWARE_VERTEXPROCESSING
	Fullscreen=yes
	RefreshRate=60
	Borderless=yes
	Resolution=1366x768
[graphics.cpp:383]: Done creating device.
[eu3application.cpp:353]: Graphics Done
[eu3graphics.cpp:265]: Load text  Loading Map-Sprites...
[eu3graphics.cpp:265]: Load text  Loading GUI Definitions...
[eu3graphics.cpp:265]: Load text  Loading Databases...
[eu3graphics.cpp:265]: Load text  Initialising Maplogic...
[eu3graphics.cpp:265]: Load text  Calculating paths...
This may take several minutes.
[eu3graphics.cpp:265]: Load text  Loading Databases II...
[eu3graphics.cpp:265]: Load text  Loading History Files...
[eu3graphics.cpp:265]: Load text  Loading Events...
[eu3graphics.cpp:265]: Load text  Loading Sounds...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Loading Flags...
[eu3graphics.cpp:265]: Load text  Executing History
[eu3graphics.cpp:265]: Load text  Creating Checksum...
[main.cpp:588]: Run Application...
[frontend.cpp:430]: entering frontend...
[eu3graphics.cpp:265]: Load text  Loading Graphics...
[frontend.cpp:468]: entering frontend...init map
[eu3application.cpp:776]: initialise map
[eu3graphics.cpp:265]: Load text  Creating Province #
[eu3graphics.cpp:265]: Load text  Creating Borders...
[provincemanager.cpp:1559]: Creating province data
[eu3graphics.cpp:265]: Load text  Creating Texts....
[eu3graphics.cpp:265]: Load text  Creating Rivers...
[eu3graphics.cpp:265]: Load text  Creating the World...
[provincemanager.cpp:1636]: Creating meshes
[provincemanager.cpp:1689]: vertex declarations done
[provincemanager.cpp:2112]: REcreating quads
[eu3graphics.cpp:265]: Load text  Creating texture for Quad 24
[provincemanager.cpp:2170]: writing quad mesh 24
[provincemanager.cpp:2170]: writing quad mesh 35
[provincemanager.cpp:2170]: writing quad mesh 101
[provincemanager.cpp:2170]: writing quad mesh 102
[provincemanager.cpp:2170]: writing quad mesh 104
[provincemanager.cpp:2170]: writing quad mesh 152
[provincemanager.cpp:2170]: writing quad mesh 179
[provincemanager.cpp:2170]: writing quad mesh 180
[provincemanager.cpp:2170]: writing quad mesh 232
[provincemanager.cpp:2170]: writing quad mesh 257
[provincemanager.cpp:2170]: writing quad mesh 258
[provincemanager.cpp:2170]: writing quad mesh 259
[provincemanager.cpp:2170]: writing quad mesh 304
[provincemanager.cpp:2170]: writing quad mesh 309
[provincemanager.cpp:2170]: writing quad mesh 310
[provincemanager.cpp:2170]: writing quad mesh 311
[provincemanager.cpp:2170]: writing quad mesh 335
[provincemanager.cpp:2170]: writing quad mesh 336
[provincemanager.cpp:2170]: writing quad mesh 337
[provincemanager.cpp:2170]: writing quad mesh 338
[provincemanager.cpp:2170]: writing quad mesh 348
[provincemanager.cpp:2170]: writing quad mesh 363
[provincemanager.cpp:2170]: writing quad mesh 381
[provincemanager.cpp:2170]: writing quad mesh 382
[provincemanager.cpp:2170]: writing quad mesh 383
[provincemanager.cpp:2170]: writing quad mesh 388
[provincemanager.cpp:2170]: writing quad mesh 389
[provincemanager.cpp:2170]: writing quad mesh 413
[provincemanager.cpp:2170]: writing quad mesh 414
[provincemanager.cpp:2170]: writing quad mesh 415
[provincemanager.cpp:2170]: writing quad mesh 416
[provincemanager.cpp:2170]: writing quad mesh 417
[provincemanager.cpp:2170]: writing quad mesh 433
[provincemanager.cpp:2170]: writing quad mesh 434
[provincemanager.cpp:2170]: writing quad mesh 435
[provincemanager.cpp:2170]: writing quad mesh 454
[provincemanager.cpp:2170]: writing quad mesh 455
[provincemanager.cpp:2170]: writing quad mesh 457
[provincemanager.cpp:2170]: writing quad mesh 458
[provincemanager.cpp:2170]: writing quad mesh 459
[provincemanager.cpp:2170]: writing quad mesh 460
[provincemanager.cpp:2170]: writing quad mesh 461
[provincemanager.cpp:2170]: writing quad mesh 462
[provincemanager.cpp:2170]: writing quad mesh 468
[provincemanager.cpp:2170]: writing quad mesh 486
[provincemanager.cpp:2170]: writing quad mesh 491
[provincemanager.cpp:2170]: writing quad mesh 492
[provincemanager.cpp:2170]: writing quad mesh 493
[provincemanager.cpp:2170]: writing quad mesh 494
[provincemanager.cpp:2170]: writing quad mesh 495
[provincemanager.cpp:2170]: writing quad mesh 496
[provincemanager.cpp:2170]: writing quad mesh 511
[provincemanager.cpp:2170]: writing quad mesh 512
[provincemanager.cpp:2170]: writing quad mesh 513
[provincemanager.cpp:2170]: writing quad mesh 532
[provincemanager.cpp:2170]: writing quad mesh 533
[provincemanager.cpp:2170]: writing quad mesh 536
[provincemanager.cpp:2170]: writing quad mesh 538
[provincemanager.cpp:2170]: writing quad mesh 539
[provincemanager.cpp:2170]: writing quad mesh 540
[provincemanager.cpp:2170]: writing quad mesh 543
[provincemanager.cpp:2170]: writing quad mesh 552
[provincemanager.cpp:2170]: writing quad mesh 557
[provincemanager.cpp:2170]: writing quad mesh 569
[provincemanager.cpp:2170]: writing quad mesh 570
[provincemanager.cpp:2170]: writing quad mesh 571
[provincemanager.cpp:2170]: writing quad mesh 572
[provincemanager.cpp:2170]: writing quad mesh 573
[provincemanager.cpp:2170]: writing quad mesh 574
[provincemanager.cpp:2170]: writing quad mesh 575
[provincemanager.cpp:2170]: writing quad mesh 588
[provincemanager.cpp:2170]: writing quad mesh 589
[provincemanager.cpp:2170]: writing quad mesh 590
[provincemanager.cpp:2170]: writing quad mesh 591
[provincemanager.cpp:2170]: writing quad mesh 592
[provincemanager.cpp:2170]: writing quad mesh 594
[provincemanager.cpp:2170]: writing quad mesh 595
[provincemanager.cpp:2170]: writing quad mesh 610
[provincemanager.cpp:2170]: writing quad mesh 611
[provincemanager.cpp:2170]: writing quad mesh 613
[provincemanager.cpp:2170]: writing quad mesh 615
[provincemanager.cpp:2170]: writing quad mesh 617
[provincemanager.cpp:2170]: writing quad mesh 624
[provincemanager.cpp:2170]: writing quad mesh 626
[provincemanager.cpp:2170]: writing quad mesh 632
[provincemanager.cpp:2170]: writing quad mesh 647
[provincemanager.cpp:2170]: writing quad mesh 648
[provincemanager.cpp:2170]: writing quad mesh 649
[provincemanager.cpp:2170]: writing quad mesh 651
[provincemanager.cpp:2170]: writing quad mesh 652
[provincemanager.cpp:2170]: writing quad mesh 653
[provincemanager.cpp:2170]: writing quad mesh 654
[provincemanager.cpp:2170]: writing quad mesh 666
[provincemanager.cpp:2170]: writing quad mesh 667
[provincemanager.cpp:2170]: writing quad mesh 668
[provincemanager.cpp:2170]: writing quad mesh 669
[provincemanager.cpp:2170]: writing quad mesh 670
[provincemanager.cpp:2170]: writing quad mesh 672
[provincemanager.cpp:2170]: writing quad mesh 673
[provincemanager.cpp:2170]: writing quad mesh 676
[eu3graphics.cpp:265]: Load text  Creating texture for Quad 689
[provincemanager.cpp:2170]: writing quad mesh 689
[provincemanager.cpp:2170]: writing quad mesh 693
[provincemanager.cpp:2170]: writing quad mesh 694
[provincemanager.cpp:2170]: writing quad mesh 699
[provincemanager.cpp:2170]: writing quad mesh 701
[provincemanager.cpp:2170]: writing quad mesh 702
[provincemanager.cpp:2170]: writing quad mesh 703
[provincemanager.cpp:2170]: writing quad mesh 704
[provincemanager.cpp:2170]: writing quad mesh 706
[provincemanager.cpp:2170]: writing quad mesh 724
[provincemanager.cpp:2170]: writing quad mesh 725
[provincemanager.cpp:2170]: writing quad mesh 726
[provincemanager.cpp:2170]: writing quad mesh 727
[provincemanager.cpp:2170]: writing quad mesh 729
[provincemanager.cpp:2170]: writing quad mesh 730
[provincemanager.cpp:2170]: writing quad mesh 731
[provincemanager.cpp:2170]: writing quad mesh 732
[provincemanager.cpp:2170]: writing quad mesh 739
[provincemanager.cpp:2170]: writing quad mesh 743
[provincemanager.cpp:2170]: writing quad mesh 744
[provincemanager.cpp:2170]: writing quad mesh 745
[provincemanager.cpp:2170]: writing quad mesh 746
[provincemanager.cpp:2170]: writing quad mesh 747
[provincemanager.cpp:2170]: writing quad mesh 748
[provincemanager.cpp:2170]: writing quad mesh 749
[provincemanager.cpp:2170]: writing quad mesh 751
[provincemanager.cpp:2170]: writing quad mesh 767
[provincemanager.cpp:2170]: writing quad mesh 769
[provincemanager.cpp:2170]: writing quad mesh 772
[provincemanager.cpp:2170]: writing quad mesh 777
[provincemanager.cpp:2170]: writing quad mesh 802
[provincemanager.cpp:2170]: writing quad mesh 803
[provincemanager.cpp:2170]: writing quad mesh 804
[provincemanager.cpp:2170]: writing quad mesh 805
[provincemanager.cpp:2170]: writing quad mesh 806
[provincemanager.cpp:2170]: writing quad mesh 808
[provincemanager.cpp:2170]: writing quad mesh 809
[provincemanager.cpp:2170]: writing quad mesh 810
[provincemanager.cpp:2170]: writing quad mesh 811
[provincemanager.cpp:2170]: writing quad mesh 821
[provincemanager.cpp:2170]: writing quad mesh 822
[provincemanager.cpp:2170]: writing quad mesh 823
[provincemanager.cpp:2170]: writing quad mesh 824
[provincemanager.cpp:2170]: writing quad mesh 825
[provincemanager.cpp:2170]: writing quad mesh 826
[provincemanager.cpp:2170]: writing quad mesh 827
[provincemanager.cpp:2170]: writing quad mesh 828
[provincemanager.cpp:2170]: writing quad mesh 839
[provincemanager.cpp:2170]: writing quad mesh 841
[provincemanager.cpp:2170]: writing quad mesh 844
[provincemanager.cpp:2170]: writing quad mesh 845
[provincemanager.cpp:2170]: writing quad mesh 847
[provincemanager.cpp:2170]: writing quad mesh 851
[provincemanager.cpp:2170]: writing quad mesh 853
[provincemanager.cpp:2170]: writing quad mesh 855
[provincemanager.cpp:2170]: writing quad mesh 859
[provincemanager.cpp:2170]: writing quad mesh 866
[provincemanager.cpp:2170]: writing quad mesh 879
[provincemanager.cpp:2170]: writing quad mesh 880
[provincemanager.cpp:2170]: writing quad mesh 881
[provincemanager.cpp:2170]: writing quad mesh 882
[provincemanager.cpp:2170]: writing quad mesh 883
[provincemanager.cpp:2170]: writing quad mesh 885
[provincemanager.cpp:2170]: writing quad mesh 887
[provincemanager.cpp:2170]: writing quad mesh 888
[provincemanager.cpp:2170]: writing quad mesh 889
[provincemanager.cpp:2170]: writing quad mesh 893
[provincemanager.cpp:2170]: writing quad mesh 899
[provincemanager.cpp:2170]: writing quad mesh 900
[provincemanager.cpp:2170]: writing quad mesh 901
[provincemanager.cpp:2170]: writing quad mesh 902
[provincemanager.cpp:2170]: writing quad mesh 903
[provincemanager.cpp:2170]: writing quad mesh 904
[provincemanager.cpp:2170]: writing quad mesh 905
[provincemanager.cpp:2170]: writing quad mesh 908
[provincemanager.cpp:2170]: writing quad mesh 912
[provincemanager.cpp:2170]: writing quad mesh 919
[provincemanager.cpp:2170]: writing quad mesh 920
[provincemanager.cpp:2170]: writing quad mesh 921
[provincemanager.cpp:2170]: writing quad mesh 922
[provincemanager.cpp:2170]: writing quad mesh 923
[provincemanager.cpp:2170]: writing quad mesh 924
[provincemanager.cpp:2170]: writing quad mesh 925
[provincemanager.cpp:2170]: writing quad mesh 927
[provincemanager.cpp:2170]: writing quad mesh 928
[provincemanager.cpp:2170]: writing quad mesh 929
[provincemanager.cpp:2170]: writing quad mesh 930
[provincemanager.cpp:2170]: writing quad mesh 935
[provincemanager.cpp:2170]: writing quad mesh 940
[provincemanager.cpp:2170]: writing quad mesh 957
[provincemanager.cpp:2170]: writing quad mesh 958
[provincemanager.cpp:2170]: writing quad mesh 959
[provincemanager.cpp:2170]: writing quad mesh 960
[provincemanager.cpp:2170]: writing quad mesh 961
[provincemanager.cpp:2170]: writing quad mesh 963
[provincemanager.cpp:2170]: writing quad mesh 964
[provincemanager.cpp:2170]: writing quad mesh 965
[provincemanager.cpp:2170]: writing quad mesh 966

**Comment by gsickk** [comment]
tried anything, maybe it's just an issue with my graphic card.
