### ISSUE TITLE
The version 1.12 does not work

### ISSUE THREAD

**Issue by lucasprado51** [simsulla/nwomod#886]
This version of this mod does not work. When the version will be corrected?

**Comment by simsulla** [comment]
Have you installed it properly? Have you cleared your cache? Have you downloaded the nwomod-1.12.zip from the official download link?

**Comment by lucasprado51** [comment]
How do I clear the cache?

**Comment by simsulla** [comment]
In the folder C:\Users\your_windwos_user\Documents\Paradox Interactive\Victoria II\NwO (exact path may vary - depending on windows version) . Remove the gfx and map folder in that folder. 

**Note:** this is not the folder where you installed the mod.
