### ISSUE TITLE
1992 researched Technology correction overhaul

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#888]
This issue has been bugging me for a while, I think this issue should be urgently addressed since many countries at the 1992 bookmark are far more technologically backward then they were really are back in 1992. A perfect example of this would be India, since in the 1992 bookmark India has roughly an early WW2 military with no technology researched at all, as you can see this is completely ridiculous since the equipment of the real life Indian Military in 1992 although behind Western militaries technological were decades more advanced than any army in WW2 for example the jet fighters they were using at that time like the Mig 21 were generations ahead of any fighter plane from WW2. If this issue was corrected, this could potentially stop the numerous wars at the 1992 bookmark over disputed territories between countries due to territorial disputes being resolved in the International Court of Justice and Arbitration only if globalisation was researched.
![20170114003529_1](https://cloud.githubusercontent.com/assets/20518264/21950499/78bcd792-d9f3-11e6-86a3-860838326356.jpg)

Also some technologies are missing some pictures
![20170114003621_1](https://cloud.githubusercontent.com/assets/20518264/21950636/e8283be8-d9f4-11e6-8cc9-b9ae0fa16126.jpg)

I will try to do as much corrections for researched for countries in the 1992 bookmark  as possible before the next version is released.

**Comment by simsulla** [comment]
Totally agree. This is one of the major issues I will work on in 2.00.

**Comment by arandomperson5000** [comment]
I have changed the amount of researched technologies for the U.S to better reflect its technological situation at 1992 and to provide a template where researched technologies could be deleted or added to better suit other countries like Russia.
[1992 USA technoligcal corrections.zip](https://github.com/simsulla/nwomod/files/706241/1992.USA.technoligcal.corrections.zip)
![20170114215527_1](https://cloud.githubusercontent.com/assets/20518264/21958418/92bc866c-daa5-11e6-9c5a-d38ae9de8541.jpg)
![20170114215539_1](https://cloud.githubusercontent.com/assets/20518264/21958420/a26939f2-daa5-11e6-8ca6-19c3b9141a06.jpg)
![20170114215553_1](https://cloud.githubusercontent.com/assets/20518264/21958435/1de50c00-daa6-11e6-9f8a-bcdf85ec59db.jpg)
![20170114215604_1](https://cloud.githubusercontent.com/assets/20518264/21958440/3d577e74-daa6-11e6-879c-58919bb52597.jpg)
![20170114215615_1](https://cloud.githubusercontent.com/assets/20518264/21958466/212190cc-daa7-11e6-899c-10f37e85e0ed.jpg)

I think the research date for the hand held devices technology is a little bit too early to be unlocked in 1990, I would rather place it in 1992 when smartphones, pads and application stores were invented or somewhere between 2008 and 2010 as they only became quite widespread within that time frame.

Also I'm not quite sure whether to remove the revolt of the masses and the decline of the west and the lost generation inventions from the popularisation of preschool technology since it appears to be leftover from vanilla Victoria 2. 
![20170114215910_1](https://cloud.githubusercontent.com/assets/20518264/21958510/187cc18e-daa8-11e6-97bc-c3bc0a294a32.jpg)

I'm as equally confused over the status of ownership of the Panama Canal in the 1992 bookmark since ownership of the canal was supposed to have been given to Panama from the U.S in 1979 however I'm not quite sure what it's status was like in 1992.
![20170114215910_1](https://cloud.githubusercontent.com/assets/20518264/21958546/8c046ecc-daa8-11e6-9f52-ac28c88a2fce.jpg)

When I was looking through the history/countries files in the vanilla version of HOD I found that decisions could be activated through the countries's text file

An example in the United Kingdom text file in history/countries for HOD
1842.8.9 = {
decision = webster_ashburton_treaty
}

1846.6.25 = {
decision = repeal_the_corn_laws
}

1857.1.1 = {
decision = crown_empress_of_india
}

1860.10.18 = {
decision = torching_of_the_summer_palace
}

**Comment by simsulla** [comment]
Moved the "Croatian war.." to issue #897

**Comment by arandomperson5000** [comment]
![20170118224155_1](https://cloud.githubusercontent.com/assets/20518264/22086250/e0114e8e-ddcf-11e6-9258-b1734550dc5e.jpg)
![20170118224202_1](https://cloud.githubusercontent.com/assets/20518264/22086271/eadb847e-ddcf-11e6-9d29-76cd257f1b20.jpg)
![20170118224224_1](https://cloud.githubusercontent.com/assets/20518264/22086284/f952d200-ddcf-11e6-89e2-22b1261b28b6.jpg)
![20170118224248_1](https://cloud.githubusercontent.com/assets/20518264/22086293/02761a7c-ddd0-11e6-9f76-168e109ed053.jpg)
![20170118224309_1](https://cloud.githubusercontent.com/assets/20518264/22086304/10306ece-ddd0-11e6-8c68-0cc0dd08baf2.jpg)

**Comment by simsulla** [comment]
Will move this issue to the main track milestone, and create a separate issue for the additional techs I am working on for 2.00. #918
