### ISSUE TITLE
Possible rework of the occupation of Korea?

### ISSUE THREAD

**Issue by CruelLove** [simsulla/nwomod#889]
The current events & decision regarding the occupation and the release of the two Koreas is rather problematic, because they don't really fit history, so I was wondering if there was any possibility to rewrite them.

The problems with the currents events are that:
1) There was no possibility to release Korea as part of the ROC's "sphere" (event 1209001) because the USA had not even been aware of them in the first place. The USA's lack of knowledge regarding the Korean peninsula was one of the major reasons for their administrative struggles and why the Provisionary Government of Korea was never given a chance in the first place.

2) There was no actual trusteeship of the Korean peninsula (as implied in decision korea_trusteeship). Due to a scandal arising from an incorrect news report about the Moscow Conference, many political groups in the South began to take a staunch anti-trustee, anti-socialist stance. The question of how to deal with these political groups eventually broke down negotiations between the USSR and the USA, who eventually went on to hold separate elections and raise separate republics instead.

3) There is no possibility for an actual united Korea to form as per historically, when this was the option agreed by both the USSR and the USA coming into 1946. I believe that there should be a possibility for a united Korea to be released, with a "first election" event determining under which superpower's influence the new state would be.

Thus, I would like to propose a chain of the following events:

1) Failures of the Military Occupation of Korea (USA)
-Large MIL and CON increases, 9 MIL in Daegu, converts a large portion of POPs to socialist
2) Establishing the Provisional People's Committee (SUN)
-Moderate CON increases, converts large portion of POPs to socialist
3) Korean Trusteeship Scandal (USA)
-Choice #1 (Suppress anti-trust movements): Moderate MIL and CON increases
-Choice #2 (Use the movements as a tool against socialism): Moderate CON increase, converts portions of POPs back to conservative, triggers event #4
4) Trusteeship dispute (SUN)
-Choice #1 (Demand ban pn anti-trusteeship movements from negotiations): Triggers event #5, makes socialist victory more likely during elections
-Choice #2 (Go ahead with the trusteeship)
5) Go ahead with elections? (USA)
-Choice #1 (Elections the way we want- separate, if necessary): Release SKO, Triggers event #6
-Choice #2 (Accede to Soviet demands)
6) Establishment of the DPRK (SUN)
-Release NKO
7) The establishment of the ROK (USA/SUN)- triggers ~1950 if not already divided
-Releases KOR, makes the other country cede provinces to KOR as well
8) / 9) First elections of the ROK (KOR)- Socialist/Conservative victory
-Likelihood based on MTTH modifiers using the POP's ideologies, and whether anti-trusteeship movements were banned (ban makes socialist victory more likely). POP ideologies from events should be balanced so that socialists will be more likely to win than conservatives either way.
-Puts the country under the appropriate country's SOI and government

What do you think about it? Worth considering or no? Hopefully even if you don't decide to use these changes, you'll at least put them into consideration if you ever happen to touch the Korean events again.

**Comment by simsulla** [comment]
On 1. "There was no possibility to release Korea as part of the ROC's "sphere" (event 1209001) because the USA had not even been aware of them in the first place", but according to [wiki ](https://en.wikipedia.org/wiki/Division_of_Korea#US_occupation_of_South_Korea)- "The Provisional Government of the Republic of Korea, which had operated from China, sent a delegation with three interpreters to Hodge, but he refused to meet with them.".
