### ISSUE TITLE
Graphics map

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#890]
**randomanon000**
I've been trying the mod out and I've been noticing that the map graphics look a tad a bit poor- it looks stretched out horizontally with the edges looking awfully pixellated as well as some random black lakes in countries and orange/greenish patches of waters nearby coasts.
Are these issues coming from my end or are they just a part of the mod?

**Comment by samwoodzadrot** [comment]
Hello. These problems with the card really hinder play. I ask you to solve the problems with the card in the next versions. Thank you!

**Comment by simsulla** [comment]
Specifically, what problem?

**Comment by samwoodzadrot** [comment]
https://raw.githubusercontent.com/wiki/simsulla/nwomod/NWO_start_dates_1992_europe.png
It's a screenshot of normal map. Right?

I have this map stretched on the sides. For example Germany looks bigger because map is stretched.

**Comment by simsulla** [comment]
This is a screenshot using settings.txt
'size=
{
	x=1280
	y=800
}'
![image](https://cloud.githubusercontent.com/assets/10263809/21996811/42ae05b4-dc2c-11e6-949e-0645fae6da09.png)

The map is a EPSG:4326 world map #709 projection.

**Comment by samwoodzadrot** [comment]
Yes! My map looks like this one, but in my settings.txt show's - 
size=
{
	x=1920
	y=1080
}

**Comment by simsulla** [comment]
Yes, that is a real world ( EPSG:4326) projection. The original Vic2 uses a "fantasy" projection.

**Comment by opportus** [comment]
Hello @simsulla, a hat tip for your work and contributor's, I really enjoy this mod.

Though, I just can't deal with this new graphical map... I've seen you mention on another issue something like that Europe is not at the correct size on the original Victoria 2 map style.
But the new map style you're using is of special kind, I mean that it makes you look at the world like through a "fish eye" lens. It's all the correct size on the equator longitude, but it flattens the world more and more as you go at top or at bottom of the map... So basically, nothing has the right size also.

Furthermore, I'm not modder at all but I guess that the issue with the 3 canals + the ressources that are off-center of the province (displaying on the limit of other provinces) are related to this new map ?

Apologizes for my english... I think I'm missing vocabulary.
