### ISSUE TITLE
Yemen Territorial Dispute Bug

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#892]
It appears that there is a bug in which Yemen is allowed to declare war on Israel without any infamy through a territorial dispute casus belli it has at the start of the 1992 bookmark.
![20170115001832_1](https://cloud.githubusercontent.com/assets/20518264/21959274/cda052ae-dab9-11e6-9063-5bad41911b64.jpg)

**Comment by simsulla** [comment]
This is part of Arab nations not accepting Israel existence. By design, to make arabs pinned against israel cased by hasving a casus belli.
