### ISSUE TITLE
Yugoslav wars

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#897]
**Galbatorix994,**
I have noticed a bug which completely breaks the Yugoslav wars in the latest version.Rather than starting with the SER tag in 1992,Yugoslavia instead has the YUG tag.As a result of this,Yugoslavia is excluded from all of the Yugoslav wars and receives various cold-war events such as the Bled agreement.

**Comment by simsulla** [comment]
By @arandomperson5000 in #888 
Fixed both the Croatian War of Independence and the Bosnian War so Yugoslavia will be an actual participant in the wars.
Yugoslav Wars.zip

**Comment by arandomperson5000** [comment]
Found another bug in which Yugoslavia doesen't have enough soldier pops to fill their brigades.
![20170115141528_1](https://cloud.githubusercontent.com/assets/20518264/21963775/43798f44-db38-11e6-9cbc-10962f686044.jpg)

**Comment by arandomperson5000** [comment]
As a potential solution to this problem, the old soldier pops could be used to solve this problem with a slight bit of tweaking to fit in with the current population of the former Yugoslavia in the 1992 bookmark. The same process could be used for other countries missing soldier pops in the 1946 bookmark.
