### ISSUE TITLE
Mistakes in Brazil

### ISSUE THREAD

**Issue by cesarcurado** [simsulla/nwomod#9]
1- Wrong Brasilia position
Brasilia should only exist after 1960, but not in Minas Gerais. 
I recommend using this for reference
http://i.imgur.com/8zW1fGZ.png
And another map of where Brasilia should be
http://i.imgur.com/ExsxU59.jpg
If you do not wish to create a new province, just use the province that is ingame named "Vila Boa" (2421).
What is currently Brasilia in the mod should probably be "Poços de Caldas", which is the largest city inside the province.

2- Workers' Party (Partido dos Trabalhadores) should be socialist and not communist.

**Comment by simsulla** [comment]
will be corrected in the next release.
