### ISSUE TITLE
Abandon claim greater Italy

### ISSUE THREAD

**Issue by catcus** [simsulla/nwomod#900]
This decision abandons all cores, except one in Lugano in Switzerland.

**Comment by simsulla** [comment]
It abandons all cores except those you control. Or are you saying all cores, including the one you control is abandoned?

**Comment by catcus** [comment]
Nope, Lugano was still under control of Switzerland. I didn't conquer any claimed cores.

**Comment by simsulla** [comment]
Ok, this is interesting, the condition is is_primary_culture = yes (i.e. the province primary culture is that of the owning country. Which is not the case in Lugano (Swiss is german). Maybe one could add a is_accepted_culture condition
