### ISSUE TITLE
Artisans to produce Services

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#904]
For many countries in the world it is true that tourism makes up a very large part of their national economy, but I don't it's portraited well enough in the mod. How do you accumulate the income of tourism in the mod? Tourism is important for many countries, notably in the mediterreanen (Asia Minor, Northern Africa). But due to the recent evcents (terrorism, arab spring) tourism has declined, which causes unemployment rates and debts. So integrating it would greatly benefit the mod, I think.

**Comment by simsulla** [comment]
As part of issue #851 I am playing around with the thought to create _services_ (maybe several types of them), as a goods. This goods would be produced by artisans (currently called entrepreneurs - to be renamed to ??).  As industrial productivity increases (particularly in the late 2000th and 2100 century), the number of workers need to produce industrial (factory) goods,  wheres services productivity changes little (i.e. artisans producing various types of services). This mod the "de-industrialization" of highly developed nations (i.e. the industry - by technology and invention - is extremely efficient and does not require lot's of workers). 
Tourism is the trade of service goods.

**Comment by Liegnitz** [comment]
Well, entrepreneurs fits just fine. I wonder, will services also need ressources or actually be ressources and will being an industrialized country be a worse choice than rather being one that mainly focuses on services ?

**Comment by simsulla** [comment]
Services
Transportation Services
Advanced Services
They would be separated by the goods that they require. Services are consumed by pops. 
Maybe some aspects of the financial industry could be considered part of "Advanced Services".

**Comment by simsulla** [comment]
From http://www.trademap.org/Index.aspx services
These are the services to be added (according to [BPM6](https://www.imf.org/external/pubs/ft/bop/2007/bopman6.htm).

travel_services (service code 6 Travel)
transport (service code 3 Transport)
advanced_services (service code 10 - Other business services)
financial_services (service code SOX Commercial services)
services (other services)

Financial_services exists already and are produced in "bank factories". The other will be produced by artisans only.

**Comment by simsulla** [comment]
Will close this issue but, we need a lot of balancing of the economy before release. It is pretty unbalanced at the moment.
