### ISSUE TITLE
Future trade goods

### ISSUE THREAD

**Issue by Tileta98** [simsulla/nwomod#907]
Hi @simsulla , I want to suggest some trade goods for the near and far future, for example Robots, Advanced Healthcare, Organic Food or Quantum Computers, for example. I'm not a modder, i can't do this for the mod.
I think that your mod is the best mod for Victoria 2, and it looks like another game, and I think that a better variety of goods could be positive for this mod.
Greetings!!!

**Comment by simsulla** [comment]
Will take this as part of Goods review #851
