### ISSUE TITLE
South Africa events

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#909]
**The B**
Sure, but my experience in modding is limited, so I don't know how plausible this is.

Mainly, I think there should be an event chain that goes:

Apartheid (1948) as is current

Defiance Campaign (1952)
Crackdown - increased militancy and support for ANC amongst non-accepted POPs
Soft approach - increased consciousness and higher support for ANC
Freedom Charter (1955)
This is a communist document - increased militancy
Ignore it - increased consciousness
Sharpeville Massacre (1960/61)
Declare a state of emergency - suppresses the ANC (somehow) and lowers militancy
Apologise - huge rise in consciousness
In 1984 there should be an event for the election of Botha. This should lead to -

Botha's Reforms
Institute the reforms - decreased consciousness and militancy
Do not institute the reforms - no change
Unban the ANC
Unban the ANC and other organisations - leads to decrease in militancy but starts event chain for the end of apartheid (possibly)
Unban the ANC and release Mandela - as above, but increases support for the ANC
Do nothing - increase in militancy and consciousness

Eventually by about 1990 it should be very difficult for the player to maintain the current state of affairs without a rebellion, and the 'Unban the ANC' event should pop up again. If you want to keep it simple, this should enable the decision to repeal apartheid, but if you would like it could lead to an end of Apartheid event chain.

The end of apartheid and the start of the new regime was quite a delicate time and I don't know how much you would want to flesh this out in events further, but it could be quite interesting or over-complex.

Yes, I think that the various African cultures should be made accepted (edit: at the end of apartheid). That's something else I forgot to put, I don't think White Anglo is the right primary culture in 1990.

**Comment by arandomperson5000** [comment]
This is definitely needs to be put into the mod as I had completed the researched technology overhaul for every single playable country on the 1992 bookmark, the old decision to apartheid should be updated since one of its requirements, liberalism is already researched by South Africa in the overhaul at the 1992 startdate, otherwise it would cause apartheid to end several years earlier than the real end of Apartheid in 1994.

**Comment by simsulla** [comment]
Events created. Note, that according to the _secunde directive_ of nwo "_the actors rule_", the view of the at the time South African government is presented in the text - as the government/player is the recipient of the event. Thus not necessary accurate.
