### ISSUE TITLE
Tripura government fix

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#915]
Noticed there was an error that was made in a previous commit in which Tripura was a democracy in the 1946 startdate instead of an absolute monarchy since Tripura was once a princely state.
[Tripura 1946 Government type Fix.zip](https://github.com/simsulla/nwomod/files/733610/Tripura.1946.Government.type.Fix.zip)
Also I'm wondering what did you think of my Buryatia commit and finally! I have finished the overhaul of the researched technologies for all countries playable right from the 1992 bookmark.

**Comment by simsulla** [comment]
See the Buryatia  issue for comments. Maybe keep comments on the "technologies .." issue in that issue. I get notified on any comment in any issue.   :)

On Tripura , please commit the file.
