### ISSUE TITLE
Franco-British Union and Caucasus Emirate suggestions

### ISSUE THREAD

**Issue by JohnLockers** [simsulla/nwomod#916]
Franco-British Union, forms rarely during the Suez Crisis to maintain the Empires https://thedailybeagle.net/2015/04/27/frangleterre-the-union-that-could-have-been/

Caucasus Emirate cores, implying an insurgency in the Caucasus against Russian rule https://en.wikipedia.org/wiki/Caucasus_Emirate

**Comment by simsulla** [comment]
No, a Franco-British Union would violate the prime directive of the mod _realism_

**Comment by simsulla** [comment]
For the Caucasus Emirate see #826
