### ISSUE TITLE
Additional Technologies

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#918]
Problems in the current tech design:

1. In the current version of NWO, every player will be able to research the full set of technologies, i.e. there is no need to choose on focus sacrificing some (like army or navy) to gain an advantage in another (like industry). Increasing the tech depth - number or reachable technologies - there will be more to research than you have time for in the game will solve this.

2. Developing countries tend to have only one or two techs less than developed nations - making them not decisively behind in productive/military capability. By making that "lag" grater the productive advantage of developed nations become bigger and more realistic, and game-play of developing nations more challenging and fun. 

3. The tech span is to narrow - i.e. start techs correlate to 20th century for a developed nation and ends maybe in the beginning of 21th. In reality developing nations are at a end of 19th century. Also the end of the tech scope could be expanded into the latter part of the 21th century - with a conservative approach not to violate the _Prime Directive_.

**Comment by simsulla** [comment]
The idea is to have 20 levels with _tentatively_ this sub sections
![image](https://cloud.githubusercontent.com/assets/10263809/22360462/41de8218-e450-11e6-8a38-e3f2f8fc1b9d.png)

**Comment by simsulla** [comment]
The overall tech time span will be c.1870s - c.2070s. 
The game time span will be c.1950-2100. A player though that starts on a 1870 level will need an additional 100 year to discover all techs, i.e. till 2200. Advanced start nations will reach completion around 2100. After that the world will be technologically stagnant. 
The  UN pop projection goes to 2300 thus this will be the end date of the game.

**Comment by simsulla** [comment]
In simsullas mind the increase in production efficiency is beyond any other factor the major force shaping our modern world - and has been so for the last hundreds of year. 
Below a graph of wheat productivity
![image](https://cloud.githubusercontent.com/assets/10263809/24899360/507c01da-1ea0-11e7-9474-3e01c3950065.png)

This is the source of wealth and welfare. And the uneven level of technological development in different parts of the world is the underpinning factor for almost all major social end ideological trends (many of the ideas existed already at the time of the Old Greeks, but these effects give those ideas room to bloom in reality of society). 
Among those ideas are social end ideological trends are
- liberal internationalist supporting globalism
- capitalist wealth, socialism, the welfare state and the wealth redistribution
- feminism and immigration.
- colonial racism, break down of traditional norms and family values and youth culture

So, in the mod we want to drive politics by tech level - a nation that is on the top level of industrial technology will benefit from free trade, low tariffs and want to open up markets by globalism (imperialism in the 1800c). A nations on a lower level need to focus there effort on a track that is suitable for them. Further more a nation that is on the top level of industrial technology, will face demands for income redistribution from a now very wealthy capitalist class, and due to their tech superiority have the economy to sustain the transfer. Less advance nations will not have economy for wealth transfer, and need to handle the social tensions there from by suppression. 

The top level of technology will (given an open market) be able to sell more than their labor force can produce. So they need more pops. This sets the under pinning for female workforce participation (feminism) and opens the door for immigration as more pops is needed. By contrast poorer (less tech advanced) will have more pops that needed.

**Comment by simsulla** [comment]
A side note;
**River974**
And I advise to change the max point of science used by day to 100 at 300 per day in the define.lua (MAX_DAILY_RESEARCH variable), because in the late game it's easy to have more than 100 per day (and with events) and it's impossible to used.

**Comment by simsulla** [comment]
I have committed the main work batch of Additional Technologies #918.
Still lots and lots of errors in the technologies and inventions files. I will fix those when I tune the production. But all dependencies (including country tech levels in the history files) should be ok.
As a player of a less developed nation you will struggle to catch up with the developed world (and make tuff choices - industry or military).

Update your code. Lots of changes. Ugh!

**Comment by arandomperson5000** [comment]
In the next release after 1.14 I think all the researched technologies that both developed and developing countries in both the 1945 and 1992 bookmarks will have be adjusted for their technological capability they had in real life in both 1945 and 1992. An example of a country whose number of researched technoliges needs to adjusted is Iraq in the 1992 bookmark, as of right now has a WW1 military despite Iraq being more a 60s to 70s style military in 1992 in real life, for example in 1992 Iraq had several hundred T-72M tanks and were producing their own local variant of that tank the Asad Babil while not as advanced as Western tanks such as the M1A1 Abrams it was still decades ahead of even the most advanced tank of WW1 with features such as an autoloader.

A Asad Babil tank ( Lion of Babylon)
![image](https://cloud.githubusercontent.com/assets/20518264/25132876/e785a61a-2442-11e7-9635-5f696d027273.png)

Remains of an Iraqi T-72M tank destroyed in the Gulf War
![image](https://cloud.githubusercontent.com/assets/20518264/25133050/7fbbe3f4-2443-11e7-9dba-ff2c7195de47.png)

Photo of a Mark IV Tank one of the most common tanks used by the British in WW1
![image](https://cloud.githubusercontent.com/assets/20518264/25133226/f5856aec-2443-11e7-9c75-e89cc2a53ab6.png)

Current researched technologies of Iraq at the 1945 bookmark
![20170418140756_1](https://cloud.githubusercontent.com/assets/20518264/25133322/39583326-2444-11e7-9fbd-7aeadbd6665b.jpg)

**Comment by simsulla** [comment]
Yes. I generated the levels based on Trade Complexity. But we need to take more factors into account. I.e. Auctoritarian nations (like Iraq) should have higher military and lower industry/productivity tech. I will update.

**Comment by arandomperson5000** [comment]
I think we will need to do another researched technology overhaul like we did in previous releases as this problem is effecting all countries on both bookmarks not just Iraq. Perhaps we could do this in the next release.

**Comment by simsulla** [comment]
Still needs a lot of tuning, but will take that as a separate tuning issue.
