### ISSUE TITLE
Start Dates

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#929]
**samwoodzadrot**
Hello. I think it would be good if it was in mod scenario in 2013-2017 years.
**simsulla**
I understand why you would like a 2017 start (I would too) but one need to way-in the benefit from the effort.
And actually we are contemplating the opposite, only having one start date 1946. It is a lot of work to maintain several start dates.

**Comment by samwoodzadrot** [comment]
In fact I do not like the scenario, 1946. I'm playing only the scenario in 1992.

**Comment by samwoodzadrot** [comment]
Just if I wanted to play in the cold war, I would have played in mod about the Cold War but I'm interested in the modern world.

**Comment by simsulla** [comment]
Ok, got it.
