### ISSUE TITLE
The buff disapper after you conquer the region

### ISSUE THREAD

**Issue by thrintyseven** [simsulla/nwomod#930]
the region in Saudi Arabia have the buff of Oil Field (RGO Throughout:+3000%)
But after i conquer the region, the buff will disappear instantly, will there have any improvement done to the issue?

**Comment by simsulla** [comment]
That is a bug. The "province modifier" should be added regardless of owner,

**Comment by simsulla** [comment]
Correction this is not a bug. It work as intended. However if you conquer a province the modifier get lost. Wait one year and then the event adding the modifier will fire again. One way to see it as that the firs year after conquest you will have production issues, then you get up to speed again.
