### ISSUE TITLE
Soviet claims to Kars

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#933]
**redstonecobra**
Hey Simsulla, been reading up on some history, and do you reckon you could add Soviet claims to Kars in Turkey? In real life there was almost a conflict over territories which had been promised during the Russian Empire.
https://upload.wikimedia.org/wikipedia/commons/f/f8/USSR_territorial_claims_to_Turkey_1945-1953.png
https://en.wikipedia.org/wiki/Soviet_territorial_claims_against_Turkey
https://en.wikipedia.org/wiki/Treaty_of_Kars

**Comment by arandomperson5000** [comment]
Having looked at the sources for Soviet claims on parts of Turkey, I noticed that there were a few problems with the idea ever being realistic. First of all I have been unable to find any Soviet newspaper articles about the subject, the ones referenced on Wikipedia only led to dead links. Also another problem I noticed is that it appears there is no official Soviet government document detailing the supposed Soviet claims on parts of Turkey, the only sources that are even referenced on the Wikipedia article are simply newspapers and the memoirs of Khrushchev.

**Comment by simsulla** [comment]
The [russian version](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%80%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BF%D1%80%D0%B5%D1%82%D0%B5%D0%BD%D0%B7%D0%B8%D0%B8_%D0%A1%D0%A1%D0%A1%D0%A0_%D0%BA_%D0%A2%D1%83%D1%80%D1%86%D0%B8%D0%B8) contains a lot more information. And maybe this book https://www.jstor.org/stable/149746?seq=1#page_scan_tab_contents

**Comment by simsulla** [comment]
The Soviet union does not claim territory (i.e. has no cores) in the mod. Thus [such claims](https://en.wikipedia.org/wiki/Treaty_of_Kars) needs to be [transcended to SSR's](https://en.wikipedia.org/wiki/Soviet_territorial_claims_against_Turkey) (Armenia, Georgia and notably Adjara)There is already a claim greater Armenia decision that in part models this. I will add a Soviet event for also claiming the area (though the AI will be inclined not to claim it). Kars to Armenian SSR, Ardahan province to Adjara.

**Comment by simsulla** [comment]
[Laz people](https://en.wikipedia.org/wiki/Laz_people) (i.e Adjara core). 
![image](https://cloud.githubusercontent.com/assets/10263809/23822117/bf77ab02-0645-11e7-814c-73e69da14bc2.png)

**Comment by simsulla** [comment]
Created events as the [Turkish Straits crisis](https://en.wikipedia.org/wiki/Turkish_Straits_crisis). soviet demands military access. If Turkey reject this, they have the option to add Armenian and Georginan cores in Kars etc...
