### ISSUE TITLE
Unbalanced and unrealistic economic size and military power of USSR

### ISSUE THREAD

**Issue by 1235789546** [simsulla/nwomod#934]
Hi. I'm playing the current version of NWO and i noted that in the 1946 scenario, the USSR has less economic points than Great Britain, which is highly unrealistic given the fact that at the end of WW2 the Soviet economy was **by FAR superior to that of Great britain** (even after the whole WW2 destruction). **It was the second economy of the world, which is a proven fact** (again, surpassing the British one). The same happens to the military, soviets are behind Great Britain, but in real history the Soviets had more units than the US and their army was certainly more powerful than the british one... Also, at that time the Soviet economy was 40% that of the US, but in the game the difference is overwhelmingly high: USSR 96 and USA 1100. Previous versions of this mod didn't have this historical inaccuracies. What i mean is, USSR ranks (prestige/economy/army) are 1/3/3, while **historically** its ranks were 2/2/2.

**Comment by simsulla** [comment]
From Maddison 1946 these where the top 10 by PPP (no 1946 statistics for China)
![image](https://cloud.githubusercontent.com/assets/10263809/22851621/779794a6-f028-11e6-87a2-5a5bc750ca11.png)
The UK had India as an vassal and occupied parts of Germany 1946. The US president Roosevelt saw the UK as the main rival, not the USSR (that then changed as the cold war got going...)

On the military it seems like a bug - yes USSR was very strong. Will look into it,

**Comment by 1235789546** [comment]
i downloaded the statistic data from that Angus Maddison guy, which numebrs corresponds with the ones you put above, but the same document also shows that the small gap between the 2 economies widens a LOT by 1949 (on favor to USSR). The document shows the Soviet economy surpassed the british one from 1948 onwards. Is that reflected in the mod? i mean the Soviet economy ends up surpassing the british one? wether the USSR is controlled by an AI or a human player?

**Comment by simsulla** [comment]
Yes it is reflected in the mod. The UK decays as a power with the decolonization.
