### ISSUE TITLE
Please focus on the modern world. (1992 scenario)

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#937]
Hi. I would like to developers shifted the focus from the Cold War scenario in the modern world, most people think I'm just interested in the modern world and not the Cold War. Please do more scenarios in the modern world as well as more events.

**Comment by simsulla** [comment]
Ok will have it in mind. 2.00 will be to some extent better cover the economics of the 21:st century, which of-cause is the framework for more qualitative late game game-play.
