### ISSUE TITLE
Federal Subjects of Russia

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#944]
Hello. I would like to ask you to add more of the Russian Federation.
For example - Khakassia, Karelia, Nenets Autonomous Okrug (Nenetsia), Kaliningrad, Krasnoyarsk Krai.
You also need to make the core province of the Far Eastern Republic in the Khabarovsk Territory, the Kamchatka Krai and Chukotka Autonomous Okrug.

Thank you!

**Comment by simsulla** [comment]
Khakassia - throughout the game period c.10 are Khakas. Likewise for Karelia (that was removed).
 Kaliningrad, Krasnoyarsk Krai are Russian and has to my knowledge no strong separatist movements.  
Will correct FER cores.
