### ISSUE TITLE
Population of China

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#948]
Hello. I noticed that for some reason you have in the game most of the population of East Turkestan are Chinese (Han). As far as I have found information East Turkestan (Xinjiang), mainly populated by Uighurs. (Of course, I mean Modern Day scenario - 1992.)

https://en.wikipedia.org/wiki/Demographics_of_China#/media/File:Ethnolinguistic_map_of_China_1983.png

**Comment by simsulla** [comment]
In the 1992 start Xinjiangs population is overwhelmingly Uighur
![image](https://cloud.githubusercontent.com/assets/10263809/23093948/19a7e512-f5f0-11e6-8b14-92ca0e179867.png)

Then Han immigration eventually turns it more Chinese. 
Realworld 2010
46% Uighur
39% Han
7% Kazakh
5% Hui
3% Other
and in the mod..
