### ISSUE TITLE
Armenia annexing Nagorno-Karabakh Republic

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#949]
Armenia annexing Nagorno-Karabakh Republic without wars.

**Comment by simsulla** [comment]
Be a bit more specific. What happened?

**Comment by samwoodzadrot** [comment]
If the Nagorno-Karabakh Republic is somehow separated from Azerbaijan that after a while it becomes a part of Armenia

**Comment by simsulla** [comment]
That is by design. Reunification of Armenian lands. There are several examples of that culture can unify its lands, Armenian is one, Kurd's another.
