### ISSUE TITLE
Greek island bordered by the continental Turkey

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#950]
One of the Greek islands in the game is connected to the mainland and is bordered by Turkey

**Comment by simsulla** [comment]
Will correct
![image](https://cloud.githubusercontent.com/assets/10263809/23099274/12afe96c-f663-11e6-8f66-34b8f80f8ffc.png)

**Comment by simsulla** [comment]
And there are other examples - need to address them as well
![image](https://cloud.githubusercontent.com/assets/10263809/23099565/cfb4deb2-f66a-11e6-9baa-4dd49aca0681.png)
