### ISSUE TITLE
Religion Overhaul

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#951]
I was honestly quite surprised this issue wasn't previously brought up at the forums or at github, the thing in question there is a noticeable lack of animist/folk religion pops especially in countries such as Togo and Madagascar where both countries contain a slight animist/folk religion majority above 50%.. Also I successfully managed to add in 3 new religions Zoroastrianism, Druze and Yezidism into a personal version of this mod I have, unfortunately I'd accidentally deleted that version however I still have some pictures that were used for the religion symbols that could be of some use in the future.
Madagascarian and Togolese censues of religion
 http://www.mapsofworld.com/madagascar/society-and-culture/religion.html
https://www.cia.gov/library/publications/the-world-factbook/geos/to.html
https://www.cia.gov/library/publications/the-world-factbook/geos/ma.html

Religion symbols
[new religion symbols.zip](https://github.com/simsulla/nwomod/files/785458/new.religion.symbols.zip)

**Comment by simsulla** [comment]
Religion as a factor in Vic2 game engine is very weak - to my understanding. Also the graphics (like lack of map) is limiting. Due to those and other game technical reasons there is a 1:1 relation of religion/culture in NWO. The major force of out time is secularization (though one could argue otherwise for the Islamic world), thus adding new religions serves little purpose. And if a religion is added it has to be culture confined.  Druze would be a possibility. Yezidism and Zoroastrianism has no culture at the moment (i.e. are to small).  If you want to make some cultures animist, one need to also do something with conversions to mod the conversion of those to Christianity and Islam ([Nigeria in the 1960s](http://www3.qeh.ox.ac.uk/pdf/nrn/BP1Ostien.pdf) is a good example as compared to [current numbers](https://en.wikipedia.org/wiki/Religion_in_Nigeria)).

**Comment by arandomperson5000** [comment]
This map of religions across the world that was made in 2008 may be quite helpful in deciding which cultures are animist or not.
http://worldmap.harvard.edu/data/geonode:wrd_province_religion_qg0

**Comment by simsulla** [comment]
Nice map. But remember the 1:1 relation of religion to culture (except secularism). So, say you make  in Madagascar animist, leave no catholic xxx.

**Comment by arandomperson5000** [comment]
Using your 1:1 relation of religion of culture I have managed to made around 47% of the population of Madagascar animist in the 1992 bookmark however when I try to change the religion of some pops on the French colony of Madagascar, the entire population of France is completely reduced to zero pops, I don't know why this is happening as in an older version of my personal version of NWO I was able to put in Druze and Yezidi pops just fine. Also the allow_desc and effect_desc problem is back again and I plan to change the government type of Kolhapur from democracy to absolute_monarchy and reduce its prestige to  the same score as other princely states such as Beroda as its current prestige score is way too high at 141 allowing Kolhapur to be a secondary power instead of a mere princely state.

**Comment by arandomperson5000** [comment]
I have added in the Druze religion to NWO and it seems to be working just fine.
![20170317002043_1](https://cloud.githubusercontent.com/assets/20518264/24024085/81641122-0aa8-11e7-992b-68fe1ee4cf8b.jpg)

**Comment by arandomperson5000** [comment]
I'm putting this issue on hold due to the 1946 pops file for France being bugged, causing the file to be unable to be modded manually, however I did managed to edit the pops of Guinea Bissau just fine on both start dates. I will add the updated for Guinea Bissau in a new commit later.

Guinea Bissau 1946 religion demographics ingame
![20170322213535_1](https://cloud.githubusercontent.com/assets/20518264/24221775/9b756216-0f47-11e7-9c88-a93da2adbbd3.jpg)

Guinea Bissau 1992 religion demographics ingame
![20170322213239_1](https://cloud.githubusercontent.com/assets/20518264/24221828/cc8854b2-0f47-11e7-823c-23851f417fe9.jpg)

**Comment by simsulla** [comment]
Bugged? How?

**Comment by arandomperson5000** [comment]
So basically when I try change a religion of  a pop lets just say Catholic to Animist in the 1946 France pops file. Even though the edited religion of a pop is correctly typed in and all that, the game will still present France with no pops ingame, I believe it is similar to the bug which causes Soviet Union to have armies out in East Germany with empty brigades that have no pops to support them.

**Comment by arandomperson5000** [comment]
In addition to the map I provided above, this book could be used as a source to find out the religion of various ethnic groups as it a detailed encyclopedia on the various ethnic groups of Africa.
https://books.google.ie/books?id=xJQuAgAAQBAJ&printsec=frontcover&dq=Encyclopedia+of+African+Peoples&hl=en&sa=X&redir_esc=y#v=onepage&q=Encyclopedia%20of%20African%20Peoples&f=false

**Comment by arandomperson5000** [comment]
Will do more research on the Yazidis to see if they could be implemented in NWO as a ethno religious group similar to the Druze. As for Zoroastrianism I still think they are way too small to implement into NWO as even some of the largest communities such as the Parsi only number in the tens of thousands.

**Comment by simsulla** [comment]
Like with the Assyrians the  latest "elections" in Iraq does not support them being a significant minority in the 2013 Nineveh Governorate election they only got less than 2% (i.e. 60,000, 1/10 of the often sited 600,000). Or do you have different data?

**Comment by arandomperson5000** [comment]
In the 1957 census the Yezidi population of Iraq  was about 55,885 with 55,129 of them living in the Mosul Province (Present day Dohuk and Nineveh Governorates). While this figure is very similar to the figure you have provided above we have to take into account of all the demographic changes that have happened in Iraq since 1957. At the time of the 1957 census Iraq's population was  6,057,493, by the 1987 census Iraq's population had increased to 16.29 million with the Christian population increasing from 206,206 in 1957 to 1.4 million in 1987, this shows that rapid population growth in Iraq wasn't just limited to Muslims. I think it is more than likely that the Yezidi population had grown several times its 1957 size by 2000. Also what we need to take into account is the 2003 invasion of Iraq which has caused religious tensions in Iraq to skyrocket thus causing a catastrophic decline in the population of religious minorities in Iraq such as the Christian population was estimated to have dropped to 450,000 by 2013 due to emigration and low birth rates however the exact population numbers are quite hazy due to the lack of an official census. As a religious minority it is more than likely that the Yezidi population in Iraq was already in decline before ISIL took over Mosul and its surrounding areas in 2014 due to the Iraq War and the April 2007 Mosul massacre which saw unidentified attackers hijacked a bus carrying workers from a textile factory in Mosul, they told all Muslims and Christians to get out of the bus, the attackers then promptly drove the bus to Eastern Mosul where they executed the remaining 23 passengers all Yezidi. With attacks like these it is possible that a large portion of the Yezidi population could have abstained from voting in the 2013 Mosul election due to a fear of them being attacked due to one of their religion's central figures Melek Taus, who is said to have refused to bow to Adam which has caused some Muslims including members of ISIL to accuse Yezidis of being devil worshippers,

**Comment by simsulla** [comment]
Yes, but no real statistics for their numbers as far as I see, except electoral figures. Yazidis are Kurds, and yes oppression and genocides has contributed to their demise but demographics is key, from the source you site https://en.wikipedia.org/wiki/Demographics_of_Iraq#Vital_statistics.
https://upload.wikimedia.org/wikipedia/commons/0/0f/Iraq_total_fertility_rate_by_region_2006.png

**Comment by arandomperson5000** [comment]
![20170528183454_1](https://cloud.githubusercontent.com/assets/20518264/26530830/758d8ddc-43d4-11e7-8c11-29452d1ea0f0.jpg)

**Comment by arandomperson5000** [comment]
I'm setting this issue as an enhancement to allow me to work on more important issues.
