### ISSUE TITLE
The Repercussions of a Yes vote victory in the 1995 Quebec independence referendum

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#953]
Having done some research it appears that the effects of a yes victory in the 1995 Quebec independence referendum were more significant in determining the territorial stability of Canada than I had ever imagined. Both sides of the referendum didn't have any sort of plan to deal with a yes vote victory, since the Canadian government at that time assumed that the no vote would almost certainly win. However the results were far closer than they had anticipated therefore the Canadian government could be woefully unprepared for a yes victory in that referendum. In 2014 Roy Romanow the former Premier(Governor) of Saskatchewan revealed than in 1995 he had set up a secret committee to develop contingency plans in the event of a Yes vote in the 1995 Quebec referendum even though he was pretty much in favour of a united Canada.

Those contingency plans were
1. Saskatchewan seceding from Canada
2.  Creating a Western union of Saskatchewan, Alberta and British Columbia independent of Canada.
3. Abandoning the Canadian dollar to use the U.S. greenback
4. The annexation of Saskatchewan to the United States.

While all of these contingency were unlikely to occur in the event of a yes victory in the referendum, it just goes to show how chaotic the situation could have been in Canada if the yes vote won in the referendum and Quebec seceded shortly afterwards.

Sources
http://www.macleans.ca/politics/ottawa/what-would-have-come-after-a-yes/
http://www.cbc.ca/news/canada/saskatchewan/saskatchewan-considered-separation-roy-romanow-reveals-1.2744298

**Comment by simsulla** [comment]
Post this in the NWO thread and see if any Canadian player has input. 

btw :) please link the sources in the text. It takes more time than necessary to read all to find where substance for a claim comes from. In this case the two last sources is the same article.
like:
_Saskatchewan revealed than in 1995 he had set up a [secret committee](http://www.macleans.ca/politics/ottawa/what-would-have-come-after-a-yes/) to_

**Comment by arandomperson5000** [comment]
**Dveduu**
Canadian here. Never heard of Saskatchewan secession, and I don't think many people would take the idea seriously. 

Now, Western secession has been talked about. Political alienation of the western provinces of British Columbia and Alberta has been known to happen- especially under Liberal governments whose power centers are in Ontario and Quebec. For example, Pierre Trudeau's National Energy Program still makes Albertans unhappy.

The main problem is BC and AB are two of the "have" provinces, and along with Ontario they pay a lot of money to the maritime provinces. There is more trade and travel between Washington state and BC than between BC and the maritimes. The idea of an independent country west of the cascade mountain range has been proposed https://en.wikipedia.org/wiki/Cascadia_(independence_movement)

Ultimately there isn't a particularly strong sense of national unity or identity in Canada, except in the case of Quebec. So I think it is entirely realistic to have Quebec as the only releasable nation in Canada.

**Comment by arandomperson5000** [comment]
I think this issue needs more feedback from Canadian player£.

**Comment by simsulla** [comment]
Yes, absolutely, but for now I would go with the one presented by **Dveduu** "_So I think it is entirely realistic to have Quebec as the only releasable nation in Canada._". I.e. Close this and focus on other maybe more pressing issues.

**Comment by arandomperson5000** [comment]
Upon thinking the on the issue more I have come up with several ideas for events and decisions that could happen in the aftermath of a yes vote victory in the Quebec independence referendum in 1995.  First of all Quebec seceding in 1995 could raise separatist sentiment in neighbouring province of Newfoundland and Labrador as it has only been part of Canada since 1949 and it appears there is some local frustration with the level of control Toronto has over Newfoundland's economy.
https://www.google.ie/amp/www.cbc.ca/amp/1.410339
http://www.thetelegram.com/news/regional/2010/7/1/senator-warns-of-newfoundland-separatism-1451626.html

Another idea I've though of is what could Quebec's relations with France could be like. I suppose it's  both countries try to create a political and economic union similar to CANZUK if Quebec becomes independent. Also I wonder if Quebec would actually try to gain St. Pierre et Miquelon and the French speaking parts of the Maritime provinces. Back to the potential economic and political union of France the reason I was suggesting it was because it appears the U.S wouldn't recognise Quebec and prevent it from joining NAFTA if the yes vote referendum possibly as part of a retaliation for the referendum destabilising Canada a major ally of the U.S.
https://www.google.ie/amp/s/sec.theglobeandmail.com/news/politics/white-house-documents-reveal-how-us-would-react-if-quebec-had-separated/article17499442/%3Fservice%3Damp
