### ISSUE TITLE
Proposal for a new flag and name for Séléka

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#954]
Séléka oculd be renamed to Logone since in December 2015 a group of ex Séléka fighters based in the market town of Kaga-Bandoro declared the Republic of Logone although this self declared country has been completely unrecognised by the international community. The Republic of Logone has also been called Dar El Kuti, the name of a historical sultanate that used to exist in the Northern areas of the Central African Republic however I haven't been able to find any reliable sources saying that Dar El Kuti is the name of this self declared state. I would also suggest a new flag for Séléka since its current flag is basically the flag of the Central African Republic.
Sources
http://af.reuters.com/article/topNews/idAFKBN0TZ0TW20151216
https://www.washingtonpost.com/world/central-african-republic-rebels-declare-autonomous-state-in-north/2015/12/15/8efdd3a8-a380-11e5-ad3f-991ce3374e23_story.html
http://www.ibtimes.co.uk/central-african-republic-muslim-seleka-leader-noureddine-adam-declares-autonomous-state-1533469
http://reliefweb.int/report/central-african-republic/dangerous-divisions-central-african-republic-faces-threat-secession
http://www.globalsecurity.org/military/world/para/logone.htm

Possible new flag for Séléka (I Wasn't able to find any reliable sources on what the flag of the Republic of
                                               Logone looks like although I guess this could do as a new flag for Séléka)
![image](https://cloud.githubusercontent.com/assets/20518264/23105381/1d8de6c2-f6d6-11e6-8bcd-ee7fee34d5ab.png)

**Comment by simsulla** [comment]
I have read [one of the sources](https://www.washingtonpost.com/world/central-african-republic-rebels-declare-autonomous-state-in-north/2015/12/15/8efdd3a8-a380-11e5-ad3f-991ce3374e23_story.html?utm_term=.56c9b4e17896). That one references  AP. And I have not been able to find that original article. 

For the rest please link the text, so I can see what source supports what claim. 

On  the flag I have also not been able to find any. Maybe search photos for Seleka troops to see what flag they might be using...

Vice News has [these documentaries](https://www.youtube.com/watch?v=VoZvdCvq2iQ) on the conflict in CAR. You might find it interesting.
