### ISSUE TITLE
Question: why not move NWO to eu4 or hoi4?

### ISSUE THREAD

**Issue by Necessarycoot72** [simsulla/nwomod#955]
I ask this because victoria 2 uses a really old engine and everywhere I go I see complaints about how modding is difficult. I know this would be a monumental undertaking but in the long run it would be beneficial and allow you to do thing leaps and bounds ahead of what victoria 2 allows you to do.

P.S I have no idea how to mod eu4 or victoria 2 so i have no idea how difficult it is.

**Comment by ss-10** [comment]
That idea would be perfect with all the advanced military and economic play mechanics of both eu4 and hoi4 it will give this mod soo much potentials and new horizons to develop

**Comment by simsulla** [comment]
Actually I have contemplated this on more than one occasion (sort of in the back of my mind 2.00 of NWO wold be a eu4 version), but each time backed of from the enormous amount of work. There are a lot of things in eu4 that is superior to vic2. To mention some diplomacy, elites/royal families, religions and trade. But there are also things missing, like no pops, factories and ideologies, and the economy is at its core less realistic. 
Furthermore it is huge work to port all events to it, _so at the moment there are no such plans. _

But please post this in the forum thread to see if there is more interest.

**Comment by simsulla** [comment]
On a port of NWO to **hoi4**. [This post](https://forum.paradoxplaza.com/forum/index.php?threads/new-world-order-mod-for-hoi4.931407/) discuss it (written before playing hoi4). From playing some hoi4 my conclusion is that this is a war only game. At it is really not what NWO/vi2 is about. One could consider a limited cold war scenario where 100% tension at all costs must be avoided (i.e. MAD Armageddon), and whomever breaches the 100% looses the game. But the economics, trade, etc is simply to simplistic and by it self not entertaining enough. So there will be no NWO port to by me. There are other mods as mentioned in the post that might tries to do post-WW2 scenario that might be worth testing out.

**Comment by Necessarycoot72** [comment]
Well pops is not really necessary since they added a manpower resource. Its a resource though and not an actual pop. There are Technology group you could repurpose to work as ideologies and development could be used as factories. yes the economy is less in depth as in vic2 but that's a small downside to how better everything else is.

P.S What forum? The paradox forum? If it is I could never get that to work. So just stopped trying. Even after they updated the system it still doesn't work. So could someone do post that for me?

**Comment by simsulla** [comment]
Or post in this [reddit thread](https://www.reddit.com/r/paradoxplaza/comments/5neygn/new_world_order_nwo_mod_for_victoria_2_v112/?st=ixtgmp3j&sh=e2ce9d45). Will close this issue awaiting such discussion. As mentioned previously no plans for a port.
