### ISSUE TITLE
A proposal to represent microstates in this mod

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#956]
![image](https://cloud.githubusercontent.com/assets/20518264/23173949/c16b7002-f852-11e6-82ce-16273bdfd941.png)
Currently as of now, there is no system in place that represents the microstates of Europe excluding Malta in this mod.. One obvious answer would be to create new countries and provinces since some microstates such as Andorra are larger than some countries that are currently in the mod such as Malta and Nauru however this is a time consuming process and some European microstates such as Monaco and the Vatican are ridiculously small, as they're even smaller or slightly larger than some cities.

Pictures showing the size of Nauru and Malta in this mod.
![20170221162114_1](https://cloud.githubusercontent.com/assets/20518264/23175202/91905308-f856-11e6-82d7-1cd6098a96e1.jpg)
![20170221163333_1](https://cloud.githubusercontent.com/assets/20518264/23175218/95c58d44-f856-11e6-8739-a718ac3ba937.jpg)

An alternative idea I've come up to this time consuming process is the creation of unique province modifiers for each of the microstates presented on the map excluding Malta that will generate a very small amount of prestige for the country owning the province with that modifier along with increasing productivity in provinces with the modifier.

Potential provinces for the modifier
Nice (Monaco)
![20170221163941_1](https://cloud.githubusercontent.com/assets/20518264/23176403/adac1b68-f85a-11e6-926d-11431fdd94ce.jpg)

Foix (Andorra)
![20170221164105_1](https://cloud.githubusercontent.com/assets/20518264/23176421/c2e7dc6a-f85a-11e6-946d-2cdb1fc1ebc9.jpg)

Rome (Vatican City)
![20170221164127_1](https://cloud.githubusercontent.com/assets/20518264/23176453/e7d109c0-f85a-11e6-9154-8ce31459a31c.jpg)

Ravenna (San Marino)
![20170221172706_1](https://cloud.githubusercontent.com/assets/20518264/23176478/07f483d0-f85b-11e6-8b5e-5f57f245490b.jpg)

Zurich (Lichtenstein)
![20170221163929_1](https://cloud.githubusercontent.com/assets/20518264/23176515/2d822a12-f85b-11e6-98d1-5d886e36ace1.jpg)

**Comment by simsulla** [comment]
Malta and these add slem military strategic to the mod. The micro states I am not sure (except additionally work adding provinces). That energy could be better used elsewhere

**Comment by arandomperson5000** [comment]
![20170412002549_1](https://cloud.githubusercontent.com/assets/20518264/24934945/b3b218a4-1f16-11e7-92d6-52d1afd74335.jpg)

**Comment by arandomperson5000** [comment]
![20170412233600_1](https://cloud.githubusercontent.com/assets/20518264/24982855/89a31520-1fdb-11e7-9293-a03b396ccfd3.jpg)
![20170412233612_1](https://cloud.githubusercontent.com/assets/20518264/24982858/9714e986-1fdb-11e7-9501-d22ff112ac1c.jpg)
![20170412234719_1](https://cloud.githubusercontent.com/assets/20518264/24982872/a3081088-1fdb-11e7-8c25-6e37355e0ced.jpg)
![20170412235148_1](https://cloud.githubusercontent.com/assets/20518264/24982883/aa149b26-1fdb-11e7-8506-8656dc64fe8a.jpg)
