### ISSUE TITLE
Status of the Papal States, United Baltic Provinces and Scandinavia

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#957]
I'm absolutely baffled on why the Papal States and the United Baltic Provinces are still on this mod. I guess that they're either remnants from the converter or from DH. I think Scandinavia should be kept in this mod just in case if a Nordic Union is ever added into this mod.

**Comment by simsulla** [comment]
Will close this referencing the waiting issue Nordic Council #801
