### ISSUE TITLE
Casus belli between allies

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#963]
**MrTrt**
Is there any plan to do something (If it can be done) about the random wars between European powers? Like Norway invading Sweden, or Germany invading the Netherlands. I usually end those wars using the console, but obviously it would be best if they didn't happen in the first place. I think war justification shouldn't be allowed between western democracies, but I don't know how to restrict that, if that's even possible.
**The Sneaky Top Hat**
I agree this is a very serious problem in this mod, a potential solution to this problem is to simply edit the relations of western countries so that their relations with other western countries is quite high to the point where they can't justify a war against them without lowering their relations with the targeted western country.
**vegku said**
Maybe a NATO like decision for only the EU countries? Like, whenever the decision is selected, relations with countries in the EU goes up by 200?

**simsulla**
This is a difficult issue. In the early version of NWO democracies could not wage war on each other- but this is a two stringent limitation - creating a situation of very few wars. So we need to find a balance, keeping the game entertaining while not diverging to much from reality. 

Looking on generic Vic2 mechanics, vassals and sphered nations are under the protection of there masters (absolutely if vassal, and indirect - i.e if you make war on a sphered nations there master will defend them), and they them selves have limited abilities to wage wars. These generic Vic2 mechanics are good, and exists in NWO as well (if not, we have a bug).

So what we have left is wars between Greater powers and nation(s) outside the spheres. And I believe that these are the ones you have issues with. 

Looking for a potential solution, we want to as a basis we want to use the generics of Vic2 as far as possible - i.e sphering (and vassals) as the prime-ware preventive - and not do lots of hard-coding. 

One suggestions for solutions is to for Great power-Great power wars using the hard coded alliances as war-blocker would be an option. I.e UK and US would thus be prevented form waring each other. As a player you should be able to remove this hindrance by leaving NATO. Smaller nations would not have this benefit and would need to go under the umbrella of sphered for protection - so their membership in an alliance would come with being sphered. I.e to be a NATO member you must be in UK, US etc.. sphere of interest.

Thus, taking he Norway-Sweden example, Sweden would be able to gain protection by placing themselves in the US sphere. One could consider a country that is without protection be given the option give some greater power more influence if any neighbor in a sphere has a casus_beli on them. 
Similarly Holland would probably seek UK, or US overlord ship asp after loosing great power status, and thus protecting themselves from Germany.

**Comment by KeyboardMonkey95** [comment]
How about making it impossible for countries with pacifism to justify most kinds of wars, while at the same time giving most parties in Europe pacifist policies, limiting pro-military to extremist parties (like populists and communists)
This way, the player would still be able to be aggressive by getting those parties to power, whereas the AI would be more likely to be peaceful, as it should.
Also, you could make a specific nation more or less likely to go to war by changing the number of parties which supports war.

**Comment by simsulla** [comment]
Good idea

**Comment by simsulla** [comment]
Will add a block for cb's such that members of NATO, ANZUS and the Rio Pact can't do war on each other. Members of SCO or CSTO can't do war on each other.
