### ISSUE TITLE
Ukraine in Russian sphere of influence

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#965]
Hello. The game has a bug with the Russian sphere of influence. Ukraine is in the game files in the Russian sphere of influence, but the game does not appear on the map as its sphere of influence at the same time in the game says that Ukraine is in the sphere of Russian influence, and it turns out that to remove Ukraine from the Russian sphere of influence is impossible.

**Comment by simsulla** [comment]
This is in part a core bug. Will avoid it by reducing Russian influence in Ukraine.
