### ISSUE TITLE
Greater Armenia

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#966]
**fr-rein**
Why there are no armenian cores on Turkey? Of course we do not talk about Great Armenia, but it should retain some claims on the historical clay.

**Comment by arandomperson5000** [comment]
There is already a decision for a Greater/Wilsonian Armenia and Armenia pretty much gave up all claims on the eastern part of Turkey when it was a puppet state of the Russian Soviet Federative Socialist Republic in the Treaty of Batum in 1921, hence explaining why Armenia doesn't have claims on to the territories it gained in the Treaty of Sveres.

**Comment by simsulla** [comment]
thanks... closing this issue.
