### ISSUE TITLE
Vietnam and Mongolia in Russian sphere of influence

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#972]
Hello. I would like to know why in the game, Mongolia and Vietnam are in the sphere of Russian influence. China has become the largest trading partner of Mongolia and the main source of foreign investment. The volume of bilateral trade reached US $ 1.13 billion. In the first nine months of 2007, reaching a growth of 90% since 2006.

**Comment by simsulla** [comment]
The game starts in the 1992. 

On Mongolia: When the USSR existed Mongolia was on the Soviet side, but has moved to Chinese sphere, but that move happens after 1992. 

On Vietnam, I don't believe should belong under Sino sphere as they has even fought a war with China Sino-Vietnamese War recently (1979), and have territorial disputes with China (in the South China sea). Though maybe Russia position 1992 could be considered significantly weakened. 

So in both cases one could consider both nations to start without sphere master... will consider it,

**Comment by simsulla** [comment]
Both Mongolia and Vietnam will remain in Russian sphere but for both China influence will be much stronger.
