### ISSUE TITLE
Incorporate SSR core (nations) into the Soviet union.

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#977]
**fr-rein**
If you help that Azerbaijan, you get 2 states of Azerbaijan existing - one is a newly formed Iranian part, and the other is not represented Soviet part.
In-game mechanics... favors the de-facto independent Azerbaijan to return it's territories. Even if you sphere it and install communism (by force if necessary). You get crisis, upset relations and such.
Lets face it: USSR wouldn't really give up the Azerbaijan Soviet Socialistic Republic. It would instead incorporate the new Azerbaijan - in a manner it happened with Western Ukraine and Western Belarus in 1939, after Molotov-Ribbentrop pact, "reuniting" the countries under Soviet banner.

**Comment by arandomperson5000** [comment]
A point I would like to add is however unlike what happened in Poland when it lost territory to Belarus and Ukraine, Iran is likely to maintain claims over those areas as it was not a puppet of the USSR unlike Poland which have claims to Kresy as it was at that time a satellite of the USSR. If the USSR still collapses in 1991 as in real life and the Nagarno Karabakh War still happens Azerbaijan could face a two front war between Iran and Armenia causing massive problems for Azerbaijan and possibly setting the stage for Iranian Irredentistism.
