### ISSUE TITLE
Possible Breakup of Iraq

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#978]
This topic was previously discussed at the Paradox forums however today I have found some new pieces of  information that could add more to this topic to discuss. I turns out the situation regarding a possible breakup of Iraq is much more dire than I had originally thought, it isn't just religious and ethnic tensions are rising but also provincialism across the Iraqi provinces particularly in the Basra governorate where its residents feel they are neglected by the main government in Baghdad and some of them are pursuing autonomy for the governorate. [[1]](http://foreignpolicy.com/2015/07/01/welcome-to-basrastan-iraq-basra-secession-oil-shiite-south/) [[2]](https://www.google.ie/amp/s/www.washingtonpost.com/amphtml/world/middle_east/as-war-rages-in-the-north-southern-iraq-makes-a-bid-for-autonomy/2015/02/15/b4367604-483d-4aaf-8e78-7856aa8c6670_story.html) [[3]](http://www.al-monitor.com/pulse/originals/2014/12/iraq-division-federal-regions-basra-independence.html#)

 As for Kurdistan on an interesting note there is a referendum planned after the Battle of Mosul is over in which Iraqi Kurdistan will decide it will become an independent country or not, if this were to happen in favour of Kurdish independence, there is a high chance that the Iraqi government could reject the result as they could see it as a serious threat to their stability thus possibly setting the stage for a Kurdish War of Independence in the near  future. [[4]](https://en.wikipedia.org/wiki/Future_Iraqi_Kurdistan_independence_referendum) [[5]](https://www.google.ie/amp/www.newsweek.com/2016/10/28/battle-against-isis-mosul-kurdistan-independence-511041.html%3Famp%3D1) [[6]](http://www.bbc.com/news/world-middle-east-28103124)

 I think ISIL is not really representative of the Sunni Arabs in Iraq as their goal is to establish a caliphate stretching all across the world, not to obtain independence for the Sunni Arabs in Iraq.

Sources
[1] http://foreignpolicy.com/2015/07/01/welcome-to-basrastan-iraq-basra-secession-oil-shiite-south/

[2] https://www.google.ie/amp/s/www.washingtonpost.com/amphtml/world/middle_east/as-war-rages-in-the-north-southern-iraq-makes-a-bid-for-autonomy/2015/02/15/b4367604-483d-4aaf-8e78-7856aa8c6670_story.html

[3] http://www.al-monitor.com/pulse/originals/2014/12/iraq-division-federal-regions-basra-independence.html#

[4] https://en.wikipedia.org/wiki/Future_Iraqi_Kurdistan_independence_referendum

[5] https://www.google.ie/amp/www.newsweek.com/2016/10/28/battle-against-isis-mosul-kurdistan-independence-511041.html%3Famp%3D1

[6] http://www.bbc.com/news/world-middle-east-28103124

**Comment by arandomperson5000** [comment]
![20170314220835_1](https://cloud.githubusercontent.com/assets/20518264/23924510/df794068-0902-11e7-8d02-dd6b81b2c73c.jpg)
I have added in the countries of Basra and Mosul into the main NWO repository, I may reduce the number of cores Basra currently has in the future.

**Comment by simsulla** [comment]
Nice with the Sunni Arab - North Iraq. 

But Isn't Basra is an unnecessary core? Iraq could be used for that. What's the point of leaving "Iraq" with only Baghdad? In general cores reflect states or cultures within existing states - or there should be a significant support for independence to warrant a core. Basra fulfills none of these criteria.   

One have to separate opinion pieces in some news outlet from actual voter support, real political programs or significant acts of violence with expressed aim of independence.

**Comment by arandomperson5000** [comment]
I will remove Basra and try to find reliable sources with actual voter statistics on its autonomist movement however the statistics on it aren't available right now. As for Mosul, it is

**Comment by arandomperson5000** [comment]
Also to consider is the status of the Nineveh Plains in NWO, ever since ISIL took over large parts of Northern Iraq in 2014, there has been a large exodus of non Sunni inhabitants in the Nineveh governorate due to religious persecution by ISIL, this had led to demands by Iraqi minorites such as the Yezidis and Assyrians living in the Nineveh governorate for a 19th governorate or even outright autonomy for the Nineveh plains.
To represent this either a decision could be created that allows certain Iraqi minorities such as the Turkmen and Christian Arabs to become accepted cultures of Iraq or a new province would be created with possibly new cores for Assyria but I'm rather in favour of making a new decision as it is much less time consuming than making a new province and new countries. Also I would like to know the reason why the Christian Arab culture is used instead of the Assyrian culture in Iraq
https://en.m.wikipedia.org/wiki/Nineveh_plains
https://en.m.wikipedia.org/wiki/Proposals_for_Assyrian_autonomy_in_Iraq

**Comment by simsulla** [comment]
The fact that the Assyrians leave makes the case for a "Assyrian" weaker. On all the pop stats (for Christians, Turkmens and even Kurds), one need to be careful on what to accept. In lack of reliable census data I find the elections a good source of current demographics (as people vote ethnocentric in Iraq overwhelmingly).

This is stats for the [2009 gov election](https://en.wikipedia.org/wiki/Ninawa_governorate_election,_2009).
Yazidi and Assyrians got less than 2% each. That is negligible. The Kurds got c30%. The rest is Sunni arab.

**Comment by simsulla** [comment]
Sure one could have Assyrians, instead of Christian  Arab. But then Lebanon would require more than on extra culture, as well as Egypt... and so on

**Comment by arandomperson5000** [comment]
Given that current version of the Iraq War in NWO doesen't represent the chaos in that happened immediately after Saddam Hussein was toppled in 2003 and before the U.S withdrew from Iraq in 2011, I have come up with a possible event chain to represent this.

Here is what the Iraq War event chain may look like.

2003 Invasion of Iraq
The current version of this event will largely be unchanged except with events detailing a U.S victory in the Iraq War and a hypothetical Iraqi victory in which Iraq successfully repulses the Coalition's invasion along with the creation of an Iraq War global flag to represent the long timeline of the conflict and to trigger events that will happen later in the Iraq War.

Iraq Insurgency (2003-2006)
After Saddam Hussein and his Baathist government is toppled, the U.S will have a choice of enforcing Debaathification or not as it pretty much restructured the entire Iraqi state most importantly its military which has led to some very dire consequences in which Iraq's military was unable to prevent ISIS from overrunning a third of the country. Along with this, militancy among the Sunni and Shiite population of Iraq will rise to represent the insurgency that followed the overthrow of Saddam Hussein in opposition to the U.S occupation of Iraq leading to the creation of small rebellions across the region.

Sectarian violence in Iraq (2006–07)
From 2006 to 2007 sectarian violence rose considerably in Iraq particularly between the Sunni and Shiite causing tens of thousands of Iraqis to be  killed, displacing over 4 million people and forcing the U.S to send in about 20,000 soldiers to help the Iraqi Army to quell the violence. This would be represented by an event for Iraq if it has the Iraq War global flag, has Shia Arab as its primary culture and is either the year 2006 or 2007 which would cause militancy to skyrocket among the Shia and Sunni populations fomenting large scale uprisings previously unseen in the war which would  cause the U.S to possibly send troops out to Iraq to protect its influence in the region. Also in 2006 Iraq will get a choice to execute Saddam Hussein if Shia Arab is their primary culture. If they do execute him it will decrease militancy consciousness among the Shia population however it will do the exact opposite for Sunni nationalists representing supporters of Saddam Hussein. If they don't execute him the results will be reversed from the other choice to execute him.

End of the Iraq War and the subsequent insurgency that happened in its aftermath (2011 to 2014)
The current version of this event in NWO will be edited to only raise militancy among the Sunni and Shia pops of Iraq and cancel out the Iraq War global flag to represent this insurgency and the end of the Iraq War.

Iraqi Civil War (2014 to Present)
This event would happen in the year 2014 and if Iraq has shia arab as its primary culture. Basically what will happen is that this event will use the effects of the current version of the Iraqi Insurgency in this mod causing a civil war in Iraq with ISIL fighting both the Kurds and the Iraqi government. Both the U.S and Iranian led interventions will be represented by two events placing the limited military intervention modifier on ISIL. There could be victory events for both ISIL and the Iraqi government.

**Comment by simsulla** [comment]
Issues to get into 1.13 need to be done by Thursday. Do you think yo will be able to fix it till then?

**Comment by arandomperson5000** [comment]
Yeah I think I should get this issue done with before Thursday

**Comment by simsulla** [comment]
Have you fixed the other errors in the validator?

**Comment by arandomperson5000** [comment]
I have added the commits 81354f4d26a24f0c213196dc62c5dadfbf5484ed and 43798d72fe6f1d5a10edeb7d7e5c5cf888c22d50 to fix the remaining errors that were shown on the validator except two parse errors in the localisation files for decisions and events, however it appears that these two errors are not related to the Breakup of Iraq commits and are quite harmless. I would need to investigate these errors more to better understand them.

**Comment by simsulla** [comment]
I fixed the remaining validator errors..
