### ISSUE TITLE
UN mandates

### ISSUE THREAD

**Issue by simsulla** [simsulla/nwomod#981]
I have toyed around with doing some thing on modding the "legal restrictions of control" that many power have over territories they control 1946. In most cases UN mandates, and temporary post WW2 occupation. In all these cases the great powers (UK, France, US, Soviet) occupies a territory with a legal mandate by the UN, once the UN retracts the mandate they have to leave. In the current setting these territories are represented as integral parts of respective nations empire. But this is not accurate. 

One idea would be to turn these states in to "special regime type" vassals, which then eventually will be prompted by the UN/world community to release - at that time the player of France, UK etc would be given an option to integrate the territory (South Africa is a real world example that integrated South West Africa / Namibia UN mandate - opposing the world community / UN), or release / return the territory.

The upside is that more nations is playable form start (among those Palestine/Israel). The downside is a more complex setting and to a large extend making a UN mandate a "vassal" does not reflect the factual total control of the colonial power.

The territories in question:
![image](https://cloud.githubusercontent.com/assets/10263809/24058552/c54a2068-0b4b-11e7-907c-399502aa2d13.png)

**Comment by simsulla** [comment]
As far as possible we want to use existing cores to mod this (to avoid to ad more hollow "occupation/mandate" cores. The regime type would be nationalist_dictatorship which already now is a special type of regime used in order to facilitate a special flag. Expect Rwanda and Burundi which will be Monarchies.

**Country - Core** (for nonexisting countrie - present)
Manchuria - MCK
Northern Papua - PAP
Fezzan - ?? potentially a new core or Azawad
Libya - LBY
USSR occupied Germany - DDR
USSR occupied Austria - AST
France occupied Germany and Austria - GER
US occupied Germany and Austria - BAV
UK occupied Germany and Austria - IAR (SLV)

The US, UK player could then follow a non historic path, leading to division of Germany perhaps closer to what was discussed in the Morgenthau plan. 
![image](https://cloud.githubusercontent.com/assets/10263809/24059618/068c7054-0b50-11e7-90bf-e79e60a4c57b.png)

**Comment by arandomperson5000** [comment]
I would suggest adding cores for Fezzan as the area of Azawad in Mali doesen't border Libya and it fits in with the Second Libyan Civil War issue #778

**Comment by simsulla** [comment]
Fair enough, add Fezzan cores as part of #778.
![image](https://cloud.githubusercontent.com/assets/10263809/24069073/658c4a1c-0b9f-11e7-8d4a-b3b1d2d6cb3b.png)
There is even a ISO 3166-1 alpha-2 code for Fezzan **LF**, according the [wiki ref](https://en.wikipedia.org/wiki/Fezzan#cite_note-10) :)

**Comment by simsulla** [comment]
**redstonecobra**
Could you make a seperate country of East Austria? so that the allies can discontinue occupation and form West Austria. In the event that the USSR creates a communist East Austria

**Comment by arandomperson5000** [comment]
I would also suggest adding in Tripolitania as there were several times where Libya could have been completely partitioned into 3 countries for example in 1951 France could have easily set up an independent country in its Fezzan Ghadarmes occupation zone, the Cyrenaica Emirate was established and the UK could have just easily gave Tripolitania independence instead of uniting it with the rest of Libya. However the exact opposite happened in which the three regions were united into Libya. Also I think I have an idea on why there is a lack of Tripolitanian autonomist movements, it is because that Tripolitania is the dominant region of Libya preventing the formation of any autonomist movement within the region.

**Comment by simsulla** [comment]
Not necessary - Libya is Tripolitania.

**Comment by arandomperson5000** [comment]
Ok

**Comment by simsulla** [comment]
Will rename nationalist_dictatorship to provisional_government, and the flags to just "special". Nationalist is a bit confusing, as these regime type will be used for special conditions of temporary occupation and minority sectarian rule.

**Comment by arandomperson5000** [comment]
Having looked at your recent commits for this issue and the list of mandates you've posted in this issue, it appears you have missed the Trust Territory of the Pacific Islands.
Here is more information about this trust territory
https://en.wikipedia.org/wiki/Trust_Territory_of_the_Pacific_Islands

**Comment by simsulla** [comment]
Added
![image](https://cloud.githubusercontent.com/assets/10263809/25591783/51e1f2a2-2eb6-11e7-8c23-c507e0f1197a.png)

**Comment by simsulla** [comment]
needs verification... but will take it as part of the tuning issue

**Comment by devinity1337** [comment]
Just an FYI. The mandates seen to ruin the independence events for certain countries. For example, Israel doesn't go through its normal independence event chain. Instead it forms a democracy right after the game starts. However it is British as primary culture and every state is a colony.

**Comment by devinity1337** [comment]
The weird British-dominated democracy bug is fixed, but I notice that none of the mandates go independent. 1948 Israel war event doesn't fire, I assume because it isn't properly targeted to the Mandate of Palestine.

Also Namibia doesn't get absorbed by South Africa, and the Libya protectorates just sort of stay there.

**Comment by simsulla** [comment]
Will investigate
