### ISSUE TITLE
Azerbaijan US influence

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#982]
Influence in Azerbaijan.
Hello, I noticed that Azerbaijan usually enters the Russian sphere of influence already by 2005, but really Azerbaijan is Turkish sphere of influence, so I have some ideas on this.
If Turkey is not a Great Power in NWO, I think you should make Azerbaijan a friendly nation for the United States and make 25 points of US influence in Azerbaijan.
Because Baku is now trying to take a neutral position in the confrontation between Russia and the United States.

**Comment by simsulla** [comment]
Added 25 point of influence for the US in Azerbaijan.
