### ISSUE TITLE
Country Military sizes

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#989]
I kinda don't get why you reduced the number of soldier the U.S has in the 1992 from about 1 million to about 770000.

Edit 
Also some of the Soviet armies stationed in Germany in the 1946 bookmark sizes are at 0 strength.
![20170319212458_1](https://cloud.githubusercontent.com/assets/20518264/24084912/c8cea204-0cea-11e7-898d-fad9b22ab5c5.jpg)

**Comment by simsulla** [comment]
Reducing the US army strength? That was not intentional. The Soviet zero armies is a bug.

**Comment by arandomperson5000** [comment]
Should I reintroduce the old soldier pops for Moscow in the 1946 bookmark to fix the Soviet zero armies bug.

**Comment by simsulla** [comment]
Yes please do,

**Comment by arandomperson5000** [comment]
ok

**Comment by arandomperson5000** [comment]
I think I may have just found out what is causing the zero armies bug, it appears that the commit Life-Ratings as TFR #626 21ee16f6404b2f23de133d14ad32cba953fbccef has significantly reduced the number of soldier pops found in the 1946 bookmark causing the zero army problem in many countries. I discovered this when I couldn't make any more brigades as a country in the 1946 bookmark for example the Soviet Union or the Republic of China.

**Comment by simsulla** [comment]
That was probably a mistake to change the Soviet soldier pops. We should revert that part of it.

**Comment by arandomperson5000** [comment]
![20170413230345_1](https://cloud.githubusercontent.com/assets/20518264/25026258/9b118180-209d-11e7-8c85-478480f97378.jpg)
Okay I have added in the old soldier pops for Moscow and most of the zero strength armies seemed to have been fixed, however there were a few zero strength armies left that weren't fixed. Upon noticing this I checked the building units tab and it seems like for the Soviet Union, you can't construct any more brigades other than ones you get at the start as there are no soldier pops left for you to recruit. The Republic of China also has the same problem, since the other countries at the 1946 bookmark could build more brigades just fine it appears that the Soviet Union and the Republic of China are the only ones suffering from this problem. I would suggest reintroducing the all of the old soldier pops for the Republic of China and the Soviet Union into NWO, as for the problem in which armies have less brigades than in previous versions I would suggest reintroducing the old oobs for countries such as the United States in both bookmarks.
![20170413230735_1](https://cloud.githubusercontent.com/assets/20518264/25026728/eac0a8da-209f-11e7-9578-d2f3ca609595.jpg)
![20170413230923_1](https://cloud.githubusercontent.com/assets/20518264/25026741/f8accd3e-209f-11e7-8851-ee95bd196296.jpg)
![20170413231043_1](https://cloud.githubusercontent.com/assets/20518264/25026748/05120b5c-20a0-11e7-9511-e290e4b92e3e.jpg)

**Comment by simsulla** [comment]
Ök

**Comment by arandomperson5000** [comment]
![20170415235447_1](https://cloud.githubusercontent.com/assets/20518264/25067320/58c69a04-2237-11e7-9714-9a2d9b251e8b.jpg)
I'm not sure why but I think the number of soldiers in the U.S army at the 1992 bookmark was at more than a million in previous versions.

**Comment by arandomperson5000** [comment]
Here is the revised soldier pops for the Republic of China in the 1946 bookmark however when I checked this file in the validator it said that there was a byte order mark at Line 1, Column 1 which is causing the Republic of China to have no pops ingame. I don't know what's causing the byte order mark, are you able to help me fix this problem.
[Republic of China.txt](https://github.com/simsulla/nwomod/files/945590/Republic.of.China.txt)

**Comment by simsulla** [comment]
In Vic2 (and NWO) files should always be ANSI encoded. In notepad++ this is easy to fix (under Encoding select ANSI).
Your Republic of China.txt file was UTF-BOM
![image](https://cloud.githubusercontent.com/assets/10263809/25283398/ebb331ee-26b3-11e7-90ff-ca6430613159.png)

I corrected and checked it in.
![image](https://cloud.githubusercontent.com/assets/10263809/25283385/e0cfd836-26b3-11e7-9783-81fe15c2a503.png)

**Comment by arandomperson5000** [comment]
Almost finished the soldier pops for the Soviet Union in the 1946 bookmark.
![20170425223443_1](https://cloud.githubusercontent.com/assets/20518264/25408881/990bc0c6-2a07-11e7-9d6c-2deb43926a1d.jpg)
