### ISSUE TITLE
Soviet Breakup

### ISSUE THREAD

**Issue by Liegnitz** [simsulla/nwomod#992]
3 out of 3 times the soviet union broke up into many microstates (Komi Nation, Gagauzia, Cicassia, etc.) even Russia existed besides it. It just seems odd that they dissolute into so many fractions. Additionally they normaly fall apart in the 80's. As far as I saw it started with a second revolution in Hungary or the democratization of the CSSR.

**Comment by simsulla** [comment]
Need to investigate... though it was possible taht also ASSR's would break out it seems to be a bit to bad for them.
![image](https://cloud.githubusercontent.com/assets/10263809/24328789/ab6efa02-11f3-11e7-8b7a-7f815cc27dfb.png)
