### ISSUE TITLE
Colonial War localisation

### ISSUE THREAD

**Issue by arandomperson5000** [simsulla/nwomod#993]
Having tested out the Colonial war events for Portugal I noticed the war wasn't immediately declared on a country seeking to gain independence from Portugal like Angola and that when a colonial war was declared its title was normally "Portuguese colonial conquest of". Given that most of the Portuguese colonial wars in the mid 20th century were officially known as wars of independence, I would like to obtain permission to change the title of a colonial war to "Country"'s war of independence and to edit the Portuguese colonial wars events so that Portugal would immediately declare war on any country seeking independence from them.

Titles of Portuguese colonial wars from 1961 to 1975
https://en.wikipedia.org/wiki/Angolan_War_of_Independence
https://en.wikipedia.org/wiki/Guinea-Bissau_War_of_Independence
https://en.wikipedia.org/wiki/Mozambican_War_of_Independence

**Comment by simsulla** [comment]
Please do,

**Comment by Liegnitz** [comment]
On Wikipedia its named similar, "Portuguese Colonial War"
