### ISSUE TITLE
Autonomous regions of Russian Federation

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/nwomod#994]
Hello. I would like to now, why don't you make core provinces for autonomous parts of Russia?
Russia may disintegrate for the next 8 years and autonomous regions may very likely begin to conduct an independent policy from Moscow. Russia already has some autonomous territories that it does not actually control (They certainly do not yet conduct an independent policy, but they do not depend so much on Moscow as much as on Japan, the US and China)

Thank you for creating the Far Eastern Republic, but I ask you to create even a few autonomous regions of Russia. You know? As the Krasnoyarsk Krai, the Nenets Autonomous District or for example Kaliningrad and other regions... (Of course i mean core provinces for them)

**Comment by simsulla** [comment]
No plans for more cores in Russia for autonomous (or previous autonomous) regions with Russian ethnic majority.

**Comment by samwoodzadrot** [comment]
But why? They also can become independent. For example, have you read a book "Fragile Empire"? 
Russian autonomous regions can begin to conduct an independent policy. My native language is Russian and I often communicate with Russians. Many residents of Sakhalin, Kamchatka, Siberia - say that it would not be bad for them to create independent states on their territories. For example, for protests in Khabarovsk, people came with the flags of the Far Eastern Republic and the slogans "Enough to feed Moscow and Chechnya!". Photo from Khabarovsk http://lurkmore.so/images/f/f3/Fer_flag.jpg

**Comment by simsulla** [comment]
There are endless amounts of more or leas weak "autonomy/discontent" movements. NWO should strive for realism, so as a general rule to qualify for a core there has to be either an existing independent or really autonomous nation in the game period, or a strong movement for independence (electoral or violent). If such conditions exist, sure we will ad cores, else not.

**Comment by samwoodzadrot** [comment]
From Russian wikipedia about movements in Russia:
The entrepreneur Vyacheslav Drezner, who attempted to hold a referendum on joining the border regions of the Republic of Karelia to Finland, was convicted by the Russian court of extremist activity and, subsequently, sentenced to a fine of 100 thousand rubles. [26] This was the first loud case of separatism in this republic. Also, leaflets with calls to hold a referendum on separation from Russia were distributed to towns and villages [27]. In this regard, a deputy of the Legislative Assembly of Karelia, Sergei Pirozhnikov, offered to ask the prosecutor to demand the blocking of the site of the Karelian nationalists, entitled "The Stop of Occupation of Karelia" [28]. Karelians themselves are ethnically close to neighboring Finns and in the history of Karelia there were periods when part or all of the territory of Karelia was part of the Finnish state.

Kaliningrad Region [edit | Edit wiki-text]
Main article: Republic (Russia)
The Baltic Republican Party, effective from December 1, 1993, set as its goal the upgrading of the status of the Kaliningrad region as part of Russia, at least to an autonomous republic with the prospect of seceding from the Russian Federation. On December 3, 2003, the party was dissolved, as its charter contradicted the Constitution of the Russian Federation. Attempts to restore the party through complaints to the ECHR were unsuccessful. The Kaliningrad regional public movement "Respublika" is the formal successor of the party.

Ural [edit] Edit wiki-text]
The Urals Republic [30] is a constituent entity of the Russian Federation, which was not stipulated by the Constitution of the Russian Federation and actually existed from July 1, 1993 to November 9, 1993, within the borders of the present-day Sverdlovsk Region. The republic was transformed from the Sverdlovsk Region in order to improve its status within the Russian Federation and to gain greater economic and legislative independence. It ceased to exist after the publication of the Decree of the President of the Russian Federation on the dissolution of the Sverdlovsk Oblast Soviet, and then - about the removal from office of the head of the administration Eduard Rossel.

Also within the framework of the "Great Ural Republic" was to be the Chelyabinsk region, in which, during the existence of the Urals Republic, an acute political crisis broke out.

Siberia
Aman Tuleev in 1993 during the meeting of participants of the Siberian Agreement (Association of Siberian Cities) put forward the idea of unification in the Siberian republic [31]. At the moment, the state, put forward by the Siberian separatists, occupies on the world map the whole Asian part of Russia (the Urals, Western and Eastern Siberia and the Far East)

In August 2014, activists filed two applications to the mayor's office of Novosibirsk to agree on the "March for the federalization of Siberia" and (after renaming) "March for the stability of the constitutional order." Both applications were rejected [32]. Organizers called for the development of federalism in the spirit of the Siberian regions of the XIX century [33]. On August 1, 2014, Russian authorities blocked the VKontakte group "March for the Federalization of Siberia" and one of its organizers, artist Artem Loskutov [34]. Roskomnadzor issued a warning to 14 media about the inadmissibility of posting information about the "March for the federalization of Siberia."

Far East 
Since the spring of 1992, part of the Far Eastern elite has taken the position of frank Far Eastern separatism and as a precedent frankly discussed the state that existed from April 1920 to November 1922 [36]. Already in the mid-90s, real proposals were put forward for the creation and unification of the new Far Eastern Republic. In particular, Viktor Ishayev, who was the governor of the Khabarovsk Territory for 17 years, called for this.

Enough to feed Moscow! 
On the Internet, despite the blocking by Roskomnadzor, in 2014 there were regular calls to go to the march "Enough to feed Moscow!". One of the organizers of the march was the above-mentioned Russian artist Artem Loskutov. According to the official version, the march was not for separation, but for the expansion of self-government and the fair distribution of financial resources. Under the same slogan, a march was prepared for the federalization of the Kuban. March in Krasnodar did not take place due to lack of participants
